TestRepo2/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <picklist>
            <picklistValues>
                <fullName>Additional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Charmer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Control</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Franchise</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Independent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SWS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Glazers</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

TestRepo2/src/objects/Brand__c.object
<CustomObject>
    <fields>
        <fullName>Generic_Brand__c</fullName>
        <formula>if(ISBLANK( Parent_Brand__c ), Name, Parent_Brand__r.Name )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Generic Brand</label>
        <type>Text</type>
    </fields>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/Sales_Volume__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sales Volumes</relationshipLabel>
        <relationshipName>Sales_Volumes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Batf_Volume_12_Mo_TY_vs_LY_Chg__c</fullName>
        <label>Batf Volume 12 Mo TY vs LY % Chg</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Brcat_Fin_Plan_Brand__c</fullName>
        <label>Brcat Fin Plan Brand</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <picklist>
            <picklistValues>
                <fullName>Spirits</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wine</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Generic_Brand__c</fullName>
        <label>Generic Brand</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Individual_Brand__c</fullName>
        <label>Individual Brand</label>
        <length>66</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Month_End__c</fullName>
        <label>Month End</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Size__c</fullName>
        <label>Size</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State_12M_Chg_vs_YA__c</fullName>
        <label>State 12M % Chg vs YA</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>State_Batf_Volume_12_Mo_TY__c</fullName>
        <label>State Batf Volume 12 Mo TY</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>State_Distro__c</fullName>
        <label>State % Distro</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Sales Volume</label>
    <nameField>
        <displayFormat>SV-{0000000}</displayFormat>
        <label>Sales Volume Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Volumes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/classes/AccountLayoutControllerExtensionTest.cls
@isTest
private class AccountLayoutControllerExtensionTest {
	 
	 
	 
	 static testMethod void testControllerExtension() {
	 	Account account = Test_Helper.testInsertAccount('test_account');
	 	Brand__c brand = Test_Helper.testInsertBrand('testBrand');
	 	
	 	//2a
	 	Sales_Volume__c salesVol1 = new Sales_Volume__c();
	 	salesVol1.Account__c = account.Id;
	 	salesVol1.Generic_Brand__c = 'gen brand';
	 	salesVol1.Division__c = 'Spirits';
	 	salesVol1.Month_End__c = Date.today();
	 	salesVol1.Batf_Volume_12_Mo_TY_vs_LY_Chg__c = .5;
	 	insert salesVol1;
	 	
	 	//3a
	 	Sales_Volume__c salesVol2 = new Sales_Volume__c();
	 	salesVol2.Account__c = account.Id;
	 	salesVol2.Brcat_Fin_Plan_Brand__c = 'test2';
	 	salesVol2.Division__c = 'Spirits';
	 	salesVol2.Batf_Volume_12_Mo_TY_vs_LY_Chg__c = .5;
	 	salesVol2.Individual_Brand__c = 'tester';
	 	salesVol2.Generic_Brand__c = 'tester';
	 	salesVol2.Brcat_Fin_Plan_Brand__c = 'tester';
	 	insert salesVol2;
	 	
	 	Sales_Volume__c salesVol2b = new Sales_Volume__c();
	 	salesVol2b.Account__c = account.Id;
	 	salesVol2b.Brcat_Fin_Plan_Brand__c = 'test2';
	 	salesVol2b.Division__c = 'Spirits';
	 	salesVol2b.Batf_Volume_12_Mo_TY_vs_LY_Chg__c = .5;
	 	salesVol2b.Individual_Brand__c = 'tester';
	 	salesVol2b.Generic_Brand__c = 'tester';
	 	salesVol2b.Brcat_Fin_Plan_Brand__c = 'tester';
	 	//insert later
	 	
	 	Sales_Volume__c salesVol2c = new Sales_Volume__c();
	 	salesVol2c.Account__c = account.Id;
	 	salesVol2c.Brcat_Fin_Plan_Brand__c = 'test2';
	 	salesVol2c.Division__c = 'Spirits';
	 	salesVol2c.Batf_Volume_12_Mo_TY_vs_LY_Chg__c = .5;
	 	salesVol2c.Individual_Brand__c = 'tester';
	 	salesVol2c.Generic_Brand__c = 'tester';
	 	salesVol2c.Brcat_Fin_Plan_Brand__c = 'tester';
	 	//insert later;
	 	
	 	Sales_Volume__c salesVol2a = new Sales_Volume__c();
	 	salesVol2a.Account__c = account.Id;
	 	salesVol2a.Brcat_Fin_Plan_Brand__c = 'test2';
	 	salesVol2a.Division__c = 'Spirits';
	 	salesVol2a.Batf_Volume_12_Mo_TY_vs_LY_Chg__c = .5;
	 	salesVol2a.Individual_Brand__c = 'tester';
	 	salesVol2a.Generic_Brand__c = 'tester';
	 	salesVol2a.Brcat_Fin_Plan_Brand__c = 'tester';
		//insert later
		
		Sales_Volume__c salesVol2d = new Sales_Volume__c();
	 	salesVol2d.Account__c = account.Id;
	 	salesVol2d.Brcat_Fin_Plan_Brand__c = 'test2';
	 	salesVol2d.Division__c = 'Spirits';
	 	salesVol2d.Batf_Volume_12_Mo_TY_vs_LY_Chg__c = .5;
	 	salesVol2d.Individual_Brand__c = 'tester';
	 	salesVol2d.Generic_Brand__c = 'tester';
	 	salesVol2d.Brcat_Fin_Plan_Brand__c = 'tester';
		//insert later	 	
	 	
	 	Sales_Volume__c salesVol3 = new Sales_Volume__c();
	 	salesVol3.Account__c = account.Id;
	 	salesVol3.State_Batf_Volume_12_Mo_TY__c = .9;
	 	salesVol3.Batf_Volume_12_Mo_TY_vs_LY_Chg__c = 50;
	 	salesVol3.State_12M_Chg_vs_YA__c = 40;
	 	salesVol3.Division__c = 'Spirits';
	 	salesVol3.Individual_Brand__c = 'tester';
	 	salesVol3.State_Distro__c = .8;
	 	salesVol3.Size__c = '1.5 L';
	 	insert salesVol3;
	 	
	 	Sales_Volume__c salesVol4 = new Sales_Volume__c();
	 	salesVol4.Account__c = account.Id;
	 	salesVol4.State_Batf_Volume_12_Mo_TY__c = .6;
	 	salesVol4.Batf_Volume_12_Mo_TY_vs_LY_Chg__c = 55;
	 	salesVol4.State_12M_Chg_vs_YA__c = 20;
	 	salesVol4.Division__c = 'Spirits';
	 	salesVol4.Individual_Brand__c = 'tester';
	 	salesVol4.State_Distro__c = .83;
	 	salesVol4.Size__c = '1.5 L';
	
	 	
	 	system.Test.StartTest();
	 		
	 		ApexPages.StandardController sc = new ApexPages.standardController(account);
	 		
	 		AccountLayoutControllerExtension ext = new AccountLayoutControllerExtension(sc);
	 		ext.getWineSpiritsOptions();
	 		
	 		insert salesVol4;
	 		insert salesVol2a;
	 		insert salesVol2d;
	 		insert salesVol2b;
	 		insert salesVol2c;
	 		AccountLayoutControllerExtension ext2 = new AccountLayoutControllerExtension(sc);
	 		
	 		AccountLayoutControllerExtension.DataFor3a datum1;
	 		AccountLayoutControllerExtension.DataFor3a datum2;
	 		datum1 = new AccountLayoutControllerExtension.DataFor3a(salesVol3);
	 		datum2 = new AccountLayoutControllerExtension.DataFor3a(salesVol4);
			datum1.compareTo(datum2);
			datum2.compareTo(datum1);
			//
			ext2.executeChartBrandChange();
			ext2.executeChartBrandChange2();
			ext2.executeChartBrandChange3();
	 		
	 	system.Test.stopTest();
	 }
	 
	 
	 static testMethod void testControllerExtension2() {
	 	
	 	
	 }
	 
	 

}