TestRepo2/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Objective__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Objective</label>
        <referenceTo>Objective__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

TestRepo2/src/objects/Action__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Actions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <formula>IF(Goal__c = null, Objective__r.Due_Date__c, Goal__r.Due_Date__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Objective__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Objective</label>
        <referenceTo>Objective__c</referenceTo>
        <relationshipName>Actions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Activity</label>
    <nameField>
        <displayFormat>A-{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>Action</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Actions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

TestRepo2/src/objects/Objective__c.object
<CustomObject>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <label>Objective</label>
    <nameField>
        <label>Objective Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Objectives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/classes/Test_Controller_TerritoryPerformance.cls
@isTest
private class Test_Controller_TerritoryPerformance {
	
	
	static testMethod void testController()
	{
		Account account = Test_Helper.testInsertAccount('test_account');
		Objective__c objective = insertObjective('test objective');
		Action__c action = insertAction(objective.Id, account);
		
		system.test.startTest();
			Controller_TerritoryPerformance controller = new Controller_TerritoryPerformance(objective.Id);
			Controller_TerritoryPerformance controller2 = new Controller_TerritoryPerformance();
			
			Controller_TerritoryPerformance.ObjectiveData datum;
			datum  = new Controller_TerritoryPerformance.ObjectiveData('test', UserInfo.getUserId()) ;
			datum.closedCount = 2;
			datum.totalCount = 4;
			datum.getMainLabel();
			datum.getClosedPercentage();
		system.test.stopTest();
		
	}
	
	
	private static Objective__c insertObjective(String name)
	{
		Objective__c objective = new Objective__c();
		objective.Name = 'test' + name;
		objective.Due_Date__c = Date.today().addDays(10);
		insert objective ;
		
		return objective;
	}
	
	private static Action__c insertAction(Id objectiveId, Account account) {
		Action__c action = new Action__c();
		action.Objective__c = objectiveId;
		action.Account__c = account.Id;
		insert action;
		
		return action;
	}
	
	
}