TestRepo2/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Objective__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Objective</label>
        <referenceTo>Objective__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

TestRepo2/src/objects/Action__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Actions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <formula>IF(Goal__c = null, Objective__r.Due_Date__c, Goal__r.Due_Date__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Goal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Goal</label>
        <referenceTo>Goal__c</referenceTo>
        <relationshipLabel>Actions</relationshipLabel>
        <relationshipName>Actions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Objective__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Objective</label>
        <referenceTo>Objective__c</referenceTo>
        <relationshipName>Actions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Activity</label>
    <nameField>
        <displayFormat>A-{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>Action</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Actions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

TestRepo2/src/objects/Goal__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Goals</relationshipLabel>
        <relationshipName>Goals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <label>Goal</label>
    <nameField>
        <label>Goal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Goals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

TestRepo2/src/objects/Objective__c.object
<CustomObject>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <label>Objective</label>
    <nameField>
        <label>Objective Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Objectives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/classes/Test_Controller_RepDailyWorksheet.cls
/**
 * Class name: Controller_RepDailyActivities.page
 * PageName: RepDailyActivies.page
 */
@isTest
private class Test_Controller_RepDailyWorksheet {

    static void init(){
    //create accounts
        Map<String, Id> accRTIdsByName = new Map<String, Id>();
        for(RecordType accRT : [SELECT Id, Name FROM RecordType WHERE SObjectType = 'Account']){
          accRTIdsByName.put(accRT.name, accRT.Id);
        }
        
        Objective__c objectiveRecord= new Objective__c(Name='Objective',Due_date__c=System.today());
        insert objectiveRecord;
        
        Goal__c goalRecord= new Goal__c(Name='Goal Record');
        insert goalRecord;
        
        Account acc=new Account(name='Account Name');
        insert acc;
        
        List<Action__c> accs = new List<Action__c>();
        
        for(Integer i = 0; i < 10; i++){
          accs.add(new Action__c(objective__c=objectiveRecord.id,account__c=acc.id));
        }
        //insert accs;
        
        Event e= new Event(Whatid=acc.id,EndDateTime=system.today(), DurationInMinutes=0, ActivityDateTime=system.today());
        insert e;  
       }
    
    static testMethod void myUnitTest() {
        
       // PageReference pageRef=null;
        PageReference pageRef = Page.RepDailyActivitiesWorksheet;
        
        Test.setCurrentPage(pageRef);
        DateTime d = Date.Today() ;
        String dateStr =  d.format('MM/dd/yyyy');
        System.currentPagereference().getParameters().put('date',dateStr);
       
        Controller_RepDailyActiviesWorksheet thecontroller=new Controller_RepDailyActiviesWorksheet();
        init();
       
        theController.getFooterLeftContent();
        theController.getOwnerName();
    }
}