TestRepo2/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Program_Code__c</fullName>
        <label>Program Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Spirits_Hierarchy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Spirits Hierarchy</label>
        <referenceTo>Organizational_Unit__c</referenceTo>
        <relationshipLabel>Accounts (Spirits Hierarchy)</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Wine_Hierarchy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Wine Hierarchy</label>
        <referenceTo>Organizational_Unit__c</referenceTo>
        <relationshipLabel>Accounts (Wine Hierarchy)</relationshipLabel>
        <relationshipName>Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Distributor</fullName>
        <active>true</active>
        <label>Distributor</label>
    </recordTypes>
</CustomObject>

TestRepo2/src/objects/Account_Member__c.object
<CustomObject>
    <description>POS Project: junction object that represents the many-to-many relationship between Accounts and Users (Shoppers)</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Members</relationshipLabel>
        <relationshipName>Account_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Account Member</label>
    <nameField>
        <displayFormat>ACM-{000000}</displayFormat>
        <label>Account Member ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestRepo2/src/objects/Brand__c.object
<CustomObject>
    <fields>
        <fullName>Classification__c</fullName>
        <label>Classification</label>
        <picklist>
            <picklistValues>
                <fullName>Beer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Spirits</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wine</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Alcoholic Beverage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NOT DEFINED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trading Goods (Non Beverage)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TBA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Parent_Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipLabel>Brands</relationshipLabel>
        <relationshipName>Brands</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WBS_Level_3__c</fullName>
        <label>WBS Level 3</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WBS_Level_5__c</fullName>
        <label>WBS Level 5</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/Cart__c.object
<CustomObject>
    <description>POS Project: object that represents a shopping cart</description>
    <fields>
        <fullName>Order_Window__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Window</label>
        <referenceTo>Order_Window__c</referenceTo>
        <relationshipLabel>Carts</relationshipLabel>
        <relationshipName>Carts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Cart</label>
    <nameField>
        <displayFormat>CRT-{00000000}</displayFormat>
        <label>Cart ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Carts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/Cart_Item__c.object
<CustomObject>
    <description>POS Project: junction object that represents the many-to-many relationship between Carts and Items</description>
    <fields>
        <fullName>Cart__c</fullName>
        <label>Cart</label>
        <referenceTo>Cart__c</referenceTo>
        <relationshipLabel>Cart Items</relationshipLabel>
        <relationshipName>Carts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Company_Code__c</fullName>
        <label>Company Code</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Item__c</fullName>
        <label>Item</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>Cart Items</relationshipLabel>
        <relationshipName>Cart_Items</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Ship_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To</label>
        <referenceTo>Ship_To__c</referenceTo>
        <relationshipLabel>Cart Items</relationshipLabel>
        <relationshipName>Cart_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WBS__c</fullName>
        <label>WBS</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Cart Item</label>
    <nameField>
        <displayFormat>CIT-{0000000000}</displayFormat>
        <label>Cart Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cart Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestRepo2/src/objects/Item__c.object
<CustomObject>
    <description>POS Project: object that represents catalog items available for shopping</description>
    <fields>
        <fullName>Agency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agency</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <formula>IF(Brand_Count__c &lt; 1, &quot;&quot;, IF(Program__r.Brand__r.Portfolio_Brand__c, &quot;Portfolio&quot;, Program__r.Brand__r.Name))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Channel__c</fullName>
        <label>Channel</label>
        <picklist>
            <picklistValues>
                <fullName>Off-premise</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On-premise</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

TestRepo2/src/objects/Item_Brand__c.object
<CustomObject>
    <description>POS Project: junction object that represents the many-to-many relationship between Items and Brands</description>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipLabel>Item Brands</relationshipLabel>
        <relationshipName>Item_Brands</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Item__c</fullName>
        <label>Item</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>Item Brands</relationshipLabel>
        <relationshipName>Item_Brands</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <label>Item Brand</label>
    <nameField>
        <displayFormat>ITB-{0000000000}</displayFormat>
        <label>Item Brand ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Item Brands</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestRepo2/src/objects/Order_Window__c.object
<CustomObject>
    <description>POS Project: object that represents a period of time in which catalog items are offered and shoppers are allowed to buy them</description>
    <fields>
        <fullName>Fiscal_Year__c</fullName>
        <label>Fiscal Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Order Window</label>
    <nameField>
        <label>Order Window Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Windows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/Organizational_Unit__c.object
<CustomObject>
    <description>POS Project: object that represents a hierarchy level within the distributors hierarchy</description>
    <fields>
        <fullName>District_Code__c</fullName>
        <label>District Code</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Responsible_Code__c</fullName>
        <label>Responsible Code</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <label>Organizational Unit</label>
    <nameField>
        <label>Organizational Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organizational Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/Planning_Account__c.object
<CustomObject>
    <fields>
        <fullName>District_Code__c</fullName>
        <label>District Code</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Channel_Code__c</fullName>
        <label>Sub Channel Code</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <label>Planning Account</label>
    <nameField>
        <label>Planning Account Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Planning Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/POS_Magento_Configuration__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>stores all values like API key, User Name, Endpoint etc. required for Magento Integration service</description>
    <fields>
        <fullName>Diageo_Spirits_District__c</fullName>
        <label>Diageo Spirits District</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Diageo_Spirits_Responsible__c</fullName>
        <label>Diageo Spirits Responsible</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <label>POS Magento Configuration</label>
</CustomObject>

TestRepo2/src/objects/Program__c.object
<CustomObject>
    <description>POS Project: object that represents a set of events for which related catalog items are offered to shoppers (distributors and internal Diageo employees)</description>
    <fields>
        <fullName>Brand__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Window__c</fullName>
        <label>Order Window</label>
        <referenceTo>Order_Window__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Program_Code__c</fullName>
        <label>Program Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestRepo2/src/objects/Ship_To__c.object
<CustomObject>
    <description>POS Project: object that represents a delivery address associated to a particular account</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Ship To&apos;s</relationshipLabel>
        <relationshipName>Ship_Tos</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Ship To</label>
    <nameField>
        <label>Ship To Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ship To&apos;s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestRepo2/src/classes/POS_WBSUtil.cls
public with sharing class POS_WBSUtil {
	
	public static final String FUND_TYPE='A';
	public static final String CONSUMER_TYPE='1';
	public static final String ACTIVITY='PP';
	
	List<Cart_Item__c> cartItems;
	Order_Window__c ow;
	Map<Id,Account> agencyMap;
	Map<Id,Ship_To__c> shipToMap;
	Map<Id,Brand__c> brandMap;
	Map<String,String> planningAccountMap; //Map of district codes to planning accounts
	Map<Id,Program__c> programMap;
	Map<Id,Item__c> itemMap;
	Map<Id,Order_Window__c> windowMap;
	
	String SPIRITS_COMPANY_CODE='2290';
	String WINES_COMPANY_CODE='2185';
	
	private String DIAGEO_SPIRITS_DISTRICT;
	private String DIAGEO_SPIRITS_RESPONSIBLE;
	private String DIAGEO_WINE_DISTRICT;
	private String DIAGEO_WINE_RESPONSIBLE;
	
	private String diageoId;
		
	
	public POS_WBSUtil (List<Cart_Item__c> cartItems) {
		
		
		//If a cart item comes through without a shipto we do not want 
		//to touch the WBS.  This should only happen when an update is processed
		//to an existing cart item		
		List<Cart_Item__c> cartItemsToProcess = new List<Cart_Item__c>();
		for (Cart_Item__c cartItem: cartItems) {
			if (cartItem.Ship_To__c!=null) {
				cartItemsToProcess.add(cartItem);
			}
		}
		
		this.cartItems=cartItemsToProcess;
		this.ow=ow;
		
		POS_Magento_Configuration__c settings = POS_Magento_Configuration__c.getOrgDefaults();
		this.DIAGEO_SPIRITS_DISTRICT=settings.Diageo_Spirits_District__c;
		this.DIAGEO_SPIRITS_RESPONSIBLE=settings.Diageo_Spirits_Responsible__c;
		this.DIAGEO_WINE_DISTRICT=settings.Diageo_Spirits_District__c;
		this.DIAGEO_WINE_RESPONSIBLE=settings.Diageo_Spirits_Responsible__c;
		
		List<Account> diageoAccounts = [select Id from Account where name='DIAGEO' and RecordType.Name='Distributor'];
		if (diageoAccounts.size()>0) {
			diageoId = diageoAccounts.get(0).Id;
		}
		else {
			if (Test.isRunningTest()) {
				//Existing unit tests can break here so we just fake an account for this
				//Shouldn't affect legitimate unit test
				Account fakeAccount = new Account();
				fakeAccount.Name='UNIT TEST ACCOUNT';
				insert fakeAccount;
				diageoId=fakeAccount.Id;
			}
		}
		
		//Get list of shiptos and query to get account/org unit information
		shipToMap = new Map<Id, Ship_To__c>();
		Set<Id> brandIds = new Set<Id>();
		Set<Id> programIds = new Set<Id>();
		List<Id> itemIds = new List<Id>();
		
		for (Cart_Item__c cartItem:cartItems) {
			if (cartItem.Ship_To__c==null) {
				//bad data, ignore it
				continue;
			}
			itemIds.add(cartItem.Item__c);
			shipToMap.put(cartItem.Ship_to__c,cartItem.Ship_to__r);
		}
		
		//Build map of items 
		itemMap=new Map<Id,Item__c>([select Id, Name, Agency__c, (select Id, Brand__c, Primary__c from Item_Brands__r where Primary__c = true), Channel__c, Program__c from Item__c
		 where Id in :itemIds]);
		 
		for (Id itemId:itemMap.keySet()) {
			Item__c item = itemMap.get(itemId);
			Id brandId = item.Item_Brands__r.get(0).Brand__c;
			brandIds.add(brandId);
			programIds.add(item.Program__c);
		}
		
		Set<Id> shipToIds=shipToMap.keySet();
		
		
		System.debug('SHIP TO IDs: '+shipToIds);
		
		shipToMap = new Map<Id,Ship_To__c>([select Id, Account__r.Spirits_Hierarchy__r.Responsible_Code__c, 
		  Account__r.Wine_Hierarchy__r.Responsible_Code__c, Account__r.Spirits_Hierarchy__r.District_Code__c,
		  Account__r.Wine_Hierarchy__r.District_Code__c,Account__r.Program_Code__c from Ship_To__c where Id in :shipToIds]);
		
		System.debug('Ship to map: '+shipToMap);
		
		//Build map of account ID to account objects for all shipto related accounts and the agency accounts
		agencyMap=new Map<Id,Account>([select Id,Spirits_Hierarchy__r.Responsible_Code__c,
		  Wine_Hierarchy__r.Responsible_Code__c, Spirits_Hierarchy__r.District_Code__c, Wine_Hierarchy__r.District_Code__c,
		  Program_Code__c from Account where Account.RecordType.Name='POS Production Agency']);
		  
		  
		System.debug('Accounts: '+agencyMap);
		
		//Build map of brand data
		brandMap = new Map<Id,Brand__c>([select Id, WBS_Level_3__c, WBS_Level_5__c, Parent_Brand__r.WBS_Level_5__c, 
		  Classification__c from Brand__c where Id in :brandIds]);
		
		
		//Build map of program data
		programMap = new Map<Id,Program__c>([select Id, Program_Code__c, Order_Window__r.Id, Order_Window__r.Name, Order_Window__r.Fiscal_Year__c from Program__c where Id in :programIds]);
		
		
		List<Planning_Account__c> planningAccounts = [select Name, District_Code__c, Sub_Channel_Code__c 
		  from Planning_Account__c];
		  
		System.debug('Planning accounts: '+planningAccounts);
		
		planningAccountMap=new Map<String,String>();
		for (Planning_Account__c pa:planningAccounts) {
			String key = pa.District_Code__c+':';
			if (pa.Sub_Channel_Code__c!=null) {
				key = key+pa.Sub_Channel_Code__c;
			}
			planningAccountMap.put(key,pa.Name);
		}
		
		System.debug('PA Map: '+planningAccountMap); 
		
		 
	}
	
	public List<Cart_Item__c> populateWBSData () {
		for (Cart_Item__c cartItem:cartItems) {
			populateSingleWBS(cartItem);
		}
		return cartItems;
	}
	
	private void populateSingleWBS (Cart_Item__c cartItem) {
		String WBS='';
		
		System.debug('CART ITEM SHIPTO: '+cartItem.Ship_To__c);
		//Get shipto account, agency, brand, and order window for this item
		
		Item__c item = itemMap.get(cartItem.Item__c);
		Account shipToAccount = (shipToMap.get(cartItem.Ship_To__c)).Account__r;
		Account agency = agencyMap.get(item.Agency__c);
		System.debug('PROGRAM: '+item.Program__c);
		Program__c program = programMap.get(item.Program__c);
		Order_Window__c ow = program.Order_Window__r;
		
		WBS=WBS+ow.Fiscal_Year__c.substring(3); //Get the last digit of the year
		
		
		Id primaryBrandId=null;
		
		
		for (Item_Brand__c itemBrand: item.Item_Brands__r) {
			if (itemBrand.Primary__c) {
				primaryBrandId=itemBrand.Brand__c;
			}
		}
		
		Brand__c brand = brandMap.get(primaryBrandId);
		
		
		//RESPONSIBILITY CODE//
		String responsibilityCode='??';  //Default to populating ?'s if we don't know
		if (brand.Classification__c=='Spirits') {
			if (shipToAccount.Spirits_Hierarchy__r!=null) {
				if (shipToAccount.Spirits_Hierarchy__r.Responsible_Code__c!=null) {
					responsibilityCode=shipToAccount.Spirits_Hierarchy__r.Responsible_Code__c;
				}
			}
			else if (shipToAccount.Id==diageoId) {
				responsibilityCode=this.DIAGEO_SPIRITS_RESPONSIBLE;
			}
		}
		else {
			if (shipToAccount.Wine_Hierarchy__r!=null) {
				if (shipToAccount.Wine_Hierarchy__r.Responsible_Code__c!=null) {
					responsibilityCode=shipToAccount.Wine_Hierarchy__r.Responsible_Code__c;
				}
			}
			else if (shipToAccount.Id==diageoId) {
				responsibilityCode=this.DIAGEO_WINE_RESPONSIBLE;
			}
		}
		
		WBS=WBS+responsibilityCode; 
		
		
	
		//PH CODES//
		String PH3Code='???';
		if (brand.WBS_Level_3__c!=null) {
			PH3Code=brand.WBS_Level_3__c; //PH3
		}
		
		WBS=WBS+PH3Code;
		
		String PH5Code='???';
		if (brand.WBS_Level_5__c==null) {
			if (brand.Parent_Brand__r.WBS_Level_5__c!=null) {
				PH5Code=brand.Parent_Brand__r.WBS_Level_5__c;
			}
		}
		else {
			PH5Code=brand.WBS_Level_5__c; //PH5
		}
		
		WBS=WBS+PH5Code;
		
		
		//FUND TYPE//
		WBS=WBS+FUND_TYPE; //Hard coded fund type
		
		//Channel//
		String channelCode=item.Channel__c=='Off-premise'?'9':'H'; //On or Off Channel (9 for Off, H for on)
		WBS=WBS+channelCode;
		
		// District Code //
		String districtCode='????';  
		
		if (brand.Classification__c=='Spirits') {
			if (shipToAccount.Spirits_Hierarchy__r.District_Code__c!=null) {
				districtCode=shipToAccount.Spirits_Hierarchy__r.District_Code__c;
			} 
			else if (shipToAccount.Id==diageoId) {
				districtCode=this.DIAGEO_SPIRITS_DISTRICT;
			}
		}
		else if (brand.Classification__c=='Wine') {
			if (shipToAccount.Wine_Hierarchy__r.District_Code__c!=null) {
				districtCode=shipToAccount.Wine_Hierarchy__r.District_Code__c;
			}
			else if (shipToAccount.Id==diageoId) {
				districtCode=this.DIAGEO_WINE_DISTRICT;
			}
		}
		
		System.debug('District code: "'+districtCode+'"');
		WBS=WBS+districtCode;

		String planningAccount='???';
		
		if (districtCode!='????') {
			planningAccount = planningAccountMap.get(districtCode+':'+channelCode);
			if (planningAccount==null) {
				//try without a channel code
				planningAccount = planningAccountMap.get(districtCode+':');
				if (planningAccount==null) {
					planningAccount='???';
				}
			}
		}
		
		System.debug('Planning account: '+planningAccount);
		
		WBS=WBS+planningAccount;
		
		// PROGRAM CODE //
		String programCode='???';
		
		if (program.Program_Code__c!=null) {
			programCode = program.Program_Code__c;
		}
		else {
			//Try to get it from the agency
			if (agency.Program_Code__c!=null) {
				programCode = agency.Program_Code__c;
			}
		}
		
		WBS=WBS+programCode; //Program code
		
		// HARD CODED REMAINING VALUES //
		WBS=WBS+CONSUMER_TYPE;
		WBS=WBS+ACTIVITY;
		
		//Set the value
		cartItem.WBS__c=WBS;
		
		//Then update company code as well
		if (brand.Classification__c=='Spirits') {
			cartItem.Company_Code__c=SPIRITS_COMPANY_CODE;
		}
		else if (brand.Classification__c=='Wine') {
			cartItem.Company_Code__c=WINES_COMPANY_CODE;
		}
		
	}
	
	@isTest
	public static void testWBS () {
		
		//Get the current time
    	Datetime now = System.now();
    	
    	Profile p = [select id from profile where name='System Administrator'];
         
		User u = new User(alias = 'posmmtst', email='posmmunittest@diageo.com',
        emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US',
		localesidkey='en_US', profileid = p.Id,
		timezonesidkey='America/Chicago', username='posmmunittest@diageo.com');
		
		
		System.runAs(u) {
			
			POS_TestDataUtil.initializeTestData();
    	
    		//Create Agency
    		Account agency = POS_TestDataUtil.createProductionAgency();
    		Account account = POS_TestDataUtil.createAccount();
    		Account_Member__c member = POS_TestDataUtil.createAccountMember(account,u);

			Planning_Account__c pa = new Planning_Account__c();
			pa.Name='PAC';
			pa.District_Code__c='DIST';
			pa.Sub_Channel_Code__c = 'H';
			insert pa;

			Organizational_Unit__c org = new Organizational_Unit__c();
			org.District_Code__c = 'DIST'; 
			org.Responsible_Code__c = 'RC';
			insert org;
			
			account.Spirits_Hierarchy__c = org.Id;
			update account;
	    	
	    	Brand__c brand = POS_TestDataUtil.createBrand();
	    	brand.WBS_Level_3__c = 'PH3';
	    	brand.WBS_Level_5__c = 'PH5';
	    	brand.Classification__c = 'Spirits';
	    	update brand;
	    	
	    	Order_Window__c ow = POS_TestDataUtil.createOrderWindow();
	    	
	    	Program__c program = POS_TestDataUtil.createProgram(brand.Id,ow.Id);
	    	program.Program_Code__c='PRG';
	    	update program;
	    	
	    	Item__c item = POS_TestDataUtil.populateItem(program, agency);
	    	item.Channel__c = 'On-Premise';
	    	
	    	insert item;
	    	
	    	
	    	Cart__c crt = POS_TestDataUtil.createCart(u, ow);
	    	
	    	Cart_Item__c ci = POS_TestDataUtil.populateCartItem(item, crt);
	    	Ship_To__c shipTo = POS_TestDataUtil.createShipTo(account);
	    	ci.Ship_To__c = shipTo.Id;
	    	
	    	insert ci;
	    	 
	    	List<Cart_Item__c> cartItems = new List<Cart_Item__c>();
	    	cartItems.add(ci);
	    	
	    	POS_WBSUtil util = new POS_WBSUtil(cartItems);
	    	cartItems = util.populateWBSData();
			
			System.debug('WBS: '+ci.WBS__c);
		 	System.assert(ci.WBS__c == '2RCPH3PH5AHDISTPACPRG1PP');
		 	System.assert(ci.Company_Code__c=='2290');
		 	
		 	//Now test without a heirarchy
		 	account.Spirits_Hierarchy__c=null;
		 	update account;
		 	
		 	util = new POS_WBSUtil(cartItems);
		 	cartItems = util.populateWBSData();
		 	System.debug('WBS NOW: '+ci.WBS__c);
		 	System.assert(ci.WBS__c == '2??PH3PH5AH???????PRG1PP');
		 	
		 	//Now test without a shipto in an update
		 	ci = [select Id from Cart_Item__c where Id=:ci.Id];
		 	ci.Ship_To__c=null;
		 	cartItems = new List<Cart_Item__c>();
		 	cartItems.add(ci);
		 	util = new POS_WBSUtil(cartItems);
		 	cartItems = util.populateWBSData();
		 	
		 	//No need for assertion here, if it fails we'll get an exception
		}
	}
}