TestRepo2/src/objects/Account_Member__c.object
<CustomObject>
    <description>POS Project: junction object that represents the many-to-many relationship between Accounts and Users (Shoppers)</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Members</relationshipLabel>
        <relationshipName>Account_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Default__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Default</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Account_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Member</label>
    <nameField>
        <displayFormat>ACM-{000000}</displayFormat>
        <label>Account Member ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestRepo2/src/classes/Test_AccountTeamMemberTrigger.cls
@isTest
public class Test_AccountTeamMemberTrigger {

	public static testmethod void testTrigger(){
		Test.starttest();
			Id uid = Userinfo.getUserId();
			Account account = new Account(Name = 'a');
			insert account;
			User user = new User(Id = uid); 
			Account_Member__c member = new Account_Member__c(Account__c = account.id, User__c = user.Id);
			insert member;
			
			Account_Member__c member1a = new Account_Member__c(User__c = uid, Account__c=account.id, Default__c = true);
			Account_Member__c member1 = new Account_Member__c(User__c = uid, Account__c=account.id, Default__c = true);
			Account_Member__c member2 = new Account_Member__c(User__c = uid, Account__c=account.id, Default__c = true);
			insert member1a;
			List<Account_Member__c> members = new List<Account_Member__c>();
			members.add(member1);
			members.add(member2);
			try{
				insert members;
				system.assert(false);
			} catch(Exception ex){
				//ok
			}
			delete member;
			try{
				delete member1a;
				system.assert(false);
			} catch(Exception ex){
				//ok
			}
		Test.stoptest(); 
	}

}