TestRepo2/src/objects/Account_Member__c.object
<CustomObject>
    <description>POS Project: junction object that represents the many-to-many relationship between Accounts and Users (Shoppers)</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Members</relationshipLabel>
        <relationshipName>Account_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Account_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Member</label>
    <nameField>
        <displayFormat>ACM-{000000}</displayFormat>
        <label>Account Member ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestRepo2/src/objects/AccountBrand__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>AccountBrand</relationshipLabel>
        <relationshipName>AccountBrand1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipLabel>AccountBrand</relationshipLabel>
        <relationshipName>AccountBrand1</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>AccountBrand</label>
    <nameField>
        <label>AccountBrand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AccountBrand</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestRepo2/src/objects/Brand__c.object
<CustomObject>
    <fields>
        <fullName>Magento_Id__c</fullName>
        <externalId>true</externalId>
        <label>Magento Id</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/Order_Window__c.object
<CustomObject>
    <description>POS Project: object that represents a period of time in which catalog items are offered and shoppers are allowed to buy them</description>
    <fields>
        <fullName>Icon_Label__c</fullName>
        <label>Icon Label</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Magento_Id__c</fullName>
        <externalId>true</externalId>
        <label>Magento Category Id</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>On_Demand_Site_URL__c</fullName>
        <label>On Demand Site URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Order_Close_Date__c</fullName>
        <label>Order Close Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Order_Delivery_Date__c</fullName>
        <label>Order Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Order_Start_Date__c</fullName>
        <label>Order Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <controllingField>Type__c</controllingField>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Budgeting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Archived</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Quarterly</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Demand</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Order Window</label>
    <nameField>
        <label>Order Window Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Windows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/Order_Window_Customer__c.object
<CustomObject>
    <description>POS Project: junction object that represents the many-to-many relationship between Order Windows and Users (customers)</description>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Order_Window_Customers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Magento_Id__c</fullName>
        <externalId>true</externalId>
        <label>Magento Id</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Open_For_Shopping__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Open for Shopping</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Order_Window__c</fullName>
        <label>Order Window</label>
        <referenceTo>Order_Window__c</referenceTo>
        <relationshipLabel>Order Window Customers</relationshipLabel>
        <relationshipName>Order_Window_Customers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Order Window Customer</label>
    <nameField>
        <displayFormat>OWC-{000000}</displayFormat>
        <label>Order Window Customer ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Window Customers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestRepo2/src/objects/POS_Magento_Configuration__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>stores all values like API key, User Name, Endpoint etc. required for Magento Integration service</description>
    <fields>
        <fullName>IDP_Url__c</fullName>
        <description>The URL to the Salesforce IDP initiated SSO</description>
        <label>IDP Url</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Magento_Catalog_Path__c</fullName>
        <label>Magento_Catalog_Path</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>POS Magento Configuration</label>
</CustomObject>

TestRepo2/src/objects/Program__c.object
<CustomObject>
    <description>POS Project: object that represents a set of events for which related catalog items are offered to shoppers (distributors and internal Diageo employees)</description>
    <fields>
        <fullName>Brand__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Magento_Id__c</fullName>
        <externalId>true</externalId>
        <label>Magento Category Id</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Window__c</fullName>
        <label>Order Window</label>
        <referenceTo>Order_Window__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestRepo2/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Magento_Id__c</fullName>
        <externalId>true</externalId>
        <label>Magento_Id</label>
        <length>80</length>
        <type>Text</type>
    </fields>
</CustomObject>

TestRepo2/src/classes/POS_OrderWindowViewController.cls
public class POS_OrderWindowViewController extends Controller_Base {

	public List <Order_Window_Customer__c> orderWindowCustomers {get;set;}
	public String baseUrl {get;set;}
	public String idpUrl {get;set;}
	
	public List<POS_BreadCrumb> breadcrumbs {get;set;} 
	public boolean ssoComplete {get;set;}
	//public boolean hasBrands {get;set;}
	
	//Maps magento Id for window to brand availability for user
	public Map <String,boolean> hasBrands {get;set;}
	
	public String hasBrandsJson {get;set;}
	
	
	
	public POS_OrderWindowViewController () {
		
		Id currentUser=UserInfo.getUserId();
		
		List<String> listOfVisibleWindowMagentoIds = new List<String>();
		
		//populate the order windows
		List <Order_Window_Customer__c> loadedOwc = [Select Open_For_Shopping__c, o.Order_Window__r.Name, o.Order_Window__r.Type__c, 
		 o.Order_Window__r.Status__c, o.Order_Window__r.Order_Start_Date__c, 
		 o.Order_Window__r.Order_Delivery_Date__c, o.Order_Window__r.Order_Close_Date__c, 
		 o.Order_Window__r.On_Demand_Site_URL__c, o.Order_Window__r.Magento_Id__c, 
		 o.Order_Window__r.Icon_Label__c from Order_Window_Customer__c o
		 where Customer__c = :currentUser and o.Order_Window__r.Status__c in ('Open','Budgeting','Closed', 'In Review') 
		 order by o.Order_Window__r.Type__c, o.Order_Window__r.Order_Start_Date__c
		]; 
		
		orderWindowCustomers=new List<Order_Window_Customer__c>();
		
		
		boolean foundQuarterly=false;
		boolean foundMonthly=false;
		
		//Need to filter order windows to ensure they meet business reqs beyond the initial query
		for (Order_Window_Customer__c owc:loadedOwc) {
			if (owc.Open_For_Shopping__c) {
				//Add any windows that are open to this user
				orderWindowCustomers.add(owc);
				listOfVisibleWindowMagentoIds.add(owc.Order_Window__r.Magento_Id__c);
				if (owc.Order_Window__r.Type__c=='Quarterly') {
					foundQuarterly=true;
					System.debug('FOUND QUARTERLY');
				}
				if (owc.Order_Window__r.Type__c=='Monthly'){
					foundMonthly=true;
					System.debug('FOUND MONTHLY');

				}
			}
			else {
				//If the window is not open to this user, add if it was recently closed
				if (owc.Order_Window__r.Status__c=='Closed') {
					DateTime thisTime = System.now();
					DateTime pastTime=thisTime.addDays(-5);
					if (pastTime<owc.Order_Window__r.Order_Close_Date__c &&
					     owc.Order_Window__r.Order_Close_Date__c<thisTime) {
						orderWindowCustomers.add(owc);
						if (owc.Order_Window__r.Type__c=='Quarterly') {
							foundQuarterly=true;
						}
						if (owc.Order_Window__r.Type__c=='Monthly'){
							foundMonthly=true;
						}
					}
				}
			}
		}
		
		//Now, if there aren't any order windows we need to just include the next 
		//upcoming window
		
		if (!foundQuarterly || !foundMonthly) {
			for (Order_Window_Customer__c owc:loadedOwc) {
				if (owc.Order_Window__r.Status__c=='In Review' || owc.Order_Window__r.Status__c=='Budgeting') {
					if (owc.Order_Window__r.Type__c=='Quarterly') {
						if (foundQuarterly) {
							continue;
						}
						else {
							System.debug('Added quarterly open window');
							orderWindowCustomers.add(owc);
							foundQuarterly=true;
						}
					}
					else if (owc.Order_Window__r.Type__c=='Monthly'){
						if (foundMonthly) {
							continue;
						}
						else {
							System.debug('Added monthly open window');
							orderWindowCustomers.add(owc);
							foundMonthly=true;
						}
					}
					
				}
			}
		}
		
		//Get a list of visible order windows 
		//populateBrandList(listOfVisibleWindowMagentoIds, currentUser);
		
		
		System.debug('Order windows: '+orderWindowCustomers);
		
		POS_Magento_Configuration__c settings = POS_Magento_Configuration__c.getOrgDefaults();
       	baseUrl = settings.Magento_Catalog_Path__c;
       	idpUrl = settings.IDP_Url__c;
		
		
       	breadCrumbs = new List<POS_BreadCrumb>();
       	breadCrumbs.add(new POS_BreadCrumb('POS','#'));
		
	    
	}
	
	//This is commented out because the call to this method was commented out above.  
	/*private void populateBrandList (List<String> displayedOrderWindowMagentoIds, String currentUser) {
		//Get list of user's brands
		List<AccountBrand__c> accountBrands = [select Id,Brand__c from AccountBrand__c where Account__c in (select Account__c from Account_Member__c where User__c = :currentUser)];
	
		List<Program__c> programs = [select Brand__c, Order_Window__r.Magento_Id__c from Program__c where Order_Window__r.Magento_Id__c in :displayedOrderWindowMagentoIds];
		
		//Build map of brands to order windows
		Map<Id,List<Order_Window__c>> brandToWindowMap = new Map<Id,List<Order_Window__c>>();
		for (Program__c program:programs) {
			List<Order_Window__c> windowList = brandToWindowMap.get(program.Brand__c);
			if (windowList == null) {
				windowList = new List<Order_Window__c>();
		    	brandToWindowMap.put(program.Brand__c,windowList);
			}
			windowList.add(program.Order_Window__r);
		}
		
		//Now iterate through account brands and flag the windows that are allowed
		
		//First, initialize the map with false values
		for (String id:displayedOrderWindowMagentoIds) {
			hasBrands.put(id,false);
		}
		
		//Now add trues where applicable
		for (AccountBrand__c acctBrand:accountBrands) {
			List<Order_Window__c> windowList = brandToWindowMap.get(acctBrand.Brand__c);
			for (Order_Window__c window:windowList) {
				hasBrands.put(window.Magento_Id__c,true);
			}
		}
		
		hasBrandsJson='';
		//hasBrandsJson = System.JSON.serialize(hasBrands);
	}*/

	
	@isTest
	public static void testOrderWindow () {
		Profile p = [select id from profile where name='System Administrator'];
         
		User u = new User(alias = 'posmmtst', email='posmmunittest@diageo.com',
        emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US',
		localesidkey='en_US', profileid = p.Id,
		timezonesidkey='America/Chicago', username='posmmunittest@diageo.com');
		
		System.runAs(u) {
			Test.startTest();
			PageReference pageRef = Page.HomePage;
        	Test.setCurrentPage(pageRef);
        	
			Order_Window__c ow = POS_TestDataUtil.createOrderWindow();
			
			Order_Window_Customer__c owc = new Order_Window_Customer__c();
			owc.Customer__c = u.Id;
			owc.Order_Window__c = ow.Id;
			insert owc;
			
			POS_OrderWindowViewController controller = new POS_OrderWindowViewController();
			
			//Should have zero right now because window was in wrong state
			System.assert(controller.orderWindowCustomers.size()==0);
			
			ow.Status__c='Open';
			update ow;
			owc.Open_For_Shopping__c = true;
			update owc;
			
			
			controller = new POS_OrderWindowViewController();
			//Should have one right now because window is in open state
			System.assert(controller.orderWindowCustomers.size()==1);
			
			ow.Status__c='Closed';
			update ow;
			owc.Open_For_Shopping__c = false;
			update owc;
			
			controller = new POS_OrderWindowViewController();
			//Should have none right now because window is closed and not open for shopping
			System.assert(controller.orderWindowCustomers.size()==0);
			
			ow.Status__c='Budgeting';
			update ow;
			owc.Open_For_Shopping__c = false;
			update owc;
			
			controller = new POS_OrderWindowViewController();
			
			Test.stopTest();
			
		}
	}
	    
    // for HTML conditional comments
    public String getLt(){
		return '<';
	}
		
	public String getGt(){
		return '>';
	}	
}