TestRepo2/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Program_Code__c</fullName>
        <label>Program Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Spirits_Hierarchy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Spirits Hierarchy</label>
        <referenceTo>Organizational_Unit__c</referenceTo>
        <relationshipLabel>Accounts (Spirits Hierarchy)</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

TestRepo2/src/objects/Account_Member__c.object
<CustomObject>
    <description>POS Project: junction object that represents the many-to-many relationship between Accounts and Users (Shoppers)</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Members</relationshipLabel>
        <relationshipName>Account_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Account Member</label>
    <nameField>
        <displayFormat>ACM-{000000}</displayFormat>
        <label>Account Member ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestRepo2/src/objects/Brand__c.object
<CustomObject>
    <fields>
        <fullName>Classification__c</fullName>
        <label>Classification</label>
        <picklist>
            <picklistValues>
                <fullName>Beer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Spirits</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wine</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Alcoholic Beverage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NOT DEFINED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trading Goods (Non Beverage)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TBA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>WBS_Level_3__c</fullName>
        <label>WBS Level 3</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WBS_Level_5__c</fullName>
        <label>WBS Level 5</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/Cart__c.object
<CustomObject>
    <description>POS Project: object that represents a shopping cart</description>
    <fields>
        <fullName>Order_Window__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Window</label>
        <referenceTo>Order_Window__c</referenceTo>
        <relationshipLabel>Carts</relationshipLabel>
        <relationshipName>Carts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Processing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Removed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Cart</label>
    <nameField>
        <displayFormat>CRT-{00000000}</displayFormat>
        <label>Cart ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Carts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/Cart_Item__c.object
<CustomObject>
    <description>POS Project: junction object that represents the many-to-many relationship between Carts and Items</description>
    <fields>
        <fullName>Cart__c</fullName>
        <label>Cart</label>
        <referenceTo>Cart__c</referenceTo>
        <relationshipLabel>Cart Items</relationshipLabel>
        <relationshipName>Carts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Company_Code__c</fullName>
        <label>Company Code</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Manual_WBS__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Manual WBS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Item__c</fullName>
        <label>Item</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>Cart Items</relationshipLabel>
        <relationshipName>Cart_Items</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Ship_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To</label>
        <referenceTo>Ship_To__c</referenceTo>
        <relationshipLabel>Cart Items</relationshipLabel>
        <relationshipName>Cart_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Selected</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Processing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shipped</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>WBS__c</fullName>
        <label>WBS</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Cart Item</label>
    <nameField>
        <displayFormat>CIT-{0000000000}</displayFormat>
        <label>Cart Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cart Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestRepo2/src/objects/Item__c.object
<CustomObject>
    <description>POS Project: object that represents catalog items available for shopping</description>
    <fields>
        <fullName>Brand__c</fullName>
        <formula>IF(Brand_Count__c &lt; 1, &quot;&quot;, IF(Program__r.Brand__r.Portfolio_Brand__c, &quot;Portfolio&quot;, Program__r.Brand__r.Name))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Channel__c</fullName>
        <label>Channel</label>
        <picklist>
            <picklistValues>
                <fullName>Off-premise</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On-premise</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Development</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Approved w/Est Price</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted w/Final Price</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Removed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

TestRepo2/src/objects/Order_Window__c.object
<CustomObject>
    <description>POS Project: object that represents a period of time in which catalog items are offered and shoppers are allowed to buy them</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <controllingField>Type__c</controllingField>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Budgeting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Archived</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Order Window</label>
    <nameField>
        <label>Order Window Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Windows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/Organizational_Unit__c.object
<CustomObject>
    <description>POS Project: object that represents a hierarchy level within the distributors hierarchy</description>
    <fields>
        <fullName>District_Code__c</fullName>
        <label>District Code</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Responsible_Code__c</fullName>
        <label>Responsible Code</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <label>Organizational Unit</label>
    <nameField>
        <label>Organizational Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organizational Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/Planning_Account__c.object
<CustomObject>
    <fields>
        <fullName>District_Code__c</fullName>
        <label>District Code</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Channel_Code__c</fullName>
        <label>Sub Channel Code</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <label>Planning Account</label>
    <nameField>
        <label>Planning Account Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Planning Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/Program__c.object
<CustomObject>
    <description>POS Project: object that represents a set of events for which related catalog items are offered to shoppers (distributors and internal Diageo employees)</description>
    <fields>
        <fullName>Brand__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Window__c</fullName>
        <label>Order Window</label>
        <referenceTo>Order_Window__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Program_Code__c</fullName>
        <label>Program Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestRepo2/src/objects/Ship_To__c.object
<CustomObject>
    <description>POS Project: object that represents a delivery address associated to a particular account</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Ship To&apos;s</relationshipLabel>
        <relationshipName>Ship_Tos</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Ship To</label>
    <nameField>
        <label>Ship To Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ship To&apos;s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestRepo2/src/classes/POS_BatchUpdateCartItems.cls
/**
Batch that periodically updates any missing or invalid WBS numbers

*/
global class POS_BatchUpdateCartItems implements Database.Batchable<sObject> {


    String query = 'select Id, Ship_To__c, Item__c, Ship_To__r.Account__c, WBS__c, Company_Code__c '+
     ' from Cart_Item__c where Ship_To__c != null and '+
     ' '+
     ' Item__r.Program__r.Order_Window__r.Status__c not in (\'Archived\',\'In Review\',\'Budgeting\') ';
    // (WBS__c=null or WBS__c like \'%?%\') and
    
    List<String> orderWindowId= new List<String>();
    Boolean isFull=false;

    /*public POS_BatchUpdateCartItems (String orderWindowId) {
        this.orderWindowId=orderWindowId;
    }*/
    
    /*
       since the trigger needs to be bulkified we will make order window id as list
    */
    public POS_BatchUpdateCartItems (Boolean isFull,List<String> orderWindowId) {
            
            this.orderWindowId=orderWindowId;
            this.isFull=isFull;
    }
    
    global database.queryLocator start(Database.BatchableContext BC) 
    {
        if(!isFull){
            query = query +' and (WBS__c=null or WBS__c like \'%?%\') AND Is_Manual_WBS__c=false';
        }
        
        if(isFull){
            query = query +' and Is_Manual_WBS__c=false';
        }
        
        if (orderWindowId!=null && orderWindowId.size()>0) {
            //query = query +' and Item__r.Program__r.Order_Window__c = \''+orderWindowId+'\'';
            query = query +' and Item__r.Program__r.Order_Window__c IN: orderWindowId';
        }
        
        if (Test.isRunningTest()) {
            query=query+' LIMIT 100';
        }
        return database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Cart_Item__c> cartItems){
        
        System.debug('Cart Items: '+cartItems);
        POS_WBSUtil util = new POS_WBSUtil(cartItems);
        cartItems = util.populateWBSData(); 
        System.debug('Cart Items with WBS: '+cartItems);
        update cartItems;
        
        
            
    }

    global void finish(Database.BatchableContext BC) {
        
    }
    
    @isTest 
    public static void testUpdateCartItems () {
        
        Test.startTest();
        POS_BatchUpdateCartItems batch = new POS_BatchUpdateCartItems(false,null);
        Database.executeBatch(batch);
        Test.stopTest();
        
    }
    
    @isTest
    public static void testWBSBatch () {
        
        //Get the current time
        Datetime now = System.now();
        
        Profile p = [select id from profile where name='System Administrator'];
         
        User u = new User(alias = 'posmmtst', email='posmmunittest@diageo.com',
        emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US',
        localesidkey='en_US', profileid = p.Id,
        timezonesidkey='America/Chicago', username='posmmunittest@diageo.com');
        
        
        System.runAs(u) {
            POS_TestDataUtil.initializeTestData();
        
            //Create Agency
            Account agency = POS_TestDataUtil.createProductionAgency();
            Account account = POS_TestDataUtil.createAccount();
            Account_Member__c member = POS_TestDataUtil.createAccountMember(account,u);

            Planning_Account__c pa = new Planning_Account__c();
            pa.Name='PAC';
            pa.District_Code__c='DIST';
            pa.Sub_Channel_Code__c = 'H';
            insert pa;

            Organizational_Unit__c org = new Organizational_Unit__c();
            org.District_Code__c = 'DIST'; 
            org.Responsible_Code__c = 'RC';
            insert org;
            
            account.Spirits_Hierarchy__c = org.Id;
            update account;
            
            Brand__c brand = POS_TestDataUtil.createBrand();
            brand.WBS_Level_3__c = 'PH3';
            brand.WBS_Level_5__c = 'PH5';
            brand.Classification__c = 'Spirits';
            update brand;
            
            Order_Window__c ow = POS_TestDataUtil.createOrderWindow();
            
            Program__c program = POS_TestDataUtil.createProgram(brand.Id,ow.Id);
            program.Program_Code__c='PRG';
            update program;
            
            Item__c item = POS_TestDataUtil.populateItem(program, agency);
            item.Channel__c = 'On-Premise';
            
            insert item;
            
            
            Cart__c crt = POS_TestDataUtil.createCart(u, ow);
            
            Cart_Item__c ci = POS_TestDataUtil.populateCartItem(item, crt);
            Ship_To__c shipTo = POS_TestDataUtil.createShipTo(account);
            ci.Ship_To__c = shipTo.Id;
            
            insert ci;
             
            System.debug('Cart Item ID: '+ci);
            List<Cart_Item__c> cartItems = new List<Cart_Item__c>();
            cartItems.add(ci);
            POS_WBSUtil util = new POS_WBSUtil(cartItems);
            cartItems = util.populateWBSData(); 
            System.assert(ci.WBS__c == '2RCPH3PH5AHDISTPACPRG1PP');
            System.assert(ci.Company_Code__c=='2290');
        
            
            Test.startTest();
            POS_BatchUpdateCartItems batch = new POS_BatchUpdateCartItems(false,null);
            Database.executeBatch(batch);
            Test.stopTest();
            
            ci = [select Id,WBS__c,Company_Code__c from Cart_Item__c where Id=:ci.Id];
            System.debug('WBS: '+ci.WBS__c);
            System.assert(ci.WBS__c == '2RCPH3PH5AHDISTPACPRG1PP');
            System.assert(ci.Company_Code__c=='2290');
             
        }
    }
}