TestRepo2/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>State__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>State</label>
        <referenceTo>State__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

TestRepo2/src/objects/Brand__c.object
<CustomObject>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/Calendar__c.object
<CustomObject>
    <label>Calendar</label>
    <nameField>
        <label>Calendar Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Calendar</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

TestRepo2/src/objects/Goal__c.object
<CustomObject>
    <fields>
        <fullName>Action_Complete__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Completed Actions</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Goal_For__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Goal For</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Goals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Goal_Level__c</fullName>
        <label>Goal Level</label>
        <picklist>
            <picklistValues>
                <fullName>Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rep</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Goal_Type__c</fullName>
        <label>Goal Type</label>
        <picklist>
            <picklistValues>
                <fullName>On-Premise - Control</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Off-Premise - Control</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Minimum_of_Accounts__c</fullName>
        <label>Goal</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Parent_Goal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Goal</label>
        <referenceTo>Goal__c</referenceTo>
        <relationshipLabel>Child Goals</relationshipLabel>
        <relationshipName>Child_Goals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Start_Date__c</fullName>
        <formula>Program__r.Start_Date__c</formula>
        <label>Program Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Calendar__c</referenceTo>
        <relationshipLabel>Goals</relationshipLabel>
        <relationshipName>Goals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WY</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Goal</label>
    <nameField>
        <label>Goal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Goals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

TestRepo2/src/objects/Order_Window__c.object
<CustomObject>
    <description>POS Project: object that represents a period of time in which catalog items are offered and shoppers are allowed to buy them</description>
    <label>Order Window</label>
    <nameField>
        <label>Order Window Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Windows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/Program__c.object
<CustomObject>
    <description>POS Project: object that represents a set of events for which related catalog items are offered to shoppers (distributors and internal Diageo employees)</description>
    <fields>
        <fullName>Brand__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Calendar__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Calendar</label>
        <referenceTo>Calendar__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Window__c</fullName>
        <label>Order Window</label>
        <referenceTo>Order_Window__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestRepo2/src/objects/State__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>State</label>
    <nameField>
        <label>State</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/classes/ActionCompleteDashboardTest.cls
@isTest
private class ActionCompleteDashboardTest {
	/*
    static testMethod void testActionCompleteDashboardController() {
        ActionCompleteDashboardController cont = new ActionCompleteDashboardController();
          //Update by Akanksha(CM Offshore)
        Date startD = Date.today();
		Date endD = Date.today().addDays(7);
		Order_Window__c ow = POS_TestDataUtil.createOrderWindow();
        Brand__c  bd = POS_TestDataUtil.createBrand();
        Account account = Test_Helper.testInsertAccount('testAcct');
        Program__c o = new Program__c(Name = 'Test Program1', Order_Window__c=ow.id, Brand__c=bd.id);
        insert o;
		Calendar__c cal = Test_Helper.testCreateCalendar('test1','Integrated National Program','tesSegment','1','desc', startD, endD, true, true);
		insert cal;
		User testUser = Test_Helper.generateTestUser('A4L91', true, 'Diageo - Sales Manager');
		account.OwnerId = testUser.Id;
		update account;
		//State__c s = new State__c(Name = 'State ' + i, Name__c = 'State ' + i);
		
        Goal__c dirGoal = new Goal__c();
    	dirGoal.Minimum_of_Accounts__c = 1;
    	dirGoal.Goal_Level__c = 'Director';
    	dirGoal.Name = 'dirGoal';
    	//dirGoal.Program_Start_Date__c = startD; 
    	dirGoal.Due_Date__c = endD;
    	dirGoal.Goal_Type__c = 'Combined Premise - Control';
    	dirGoal.Action_Complete__c = 1;
    	dirGoal.Program__c = cal.id;
    	dirGoal.State__c = 'Alabama';
    	dirGoal.Due_Date__c =  Date.today().addDays(10);
    	dirGoal.Goal_For__c = testUser.id;
    	insert dirGoal;
    	system.debug('#######dirGoal'+dirGoal);
    	system.debug('#######cal'+cal);
    	
		Goal__c mgrGoal = new Goal__c();
    	mgrGoal.Minimum_of_Accounts__c = 1;
    	mgrGoal.Goal_Level__c = 'Manager';
    	mgrGoal.Parent_Goal__c = dirGoal.Id;
    	mgrGoal.Name = 'mgrGoal';
    	mgrGoal.Due_Date__c = endD;
    	mgrGoal.Goal_Type__c = 'Combined Premise - Control';
    	mgrGoal.Action_Complete__c = 1;
    	mgrGoal.Program__c = cal.id;
    	mgrGoal.State__c = 'Michigan';
    	dirGoal.Due_Date__c =  Date.today().addDays(10);
    	dirGoal.Goal_For__c = testUser.id;
    	insert mgrGoal;
    	system.debug('#######mgrGoal'+mgrGoal);
    	
		Goal__c repGoal = new Goal__c();
    	repGoal.Minimum_of_Accounts__c = 1;
    	repGoal.Goal_Level__c = 'Rep';
    	repGoal.Parent_Goal__c = mgrGoal.Id;
    	repGoal.Name = 'repGoal';
    	repGoal.Due_Date__c = endD;
    	repGoal.Goal_Type__c = 'Combined Premise - Control';
    	repGoal.Action_Complete__c = 1;
    	repGoal.Program__c = cal.id;
    	repGoal.State__c = 'Michigan';
    	dirGoal.Due_Date__c =  Date.today().addDays(10);
    	dirGoal.Goal_For__c = testUser.id;
    	insert repGoal;
    	system.debug('#######repGoal'+repGoal);
    	
        cont.mode = 'exec';
        cont.chart = 'state';
        
        cont.mode = 'exec';
        cont.chart = 'west';
        cont.init();
        
        cont.mode = 'exec';
        cont.chart = 'east';
        cont.init();
        
        cont.mode = 'exec';
        cont.chart = 'goalFor';
        cont.init();
        
        cont.mode = 'dir';
        cont.chart = 'state';
        cont.init();
        
        cont.mode = 'dir';
        cont.chart = 'west';
        cont.init();
        
        cont.mode = 'dir';
        cont.chart = 'east';
        cont.init();
        
        
        cont.mode = 'mgr';
        cont.chart = 'state';
        cont.init();
        
        cont.mode = 'mgr';
        cont.chart = 'prog';
        cont.init();
        
        
        cont.mode = 'rep';
        cont.chart = 'state';
        cont.init();
        
        cont.mode = 'rep';
        cont.chart = 'prog';
        cont.init();
        
        cont.nameChanged();
      	cont.typeChanged();
    	cont.forChanged();
        cont.chanChanged();
        cont.rtChanged();
    }
    */
}