TestRepo2/src/objects/Account_Member__c.object
<CustomObject>
    <description>POS Project: junction object that represents the many-to-many relationship between Accounts and Users (Shoppers)</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Members</relationshipLabel>
        <relationshipName>Account_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Account_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Member</label>
    <nameField>
        <displayFormat>ACM-{000000}</displayFormat>
        <label>Account Member ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestRepo2/src/objects/AccountBrand__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>AccountBrand</relationshipLabel>
        <relationshipName>AccountBrand1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipLabel>AccountBrand</relationshipLabel>
        <relationshipName>AccountBrand1</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>AccountBrand</label>
    <nameField>
        <label>AccountBrand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AccountBrand</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestRepo2/src/objects/Brand__c.object
<CustomObject>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/Budget__c.object
<CustomObject>
    <description>POS Project: object that represents an estimate of expenditure for a given brand, order window and shopper</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Budgets</relationshipLabel>
        <relationshipName>Budgets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipLabel>Budgets</relationshipLabel>
        <relationshipName>Budgets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Window__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Window</label>
        <referenceTo>Order_Window__c</referenceTo>
        <relationshipLabel>Budgets</relationshipLabel>
        <relationshipName>Budgets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Organizational_Unit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organizational Unit</label>
        <referenceTo>Organizational_Unit__c</referenceTo>
        <relationshipLabel>Budgets</relationshipLabel>
        <relationshipName>Budgets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Budgets</relationshipLabel>
        <relationshipName>Budgets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Budget</label>
    <nameField>
        <displayFormat>BDG-{0000000}</displayFormat>
        <label>Budget ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budgets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/Order_Window__c.object
<CustomObject>
    <description>POS Project: object that represents a period of time in which catalog items are offered and shoppers are allowed to buy them</description>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Quarterly</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Demand</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Order Window</label>
    <nameField>
        <label>Order Window Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Windows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/Organizational_Unit__c.object
<CustomObject>
    <description>POS Project: object that represents a hierarchy level within the distributors hierarchy</description>
    <fields>
        <fullName>Label__c</fullName>
        <label>Label</label>
        <picklist>
            <picklistValues>
                <fullName>Division</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Market</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>State District</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Region</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Spirits</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wine</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Organizational Unit</label>
    <nameField>
        <label>Organizational Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organizational Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/Program__c.object
<CustomObject>
    <description>POS Project: object that represents a set of events for which related catalog items are offered to shoppers (distributors and internal Diageo employees)</description>
    <fields>
        <fullName>Brand__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Window__c</fullName>
        <label>Order Window</label>
        <referenceTo>Order_Window__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestRepo2/src/classes/POS_TestBudgetingGridController.cls
@isTest
public class POS_TestBudgetingGridController {
	public static testmethod void test(){
		Test.startTest();
		
		User currUser = [select id from User where id = :Userinfo.getUserId()];
		System.runas(currUser){
			
			POS_TestDataUtil.initializeTestData();
			Order_Window__c orderWindow = POS_TestDataUtil.createOrderWindow();
			Brand__c brand 				= POS_TestDataUtil.createBrand();
			Program__c program 			= POS_TestDataUtil.createProgram(brand.id, orderWindow.id);
			User user 					= POS_TestDataUtil.createStdUser();
			Organizational_Unit__c orgUnit = new Organizational_Unit__c(Name = 'test ou', Label__c = 'Division', Type__c = 'Spirits');
			insert orgUnit;
			Account account = Test_Helper.testInsertAccount('acc name', orgUnit.id);
			Account_Member__c member	= new Account_Member__c(Account__c = account.id, User__c = user.id);
			insert member;
			Budget__c budget			= new Budget__c();
			AccountBrand__c ab = new AccountBrand__c(Account__c = account.id, Brand__c = brand.id);
			insert ab;
			
			POS_BudgetingGridController.SlickGridRow sgr1 = new POS_BudgetingGridController.SlickGridRow();
			sgr1.indent			= '0';
			sgr1.updated		= true;
			sgr1.Budget			= 2000;
			sgr1.Shopper		= user.UserName;
			sgr1.ShopperId		= user.Id;
			sgr1.Brand			= brand.Name;
			sgr1.BrandId		= brand.Id;
			sgr1.Id				= 'new_1234';
			sgr1.Program		= program.Name;
			sgr1.ProgramId		= program.Id;
			//sgr1.parentId		= program.Id;
			sgr1.DistributorId 	= account.Id;
			sgr1.GeographyId	= orgUnit.Id;
			sgr1.Channel		= 'On Premise';
			POS_BudgetingGridController.SlickGridRow sgr2 = new POS_BudgetingGridController.SlickGridRow();
			sgr2.indent			= '0';
			sgr2.updated		= true;
			sgr2.Budget			= 2000;
			sgr2.Shopper		= user.UserName;
			sgr2.ShopperId		= user.Id;
			sgr2.Brand			= brand.Name;
			sgr2.BrandId		= brand.Id;
			sgr2.Id				= 'new_1234';
			sgr2.Program		= program.Name;
			
			List<POS_BudgetingGridController.SlickGridRow> rows = new List<POS_BudgetingGridController.SlickGridRow>();
			rows.add(sgr1);
			rows.add(sgr2);
			
			PageReference currPage = new PageReference('/apex/POS_BudgetingGrid?owId='+orderWindow.Id+'&gridData=');
			Test.setCurrentPage(currPage);
			
			System.runAs(user){
				POS_BudgetingGridController controller = new POS_BudgetingGridController();
				Budget__c nbudget1 = sgr1.populateBudgetObjectRecord(budget);
				Budget__c nbudget2 = sgr2.populateBudgetObjectRecord(budget);
				List<Budget__c> budgetRecs = controller.getBudgetObjectRecords(rows);
				System.assertEquals(2, budgetRecs.size());
				List<Budget__c> deleted = controller.getBudgetObjectRecordsForDelete('');
				//controller.propogateRowData();
				//controller.saveGrid();
			}
		}
		
		Test.stopTest();
	}
}