TestRepo2/src/objects/Account_Member__c.object
<CustomObject>
    <description>POS Project: junction object that represents the many-to-many relationship between Accounts and Users (Shoppers)</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Members</relationshipLabel>
        <relationshipName>Account_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Account Member</label>
    <nameField>
        <displayFormat>ACM-{000000}</displayFormat>
        <label>Account Member ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestRepo2/src/objects/AccountBrand__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>AccountBrand</relationshipLabel>
        <relationshipName>AccountBrand1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipLabel>AccountBrand</relationshipLabel>
        <relationshipName>AccountBrand1</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>AccountBrand</label>
    <nameField>
        <label>AccountBrand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AccountBrand</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestRepo2/src/objects/Brand__c.object
<CustomObject>
    <fields>
        <fullName>Brand_Type__c</fullName>
        <label>Brand Type</label>
        <picklist>
            <picklistValues>
                <fullName>Generic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Individual</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Gin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Irish</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Liqueur</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non Alcoholic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready to Serve</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rum</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scotch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tequila</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vodka</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Whiskey - NAW</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Classification__c</fullName>
        <label>Classification</label>
        <picklist>
            <picklistValues>
                <fullName>Beer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Spirits</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wine</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Alcoholic Beverage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NOT DEFINED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trading Goods (Non Beverage)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TBA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>diageo_direct_visible__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Diageo Direct Visible</label>
        <type>Checkbox</type>
    </fields>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/Cart__c.object
<CustomObject>
    <description>POS Project: object that represents a shopping cart</description>
    <fields>
        <fullName>Order_Window__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Window</label>
        <referenceTo>Order_Window__c</referenceTo>
        <relationshipLabel>Carts</relationshipLabel>
        <relationshipName>Carts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shopper__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shopper</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Carts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Cart</label>
    <nameField>
        <displayFormat>CRT-{00000000}</displayFormat>
        <label>Cart ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Carts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/Cart_Item__c.object
<CustomObject>
    <description>POS Project: junction object that represents the many-to-many relationship between Carts and Items</description>
    <fields>
        <fullName>Cart__c</fullName>
        <label>Cart</label>
        <referenceTo>Cart__c</referenceTo>
        <relationshipLabel>Cart Items</relationshipLabel>
        <relationshipName>Carts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Item__c</fullName>
        <label>Item</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>Cart Items</relationshipLabel>
        <relationshipName>Cart_Items</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Packout_Quantity__c</fullName>
        <formula>Item__r.Packout_Quantity__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Packout Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Ship_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To</label>
        <referenceTo>Ship_To__c</referenceTo>
        <relationshipLabel>Cart Items</relationshipLabel>
        <relationshipName>Cart_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Cart Item</label>
    <nameField>
        <displayFormat>CIT-{0000000000}</displayFormat>
        <label>Cart Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cart Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestRepo2/src/objects/Item__c.object
<CustomObject>
    <description>POS Project: object that represents catalog items available for shopping</description>
    <fields>
        <fullName>Agency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agency</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <formula>IF(Brand_Count__c &lt; 1, &quot;&quot;, IF(Program__r.Brand__r.Portfolio_Brand__c, &quot;Portfolio&quot;, Program__r.Brand__r.Name))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Regular</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Alcohol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VAP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tray Pack</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dummy Bottles</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Current_Price__c</fullName>
        <label>Current Price</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Estimated_Price__c</fullName>
        <label>Estimated Price</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Estimated_Shipping_Tax__c</fullName>
        <label>Estimated Shipping/Tax %</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Item_Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Item Category</label>
        <referenceTo>Item_Category__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Minimum_Quantity__c</fullName>
        <label>Minimum Quantity</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Packout_Quantity__c</fullName>
        <label>Packout Quantity</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <recordTypes>
        <fullName>Kit</fullName>
        <active>true</active>
        <description>Kit master, groups a set of standard items, can be ordered</description>
        <label>Kit</label>
    </recordTypes>
    <recordTypes>
        <fullName>Standard</fullName>
        <active>true</active>
        <description>Regular item, may be offered as standalone or as part of a kit, can be ordered</description>
        <label>Standard</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

TestRepo2/src/objects/Order_Window__c.object
<CustomObject>
    <description>POS Project: object that represents a period of time in which catalog items are offered and shoppers are allowed to buy them</description>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Quarterly</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Demand</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Order Window</label>
    <nameField>
        <label>Order Window Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Windows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/Program__c.object
<CustomObject>
    <description>POS Project: object that represents a set of events for which related catalog items are offered to shoppers (distributors and internal Diageo employees)</description>
    <fields>
        <fullName>Brand__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Window__c</fullName>
        <label>Order Window</label>
        <referenceTo>Order_Window__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestRepo2/src/objects/Ship_To__c.object
<CustomObject>
    <description>POS Project: object that represents a delivery address associated to a particular account</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Ship To&apos;s</relationshipLabel>
        <relationshipName>Ship_Tos</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Ship To</label>
    <nameField>
        <label>Ship To Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ship To&apos;s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestRepo2/src/classes/POS_TestDataUtil.cls
/**
 * @author      Model Metrics {Venkatesh Kamat}
 * @date        05/08/2012
 * @description Reusable helper methods for preparing data for Unit Tests
 */
 
@isTest
public class POS_TestDataUtil {
    
    private static RecordType productionAgency = [select Id, Name from RecordType where Name='POS Production Agency'];
    private static RecordType distributorAccount = [select Id, Name from RecordType where Name='Distributor'];
    
    public static void initializeTestData () {
        //Added to acommodate brand update trigger from Diageo Direct
        List<Account> accounts = [SELECT Id FROM Account WHERE Name LIKE 'Diageo'];
        if (accounts.size()==0) {
            Account diageo = new Account();
            diageo.Name='Diageo';
            diageo.RecordTypeId=distributorAccount.Id;
            insert diageo;
        }
        
        //Added to acommodate brand update trigger from Diageo Direct
        List<Brand__c> brands = [SELECT Id FROM Brand__c WHERE Name LIKE 'Portfolio'];
        if (brands.size()==0) {
            Brand__c portfolio = new Brand__c();
            portfolio.Name='Portfolio';
            insert portfolio;
        }
    }
    
    public static Item__c createItem(Program__c pg){

        Account agency = new Account(Name='POS TEST AGENCY', RecordTypeId = productionAgency.Id);
        insert agency;      
        
        Item__c o = populateItem(pg, agency);
        insert o;
        return o; 
    }
    
    public static Account createProductionAgency () {
        Account agency = new Account(Name='POS TEST AGENCY', RecordTypeId = productionAgency.Id);
        insert agency;      
        return agency;
    }
    
    public static Account createDistributorAccount () {
        Account dist = new Account(Name='POS Distributor', RecordTypeId = distributorAccount.Id);
        insert dist;        
        return dist;
    }
    
    public static Item__c createKit(Program__c pg){

        Id kitRecTypeId = [select id from RecordType where DeveloperName = 'Kit'].id;
        Account agency = new Account(Name='POS TEST AGENCY', RecordTypeId = productionAgency.Id);
        insert agency;      
        
        return createKit(pg,agency);
    }    
    
    public static Item__c createKit(Program__c pg, Account agency){

        Id kitRecTypeId = [select id from RecordType where DeveloperName = 'Kit'].id;
        
        Item__c o = populateItem(pg, agency);
        o.recordTypeId=kitRecTypeId;
        
        insert o;
        return o; 
    }    
      
    
    public static Item__c populateItem(Program__c pg, Account ag){
        // create ItemCategory records which is required while creating Item
        Item_Category__c ic = createItemCategory();
        
        Item__c o = new Item__c(name='itemName',Description__c='Uit Test Item Description', Current_Price__c=19.99, Estimated_Price__c=17.99, 
                    Estimated_Shipping_Tax__c=7.65, Category__c='Regular', Minimum_Quantity__c=10, Packout_Quantity__c=10, 
                    Program__c=pg.id, Item_Category__c=ic.id, agency__c=ag.id);
        return o;                        
    }
    
   public static Cart_Item__c populateCartItem(Item__c it, Cart__c crt){
        
        Ship_To__c st = createShipTo();
        Cart_Item__c o = new Cart_Item__c(Cart__c=crt.id, Item__c=it.id, Ship_To__c=st.id, Quantity__c=40);
        return o;                        
    } 

    
    public static Cart__c createCart(User shpr, Order_Window__c ow){
        Cart__c crt = new Cart__c(Shopper__c = shpr.id,
                                  Order_Window__c = ow.id);
        insert crt;
        return crt;                        
    } 
    
    public static Ship_To__c createShipTo(Account act){
        Ship_To__c sh = new Ship_To__c(Account__c = act.id,
                                  Name = 'Test ShipTo');
        insert sh;
        return sh;                        
    }                       
    
    public static Account createAccount(){
        Account act = new Account(Name = 'Test Account',
                                  Type = 'Customer');
        insert act;
        return act;                        
    }
    
    public static Ship_To__c createShipTo(){
        Account act = createAccount();
        Ship_To__c shipTo = new Ship_To__c();
        shipTo.Account__c = act.Id;
        shipTo.Name='Test Ship To';
        
        insert shipTo;        
        return shipTo;                        
    }    
    
   /* public static Account createCustomerPortalAccountRole(){
        UserRole r = new UserRole(Name = 'Test Account',
                                  Type = 'Customer', IsCustomerPortal = true);
        insert act;
        return act;                        
    } */   

    public static Contact createContact(Account acct){
        Contact c = new Contact(Account = acct, FirstName = 'cfName', LastName ='clName', Email='fclName@test.pos.com');
        insert c;
        return c;                        
    }    
    
    
    public static Brand__c createBrand(){
        
        Brand__c brd = new Brand__c(Name = 'Test Brand', Classification__c='Spirits', Diageo_Direct_Visible__c=true, Brand_Type__c='Individual');
        insert brd;
        return brd;                        
    }
    
    public static Order_Window__c createOrderWindow(){
        Order_Window__c o = new Order_Window__c(Name = 'Test OW', Type__c='Monthly', Status__c='Open');
        o.Fiscal_Year__c = '2012';
        DateTime now = System.now();
        Date nowDate = date.newinstance(now.year(), now.month(), now.day());
        Date later = nowDate.addDays(90);
        Date muchLater = later.addDays(90);
        o.Order_Close_Date__c=later;
        o.Order_Delivery_Date__c=muchLater;
        o.Order_Start_Date__c=nowDate;
        insert o; 
        return o;                        
    } 
         
    
    public static Program__c createProgram(){
        Order_Window__c ow = createOrderWindow();
        Brand__c  bd = createBrand();
        
        Program__c o = new Program__c(Name = 'Test Program1', Order_Window__c=ow.id, Brand__c=bd.id);
        insert o;
        return o;                        
    } 
    
    public static Program__c createProgram(Id owId){
        Brand__c  bd = createBrand();
        Program__c o = new Program__c(Name = 'Test Program2', Order_Window__c=owId, Brand__c=bd.id);
        insert o;
        return o;                        
    }    
    
    public static Program__c createProgram(Id brandId, Id owId){
        
        Program__c o = new Program__c(Name = 'Test Program2', Order_Window__c=owId, Brand__c=brandId);
        insert o;
        return o;                        
    }          
        
    public static Account_Member__c createAccountMember(Account a, User u){
        Account_Member__c am = new Account_Member__c(Account__c=a.id, User__c=u.id);
        insert am;
        return am;                        
    }    
    
    public static AccountBrand__c createAccountBrand(Account a, Brand__c b){
        AccountBrand__c ab = new AccountBrand__c(Account__c=a.id, Brand__c=b.id);
        insert ab;
        return ab;                        
    }
    
    public static Organizational_Unit__c createOrgUnit(){
        Organizational_Unit__c orgunit = new Organizational_Unit__c();
        orgunit.Name='Charmer';
        orgunit.Type__c='Spirit';
        orgunit.Responsible_Code__c='BN';
        orgunit.District_Code__c='4450';
        orgunit.Label__c='Division';
        insert orgunit;
        return orgunit; 
    }
    
    public static Item_Category__c createItemCategory(){
        Item_Category__c o = new Item_Category__c(Name='Test Item Category', Customer_Marketing_Category__c='Bar', Material_Code__c='55B.91', 
                                Primary_Group__c='Display', Primary_Type__c='PRINT');
        insert o;
        return o;                        
    }    
    
    public static User createStdUser() {
        Profile p = [select id from profile where name='Standard User' limit 1]; 
        User testUser = new User(alias = 'standt', email='standarduser@modelmetrics.pos.com', 
            emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US', 
            localesidkey='en_US', profileid = p.Id, firstname='phil',
            timezonesidkey='America/Los_Angeles', username='standarduser@modelmetrics.pos.com');
        insert testUser; 
        return testUser;     
     } 
     
    public static User createCMAdminUser() {
        Profile p = [select id from profile where name='POS - CM Administrator' limit 1]; 
        User testUser = new User(alias = 'cmadmin', email='cmadminuser@modelmetrics.pos.com', 
            emailencodingkey='UTF-8', lastname='Admin', languagelocalekey='en_US', 
            localesidkey='en_US', profileid = p.Id, firstname='CM',
            timezonesidkey='America/Los_Angeles', username='cmadminuser@modelmetrics.pos.com');
        insert testUser; 
        return testUser;     
     }  
     
    public static User createDiageoEmployeeUser() {
        Profile p = [select id from profile where name='Diageo Employee' limit 1]; 
        User testUser = new User(alias = 'demp', email='demp@modelmetrics.pos.com', 
            emailencodingkey='UTF-8', lastname='Employee', languagelocalekey='en_US', 
            localesidkey='en_US', profileid = p.Id, firstname='D',
            timezonesidkey='America/Los_Angeles', username='demp@modelmetrics.pos.com');
        insert testUser; 
        return testUser;     
     }         
     
    public static User createPortalUser(Contact c) {
        Profile p = [select id from profile where name='Distributor Portal User' limit 1];
        //UserRole r = [select id from UserRole where name='Manager' and PortalAccountId=:a.id limit 1]; 
        User testUser = new User(alias = 'standt', email='portaluser@modelmetrics.pos.com', 
            emailencodingkey='UTF-8', lastname='PTesting', languagelocalekey='en_US', 
            localesidkey='en_US', profileid = p.Id, firstname='Dist', contactId=c.id,
            PortalRole = 'Manager',
            timezonesidkey='America/Los_Angeles', username='portaluser@modelmetrics.pos.com');
            
        System.debug('c.account.owner.UserRoleId -' + c.account.owner.UserRoleId);    
        insert testUser; 
        return testUser;     
     }        
 
}