TestRepo2/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Objective__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Objective</label>
        <referenceTo>Objective__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

TestRepo2/src/objects/Action__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Actions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <formula>IF(Goal__c = null, Objective__r.Due_Date__c, Goal__r.Due_Date__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Objective__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Objective</label>
        <referenceTo>Objective__c</referenceTo>
        <relationshipName>Actions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Activity</label>
    <nameField>
        <displayFormat>A-{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>Action</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Actions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

TestRepo2/src/objects/Objective__c.object
<CustomObject>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <label>Objective</label>
    <nameField>
        <label>Objective Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Objectives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/classes/Test_Controller_ActivitiesByAcct.cls
@isTest
private class Test_Controller_ActivitiesByAcct {
	
	
	static testMethod void testController()
	{
		Account account = Test_Helper.testInsertAccount('test_account');
		Account account2 = Test_Helper.testInsertAccount('test_account2');
		
		List<Action__c> actionsToInsert = new List<Action__c>();
		
		Objective__c lastInsertedObjective;
		for(String str : new String[]{'1','2','3','4','5','6','7','8','9','10','11','12','13','14','15'}) {
			lastInsertedObjective = insertObjective(str);
			actionsToInsert.add(createAction(lastInsertedObjective.Id, account));
		}
		
		actionsToInsert.add(createAction(lastInsertedObjective.Id, account2));
		
		insert actionsToInsert;
		
		system.test.startTest();
			Controller_ActivitiesByAcct controller = new Controller_ActivitiesByAcct();
			controller.getDynamicPageBlockTableContent();
		system.test.stopTest();
	}
	
	private static Objective__c insertObjective(String name)
	{
		Objective__c objective = new Objective__c();
		objective.Name = 'test' + name;
		objective.Due_Date__c = Date.today().addDays(10);
		insert objective ;
		
		return objective;
	}
	
	private static Action__c createAction(Id objectiveId, Account account) {
		Action__c action = new Action__c();
		action.Objective__c = objectiveId;
		action.Account__c = account.Id;
		return action;
	}

}