TestRepo2/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Primary_Demographic__c</fullName>
        <label>Primary Demographic</label>
        <picklist>
            <picklistValues>
                <fullName>General Market</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Hispanic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AfAm</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LGBT</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
</CustomObject>

TestRepo2/src/objects/Goal_Account_Report_Item__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Goal Account Report Items</relationshipLabel>
        <relationshipName>Goal_Account_Report_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Primary_Demographic__c</fullName>
        <label>Primary Demographic</label>
        <picklist>
            <picklistValues>
                <fullName>General Market</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hispanic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AfAm</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LGBT</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Goal Account Report Item</label>
    <nameField>
        <displayFormat>GARI-{00000000}</displayFormat>
        <label>Goal Account Report Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Goal Account Report Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestRepo2/src/classes/GoalAccountReportItemActions.cls
public with sharing class GoalAccountReportItemActions {

	public static void copyFieldsFromAccount(List<Goal_Account_Report_Item__c> garis){
		Set<Id> accIds = new Set<Id>();
		for(Goal_Account_Report_Item__c gari : garis){
			if(gari.Account__c != null){
				accIds.add(gari.Account__c);
			}
		}
		Map<Id, Account> accsById = new Map<Id, Account>([SELECT Id, OwnerId, Owner.FirstName, Owner.LastName, Primary_Demographic__c FROM Account WHERE Id IN :accIds]);
		
		for(Goal_Account_Report_Item__c gari : garis){
			if(gari.Account__c != null){
				Account acc = accsById.get(gari.Account__c);
				if(acc != null){
					gari.Primary_Demographic__c = acc.Primary_Demographic__c;
					if(acc.OwnerId != null){
						gari.User__c = acc.Owner.FirstName + ' ' + acc.Owner.LastName;
					}
				}
			}
		}
	}

}