TestRepo2/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>State__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>State</label>
        <referenceTo>State__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

TestRepo2/src/objects/Brand__c.object
<CustomObject>
    <fields>
        <fullName>Brand_Type__c</fullName>
        <label>Brand Type</label>
        <picklist>
            <picklistValues>
                <fullName>Generic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Individual</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Classification__c</fullName>
        <label>Classification</label>
        <picklist>
            <picklistValues>
                <fullName>Beer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Spirits</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wine</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Alcoholic Beverage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NOT DEFINED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trading Goods (Non Beverage)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TBA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>diageo_direct_visible__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Diageo Direct Visible</label>
        <type>Checkbox</type>
    </fields>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/Cart__c.object
<CustomObject>
    <description>POS Project: object that represents a shopping cart</description>
    <fields>
        <fullName>Order_Window__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Window</label>
        <referenceTo>Order_Window__c</referenceTo>
        <relationshipLabel>Carts</relationshipLabel>
        <relationshipName>Carts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Cart</label>
    <nameField>
        <displayFormat>CRT-{00000000}</displayFormat>
        <label>Cart ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Carts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/Cart_Item__c.object
<CustomObject>
    <description>POS Project: junction object that represents the many-to-many relationship between Carts and Items</description>
    <fields>
        <fullName>City__c</fullName>
        <formula>Ship_To__r.City__c</formula>
        <label>City</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Email__c</fullName>
        <formula>Ship_To__r.Contact_Email__c</formula>
        <label>Contact Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To</label>
        <referenceTo>Ship_To__c</referenceTo>
        <relationshipLabel>Cart Items</relationshipLabel>
        <relationshipName>Cart_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <formula>TEXT(Ship_To__r.State__c)</formula>
        <label>State</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_2__c</fullName>
        <formula>Ship_To__r.Street_2__c</formula>
        <label>Street 2</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <formula>Ship_To__r.Street__c</formula>
        <label>Street</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <formula>Ship_To__r.Zip__c</formula>
        <label>Zip</label>
        <type>Text</type>
    </fields>
    <label>Cart Item</label>
    <nameField>
        <displayFormat>CIT-{0000000000}</displayFormat>
        <label>Cart Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cart Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestRepo2/src/objects/Item__c.object
<CustomObject>
    <description>POS Project: object that represents catalog items available for shopping</description>
    <fields>
        <fullName>Brand__c</fullName>
        <formula>IF(Brand_Count__c &lt; 1, &quot;&quot;, IF(Program__r.Brand__r.Portfolio_Brand__c, &quot;Portfolio&quot;, Program__r.Brand__r.Name))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

TestRepo2/src/objects/Program__c.object
<CustomObject>
    <description>POS Project: object that represents a set of events for which related catalog items are offered to shoppers (distributors and internal Diageo employees)</description>
    <fields>
        <fullName>Brand__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Window__c</fullName>
        <label>Order Window</label>
        <referenceTo>Order_Window__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestRepo2/src/objects/Ship_To__c.object
<CustomObject>
    <description>POS Project: object that represents a delivery address associated to a particular account</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Ship To&apos;s</relationshipLabel>
        <relationshipName>Ship_Tos</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Address_Type__c</fullName>
        <label>Address Type</label>
        <picklist>
            <picklistValues>
                <fullName>Commercial</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Residential</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Storage Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Attention__c</fullName>
        <label>Attention</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Email__c</fullName>
        <label>Contact Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Is_Deleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Deleted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Removed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Removed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NH</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Street_2__c</fullName>
        <label>Street 2</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <label>Zip</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Ship To</label>
    <nameField>
        <label>Ship To Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ship To&apos;s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestRepo2/src/objects/User_Ship_To__c.object
<CustomObject>
    <description>POS Project: junction object that represents the many-to-many relationship between Users (customers) and Ship Tos (delivery addresses)</description>
    <fields>
        <fullName>Favorite__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Favorite</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Magento_Ship_To_ID__c</fullName>
        <externalId>true</externalId>
        <label>Magento Ship To ID</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_To__c</fullName>
        <label>Ship To</label>
        <referenceTo>Ship_To__c</referenceTo>
        <relationshipLabel>User Ship Tos</relationshipLabel>
        <relationshipName>User_Ship_Tos</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Ship_Tos</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Ship To</label>
    <nameField>
        <displayFormat>UST-{00000000}</displayFormat>
        <label>User Ship To ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Ship Tos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestRepo2/src/classes/POS_ShipTosMigrateToAccount.cls
public class POS_ShipTosMigrateToAccount {
    public Set<String> shipToIds = new Set<String>();
    public List<sObject> shipTos = new List<sObject>();
    
    public Ship_To__c st {get;set;}
    
    public POS_ShipTosMigrateToAccount(){  
        if(ApexPages.currentPage().getParameters().get('shipToIds') <> null) {
            shipToIds.addAll(
                ApexPages.currentPage().getParameters().get('shipToIds').split(',',-1)
            );
        }
        
        st = new Ship_To__c(); 
    }
         
    public List<sObject> getShipTos() {
        return [Select Id, Name from Ship_To__c where Id in :shipToIds];
    }
    
    // transfer many ShipTos to an account
    // this method is called from VF page POS_ShiptosMigrateToAccount
    public void doTransfers(){
        if(st.Account__c != null) {
            try {
                for(String shipToId : shipToIds) {
                    doTransfer(shipToId, st.Account__c);
                }
                
                ApexPages.addMessage(
                    new ApexPages.message(ApexPages.severity.INFO, 'All Ship To(s) have been moved to this account!')
                );    
            } catch (Exception e) {
                ApexPages.addMessages(e);
            }
        } 
    }
             
     /*        
        ID:US879
        Name: POS Admin: Realign Ship to to a different account
        Description:
        As a POS Admin I'd like to have the ability to reassign a ship to from one account to another and have all the corresponding child  objects moved automatically.  Due to salesforce restriction on child relationships this will need to be achieved with a copy then delete of ship to.
         
        Acceptance Criteria:
         
        - Inputs are Ship to and Target account for the move.
        - Tool should create a new shipto on the target account with the right owner transferred.
        - Should move all user ship tos, to the new ship to
        - Should move all cart items to the new ship to.
        - Should mark the old ship to as removed.
     */
     
     
     public void doTransfer(Ship_To__c shipto,Account target){
         doTransfer(shipto.Id,target.Id);
     }
     
     public void doTransfer(String shipToId,String Id){
             
            //first we will fetch all the relevant ship to details - we dont rely on the record passed as it may not contains all details
            try{
                List<Ship_To__c> shipToList = [Select Name, Account__c,Address_Type__c,Attention__c,City__c,Contact_Email__c,Notes__c,Phone__c,Removed__c,State__c,Street__c,Street_2__c,Zip__c,Is_Deleted__c FROM Ship_To__c WHERE Id=:shiptoId LIMIT 1];
            
                if(shipToList .size()==0) return;
                Ship_To__c ship=shipToList [0];
                Ship_To__c newshipto= ship.clone(false,true);
                newshipto.Account__c=id;
                //newshipto.CreatedById = ship.CreatedById;
                
                insert newshipto;     
                
                //lets update the old ship as removed
                ship.Removed__c=true;
                update ship;
                
                //once we have the new shipto created start the batch processes:to move the cart items(existing)
                POS_BatchUpdateShiptos batch = new POS_BatchUpdateShiptos(ship , newshipto);
                Database.executeBatch(batch); 
                
                //move all the user shipto also :-  we will use future method
                transferUserShipTo(shipToId,newshipto.Id);  
                
            }catch(Exception e){
            
            }
             
     }
     @future
     public static void transferUserShipTo(String oldShipToId,String newShipToId){
             //get all the user ships
             List<User_Ship_To__c> ushipto =[Select Id,Ship_To__c,User__c,Magento_Ship_To_ID__c,Favorite__c FROM User_Ship_To__c WHERE Ship_To__c=:oldShipToId];
             if(ushipto .size()==0) return;
             List<User_Ship_To__c> toInsert = new List<User_Ship_To__c>();
             for (User_Ship_To__c shipto:ushipto ) {
                User_Ship_To__c newus = shipto.clone(false,true);
                newus.Ship_To__c=newShipToId;
                toInsert.add(newus);
             } 
             insert  toInsert ;            
             delete ushipto;
     }
      
     static testmethod void testMigration(){
         Account newAccount = new Account(Name='test1');    
         insert newAccount;
         
           Brand__c brd = new Brand__c(Name = 'Portfolio', Classification__c='Spirits', Diageo_Direct_Visible__c=true, Brand_Type__c='Individual');
          insert brd;
         
         //let us create a ship to
          Order_Window__c ow = POS_TestDataUtil.createOrderWindow();
          Program__c program = POS_TestDataUtil.createProgram(ow.Id);
          Item__c item = POS_TestDataUtil.createItem(program);
          User shopper = [Select Id,Name FROM User WHERE Id=:UserInfo.getUserId()];
          Cart__c cart = POS_TestDataUtil.createCart(shopper, ow);
          
        
          
          Ship_To__c shipTo = POS_TestDataUtil.createShipTo();
          
          Cart_Item__c cartItem = new Cart_Item__c();
          cartItem.Item__c=item.Id;
          cartItem.Cart__c=cart.Id;
          cartItem.Quantity__c=item.Packout_Quantity__c;
          cartItem.Ship_To__c=shipTo.Id;
          insert cartItem;
          
          //create user ship to
          User_Ship_To__c us = new User_Ship_To__c();
          us.User__c =shopper .Id;
          us.ship_to__c=shipTo.Id;
          insert us;
          
          
          Test.startTest();
             POS_ShipTosMigrateToAccount job= new POS_ShipTosMigrateToAccount();
             job.doTransfer(shipTo, newAccount);
          Test.StopTest();
          
     } 
}