TestRepo2/src/objects/Account_Member__c.object
<CustomObject>
    <description>POS Project: junction object that represents the many-to-many relationship between Accounts and Users (Shoppers)</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Members</relationshipLabel>
        <relationshipName>Account_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Account_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Member</label>
    <nameField>
        <displayFormat>ACM-{000000}</displayFormat>
        <label>Account Member ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestRepo2/src/objects/Brand__c.object
<CustomObject>
    <fields>
        <fullName>Magento_Id__c</fullName>
        <externalId>true</externalId>
        <label>Magento Id</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/Item__c.object
<CustomObject>
    <description>POS Project: object that represents catalog items available for shopping</description>
    <fields>
        <fullName>Agency_Item_ID__c</fullName>
        <externalId>true</externalId>
        <label>Agency Item ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Agency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agency</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <formula>IF(Brand_Count__c &lt; 1, &quot;&quot;, IF(Program__r.Brand__r.Portfolio_Brand__c, &quot;Portfolio&quot;, Program__r.Brand__r.Name))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Price__c</fullName>
        <label>Current Price</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Estimated_Price__c</fullName>
        <label>Estimated Price</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Estimated_Shipping_Tax__c</fullName>
        <label>Estimated Shipping/Tax %</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Item_ID__c</fullName>
        <displayFormat>ITM-{00000000}</displayFormat>
        <label>Item ID</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Kit_Only__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Kit Only</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Magento_ID__c</fullName>
        <externalId>true</externalId>
        <label>Magento ID</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Minimum_Quantity__c</fullName>
        <label>Minimum Quantity</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Packout_Quantity__c</fullName>
        <label>Packout Quantity</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>Item Variations</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Driver__c</fullName>
        <formula>TEXT(Program__r.Sales_Driver__c)</formula>
        <label>Sales Driver</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Development</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Approved w/Est Price</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted w/Final Price</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Removed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <recordTypes>
        <fullName>Roll_Up</fullName>
        <active>true</active>
        <description>Parent item for item variations, cannot be ordered</description>
        <label>Roll-Up</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

TestRepo2/src/objects/Item_Image__c.object
<CustomObject>
    <description>POS Project: object that represents the item metadata for an catalog item image</description>
    <fields>
        <fullName>Item__c</fullName>
        <label>Item</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>Item Images</relationshipLabel>
        <relationshipName>Item_Images</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Magento_Image_URL__c</fullName>
        <label>Magento Image URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Magento_Image__c</fullName>
        <formula>IF(ISBLANK(Magento_Image_URL__c), &quot;&quot;, HYPERLINK(Magento_Image_URL__c, IMAGE(Magento_Image_URL__c, Name , 60, 60), &quot;_blank&quot;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Magento Image</label>
        <type>Text</type>
    </fields>
    <label>Item Image</label>
    <nameField>
        <displayFormat>IMG-{0000000}</displayFormat>
        <label>Item Image Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Item Images</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestRepo2/src/objects/Legal_Disclaimer__c.object
<CustomObject>
    <description>POS Project: object that represents a legal disclaimer which is presented on the POS Portal before users enter into the e-commerce platform</description>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ItemsCatalog_Message__c</fullName>
        <description>message displayed on every page on generated ItemsCatalog pdf.</description>
        <label>ItemsCatalog Message</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Legal Disclaimer</label>
    <nameField>
        <displayFormat>LGD-{000000}</displayFormat>
        <label>Legal Disclaimer ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Legal Disclaimers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/Order_Window__c.object
<CustomObject>
    <description>POS Project: object that represents a period of time in which catalog items are offered and shoppers are allowed to buy them</description>
    <fields>
        <fullName>Magento_Id__c</fullName>
        <externalId>true</externalId>
        <label>Magento Category Id</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Close_Date__c</fullName>
        <label>Order Close Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Order_Start_Date__c</fullName>
        <label>Order Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <controllingField>Type__c</controllingField>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Budgeting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Archived</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Order Window</label>
    <nameField>
        <label>Order Window Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Windows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/POS_Magento_Configuration__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>stores all values like API key, User Name, Endpoint etc. required for Magento Integration service</description>
    <fields>
        <fullName>Thumbnail_URL__c</fullName>
        <description>The base URL for getting thumbnails from Magento</description>
        <label>Thumbnail URL</label>
        <type>Url</type>
    </fields>
    <label>POS Magento Configuration</label>
</CustomObject>

TestRepo2/src/objects/Program__c.object
<CustomObject>
    <description>POS Project: object that represents a set of events for which related catalog items are offered to shoppers (distributors and internal Diageo employees)</description>
    <fields>
        <fullName>Brand__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Magento_Id__c</fullName>
        <externalId>true</externalId>
        <label>Magento Category Id</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Window__c</fullName>
        <label>Order Window</label>
        <referenceTo>Order_Window__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Program_ID__c</fullName>
        <displayFormat>PRG-{000000}</displayFormat>
        <label>Program ID</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Sales_Driver__c</fullName>
        <label>Sales Driver</label>
        <picklist>
            <picklistValues>
                <fullName>INP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Distribution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Display/Visibility</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Innovation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sustainovation</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestRepo2/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Magento_Id__c</fullName>
        <externalId>true</externalId>
        <label>Magento_Id</label>
        <length>80</length>
        <type>Text</type>
    </fields>
</CustomObject>

TestRepo2/src/classes/POS_DownloadItemCatalogController.cls
/**
 * @author      Model Metrics {Venkatesh Kamat}
 * @date        08/14/2012
 * @description Controller to list items of a given OrderWindow, support filtering by one or more Brands
 **/
public without sharing class POS_DownloadItemCatalogController {
    
    public Order_Window__c orderWindow{get; set;}
    public List<Program__c> orderwindowData{get; set;}
    public Map<Id, Item__c> itemWithImages{get; set;}
    public String disclaimerText {get;set;}
    public String thumbnailUrl {get;set;}
    
    public POS_DownloadItemCatalogController() {
        String owId = ApexPages.currentPage().getParameters().get('owId');
        
        
		POS_Magento_Configuration__c settings = POS_Magento_Configuration__c.getOrgDefaults();
		thumbnailUrl = settings.Thumbnail_Url__c;

        orderWindow = [SELECT Name, Status__c, Order_Start_Date__c, Order_Close_Date__c  from Order_Window__c where Magento_Id__c=:owId];
        orderwindowData = 	[SELECT Order_Window__r.Name, Brand__r.name, Program_ID__c, Id, Name, Sales_Driver__c,
						(select id, Name, Item_ID__c, Description__c, Agency_Item_ID__c, Minimum_Quantity__c, Packout_Quantity__c, Estimated_Price__c, Estimated_Shipping_Tax__c, Current_Price__c, Magento_Id__c 
						from Items__r where Status__c not in ('Development','Removed','Cancelled') and RecordType.DeveloperName!='Roll_Up' and Kit_Only__c!=true order by Name ) 
						FROM Program__c where Order_Window__r.Magento_Id__c= :owId order by Name];
						
		Legal_Disclaimer__c ld = [SELECT ItemsCatalog_Message__c FROM Legal_Disclaimer__c where End_Date__c = null limit 1];
		disclaimerText = ld.ItemsCatalog_Message__c;						
		
		List<Id> itmIds = new List<Id>(); 
		
		List<Program__c> programsWithItems = new List<Program__c>();
		
		
		for(Program__c prg : orderwindowData) {
			if (prg.Items__r.size()>0) {
				programsWithItems.add(prg);
			}
			for(Item__c itm : prg.Items__r) {
				itmIds.add(itm.Id);
			}
		}
		
		System.debug('ORDER WINDOW DATA: '+orderWindowData);
		
		//Now copy back the programs that have items to eliminate blanks
		orderWindowData = programsWithItems;
		
		System.debug('ORDER WINDOW DATA 2: '+orderWindowData);
		
		
		// query list of images corresponding to all the Items of the OW above.
		itemWithImages = new Map<Id, Item__c>([SELECT Id, (SELECT Magento_Image_URL__c,Magento_Image__c FROM Item_Images__r) FROM Item__c where Id in :itmIds]);
        
        System.debug('orderwindowData -' + orderwindowData + ' itemWithImages -' + itemWithImages);

    }
    
    @isTest(SeeAllData=true)
	public static void testDownloadItemCatalog () {
		
		Profile p = [select id from profile where name='POS - CM Administrator'];
         
		User u = new User(alias = 'posmmtst', email='posmmunittest@diageo.com',
        emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US',
		localesidkey='en_US', profileid = p.Id,
		timezonesidkey='America/Chicago', username='posmmunittest@diageo.com');
		
		System.runAs(u) {
			//Create some test data
			Account account = new Account();
			account.Name='POS Unit Test Account';
			insert account;
			
			Account_Member__c am = new Account_Member__c();
			am.Account__c = account.Id;
			am.User__c = u.Id;
			insert am;
			
		    Account agency = POS_TestDataUtil.createProductionAgency();
		   
		   	Order_Window__c ow = POS_TestDataUtil.createOrderWindow();
		   	ow.Magento_Id__c = '1';
		   	update ow;
		   	
		    Program__c program = POS_TestDataUtil.createProgram(ow.Id);
		    Item__c item = POS_TestDataUtil.populateItem(program, agency);
		    item.Status__c='Approved w/Est Price';
		    insert item;
		   
		    String owId = program.Order_Window__c;
			Test.setCurrentPageReference(new PageReference('Page.POS_DownloadItemCatalog'));
			System.currentPagereference().getParameters().put('owId',ow.Magento_Id__c);		    
		    
		    POS_DownloadItemCatalogController ctrl = new POS_DownloadItemCatalogController();	
		    
		    System.assertEquals(1, ctrl.orderwindowData.size());
		}
	}     
    
}