TestRepo2/src/objects/AccountBrand__c.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipLabel>AccountBrand</relationshipLabel>
        <relationshipName>AccountBrand1</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>AccountBrand</label>
    <nameField>
        <label>AccountBrand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AccountBrand</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestRepo2/src/objects/Brand__c.object
<CustomObject>
    <fields>
        <fullName>Content_Description__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Content Description (logo)</description>
        <label>Content Description</label>
        <referenceTo>Content_Description__c</referenceTo>
        <relationshipLabel>Brands</relationshipLabel>
        <relationshipName>Brands</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/Content_Description__c.object
<CustomObject>
    <fields>
        <fullName>Content_Version_Id_Low__c</fullName>
        <label>Content Version Id Low</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Content_Version_Id__c</fullName>
        <label>Content Version Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Content Description</label>
    <nameField>
        <label>Content Description Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Content Descriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/ContentBrand__c.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipLabel>ContentBrand</relationshipLabel>
        <relationshipName>ContentBrand</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Content_Description__c</fullName>
        <label>Content Description</label>
        <referenceTo>Content_Description__c</referenceTo>
        <relationshipLabel>ContentBrand</relationshipLabel>
        <relationshipName>ContentBrand_del</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>ContentBrand</label>
    <nameField>
        <label>ContentBrand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ContentBrand</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestRepo2/src/classes/Test_ControllerBasket.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class Test_ControllerBasket {

    static testmethod void testBrands(){
        // insert test user data
        Account a = Test_Helper.testInsertAccount('Test Account');
        Contact c = Test_Helper.testInsertContact('TestFirst', 'TestLast', a.ID);
        User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
        User u;     
    
        System.runAs (thisUser) {
            u = Test_Helper.testInsertDistributorPortalUser(c.ID);
        }
        
        // insert test brands
        Brand__c brandA = Test_Helper.testInsertBrand('Test Brand A');
        
        // hook one of the parent brands too the user's account
        AccountBrand__c accBrand = Test_Helper.testInsertAccountBrand(a.ID, brandA.ID);
        
        // insert test content that looks up to the previoulsy inserted brands
        Content_Description__c contentA = Test_Helper.testInsertContentDescriptionExtended('rose');
        Content_Description__c contentB = Test_Helper.testInsertContentDescriptionExtended('orchid');
        Content_Description__c contentC = Test_Helper.testInsertContentDescriptionExtended('tulip');
        
        contentA.Content_Version_Id_Low__c = contentA.Content_Version_Id__c;
        contentA.Content_Version_Id__c = null;
        update contentA;
        
        
        // insert the join records between content and brand        
        ContentBrand__c cbA = Test_Helper.testInsertContentBrand(contentA.id, brandA.id);
        ContentBrand__c cbB = Test_Helper.testInsertContentBrand(contentB.id, brandA.id);
        ContentBrand__c cbC = Test_Helper.testInsertContentBrand(contentC.id, brandA.id);
        
        Test.startTest();

        PageReference pageRef = Page.Basket;
        Test.setCurrentPage(pageRef);
                
        System.runAs(u){
            Controller_Basket cBasket = new Controller_Basket();
            
            // clear basket
            cBasket.clearBasket();
            System.assertEquals(0, cBasket.basketItemsNo);
            
            // add single
            cBasket.cVersionId = contentB.Content_Version_Id__c;
            
            cBasket.addToBasket();
            System.assertEquals(1, cBasket.basketItemsNo);
            
            //remove single
            cBasket.removeFromBasket();
            System.assertEquals(0 , cBasket.basketItemsNo);
            
            // add multiple
            cBasket.cVersionIds = contentA.Content_Version_Id_Low__c+','+contentB.Content_Version_Id__c;
            cBasket.addToBasketMultiple();
            System.assertEquals(2, cBasket.basketItemsNo);
            
            cBasket.refreshPageContent();
            
            //remove multiple
            cBasket.removeFromBasketMultiple();
            System.assertEquals(0, cBasket.basketItemsNo);


            Service_Basket.getNumberOfItems();

            cBasket.showFirstPage();
            cBasket.showPrevPage();

            delete cbA;
            delete cbB;
            delete cbC;
            cBasket.refreshPageContent();
            cBasket.removeTrashFromBasket();
            
        }
        
        Test.stopTest();
    }

}