TestRepo2/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Has_Attachment__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has Attachment</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

TestRepo2/src/objects/Action__c.object
<CustomObject>
    <fields>
        <fullName>Has_Attachment__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has Attachment</label>
        <type>Checkbox</type>
    </fields>
    <label>Activity</label>
    <nameField>
        <displayFormat>A-{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>Action</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Actions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

TestRepo2/src/classes/AttachmentActionsTest.cls
@isTest
private class AttachmentActionsTest {

    static testMethod void testUpdateParentActions() {
        Action__c rec = new Action__c();
        insert rec;
        
        rec = [SELECT Id, Has_Attachment__c FROM Action__c WHERE Id = :rec.Id];
        System.assertEquals(false, rec.Has_Attachment__c);
        
        Attachment att = new Attachment();
        att.ParentId = rec.Id;
        att.Name = 'test';
        att.Body = Blob.valueOf('test');
        
        Test.startTest();
        
        insert att;
        
        Test.stopTest();
        
        rec = [SELECT Id, Has_Attachment__c FROM Action__c WHERE Id = :rec.Id];
        System.assertEquals(true, rec.Has_Attachment__c);
        
        delete att;
        
        rec = [SELECT Id, Has_Attachment__c FROM Action__c WHERE Id = :rec.Id];
        System.assertEquals(false, rec.Has_Attachment__c);
    }

    static testMethod void testUpdateParentAccounts() {
        Account rec = new Account();
        rec.Name = 'test account';
        insert rec;
        
        rec = [SELECT Id, Has_Attachment__c FROM Account WHERE Id = :rec.Id];
        System.assertEquals(false, rec.Has_Attachment__c);
        
        Attachment att = new Attachment();
        att.ParentId = rec.Id;
        att.Name = 'test';
        att.Body = Blob.valueOf('test');
        
        Test.startTest();
        
        insert att;
        
        Test.stopTest();
        
        rec = [SELECT Id, Has_Attachment__c FROM Account WHERE Id = :rec.Id];
        System.assertEquals(true, rec.Has_Attachment__c);
        
        delete att;
        
        rec = [SELECT Id, Has_Attachment__c FROM Account WHERE Id = :rec.Id];
        System.assertEquals(false, rec.Has_Attachment__c);
    }
}