TestRepo2/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Segmentatiobn__c</fullName>
        <label>Account Segmentation</label>
        <picklist>
            <picklistValues>
                <fullName>A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Called_On__c</fullName>
        <defaultValue>false</defaultValue>
        <description>As a Sales Rep, I need the Called On field so I can flag the accounts that I visit</description>
        <inlineHelpText>Check this box if this is an Account that is visited by a Sales Rep</inlineHelpText>
        <label>Called On</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Licensee_State_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Licensee State Code</label>
        <referenceTo>State_Code__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NABCA_Licensee_State__c</fullName>
        <label>NABCA Licensee State</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NABCA_Sector_Code__c</fullName>
        <label>NABCA Sector Code</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Nabca_Account_Name__c</fullName>
        <label>NABCA Account Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Demographic__c</fullName>
        <label>Primary Demographic</label>
        <picklist>
            <picklistValues>
                <fullName>General Market</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Hispanic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AfAm</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LGBT</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>State</label>
        <referenceTo>State__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Territory</label>
        <referenceTo>Territory__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

TestRepo2/src/objects/Action__c.object
<CustomObject>
    <fields>
        <fullName>Called_On_Accounts__c</fullName>
        <label>Called On Accounts</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Goal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Goal</label>
        <referenceTo>Goal__c</referenceTo>
        <relationshipLabel>Actions</relationshipLabel>
        <relationshipName>Actions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Activity</label>
    <nameField>
        <displayFormat>A-{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>Action</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Actions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

TestRepo2/src/objects/Goal__c.object
<CustomObject>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WY</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Goal</label>
    <nameField>
        <label>Goal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Goals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

TestRepo2/src/objects/Goal_Account_Report_Item__c.object
<CustomObject>
    <fields>
        <fullName>Goal__c</fullName>
        <label>Goal</label>
        <referenceTo>Goal__c</referenceTo>
        <relationshipLabel>Goal Account Report Items</relationshipLabel>
        <relationshipName>Goal_Account_Report_Items</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Primary_Demographic__c</fullName>
        <label>Primary Demographic</label>
        <picklist>
            <picklistValues>
                <fullName>General Market</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hispanic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AfAm</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LGBT</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <formula>Account__r.State__r.Abbreviation__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>State</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Goal Account Report Item</label>
    <nameField>
        <displayFormat>GARI-{00000000}</displayFormat>
        <label>Goal Account Report Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Goal Account Report Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestRepo2/src/objects/Goal_Product_Link__c.object
<CustomObject>
    <fields>
        <fullName>Goal__c</fullName>
        <label>Goal</label>
        <referenceTo>Goal__c</referenceTo>
        <relationshipName>Goal_Product_Links</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Goal Brand</label>
    <nameField>
        <displayFormat>GPL-{0000000000}</displayFormat>
        <label>Brand ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Goal Brands</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestRepo2/src/objects/State__c.object
<CustomObject>
    <fields>
        <fullName>Abbreviation__c</fullName>
        <label>Abbreviation</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>State</label>
    <nameField>
        <label>State</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/State_Code__c.object
<CustomObject>
    <fields>
        <fullName>State_Code__c</fullName>
        <externalId>true</externalId>
        <label>State Code</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>State Code</label>
    <nameField>
        <label>State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>State Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/State_User_Report_Item__c.object
<CustomObject>
    <fields>
        <fullName>Accounts__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Accounts</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Called_On_Accounts__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Called On Accounts</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Key__c</fullName>
        <formula>IF(AND(State__c != null, Account_Segmentation__c != null), LEFT(State__c, 15) + &apos;|&apos; + Account_Segmentation__c + &apos;|&apos; + TEXT(Premise__c),
IF(AND(State__c != null, Primary_Demographic__c != null), LEFT(State__c, 15) + &apos;|&apos; + Primary_Demographic__c + &apos;|&apos; + TEXT(Premise__c),
IF(AND(User__c != null, Account_Segmentation__c != null), LEFT(User__c, 15) + &apos;|&apos; + Account_Segmentation__c + &apos;|&apos; + TEXT(Premise__c),
IF(AND(User__c != null, Primary_Demographic__c != null), LEFT(User__c, 15) + &apos;|&apos; + Primary_Demographic__c + &apos;|&apos; + TEXT(Premise__c),
null))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Key</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Demographic__c</fullName>
        <label>Primary Demographic</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>State</label>
        <referenceTo>State__c</referenceTo>
        <relationshipLabel>State User Report Items</relationshipLabel>
        <relationshipName>State_User_Report_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>State_User_Report_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>State User Report Item</label>
    <nameField>
        <displayFormat>SURI-{00000000}</displayFormat>
        <label>State User Report Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>State User Report Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/Territory__c.object
<CustomObject>
    <description>&quot;Rep&quot;, who is at the most granular level of role hierarchy, is always the Owner of a given Territory record.</description>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WY</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Territory</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

TestRepo2/src/classes/AccountActionsTest.cls
@isTest
private class AccountActionsTest {
	
    static testMethod void testUpdateRecordTypes() {
    	List<Account> accs = new List<Account>();
    	
        Account acc1 = new Account();
        acc1.Name = 'test account';
        acc1.NABCA_Sector_Code__c = 'o';
        accs.add(acc1);
        
        Account acc2 = new Account();
        acc2.Name = 'test account';
        acc2.NABCA_Sector_Code__c = 'f';
        accs.add(acc2);
        
        Account acc3 = new Account();
        acc3.Name = 'test account';
        accs.add(acc3);
        
        Account acc4 = new Account();
        acc4.Name = 'test account';
        accs.add(acc4);
        
        Test.startTest();
        
       	insert accs;
       	
       	acc3.NABCA_Sector_Code__c = 'o';
       	acc4.NABCA_Sector_Code__c = 'c';
       	
       	update accs;
       	
       	Test.stopTest();
       	
       	acc1 = [SELECT Id, RecordType.Name FROM Account WHERE Id = :acc1.Id];
       	System.assertEquals('On-Premise - Control', acc1.RecordType.Name);
       	
       	acc2 = [SELECT Id, RecordType.Name FROM Account WHERE Id = :acc2.Id];
       	System.assertEquals('Off-Premise - Control', acc2.RecordType.Name);
       	
       	acc3 = [SELECT Id, RecordType.Name FROM Account WHERE Id = :acc3.Id];
       	System.assertEquals('On-Premise - Control', acc3.RecordType.Name);
       	
       	acc4 = [SELECT Id, RecordType.Name FROM Account WHERE Id = :acc4.Id];
       	System.assertEquals('Off-Premise - Control', acc4.RecordType.Name);
    }
    
    static testMethod void testCheckNABCATerritory() {
    	State_Code__c code = new State_Code__c();
    	code.State_Code__c = 'DM';
    	insert code;
    	
    	Territory__c terr = new Territory__c();
    	terr.Name = 'DM1 Holding';
    	insert terr;
    	
    	Account acc1 = new Account();
    	acc1.Name = 'Test Account';
    	acc1.Nabca_Account_Name__c = 'Test Account (test)';
    	acc1.Licensee_State_Code__c = code.Id;
    	
    	Account acc2 = new Account();
    	acc2.Name = 'Test Account';
    	acc2.Nabca_Account_Name__c = 'Test Account (test)';
    	
    	Test.startTest();
    	
    	insert acc1;
    	insert acc2;
    	
    	Test.stopTest();
    	
    	acc1 = [SELECT Id, Territory__c FROM Account WHERE Id = :acc1.Id];
    	System.assertEquals(terr.Id, acc1.Territory__c);
    	acc2 = [SELECT Id, Territory__c FROM Account WHERE Id = :acc2.Id];
    	System.assertEquals(null, acc2.Territory__c);
    	
    	acc2.Licensee_State_Code__c = code.Id;
    	update acc2;
    	acc2 = [SELECT Id, Territory__c FROM Account WHERE Id = :acc2.Id];
    	System.assertEquals(terr.Id, acc2.Territory__c);
    }
    
    static testMethod void testSURIUpdating() {
    	Map<String, Id> accRTIDsByName = new Map<String, Id>();
		for(RecordType rt : [SELECT Id, Name FROM RecordType WHERE SObjectType = 'Account' AND Name LIKE '%Premise%']){
			accRTIDsByName.put(rt.Name, rt.Id);
		}
		
    	State__c state = new State__c();
    	state.Abbreviation__c = 'DM';
    	state.Name__c = 'Davebraska';
    	insert state;
    	
    	User use = new User(alias = 'unittest', email='unittest@modelmetrics.com', 
	        emailencodingkey='UTF-8', lastname='Testing', 
	        languagelocalekey='en_US', 
	        localesidkey='en_US', profileid = UserInfo.getProfileId(),
	        timezonesidkey='America/Chicago', 
	        username='unittest@modelmetrics.com');
	    insert use;
	    
	    List<Account> accs = new List<Account>();
    	
    	Account acc1 = new Account();
    	acc1.Name = 'acc1';
    	acc1.NABCA_Licensee_State__c = 'DM';
    	acc1.OwnerId = use.Id;
    	acc1.Account_Segmentatiobn__c = 'A';
    	acc1.Primary_Demographic__c = 'Asian';
    	acc1.RecordTypeId = accRTIDsByName.get('On-Premise - Control');
    	accs.add(acc1);
    	
    	Account acc2 = new Account();
    	acc2.Name = 'acc2';
    	acc2.NABCA_Licensee_State__c = 'DM';
    	acc2.OwnerId = use.Id;
    	acc2.Account_Segmentatiobn__c = 'A';
    	acc2.Primary_Demographic__c = 'AfAm';
    	acc2.RecordTypeId = accRTIDsByName.get('On-Premise - Control');
    	accs.add(acc2);
    	
    	Account acc3 = new Account();
    	acc3.Name = 'acc3';
    	acc3.NABCA_Licensee_State__c = 'DM';
    	acc3.OwnerId = use.Id;
    	acc3.Account_Segmentatiobn__c = 'A';
    	acc3.Primary_Demographic__c = 'Asian';
    	acc3.RecordTypeId = accRTIDsByName.get('On-Premise - Control');
    	acc3.Called_On__c = true;
    	accs.add(acc3);
    	
    	
    	Account acc4 = new Account();
    	acc4.Name = 'acc4';
    	acc4.NABCA_Licensee_State__c = 'DM';
    	acc4.OwnerId = use.Id;
    	acc4.Account_Segmentatiobn__c = 'A';
    	acc4.Primary_Demographic__c = 'AfAm';
    	acc4.RecordTypeId = accRTIDsByName.get('On-Premise - Control');
    	acc4.Called_On__c = true;
    	//accs.add(acc4);
    	
    	Test.startTest();
    	
    	insert accs;
    	insert acc4;
    	
    	Test.stopTest();
    	
    	String stateId = String.valueOf(state.Id).subString(0, 15);
    	String useId = String.valueOf(use.Id).subString(0, 15);
    	
    	List<State_User_Report_Item__c> suris = [SELECT Id, Key__c, Accounts__c, Called_On_Accounts__c FROM State_User_Report_Item__c WHERE State__c = :state.Id OR User__c = :use.Id ORDER BY Key__c];
    	System.assertEquals(6, suris.size());
    	for(State_User_Report_Item__c suri : suris){
    		if(suri.Key__c == stateId + '|' + 'A' + '|On' || suri.Key__c == useId + '|' + 'A' + '|On'){
    			System.assertEquals(4, suri.Accounts__c);
    			System.assertEquals(2, suri.Called_On_Accounts__c);
    		} else if(suri.Key__c == stateId + '|' + 'Asian' + '|On' || suri.Key__c == useId + '|' + 'Asian' + '|On'){
    			System.assertEquals(2, suri.Accounts__c);
    			System.assertEquals(1, suri.Called_On_Accounts__c);
    		} else if(suri.Key__c == stateId + '|' + 'AfAm' + '|On' || suri.Key__c == useId + '|' + 'AfAm' + '|On'){
    			System.assertEquals(2, suri.Accounts__c);
    			System.assertEquals(1, suri.Called_On_Accounts__c);
    		}
    	}
    	
    	acc4.Primary_Demographic__c = 'Asian';
    	update acc4;
    	
    	suris = [SELECT Id, Key__c, Accounts__c, Called_On_Accounts__c FROM State_User_Report_Item__c WHERE State__c = :state.Id OR User__c = :use.Id];
    	System.assertEquals(6, suris.size());
    	for(State_User_Report_Item__c suri : suris){
    		if(suri.Key__c == stateId + '|' + 'A' + '|On' || suri.Key__c == useId + '|' + 'A' + '|On'){
    			System.assertEquals(4, suri.Accounts__c);
    			System.assertEquals(2, suri.Called_On_Accounts__c);
    		} else if(suri.Key__c == stateId + '|' + 'Asian' + '|On' || suri.Key__c == useId + '|' + 'Asian' + '|On'){
    			System.assertEquals(3, suri.Accounts__c);
    			System.assertEquals(2, suri.Called_On_Accounts__c);
    		} else if(suri.Key__c == stateId + '|' + 'AfAm' + '|On' || suri.Key__c == useId + '|' + 'AfAm' + '|On'){
    			System.assertEquals(1, suri.Accounts__c);
    			System.assertEquals(0, suri.Called_On_Accounts__c);
    		}
    	}
    	
    	delete acc2;
    	
    	suris = [SELECT Id, Key__c, Accounts__c, Called_On_Accounts__c FROM State_User_Report_Item__c WHERE State__c = :state.Id OR User__c = :use.Id];
    	System.assertEquals(6, suris.size());
    	for(State_User_Report_Item__c suri : suris){
    		if(suri.Key__c == stateId + '|' + 'A' + '|On' || suri.Key__c == useId + '|' + 'A' + '|On'){
    			System.assertEquals(3, suri.Accounts__c);
    			System.assertEquals(2, suri.Called_On_Accounts__c);
    		} else if(suri.Key__c == stateId + '|' + 'Asian' + '|On' || suri.Key__c == useId + '|' + 'Asian' + '|On'){
    			System.assertEquals(3, suri.Accounts__c);
    			System.assertEquals(2, suri.Called_On_Accounts__c);
    		} else if(suri.Key__c == stateId + '|' + 'AfAm' + '|On' || suri.Key__c == useId + '|' + 'AfAm' + '|On'){
    			System.assertEquals(0, suri.Accounts__c);
    			System.assertEquals(0, suri.Called_On_Accounts__c);
    		}
    	}
    }
    
    static testMethod void testSURIUpdatingWithGARIs() {
    	Map<String, Id> accRTIDsByName = new Map<String, Id>();
		for(RecordType rt : [SELECT Id, Name FROM RecordType WHERE SObjectType = 'Account' AND Name LIKE '%Premise%']){
			accRTIDsByName.put(rt.Name, rt.Id);
		}
		
    	State__c state = new State__c();
    	state.Abbreviation__c = 'DM';
    	state.Name__c = 'Davebraska';
    	insert state;
    	
    	User use = new User(alias = 'unittest', email='unittest@modelmetrics.com', 
	        emailencodingkey='UTF-8', lastname='Testing', 
	        languagelocalekey='en_US', 
	        localesidkey='en_US', profileid = UserInfo.getProfileId(),
	        timezonesidkey='America/Chicago', 
	        username='unittest@modelmetrics.com');
	    insert use;
	    
	    List<Account> accs = new List<Account>();
    	
    	Account acc1 = new Account();
    	acc1.Name = 'acc1';
    	acc1.NABCA_Licensee_State__c = 'DM';
    	acc1.OwnerId = use.Id;
    	acc1.Account_Segmentatiobn__c = 'A';
    	acc1.Primary_Demographic__c = 'Asian';
    	acc1.RecordTypeId = accRTIDsByName.get('On-Premise - Control');
    	accs.add(acc1);
    	
    	Account acc2 = new Account();
    	acc2.Name = 'acc2';
    	acc2.NABCA_Licensee_State__c = 'DM';
    	acc2.OwnerId = use.Id;
    	acc2.Account_Segmentatiobn__c = 'A';
    	acc2.Primary_Demographic__c = 'AfAm';
    	acc2.RecordTypeId = accRTIDsByName.get('On-Premise - Control');
    	accs.add(acc2);
    	
    	Account acc3 = new Account();
    	acc3.Name = 'acc3';
    	acc3.NABCA_Licensee_State__c = 'DM';
    	acc3.OwnerId = use.Id;
    	acc3.Account_Segmentatiobn__c = 'A';
    	acc3.Primary_Demographic__c = 'Asian';
    	acc3.RecordTypeId = accRTIDsByName.get('On-Premise - Control');
    	acc3.Called_On__c = true;
    	accs.add(acc3);
    	
    	
    	Account acc4 = new Account();
    	acc4.Name = 'acc4';
    	acc4.NABCA_Licensee_State__c = 'DM';
    	acc4.OwnerId = use.Id;
    	acc4.Account_Segmentatiobn__c = 'A';
    	acc4.Primary_Demographic__c = 'AfAm';
    	acc4.RecordTypeId = accRTIDsByName.get('On-Premise - Control');
    	acc4.Called_On__c = true;
    	accs.add(acc4);
    	
    	insert accs;
    	
    	Goal__c goal = new Goal__c();
    	insert goal;
    	
    	Goal_Product_Link__c gpl = new Goal_Product_Link__c();
    	gpl.Goal__c = goal.Id;
    	gpl.Product_Classification__c = 'test class';
    	gpl.Product_Group__c = 'test group';
    	gpl.Report_Brand__c = 'test report brand';
    	gpl.Generic_Brand__c = 'test generic brand';
    	gpl.Sub_Brand__c = 'test sub brand';
    	gpl.Individual_Brand__c = 'test individual brand';
    	gpl.Size__c = 'test size';
    	insert gpl;
    	
    	List<Action__c> acts = new List<Action__c>();
    	
    	Action__c act1 = new Action__c();
    	act1.Goal__c = goal.Id;
    	act1.Account__c = acc1.Id;
    	acts.add(act1);
    	
    	Action__c act2 = new Action__c();
    	act2.Goal__c = goal.Id;
    	act2.Account__c = acc2.Id;
    	acts.add(act2);
    	
    	Action__c act3 = new Action__c();
    	act3.Goal__c = goal.Id;
    	act3.Account__c = acc3.Id;
    	acts.add(act3);
    	
    	Action__c act4 = new Action__c();
    	act4.Goal__c = goal.Id;
    	act4.Account__c = acc4.Id;
    	acts.add(act4);
    	
    	insert acts;
    	
    	Test.startTest();
    	
    	act1.Status__c = 'Closed - Complete';
    	act2.Status__c = 'Closed - Complete';
    	act3.Status__c = 'Closed - Complete';
    	act4.Status__c = 'Closed - Complete';
    	update acts;
    	
    	Test.stopTest();
    	
    	String stateId = String.valueOf(state.Id).subString(0, 15);
    	String useId = String.valueOf(use.Id).subString(0, 15);
    	
    	List<State_User_Report_Item__c> suris = [SELECT Id, Key__c, Accounts__c, Called_On_Accounts__c FROM State_User_Report_Item__c WHERE State__c = :state.Id OR User__c = :use.Id];
    	System.assertEquals(6, suris.size());
    	for(State_User_Report_Item__c suri : suris){
    		if(suri.Key__c == stateId + '|' + 'A' + '|On' || suri.Key__c == useId + '|' + 'A' + '|On'){
    			System.assertEquals(4, suri.Accounts__c);
    			System.assertEquals(2, suri.Called_On_Accounts__c);
    		} else if(suri.Key__c == stateId + '|' + 'Asian' + '|On' || suri.Key__c == useId + '|' + 'Asian' + '|On'){
    			System.assertEquals(2, suri.Accounts__c);
    			System.assertEquals(1, suri.Called_On_Accounts__c);
    		} else if(suri.Key__c == stateId + '|' + 'AfAm' + '|On' || suri.Key__c == useId + '|' + 'AfAm' + '|On'){
    			System.assertEquals(2, suri.Accounts__c);
    			System.assertEquals(1, suri.Called_On_Accounts__c);
    		}
    	}
    	
    	List<Goal_Account_Report_Item__c> garis =
    		[SELECT Id,
    				Account__c,
    				State_Accounts_AS__c,
    				State_Accounts_PD__c,
    				State_Called_On_Accounts_AS__c,
    				State_Called_On_Accounts_PD__c,
    				User_Accounts_AS__c,
    				User_Accounts_PD__c,
    				User_Called_On_Accounts_AS__c,
    				User_Called_On_Accounts_PD__c
    		   FROM Goal_Account_Report_Item__c
    		  WHERE Goal__c = :goal.Id
    		];
    	System.assertEquals(4, garis.size());
    	for(Goal_Account_Report_Item__c gari : garis){
    		if(gari.Account__c == acc1.Id){
    			System.assertEquals(4, gari.State_Accounts_AS__c);
    			System.assertEquals(2, gari.State_Accounts_PD__c);
    			System.assertEquals(2, gari.State_Called_On_Accounts_AS__c);
    			System.assertEquals(1, gari.State_Called_On_Accounts_PD__c);
    		} else if(gari.Account__c == acc2.Id){
    			System.assertEquals(4, gari.State_Accounts_AS__c);
    			System.assertEquals(2, gari.State_Accounts_PD__c);
    			System.assertEquals(2, gari.State_Called_On_Accounts_AS__c);
    			System.assertEquals(1, gari.State_Called_On_Accounts_PD__c);
    		} else if(gari.Account__c == acc3.Id){
    			System.assertEquals(4, gari.State_Accounts_AS__c);
    			System.assertEquals(2, gari.State_Accounts_PD__c);
    			System.assertEquals(2, gari.State_Called_On_Accounts_AS__c);
    			System.assertEquals(1, gari.State_Called_On_Accounts_PD__c);
    		} else if(gari.Account__c == acc4.Id){
    			System.assertEquals(4, gari.State_Accounts_AS__c);
    			System.assertEquals(2, gari.State_Accounts_PD__c);
    			System.assertEquals(2, gari.State_Called_On_Accounts_AS__c);
    			System.assertEquals(1, gari.State_Called_On_Accounts_PD__c);
    		}
    	}
    	
    	acc4.Primary_Demographic__c = 'Asian';
    	update acc4;
    	
    	suris = [SELECT Id, Key__c, Accounts__c, Called_On_Accounts__c FROM State_User_Report_Item__c WHERE State__c = :state.Id OR User__c = :use.Id];
    	System.assertEquals(6, suris.size());
    	for(State_User_Report_Item__c suri : suris){
    		if(suri.Key__c == stateId + '|' + 'A' + '|On' || suri.Key__c == useId + '|' + 'A' + '|On'){
    			System.assertEquals(4, suri.Accounts__c);
    			System.assertEquals(2, suri.Called_On_Accounts__c);
    		} else if(suri.Key__c == stateId + '|' + 'Asian' + '|On' || suri.Key__c == useId + '|' + 'Asian' + '|On'){
    			System.assertEquals(3, suri.Accounts__c);
    			System.assertEquals(2, suri.Called_On_Accounts__c);
    		} else if(suri.Key__c == stateId + '|' + 'AfAm' + '|On' || suri.Key__c == useId + '|' + 'AfAm' + '|On'){
    			System.assertEquals(1, suri.Accounts__c);
    			System.assertEquals(0, suri.Called_On_Accounts__c);
    		}
    	}
    	
    	garis =
    		[SELECT Id,
    				Account__c,
    				State_Accounts_AS__c,
    				State_Accounts_PD__c,
    				State_Called_On_Accounts_AS__c,
    				State_Called_On_Accounts_PD__c,
    				User_Accounts_AS__c,
    				User_Accounts_PD__c,
    				User_Called_On_Accounts_AS__c,
    				User_Called_On_Accounts_PD__c
    		   FROM Goal_Account_Report_Item__c
    		  WHERE Goal__c = :goal.Id
    		];
    	System.assertEquals(4, garis.size());
    	for(Goal_Account_Report_Item__c gari : garis){
    		if(gari.Account__c == acc1.Id){
    			System.assertEquals(4, gari.State_Accounts_AS__c);
    			System.assertEquals(3, gari.State_Accounts_PD__c);
    			System.assertEquals(2, gari.State_Called_On_Accounts_AS__c);
    			System.assertEquals(2, gari.State_Called_On_Accounts_PD__c);
    		} else if(gari.Account__c == acc2.Id){
    			System.assertEquals(4, gari.State_Accounts_AS__c);
    			System.assertEquals(1, gari.State_Accounts_PD__c);
    			System.assertEquals(2, gari.State_Called_On_Accounts_AS__c);
    			System.assertEquals(0, gari.State_Called_On_Accounts_PD__c);
    		} else if(gari.Account__c == acc3.Id){
    			System.assertEquals(4, gari.State_Accounts_AS__c);
    			System.assertEquals(3, gari.State_Accounts_PD__c);
    			System.assertEquals(2, gari.State_Called_On_Accounts_AS__c);
    			System.assertEquals(2, gari.State_Called_On_Accounts_PD__c);
    		} else if(gari.Account__c == acc4.Id){
    			System.assertEquals(4, gari.State_Accounts_AS__c);
    			System.assertEquals(3, gari.State_Accounts_PD__c);
    			System.assertEquals(2, gari.State_Called_On_Accounts_AS__c);
    			System.assertEquals(2, gari.State_Called_On_Accounts_PD__c);
    		}
    	}
    }
}