TestRepo2/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Called_On__c</fullName>
        <defaultValue>false</defaultValue>
        <description>As a Sales Rep, I need the Called On field so I can flag the accounts that I visit</description>
        <inlineHelpText>Check this box if this is an Account that is visited by a Sales Rep</inlineHelpText>
        <label>Called On</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>State</label>
        <referenceTo>State__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Territory</label>
        <referenceTo>Territory__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

TestRepo2/src/objects/Goal__c.object
<CustomObject>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Goal_For__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Goal For</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Goals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Goal_Level__c</fullName>
        <label>Goal Level</label>
        <picklist>
            <picklistValues>
                <fullName>Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rep</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Goal_Type__c</fullName>
        <label>Goal Type</label>
        <picklist>
            <picklistValues>
                <fullName>On-Premise - Control</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Off-Premise - Control</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Minimum_of_Accounts__c</fullName>
        <label>Goal</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Parent_Goal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Goal</label>
        <referenceTo>Goal__c</referenceTo>
        <relationshipLabel>Child Goals</relationshipLabel>
        <relationshipName>Child_Goals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <picklist>
            <picklistValues>
                <fullName>National</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Local</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WY</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Goal</label>
    <nameField>
        <label>Goal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Goals</pluralLabel>
    <recordTypes>
        <fullName>Ad_Execution</fullName>
        <active>true</active>
        <label>Ad Execution</label>
    </recordTypes>
    <recordTypes>
        <fullName>Cold_Box_Goals</fullName>
        <active>true</active>
        <label>Cold Box Goals</label>
    </recordTypes>
    <recordTypes>
        <fullName>Display_Goals</fullName>
        <active>true</active>
        <label>Display Goals</label>
    </recordTypes>
    <recordTypes>
        <fullName>Distribution_POD_Goals</fullName>
        <active>true</active>
        <label>Distribution (POD) Goals</label>
    </recordTypes>
    <recordTypes>
        <fullName>Ease_of_Shop</fullName>
        <active>true</active>
        <label>Ease of Shop</label>
    </recordTypes>
    <recordTypes>
        <fullName>Feature</fullName>
        <active>true</active>
        <label>Feature Goals</label>
    </recordTypes>
    <recordTypes>
        <fullName>Menu</fullName>
        <active>true</active>
        <label>Menu Goals</label>
    </recordTypes>
    <recordTypes>
        <fullName>Shelf_Set_Goals</fullName>
        <active>true</active>
        <label>Shelf Set Goals</label>
    </recordTypes>
    <recordTypes>
        <fullName>Staff_Training_Goals</fullName>
        <active>true</active>
        <label>Staff Training Goals</label>
    </recordTypes>
    <recordTypes>
        <fullName>Tasting_Goals</fullName>
        <active>true</active>
        <label>Tasting Goals</label>
    </recordTypes>
    <recordTypes>
        <fullName>Volume_Goals</fullName>
        <active>true</active>
        <label>Volume/QD Goals</label>
    </recordTypes>
    <recordTypes>
        <fullName>Window_Display_Goals</fullName>
        <active>true</active>
        <label>Window Display Goals</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

TestRepo2/src/objects/Goal_Product_Link__c.object
<CustomObject>
    <fields>
        <fullName>Generic_Brand__c</fullName>
        <label>Generic Brand</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Goal__c</fullName>
        <label>Goal</label>
        <referenceTo>Goal__c</referenceTo>
        <relationshipName>Goal_Product_Links</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Goal Brand</label>
    <nameField>
        <displayFormat>GPL-{0000000000}</displayFormat>
        <label>Brand ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Goal Brands</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestRepo2/src/objects/State__c.object
<CustomObject>
    <label>State</label>
    <nameField>
        <label>State</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/Territory__c.object
<CustomObject>
    <description>&quot;Rep&quot;, who is at the most granular level of role hierarchy, is always the Owner of a given Territory record.</description>
    <fields>
        <fullName>Director__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Director</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territories1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SAM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Diageo Goal Creator</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territories2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WY</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Territory</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

TestRepo2/src/classes/ActionAssignmentControllerTest.cls
@isTest
private class ActionAssignmentControllerTest {

    static testMethod void testActionAssignmentController() {
        Id samProfId = [SELECT Id FROM Profile WHERE Name = 'Control - Sales Manager'].Id;
        User sam = Test_RecordUtil.newUser('sam', samProfId);
        User dir1 = Test_RecordUtil.newUser('dir1', samProfId);
        User mgr1 = Test_RecordUtil.newUser('mgr1', samProfId);
        User rep1 = Test_RecordUtil.newUser('rep1', samProfId);
        User dirmgr1 = Test_RecordUtil.newUser('dirmgr1', samProfId);
        
        List<User> users = new List<User>();
        users.add(sam);
        users.add(dir1);
        users.add(mgr1);
        users.add(rep1);
        users.add(dirmgr1);
        insert users;
        
        //create territories
        Territory__c terr1 = Test_RecordUtil.newTerritory('terr1');
        terr1.SAM__c = sam.Id;
        terr1.Director__c = dir1.Id;
        terr1.Manager__c = mgr1.Id;
        terr1.OwnerId = rep1.Id;
        insert terr1;
        Territory__c terr2 = Test_RecordUtil.newTerritory('terr2');
        terr2.SAM__c = sam.Id;
        terr2.Director__c = dirmgr1.Id;
        terr2.Manager__c = dirmgr1.Id;
        terr2.OwnerId = rep1.Id;
        insert terr2;
        
        Account acc1 = new Account();
        acc1.Name = 'Test Account';
        acc1.Territory__c = terr1.Id;
        acc1.RecordTypeId = [SELECT Id FROM RecordType WHERE SObjectType = 'Account' AND Name = 'On Premise'].Id;
        acc1.Called_On__c = true;
        acc1.OwnerId = rep1.Id;
        insert acc1;
        
        Account acc2 = new Account();
        acc2.Name = 'Test Account';
        acc2.Territory__c = terr1.Id;
        acc2.RecordTypeId = [SELECT Id FROM RecordType WHERE SObjectType = 'Account' AND Name = 'Off Premise'].Id;
        acc2.Called_On__c = true;
        acc2.OwnerId = rep1.Id;
        insert acc2;
        
        Goal__c goal1 = new Goal__c();
        goal1.Priority__c = 'National';
        goal1.OwnerId = mgr1.Id;
        goal1.Goal_For__c = mgr1.Id;
        goal1.Name = 'Distribution Goals - Dave Test - On';
        goal1.Goal_Type__c = 'On-Premise - Control';
        goal1.State__c = 'PA';
        goal1.Minimum_of_Accounts__c = 2;
        goal1.Start_Date__c = Date.today();
        goal1.Due_Date__c = Date.today().addDays(1);
        goal1.Goal_Level__c = 'Manager';
        insert goal1;
        
        Goal_Product_Link__c gpl1 = new Goal_Product_Link__c();
        gpl1.Generic_Brand__c = 'Test Brand';
        gpl1.Goal__c = goal1.Id;
        insert gpl1;
        
        Goal__c goal2 = new Goal__c();
        goal2.Priority__c = 'National';
        goal2.OwnerId = rep1.Id;
        goal2.Goal_For__c = rep1.Id;
        goal2.Name = 'Distribution Goals - Dave Test - On';
        goal2.Goal_Type__c = 'On-Premise - Control';
        goal2.State__c = 'PA';
        goal2.Minimum_of_Accounts__c = 2;
        goal2.Start_Date__c = Date.today();
        goal2.Due_Date__c = Date.today().addDays(1);
        goal2.Goal_Level__c = 'Rep';
        insert goal2;
        
        Goal_Product_Link__c gpl2 = new Goal_Product_Link__c();
        gpl2.Generic_Brand__c = 'Test Brand';
        gpl2.Goal__c = goal2.Id;
        insert gpl2;
        
        Map<String, Id> goalRTIdsByDevName = new Map<String, Id>();
        for(RecordType rt : [SELECT Id, DeveloperName FROM RecordType WHERE SObjectType = 'Goal__c']){
        	goalRTIdsByDevName.put(rt.DeveloperName, rt.Id);
        }
        
        Test.startTest();
        
        System.runAs(mgr1){
        	ActionAssignmentController cont = new ActionAssignmentController();
        	
        	cont.dummyGoalId = goal1.Id;
        	ActionAssignmentController.getManagerTerritories();
        	ActionAssignmentController.getUserGoals();
        	ActionAssignmentController.getPriorities();
        	cont.assignDummyEditGoal();
        	cont.doNothing();
        	cont.saveDummyGoal();
        	
        	List<Goal__c> childGoals = new List<Goal__c>();
        	Goal__c childGoal = new Goal__c();
        	childGoal.Parent_Goal__c = goal1.Id;
        	childGoal.Goal_For__c = rep1.Id;
        	childGoals.add(childGoal);
        	ActionAssignmentGoalSaver.saveGoals(childGoals);
        }
        
        System.runAs(rep1){
        	ActionAssignmentController cont = new ActionAssignmentController();
        	
        	cont.dummyGoalId = goal2.Id;
        	ActionAssignmentController.getRepTerritories();
        	cont.assignDummyViewGoal();
        	
        	goal2.RecordTypeId = goalRTIdsByDevName.get('Ad_Execution');
        	update goal2;
        	cont.assignDummyViewGoal();
        	
        	goal2.RecordTypeId = goalRTIdsByDevName.get('Cold_Box_Goals');
        	update goal2;
        	cont.assignDummyViewGoal();
        	
        	goal2.RecordTypeId = goalRTIdsByDevName.get('Display_Goals');
        	update goal2;
        	cont.assignDummyViewGoal();
        	
        	goal2.RecordTypeId = goalRTIdsByDevName.get('Distribution_POD_Goals');
        	update goal2;
        	cont.assignDummyViewGoal();
        	
        	goal2.RecordTypeId = goalRTIdsByDevName.get('Ease_of_Shop');
        	update goal2;
        	cont.assignDummyViewGoal();
        	
        	goal2.RecordTypeId = goalRTIdsByDevName.get('Feature');
        	update goal2;
        	cont.assignDummyViewGoal();
        	
        	goal2.RecordTypeId = goalRTIdsByDevName.get('Menu');
        	update goal2;
        	cont.assignDummyViewGoal();
        	
        	goal2.RecordTypeId = goalRTIdsByDevName.get('Shelf_Set_Goals');
        	update goal2;
        	cont.assignDummyViewGoal();
        	
        	goal2.RecordTypeId = goalRTIdsByDevName.get('Staff_Training_Goals');
        	update goal2;
        	cont.assignDummyViewGoal();
        	
        	goal2.RecordTypeId = goalRTIdsByDevName.get('Tasting_Goals');
        	update goal2;
        	cont.assignDummyViewGoal();
        	
        	goal2.RecordTypeId = goalRTIdsByDevName.get('Volume_Goals');
        	update goal2;
        	cont.assignDummyViewGoal();
        	
        	goal2.RecordTypeId = goalRTIdsByDevName.get('Window_Display_Goals');
        	update goal2;
        	cont.assignDummyViewGoal();
        	
        	List<String> terrIds = new List<String>();
        	terrIds.add(terr1.Id);
        	ActionAssignmentController.getAccounts(terrIds);
        	
        	ActionAssignmentController.saveActions(goal2.Id, acc1.Id + ',' + acc2.Id);
        }
    }
}