TestRepo2/src/objects/AccountBrand__c.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipLabel>AccountBrand</relationshipLabel>
        <relationshipName>AccountBrand1</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>AccountBrand</label>
    <nameField>
        <label>AccountBrand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AccountBrand</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestRepo2/src/objects/Brand__c.object
<CustomObject>
    <fields>
        <fullName>Content_Description__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Content Description (logo)</description>
        <label>Content Description</label>
        <referenceTo>Content_Description__c</referenceTo>
        <relationshipLabel>Brands</relationshipLabel>
        <relationshipName>Brands</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/Content_Description__c.object
<CustomObject>
    <fields>
        <fullName>Content_Version_Id_Low__c</fullName>
        <label>Content Version Id Low</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Content_Version_Id__c</fullName>
        <label>Content Version Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Content Description</label>
    <nameField>
        <label>Content Description Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Content Descriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/ContentBrand__c.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipLabel>ContentBrand</relationshipLabel>
        <relationshipName>ContentBrand</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Content_Description__c</fullName>
        <label>Content Description</label>
        <referenceTo>Content_Description__c</referenceTo>
        <relationshipLabel>ContentBrand</relationshipLabel>
        <relationshipName>ContentBrand_del</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>ContentBrand</label>
    <nameField>
        <label>ContentBrand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ContentBrand</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestRepo2/src/classes/Test_ControllerBaseRemote.cls
@isTest
private class Test_ControllerBaseRemote {

     static testMethod void testController1() {
	
        Account a = Test_Helper.testInsertAccount('Test Account');
        Contact c = Test_Helper.testInsertContact('TestFirst', 'TestLast', a.ID);
        User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];   
        User u;
      	System.runAs (thisUser) {
        	u = Test_Helper.testInsertDistributorPortalUser(c.ID);
      	}
      	
    	Test.StartTest();    
    	System.runAs(u){	
	    	String searchFor = 'mar';
	       	Controller_BaseRemote.getPossibleShareUsers(searchFor, '');
	       	Controller_BaseRemote.downloadVideoFromBC('1234');
	       	Controller_BaseRemote cc  = new Controller_BaseRemote();
	       	Controller_Base		  bb  = new Controller_Base();
	       	Controller_BaseRemote dd = new Controller_BaseRemote(bb);
	       	
	       	Controller_BaseRemote.searchPILBrand('Smirnoff');
    	}       	
       	Test.StopTest();
     }
      
      static testmethod void testController(){
        // insert test user data  
        Account a = Test_Helper.testInsertAccount('Test Account');
        Contact c = Test_Helper.testInsertContact('TestFirst', 'TestLast', a.ID);
        User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];   
        User u;
      	System.runAs (thisUser) {
        	u = Test_Helper.testInsertDistributorPortalUser(c.ID);
      	}
        
        // insert test brands
        Brand__c brandA = Test_Helper.testInsertBrand('Test Brand A');
        
        // hook one of the parent brands too the user's account
        AccountBrand__c accBrand = Test_Helper.testInsertAccountBrand(a.ID, brandA.ID);
        
        // insert test content that looks up to the previoulsy inserted brands 
        Content_Description__c contentA = Test_Helper.testInsertContentDescriptionExtended('rose');
        Content_Description__c contentB = Test_Helper.testInsertContentDescriptionExtended('orchid');
        Content_Description__c contentC = Test_Helper.testInsertContentDescriptionExtended('tulip');
		
		contentA.Content_Version_Id_Low__c = contentA.Content_Version_Id__c;
		contentA.Content_Version_Id__c = null;
		update contentA;
		
        // insert the join records between content and brand        
        ContentBrand__c cbA = Test_Helper.testInsertContentBrand(contentA.id, brandA.id);
        ContentBrand__c cbB = Test_Helper.testInsertContentBrand(contentB.id, brandA.id);
        ContentBrand__c cbC = Test_Helper.testInsertContentBrand(contentC.id, brandA.id);

        Test.startTest();

        System.runAs(u){       	
	  		    
		    Controller_BaseRemote.cacheDownload(contentB.Content_Version_Id__c);
       		Controller_BaseRemote.cacheDownload(contentA.Content_Version_Id_Low__c);
       		
       		Controller_BaseRemote.searchPILBrand('Smirnoff');
        }
        
        Test.stopTest();
    }
}