TestRepo2/src/objects/Account_Member__c.object
<CustomObject>
    <description>POS Project: junction object that represents the many-to-many relationship between Accounts and Users (Shoppers)</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Members</relationshipLabel>
        <relationshipName>Account_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Account_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Member</label>
    <nameField>
        <displayFormat>ACM-{000000}</displayFormat>
        <label>Account Member ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestRepo2/src/objects/Item__c.object
<CustomObject>
    <description>POS Project: object that represents catalog items available for shopping</description>
    <fields>
        <fullName>Agency_Item_ID__c</fullName>
        <externalId>true</externalId>
        <label>Agency Item ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Agency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agency</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Magento_ID__c</fullName>
        <externalId>true</externalId>
        <label>Magento ID</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Development</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Approved w/Est Price</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted w/Final Price</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Removed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

TestRepo2/src/objects/Order_Window__c.object
<CustomObject>
    <description>POS Project: object that represents a period of time in which catalog items are offered and shoppers are allowed to buy them</description>
    <fields>
        <fullName>Magento_Id__c</fullName>
        <externalId>true</externalId>
        <label>Magento Category Id</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <controllingField>Type__c</controllingField>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Budgeting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Archived</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Order Window</label>
    <nameField>
        <label>Order Window Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Windows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/POSAPIConfiguration__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>POS_Agency_Profile_Name__c</fullName>
        <label>POS Agency Profile Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>POS API Configuration</label>
</CustomObject>

TestRepo2/src/objects/Program__c.object
<CustomObject>
    <description>POS Project: object that represents a set of events for which related catalog items are offered to shoppers (distributors and internal Diageo employees)</description>
    <fields>
        <fullName>Magento_Id__c</fullName>
        <externalId>true</externalId>
        <label>Magento Category Id</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Window__c</fullName>
        <label>Order Window</label>
        <referenceTo>Order_Window__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestRepo2/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Magento_Id__c</fullName>
        <externalId>true</externalId>
        <label>Magento_Id</label>
        <length>80</length>
        <type>Text</type>
    </fields>
</CustomObject>

TestRepo2/src/classes/POS_APIUpsertItem.cls
@RestResource(urlMapping='/UpsertItem/*')
global with sharing class POS_APIUpsertItem {
    
    public static String STATUS_SUCCESS='success';
    public static String STATUS_FAIL='fail';
    
    @HttpPost
    global static UpsertResponse doPost (Item__c item, RestResponse res) {
        
        String userId = UserInfo.getUserId();
        
        POSAPIConfiguration__c settings = POSAPIConfiguration__c.getOrgDefaults();
        String PROFILE_NAME = settings.POS_Agency_Profile_Name__c;
        
        List<Account_Member__c> accountMembers = [select a.Account__c from Account_Member__c a where a.User__c= :userId
            and a.Account__r.RecordType.Name = :PROFILE_NAME];
            
        //There should be one and only one agency associated with this account
        if (accountMembers == null || accountMembers.size()!=1) {
            res.StatusCode = 400;
            res.addHeader('Error','Misconfiguration: account not configured for a single POS agency');
            return new UpsertResponse();
            
        }
        
        //They must provide an agency item Id
        if (item.Agency_Item_Id__c==null) {
            res.StatusCode = 400;
            res.addHeader('Error','Agency Item ID is a required field');
            return new UpsertResponse();
        }
        
        //They must set the program if it's a new item
        if (item.Id==null && item.Program__c==null) {
            res.StatusCode = 400;
            res.addHeader('Error','Items must be associated with a valid Program');
            return new UpsertResponse();
        }
        
        Id agency = accountMembers.get(0).Account__c;
        
        UpsertResponse upsertResponse = new UpsertResponse();
        try {
            
            upsertResponse.AgencyItemId=item.Agency_Item_Id__c;
            //Check to see if this is an update
            if (item.Id!=null) {
                //It's an update
                //Get Magento ID from the current version of the item (API should not allow change of Magento ID)
                Id itemId = item.Id;
                Item__c currentItem = [select Magento_Id__c from Item__c where Id=:itemId];
                item.Magento_ID__c=currentItem.Magento_ID__c;
                upsertResponse.Id=item.Id;
                update item;
                upsertResponse.status=STATUS_SUCCESS;
            }
            else {
                item.Agency__c=agency;
                insert item;
                upsertResponse.Id=item.Id;
                upsertResponse.status=STATUS_SUCCESS;
            }
        }
        catch (Exception e) {
            upsertResponse.status=STATUS_FAIL;
            upsertResponse.statusDetail=e.getMessage();
        }
        return upsertResponse;
        
    }
    
    global class UpsertResponse {
        public String Id {get;set;}
        public String AgencyItemId {get;set;}
        public String status {get;set;}
        public String statusDetail {get;set;}
        
    }
    
    @IsTest(SeeAllData=true)
    public static void testUpsertItem () {
        
        //Get the current time
        Datetime now = System.now();
        
        Profile p = [select id from profile where name='POS - API User Agency'];
         
        User u = new User(alias = 'posmmtst', email='posmmunittest@diageo.com',
        emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US',
        localesidkey='en_US', profileid = p.Id,
        timezonesidkey='America/Chicago', username='posmmunittest@diageo.com');
        RecordType posAgencyRecordType = [select Id from RecordType where Name='POS Production Agency' and sObjectType='Account'];
        
        
        System.runAs(u) {
            POSAPIConfiguration__c settings = POSAPIConfiguration__c.getOrgDefaults();
        
            //Now test queries for other filters
            Order_Window__c window = POS_TestDataUtil.createOrderWindow();
            window.Status__c='In Review';
            update window;
            
            Program__c program = POS_TestDataUtil.createProgram();
            Account account = POS_TestDataUtil.createAccount();
            account.RecordTypeId = posAgencyRecordType.Id;
            update account;
            
            
            //Test if this user isn't associated with an agency account
            Item__c item = POS_TestDataUtil.populateItem(program,account);
            item.Agency_Item_Id__c = 'AGENCYID';
            
            RestResponse restResponse = new RestResponse();
            UpsertResponse response = POS_APIUpsertItem.doPost(item, restResponse);
            System.assert(restResponse.StatusCode==400);  //We get 400 because it's not permitted
            
            //Now associate them then try again
            POS_TestDataUtil.createAccountMember(account, u);
            
            restResponse = new RestResponse();
            response = POS_APIUpsertItem.doPost(item, restResponse);
            System.debug('Response: '+restResponse);
            
            //Make sure item got added
            String itemId = response.Id;
            List<Item__c> loadedItems = [select Id, Agency_Item_Id__c from Item__c where Id=:itemId];
            
            System.assert(loadedItems.size()==1);
            
            //Test an update
            restResponse = new RestResponse();
            response = POS_APIUpsertItem.doPost(item, new RestResponse());
            String agencyId = response.AgencyItemId;
            
            //If it reinserted the same record we'd have two results here
            loadedItems = [select Id, Agency_Item_Id__c from Item__c where Agency_Item_Id__c=:agencyId];
            System.assert(loadedItems.size()==1);
            
            
            //Test that it's rejected if the agency ID isn't there
            item = new Item__c();
            item.Program__c = program.Id;
    
            restResponse = new RestResponse();
            response = POS_APIUpsertItem.doPost(item, restResponse);
            System.assert(restResponse.StatusCode==400);  //We get 400 because it's not permitted
            
            //Test if no program is associated
            
            item = new Item__c();
            item.Program__c = null;
            restResponse = new RestResponse();
            response = POS_APIUpsertItem.doPost(item, restResponse);
            System.assert(restResponse.StatusCode==400);  //We get 400 because it's not permitted
            
            
        
        }
    }
        
     
}