TestRepo2/src/objects/AccountBrand__c.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipLabel>AccountBrand</relationshipLabel>
        <relationshipName>AccountBrand1</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>AccountBrand</label>
    <nameField>
        <label>AccountBrand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AccountBrand</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestRepo2/src/objects/Brand__c.object
<CustomObject>
    <fields>
        <fullName>Content_Description__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Content Description (logo)</description>
        <label>Content Description</label>
        <referenceTo>Content_Description__c</referenceTo>
        <relationshipLabel>Brands</relationshipLabel>
        <relationshipName>Brands</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/Content_Description__c.object
<CustomObject>
    <fields>
        <fullName>Content_ID__c</fullName>
        <label>Content ID</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Content_Version_Id_Low__c</fullName>
        <label>Content Version Id Low</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Content_Version_Id__c</fullName>
        <label>Content Version Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Content Description</label>
    <nameField>
        <label>Content Description Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Content Descriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/Content_Subscription__c.object
<CustomObject>
    <description>Content subscription object that subscribes a user to a piece of content</description>
    <fields>
        <fullName>Content__c</fullName>
        <label>Content</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Content_Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Content Subscription</label>
    <nameField>
        <displayFormat>CS-{000000}</displayFormat>
        <label>Content Subscription Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Content Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/ContentBrand__c.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipLabel>ContentBrand</relationshipLabel>
        <relationshipName>ContentBrand</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Content_Description__c</fullName>
        <label>Content Description</label>
        <referenceTo>Content_Description__c</referenceTo>
        <relationshipLabel>ContentBrand</relationshipLabel>
        <relationshipName>ContentBrand_del</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>ContentBrand</label>
    <nameField>
        <label>ContentBrand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ContentBrand</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestRepo2/src/classes/Test_ControllerFollow.cls
/*******************************************************************************
Name        : Test_ControllerFollow.cls

Updated By  : Basant Verma (Appirio Offshore)   
Date        : 6/10/13
Description	: Test Class which provide code coverage for 
									Controller_Follow.cls and Service_Follow  
									
Updated By  : Basant Verma (Appirio Offshore)   
Date        : 6/12/13
Story/Task  : US79/DE569
*******************************************************************************/
@isTest
private class Test_ControllerFollow {

    static testmethod void testFollow(){
        // insert test user data
        Account a = Test_Helper.testInsertAccount('Test Account');
        Contact c = Test_Helper.testInsertContact('TestFirst', 'TestLast', a.ID);
        User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
        User u;     
    
        System.runAs (thisUser) {
            u = Test_Helper.testInsertDistributorPortalUser(c.ID);
        }
        
        // insert test brands
        Brand__c brandA = Test_Helper.testInsertBrand('Test Brand A');
        
        // hook one of the parent brands too the user's account
        AccountBrand__c accBrand = Test_Helper.testInsertAccountBrand(a.ID, brandA.ID);
        
        // insert test content that looks up to the previoulsy inserted brands
        Content_Description__c contentA = Test_Helper.testInsertContentDescriptionExtended('rose');
        Content_Description__c contentB = Test_Helper.testInsertContentDescriptionExtended('orchid');
        Content_Description__c contentC = Test_Helper.testInsertContentDescriptionExtended('tulip');
        Content_Description__c contentD = Test_Helper.testInsertContentDescriptionExtended('Test');
        
        contentA.Content_Version_Id_Low__c = contentA.Content_Version_Id__c;
        contentA.Content_Version_Id__c = null;
        update contentA;
        
        
        // insert the join records between content and brand        
        ContentBrand__c cbA = Test_Helper.testInsertContentBrand(contentA.id, brandA.id);
        ContentBrand__c cbB = Test_Helper.testInsertContentBrand(contentB.id, brandA.id);
        ContentBrand__c cbC = Test_Helper.testInsertContentBrand(contentC.id, brandA.id);
        
        Test.startTest();

        System.runAs(u){
	        	Content_Subscription__c sub = new Content_Subscription__c();
		        sub.User__c = u.Id;
						sub.Content__c = contentD.Content_ID__c;
						insert sub;
						
						PageReference pageRef = Page.FollowedItems;
        		Test.setCurrentPage(pageRef);
            Controller_Follow cFollow = new Controller_Follow();
           
            System.assertEquals(1, Service_Follow.getNumberOfItems());
            
            // add single
            cFollow.cVersionId = contentB.Content_Version_Id__c;
            
            cFollow.addToFollow();
            System.assertEquals(2, Service_Follow.getNumberOfItems());
            
            //remove single
            cFollow.removeFromFollow();
            System.assertEquals(1 , Service_Follow.getNumberOfItems());
            
            // add multiple
            cFollow.cVersionIds = contentA.Content_Version_Id_Low__c+','+contentB.Content_Version_Id__c;
            cFollow.addToFollowMultiple();
            System.assertEquals(3, Service_Follow.getNumberOfItems());
            
            cFollow.refreshPageContent();
            
            //remove multiple
            cFollow.removeFromFollowMultiple();
            System.assertEquals(1, Service_Follow.getNumberOfItems());
            
            // Start : Changes for US79/DE569 by Basant Verma
            // For Service Notification 
            // add single
            cFollow.cVersionId = contentB.Content_Version_Id__c;
            List<Id> cvIds = new List<Id>();
            cvIds.add(cFollow.cVersionId);
            Service_Notification.addFollow(cvIds);
            System.assertEquals(2, Service_Follow.getNumberOfItems());
            
            //remove single
            cvIds = new List<Id>();
            cvIds.add(cFollow.cVersionId);
            Service_Notification.removeFollow(cvIds);
            System.assertEquals(1 , Service_Notification.getFollowIds().size());
						// End : Changes for US79/DE569 by Basant Verma
						
            Service_Follow.getNumberOfItems();

            cFollow.showFirstPage();
            cFollow.showPrevPage();

            delete cbA;
            delete cbB;
            delete cbC;
            cFollow.refreshPageContent();
            cFollow.removeTrashFromFollowed();
            
        }
        
        Test.stopTest();
    }

}