TestRepo2/src/objects/Action__c.object
<CustomObject>
    <fields>
        <fullName>Cases_Displayed__c</fullName>
        <label>Cases Displayed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <formula>IF(Goal__c = null, Objective__r.Due_Date__c, Goal__r.Due_Date__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Goal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Goal</label>
        <referenceTo>Goal__c</referenceTo>
        <relationshipLabel>Actions</relationshipLabel>
        <relationshipName>Actions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Activity</label>
    <nameField>
        <displayFormat>A-{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>Action</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Actions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

TestRepo2/src/objects/Goal__c.object
<CustomObject>
    <fields>
        <fullName>Cases_Displayed__c</fullName>
        <label>Cases Displayed</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Cascaded</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Goal_Type__c</fullName>
        <label>Goal Type</label>
        <picklist>
            <picklistValues>
                <fullName>On-Premise - Control</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Off-Premise - Control</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Long_Name__c</fullName>
        <label>Long Name</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Minimum_of_Accounts__c</fullName>
        <label>Goal</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Parent_Goal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Goal</label>
        <referenceTo>Goal__c</referenceTo>
        <relationshipLabel>Child Goals</relationshipLabel>
        <relationshipName>Child_Goals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <picklist>
            <picklistValues>
                <fullName>National</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Local</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WY</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Goal</label>
    <nameField>
        <label>Goal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Goals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

TestRepo2/src/objects/State__c.object
<CustomObject>
    <label>State</label>
    <nameField>
        <label>State</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/classes/GoalAdminController.cls
public with sharing class GoalAdminController {
	
	//ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'quick dave test, please ignore: ' + dummyOnGoal));
	
	public Boolean shouldShowGridBlock						{get;set;}

	public String filterStateSelection						{get;set;}
	public List<SelectOption> filterStateChoices			{get;set;}
	
	public String filterTypeSelection						{get;set;}
	public List<SelectOption> filterTypeChoices				{get;set;}
	
	public String filterPrioritySelection					{get;set;}
	public List<SelectOption> filterPriorityChoices			{get;set;}
	
	public String filterDueDateSelection					{get;set;}
	public List<SelectOption> filterDueDateChoices			{get;set;}
	
	public String filterRecTypeSelection					{get;set;}
	public List<SelectOption> filterRecTypeChoices			{get;set;}
	
	public String filterNameValue							{get;set;}
	
	public Boolean showGoalDetail							{get;set;}
	public Boolean showGroupDetail							{get;set;}
	public String selectedGoalId							{get;set;}
	public String selectedGroupIds							{get;set;}
	public Goal__c selectedGoal								{get;set;}
	public List<Goal__c> selectedGroupGoals					{get;set;}
	public List<Goal__c> childGoals							{get;set;}
	public List<Action__c> childActions						{get;set;}

	public GoalAdminController(){
		shouldShowGridBlock = false;
		showGoalDetail = false;		
		showGroupDetail = false;		
		populateFilterDropdowns();
	}
	
	private void populateFilterDropdowns(){
		Schema.DescribeFieldResult result;
		
		filterStateChoices = new List<SelectOption>();
		filterStateChoices.add(new SelectOption('Any', 'Any'));
		result = Goal__c.State__c.getDescribe();
		for(Schema.PicklistEntry ple : result.getPicklistValues()){
			if(ple.isActive()){
				filterStateChoices.add(new SelectOption(ple.getValue(), ple.getLabel()));
			}
		}
		filterStateSelection = 'Any';
		
		filterTypeChoices = new List<SelectOption>();
		filterTypeChoices.add(new SelectOption('Any', 'Any'));
		result = Goal__c.Goal_Type__c.getDescribe();
		for(Schema.PicklistEntry ple : result.getPicklistValues()){
			if(ple.isActive()){
				filterTypeChoices.add(new SelectOption(ple.getValue(), ple.getLabel()));
			}
		}
		filterTypeSelection = 'Any';
		
		filterPriorityChoices = new List<SelectOption>();
		filterPriorityChoices.add(new SelectOption('Any', 'Any'));
		result = Goal__c.Priority__c.getDescribe();
		for(Schema.PicklistEntry ple : result.getPicklistValues()){
			if(ple.isActive()){
				filterPriorityChoices.add(new SelectOption(ple.getValue(), ple.getLabel()));
			}
		}
		filterPrioritySelection = 'Any';
		
		filterDueDateChoices = new List<SelectOption>();
		Date nineMonthsAhead = Date.today().toStartOfMonth().addMonths(9);
		Integer numMonths = 11;
		for(Integer i = numMonths; i >= 0; i--){
			Date d = nineMonthsAhead.addMonths(-1 * i);
			String value = String.valueOf(d) + '|' + String.valueOf(d.addMonths(1));
			String label = monthString(d);
			filterDueDateChoices.add(new SelectOption(value, label));
		}
		filterDueDateSelection = String.valueOf(Date.today().toStartOfMonth()) + '|' + String.valueOf(Date.today().toStartOfMonth().addMonths(1));
		
		filterRecTypeChoices = new List<SelectOption>();
		filterRecTypeChoices.add(new SelectOption('Any', 'Any'));
		Map<String, Schema.RecordTypeInfo> rtMap = Schema.SObjectType.Goal__c.getRecordTypeInfosByName();
		List<String> rtNames = new List<String>();
		rtNames.addAll(rtMap.keySet());
		rtNames.sort();
		for(String rtName : rtNames){
			if(rtName != 'Master'){
				filterRecTypeChoices.add(new SelectOption(rtMap.get(rtName).getRecordTypeId(), rtName));
			}
		}
		filterRecTypeSelection = 'Any';
	}
	
	private String monthString(Date d){
		if(d.month() == 1){
			return 'January ' + d.year();
		} else if(d.month() == 2){
			return 'February ' + d.year();
		} else if(d.month() == 3){
			return 'March ' + d.year();
		} else if(d.month() == 4){
			return 'April ' + d.year();
		} else if(d.month() == 5){
			return 'May ' + d.year();
		} else if(d.month() == 6){
			return 'June ' + d.year();
		} else if(d.month() == 7){
			return 'July ' + d.year();
		} else if(d.month() == 8){
			return 'August ' + d.year();
		} else if(d.month() == 9){
			return 'September ' + d.year();
		} else if(d.month() == 10){
			return 'October ' + d.year();
		} else if(d.month() == 11){
			return 'November ' + d.year();
		}
		return 'December ' + d.year();
	}
	
	public void hideGridBlock(){
		shouldShowGridBlock = false;
	}
	
	@RemoteAction
	public static List<Goal__c> performFilterQuery(String queryString){
		return Database.query(queryString);
	}
	
	public void showGridBlock(){
		shouldShowGridBlock = true;
	}
	
	public void doNothing(){}
	
	public void goalSelected(){
		showGoalDetail = false;
		showGroupDetail = false;
		if(selectedGoalId == null || selectedGoalId == ''){
			selectedGoal = null;
		} else {
			showGoalDetail = true;
			selectedGoal =
				[SELECT Id,
						Name,
						Long_Name__c,
						Minimum_of_Accounts__c,
						Cases_Displayed__c,
						Start_Date__c,
						Due_Date__c,
						RecordTypeId,
						RecordType.Name,
						Priority__c,
						Parent_Goal__c,
						Completed__c
				   FROM Goal__c
				  WHERE Id = :selectedGoalId
				];
			if(selectedGoal.Long_Name__c == null){
				selectedGoal.Long_Name__c = selectedGoal.Name;
			}
				
			childGoals = 
				[SELECT Id,
						(SELECT Id FROM Actions__r)
				   FROM Goal__c
				  WHERE Parent_Goal__c = :selectedGoalId
				     OR Parent_Goal__r.Parent_Goal__c = :selectedGoalId
				     OR Parent_Goal__r.Parent_Goal__r.Parent_Goal__c = :selectedGoalId
				];
			
			childActions = new List<Action__c>();
			for(Goal__c child : childGoals){
				childActions.addAll(child.Actions__r);
			}
		}
	}
	
	public void groupSelected(){
		showGoalDetail = false;
		showGroupDetail = false;
		if(selectedGroupIds == null || selectedGroupIds == ''){
			selectedGoal = null;
		} else {
			showGroupDetail = true;
			List<String> goalIds = selectedGroupIds.split(',');
			selectedGroupGoals =
				[SELECT Id,
						Name,
						Long_Name__c,
						Minimum_of_Accounts__c,
						Cases_Displayed__c,
						Start_Date__c,
						Due_Date__c,
						RecordTypeId,
						RecordType.Name,
						Priority__c,
						Parent_Goal__c,
						Completed__c
				   FROM Goal__c
				  WHERE Id IN :goalIds
				     OR Parent_Goal__c IN :goalIds
				     OR Parent_Goal__r.Parent_Goal__c IN :goalIds
				];
				
			selectedGoal = selectedGroupGoals[0];
			if(selectedGoal.Long_Name__c == null){
				selectedGoal.Long_Name__c = selectedGoal.Name;
			}
			
			childGoals = 
				[SELECT Id
				   FROM Goal__c
				  WHERE Parent_Goal__c IN :goalIds
				     OR Parent_Goal__r.Parent_Goal__c IN :goalIds
				     OR Parent_Goal__r.Parent_Goal__r.Parent_Goal__c IN :goalIds
				];
		}
	}
	
	public void deleteSelectedGoal(){
		delete selectedGoal;
		delete childGoals;
		delete childActions;
		
		showGoalDetail = false;
		selectedGoal = null;
	}
	
	public void hideDetail(){
		showGoalDetail = false;
		showGroupDetail = false;
	}
	
	public void cancelGoalSelect(){
		showGoalDetail = false;
	}
	
	public void cancelGroupSelect(){
		showGroupDetail = false;
	}
	
	public void saveChanges(){
		if(showGoalDetail){
			update selectedGoal;
			showGoalDetail = false;
			
		} else if(showGroupDetail){
			if(selectedGoal.Long_Name__c.length() >= 80){
				selectedGoal.Name = selectedGoal.Long_Name__c.substring(0, 80);
			} else {
				selectedGoal.Name = selectedGoal.Long_Name__c;
			}
			
			for(Goal__c goal : selectedGroupGoals){
				goal.Long_Name__c = selectedGoal.Long_Name__c;
				goal.Name = selectedGoal.Name;
				goal.Start_Date__c = selectedGoal.Start_Date__c;
				goal.Due_Date__c = selectedGoal.Due_Date__c;
				goal.Priority__c = selectedGoal.Priority__c;
			}
			
			update selectedGroupGoals;
			showGroupDetail = false;
		}
	}

}