TestRepo2/src/objects/Action__c.object
<CustomObject>
    <fields>
        <fullName>BrandBottle_Size__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BrandBottle Size</label>
        <referenceTo>BrandBottle_Size__c</referenceTo>
        <relationshipLabel>Actions</relationshipLabel>
        <relationshipName>Actions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Goal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Goal</label>
        <referenceTo>Goal__c</referenceTo>
        <relationshipLabel>Actions</relationshipLabel>
        <relationshipName>Actions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Activity</label>
    <nameField>
        <displayFormat>A-{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>Action</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Actions</pluralLabel>
    <recordTypes>
        <fullName>Display</fullName>
        <active>true</active>
        <label>Display - Franchise</label>
    </recordTypes>
    <recordTypes>
        <fullName>General</fullName>
        <active>true</active>
        <label>General - Franchise</label>
    </recordTypes>
    <recordTypes>
        <fullName>Training</fullName>
        <active>true</active>
        <label>Staff Training - Control</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

TestRepo2/src/objects/Bottle_Size__c.object
<CustomObject>
    <label>Bottle Size</label>
    <nameField>
        <label>Size</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bottle Sizes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/Brand__c.object
<CustomObject>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/Brand_Bottle_Goal__c.object
<CustomObject>
    <description>This is a junction object that links Brand Bottles to Goals</description>
    <fields>
        <fullName>BrandBottle_Size__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>BrandBottle Size</label>
        <referenceTo>BrandBottle_Size__c</referenceTo>
        <relationshipName>Brand_Bottle_Goals</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Goal__c</fullName>
        <label>Goal</label>
        <referenceTo>Goal__c</referenceTo>
        <relationshipName>Brand_Bottle_Goals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Brand-Bottle Size</label>
    <nameField>
        <displayFormat>BBG - {00000}</displayFormat>
        <label>Brand Bottle Goal</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brand-Bottle Sizes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestRepo2/src/objects/BrandBottle_Size__c.object
<CustomObject>
    <fields>
        <fullName>Bottle_Size__c</fullName>
        <label>Bottle Size</label>
        <referenceTo>Bottle_Size__c</referenceTo>
        <relationshipLabel>BrandBottle Sizes</relationshipLabel>
        <relationshipName>BrandBottle_Sizes</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipLabel>BrandBottle Sizes</relationshipLabel>
        <relationshipName>BrandBottle_Sizes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>BrandBottle Size</label>
    <nameField>
        <label>BrandBottle Size Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BrandBottle Sizes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestRepo2/src/objects/Goal__c.object
<CustomObject>
    <fields>
        <fullName>Goal_Type__c</fullName>
        <label>Goal Type</label>
        <picklist>
            <picklistValues>
                <fullName>On-Premise - Control</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Off-Premise - Control</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Parent_Goal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Goal</label>
        <referenceTo>Goal__c</referenceTo>
        <relationshipLabel>Child Goals</relationshipLabel>
        <relationshipName>Child_Goals</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Goal</label>
    <nameField>
        <label>Goal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Goals</pluralLabel>
    <recordTypes>
        <fullName>Feature</fullName>
        <active>true</active>
        <label>Feature Goals</label>
    </recordTypes>
    <recordTypes>
        <fullName>Menu</fullName>
        <active>true</active>
        <label>Menu Goals</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

TestRepo2/src/classes/Test_Controller_ActionCreationPage.cls
@isTest
private class Test_Controller_ActionCreationPage {
/*
    static testMethod void testController() {
        // This page is largely written in JS and JQuery, not Apex,
        //   so this test will be minimal
        Controller_ActionCreationPage cont = new Controller_ActionCreationPage();
        cont.addReadOnlyMessage();
        cont.addRepReadOnlyMessage();
        
        Controller_ActionCreationPage.getAccounts(new List<String>());
        Controller_ActionCreationPage.getChannels();
        Controller_ActionCreationPage.getManagerGoals();
        Controller_ActionCreationPage.getManagerTerritories();
        Controller_ActionCreationPage.getRepGoals();
        Controller_ActionCreationPage.getRepTerritories();
        
        Goal__c parentGoal = new Goal__c();
        parentGoal.Goal_Type__c = 'Off-Premise';
        insert parentGoal;
        
        List<Goal__c> goals = new List<Goal__c>();
        Goal__c goal = new Goal__c();
        goal.Parent_Goal__c = parentGoal.Id;
        goals.add(goal);
        
        Test_RecordUtil.ensureBrandCanBeCreated();
        Brand__c brand = Test_RecordUtil.newBrand('test brand');
        insert brand;
        Bottle_Size__c bs = Test_RecordUtil.newBottleSize('test bs');
        insert bs;
        BrandBottle_Size__c bbs = Test_RecordUtil.newBrandBottleSize('test bbs', brand.Id, bs.Id);
        insert bbs;
        Brand_Bottle_Goal__c parentBBG = new Brand_Bottle_Goal__c();
        parentBBG.Goal__c = parentGoal.Id;
        parentBBG.BrandBottle_Size__c = bbs.Id;
        insert parentBBG;
        
        Controller_ActionCreationPage.saveGoals(goals, false);
        
        Controller_ActionCreationPage.saveActions(new List<Action__c>(), false);
        
        cont = new Controller_ActionCreationPage();
        cont.getUserAgent();
        cont.addReadOnlyMessage();
        cont.addRepReadOnlyMessage();
        cont.assignDummyViewGoal();
        
        List<RecordType> goalRTs = [SELECT Id, Name FROM RecordType WHERE SObjectType = 'Goal__c'];
        Map<String, Id> goalRTIdsByName = new Map<String, Id>();
        for(RecordType rt : goalRTs){
        	goalRTIdsByName.put(rt.Name, rt.Id);
        }
        cont.dummyGoalId = parentGoal.Id;
        
        parentGoal.RecordTypeId = goalRTIdsByName.get('Display Goals');
        update parentGoal;
        cont.assignDummyGoal();
        
        parentGoal.RecordTypeId = goalRTIdsByName.get('Distribution Goals');
        update parentGoal;
        cont.assignDummyGoal();
        
        parentGoal.RecordTypeId = goalRTIdsByName.get('General Goals');
        update parentGoal;
        cont.assignDummyGoal();
        
        parentGoal.RecordTypeId = goalRTIdsByName.get('Ad Execution');
        update parentGoal;
        cont.assignDummyGoal();
        
        parentGoal.RecordTypeId = goalRTIdsByName.get('Ease of Shop');
        update parentGoal;
        cont.assignDummyGoal();
        
        parentGoal.RecordTypeId = goalRTIdsByName.get('Feature Goals');
        update parentGoal;
        cont.assignDummyGoal();
        
        parentGoal.RecordTypeId = goalRTIdsByName.get('Menu Goals');
        update parentGoal;
        cont.assignDummyGoal();
        
        parentGoal.RecordTypeId = goalRTIdsByName.get('Shelf Set Goals');
        update parentGoal;
        cont.assignDummyGoal();
        
        parentGoal.RecordTypeId = goalRTIdsByName.get('Staff Training Goals');
        update parentGoal;
        cont.assignDummyGoal();
        
        parentGoal.RecordTypeId = goalRTIdsByName.get('Window Display Goals');
        update parentGoal;
        cont.assignDummyGoal();
        
        parentGoal.RecordTypeId = goalRTIdsByName.get('Bar Promotion Goals');
        update parentGoal;
        cont.assignDummyGoal();
        
        parentGoal.RecordTypeId = goalRTIdsByName.get('Cold Box Goals');
        update parentGoal;
        cont.assignDummyGoal();
        
        parentGoal.RecordTypeId = goalRTIdsByName.get('Tasting Goals');
        update parentGoal;
        cont.assignDummyGoal();
        
        cont.dummyBBG = new Brand_Bottle_Goal__c();
        cont.dummyBBG.BrandBottle_Size__c = bbs.Id;
        cont.bbgSelName = 'dummy BBG';
        cont.addBBG();
        cont.removeBBGs();
        
        cont.saveGoal();
    }*/
}