TestRepo2/src/objects/Attribute__c.object
<CustomObject>
    <description>An Object that stores all the Attribute Types(Color,Flavor,Type) and its associated Attribute Values(Blue,Banana,Cocktails) along with its associated Atribute Value&apos;s Images(Fireworks Image for 4th of July)</description>
    <fields>
        <fullName>API_External_ID__c</fullName>
        <displayFormat>A-{0000}</displayFormat>
        <externalId>true</externalId>
        <label>API External ID</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Attribute_Value__c</fullName>
        <description>A Field That stores the Value of respective Attribute Type(Blue,Green,Banana,English)</description>
        <label>Attribute Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Attribute</label>
    <nameField>
        <displayFormat>ATTR-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attributes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/Diageo_Brand__c.object
<CustomObject>
    <fields>
        <fullName>API_External_ID__c</fullName>
        <description>External ID field for usage in the RecipeDB API.</description>
        <displayFormat>B-{0000}</displayFormat>
        <externalId>true</externalId>
        <label>API External ID</label>
        <type>AutoNumber</type>
    </fields>
    <label>Recipe Brand</label>
    <nameField>
        <label>Recipe Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recipe Brands</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

TestRepo2/src/objects/Diageo_Ingredient__c.object
<CustomObject>
    <fields>
        <fullName>API_External_ID__c</fullName>
        <displayFormat>RI-{0000}</displayFormat>
        <externalId>true</externalId>
        <label>API External ID</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Recipe__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Recipe</label>
        <referenceTo>Recipe__c</referenceTo>
        <relationshipLabel>Recipe Ingredients</relationshipLabel>
        <relationshipName>Diageo_Ingredients</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Recipe Ingredient</label>
    <nameField>
        <displayFormat>DI-{00000}</displayFormat>
        <label>Diageo Ingredient Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recipe Ingredients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/Diageo_Product__c.object
<CustomObject>
    <fields>
        <fullName>API_External_ID__c</fullName>
        <displayFormat>DP-{0000}</displayFormat>
        <externalId>true</externalId>
        <label>API External ID</label>
        <type>AutoNumber</type>
    </fields>
    <label>Recipe Diageo Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recipe Diageo Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

TestRepo2/src/objects/Digital_Published_Asset__c.object
<CustomObject>
    <description>An object to track Assets which leverage Recipe DB. (Websites, mobile apps, etc.)</description>
    <fields>
        <fullName>API_External_ID__c</fullName>
        <displayFormat>DPA-{0000}</displayFormat>
        <externalId>true</externalId>
        <label>API External ID</label>
        <type>AutoNumber</type>
    </fields>
    <label>Digital Published Asset</label>
    <nameField>
        <label>Digital Published Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Digital Published Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/Occasion__c.object
<CustomObject>
    <fields>
        <fullName>API_External_ID__c</fullName>
        <displayFormat>O-{0000}</displayFormat>
        <externalId>true</externalId>
        <label>API External ID</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Name_Of_The_Occasion__c</fullName>
        <label>Name of the Occasion</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Occasion</label>
    <nameField>
        <displayFormat>Occ-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Occasions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/Preparation_Step__c.object
<CustomObject>
    <fields>
        <fullName>Recipe__c</fullName>
        <label>Recipe</label>
        <referenceTo>Recipe__c</referenceTo>
        <relationshipLabel>Preparation Steps</relationshipLabel>
        <relationshipName>Preparation_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Preparation Step</label>
    <nameField>
        <displayFormat>Prepstep-{000000000}</displayFormat>
        <label>Step</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Preparation Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestRepo2/src/objects/Published_Recipe__c.object
<CustomObject>
    <description>Junction object between Digital Published Asset &amp; Recipe</description>
    <fields>
        <fullName>Recipe__c</fullName>
        <label>Recipe</label>
        <referenceTo>Recipe__c</referenceTo>
        <relationshipLabel>Asset - Recipe Use</relationshipLabel>
        <relationshipName>Published_Recipes</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suppressed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Published Recipe</label>
    <nameField>
        <displayFormat>PR-{00000}</displayFormat>
        <label>Published Recipe Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Published Recipes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestRepo2/src/objects/Recipe__c.object
<CustomObject>
    <fields>
        <fullName>API_External_ID__c</fullName>
        <description>External ID to be used for RecipeDB API purposes.</description>
        <displayFormat>R-{0000}</displayFormat>
        <externalId>true</externalId>
        <label>API External ID</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Occasion__c</fullName>
        <label>Occasion</label>
        <picklist>
            <controllingField>Occasion_Type__c</controllingField>
            <picklistValues>
                <fullName>4th of July</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anniversary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>April Fool&apos;s Day</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Award Show Night</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Baby Shower</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bachelorette Party</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bachelor Party</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BBQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beach Party</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Before the Bar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Block Party</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Board Game Night</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bonfire Party</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Book Club</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bridal Shower</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brunch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Camping</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carnival Night</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Casino Night</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cinco de Mayo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Clambake</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Class Reunion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cocktail Party</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cuban Night</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Day at the Races</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>December Holidays</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dessert Party</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Draft Party</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Election Day</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engagement Party</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Recipe_Tag__c</fullName>
        <label>Recipe_Tag</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Recipe_Title__c</fullName>
        <label>Recipe Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Archive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>recordSaved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>recordSaved</label>
        <type>Checkbox</type>
    </fields>
    <label>Recipe</label>
    <nameField>
        <displayFormat>RCP-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recipes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/Recipe_Attribute__c.object
<CustomObject>
    <fields>
        <fullName>Attribute_Value__c</fullName>
        <formula>Attribute__r.Name</formula>
        <label>Attribute Value</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Attribute__c</fullName>
        <label>Attribute</label>
        <referenceTo>Attribute__c</referenceTo>
        <relationshipLabel>Recipe Attributes</relationshipLabel>
        <relationshipName>Recipe_Attributes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Recipe__c</fullName>
        <label>Recipe</label>
        <referenceTo>Recipe__c</referenceTo>
        <relationshipLabel>Recipe Attributes</relationshipLabel>
        <relationshipName>Recipe_Attributes</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Recipe Attribute</label>
    <nameField>
        <displayFormat>RATTR-{0000}</displayFormat>
        <label>Recipe Attribute ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recipe Attributes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestRepo2/src/objects/Recipe_Non_Diageo_Product__c.object
<CustomObject>
    <fields>
        <fullName>API_External_ID__c</fullName>
        <displayFormat>NDP-{0000}</displayFormat>
        <externalId>true</externalId>
        <label>API External ID</label>
        <type>AutoNumber</type>
    </fields>
    <label>Recipe Non-Diageo Product</label>
    <nameField>
        <label>Recipe Non-Diageo Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recipe Non-Diageo Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

TestRepo2/src/objects/Recipe_Occasion__c.object
<CustomObject>
    <fields>
        <fullName>Occasion__c</fullName>
        <label>Occasion</label>
        <referenceTo>Occasion__c</referenceTo>
        <relationshipLabel>Recipe Occasions</relationshipLabel>
        <relationshipName>Recipe_Occasions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Recipe__c</fullName>
        <label>Recipe</label>
        <referenceTo>Recipe__c</referenceTo>
        <relationshipLabel>Recipe Occasions</relationshipLabel>
        <relationshipName>Recipe_Occasions</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Recipe Occasion</label>
    <nameField>
        <displayFormat>ROCC-{0000}</displayFormat>
        <label>RecipeOccasion</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recipe Occasions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestRepo2/src/classes/APPIRIO_WebServiceCallKeywordSearch.cls
/********************************************************************************************************************
Name        : APPIRIO_WebServiceCallKeywordSearch
Updated By  : Appirio Offshore(Rishi Khirbat)   
Date        : 21th Jan, 2013
Purpose     : Create Web Service Call for Keyword Search.
Ref         : T-111298
			  INPUT PARAMETERS:
				Digital Published Asset API External ID
				Search string
			  OUTPUT:
				Recipes matching search terms in HEADER XML format (T-105831)
				Include the Main Drink image for each recipe in an encoded format (w/ filename & ContentDisplayID)
				
				SEARCH DETAILS:
				For search logic, use the same query that is used in MM_RecipeView when performing a search on those pages. 
				The exact same search logic is what should be executed using the Search String input parameter.
********************************************************************************************************************/
@RestResource(urlMapping='/CallKeywordSearch/*')
global with sharing class APPIRIO_WebServiceCallKeywordSearch {
	//Web Service Call for Keyword Search.
	@HttpGet
	webservice static String WebServiceCallKeywordSearch() {
		
		RestRequest req = RestContext.request;
		map<String,String> paramMap = req.params;
		
		//input parameter
		Integer resumePoint;
		Boolean endOfResponse = true;
		String APIExternalID = paramMap.get('APIExternalID');
		String searchKeyword = paramMap.get('searchKeyword');
		
		if(searchKeyword == null || searchKeyword.trim() == '') {
        	return 'Keyword Search cannot be blank.';
        }
        
		if(paramMap.get('resumePoint') != null){
			resumePoint = Integer.valueOf(paramMap.get('resumePoint'));
		} 
		
		if(ResumePoint == null || ResumePoint == 0) {
			resumePoint = 1;
		}
		
        searchKeyword = String.escapeSingleQuotes(searchKeyword);
        String brandSearchTerm = searchKeyword.replace(' ','%');
	    searchKeyword = searchKeyword.replace('*','\\*');
	    
	    String sa ='%'+brandSearchTerm+'%';
	    String st = '%'+searchKeyword+'%';
        
        List<String> temp = new List<String>();
        map<String,Id> searchKeywordRecipeIds = new map<String,Id>();
        
        String query = 'select Id, API_External_ID__c from Recipe__c where recordSaved__c=true And (Recipe_Title__c like \'%'+searchKeyword+'%\' or Status__c like \'%'+searchKeyword+'%\' or Recipe_Tag__c like \'%'+searchKeyword+'%\') order by API_External_ID__c';
        //for(Recipe__c recipe :[select id from Recipe__c where Recipe_Title__c like :st or Status__c like :st or Recipe_Tag__c like :st]) {
        for(Recipe__c recipe :(List<Recipe__c>)Database.query(query)) {
        	searchKeywordRecipeIds.put(recipe.API_External_ID__c, recipe.Id);
        	temp.add(recipe.API_External_ID__c);
        }
        
        query = 'select Id, API_External_ID__c from Recipe__c where id IN (select Recipe__c from Recipe_Attribute__c where Recipe__r.recordSaved__c = true And Attribute__r.Attribute_Value__c like \'%'+searchKeyword+'%\') order by API_External_ID__c';
        //for(Recipe__c recipe :[select id from Recipe__c where id IN (select Recipe__c from Recipe_Attribute__c where Attribute__r.Attribute_Value__c like:st)]) {
        for(Recipe__c recipe :(List<Recipe__c>)Database.query(query)) {
        	searchKeywordRecipeIds.put(recipe.API_External_ID__c, recipe.Id);
        	temp.add(recipe.API_External_ID__c);
        }
        
        query = 'select Id, API_External_ID__c from Recipe__c where id IN (select Recipe__c from Recipe_Occasion__c where Recipe__r.recordSaved__c = true And (Occasion__r.Name_Of_The_Occasion__c like \'%'+searchKeyword+'%\' or Occasion__r.Occasion_Type__c like \'%'+searchKeyword+'%\'))  order by API_External_ID__c';
        //for(Recipe__c recipe :[select id from Recipe__c where id IN (select Recipe__c from Recipe_Occasion__c where Occasion__r.Name_Of_The_Occasion__c like:st or Occasion__r.Occasion_Type__c like:st)]) {
        for(Recipe__c recipe :(List<Recipe__c>)Database.query(query)) {
        	searchKeywordRecipeIds.put(recipe.API_External_ID__c, recipe.Id);
        	temp.add(recipe.API_External_ID__c);
        }
        
        query = 'select Id, API_External_ID__c from Recipe__c where id IN (Select Recipe__c from Preparation_Step__c where Recipe__r.recordSaved__c = true And Description__c like \'%'+searchKeyword+'%\')  order by API_External_ID__c';
        //for(Recipe__c recipe :[select id from Recipe__c where id IN (Select Recipe__c from Preparation_Step__c where Description__c like :st)]) {
        for(Recipe__c recipe :(List<Recipe__c>)Database.query(query)) {
        	searchKeywordRecipeIds.put(recipe.API_External_ID__c, recipe.Id);
        	temp.add(recipe.API_External_ID__c);
        }
        
        query = 'select Id, API_External_ID__c from Recipe__c where id IN (select Recipe__c FROM Diageo_Ingredient__c Where Recipe__r.recordSaved__c = true And (Recipe_Diageo_Product__r.Name like \'%'+searchKeyword+'%\' or Recipe_Non_Diageo_Product__r.Name like \'%'+searchKeyword+'%\' or Recipe_Diageo_Product__r.Short_Description__c like \'%'+searchKeyword+'%\' or Recipe_Brand__r.Short_Description__c like \'%'+searchKeyword+'%\'))  order by API_External_ID__c';
        //for(Recipe__c recipe :[select id from Recipe__c where id IN (select Recipe__c FROM Diageo_Ingredient__c Where Recipe_Diageo_Product__r.Name like :sa or Recipe_Non_Diageo_Product__r.Name like :sa or Recipe_Diageo_Product__r.Short_Description__c like :st or Recipe_Brand__r.Short_Description__c like :st)]) {
        for(Recipe__c recipe :(List<Recipe__c>)Database.query(query)) {
        	searchKeywordRecipeIds.put(recipe.API_External_ID__c, recipe.Id);
        	temp.add(recipe.API_External_ID__c);
        }
        
        set<Id> setRcipeIds = new set<Id>();
        List<Id> recipeIds = new List<Id>();
        
        if(APIExternalID == null || APIExternalID.trim() == '') {
        	temp.sort();
        	setRcipeIds = new set<Id>();
        	for(String str :temp) {
        		if(!setRcipeIds.contains(searchKeywordRecipeIds.get(str))) {
	        		recipeIds.add(searchKeywordRecipeIds.get(str));
	        		setRcipeIds.add(searchKeywordRecipeIds.get(str));	
	        	}
            }
        } else {
        	setRcipeIds = new set<Id>();
        	//Query all Published_Recipe__c records where Asset__c = input parameter with Search Keyword.
        	for(Published_Recipe__c publishedRecipe :[Select Recipe__c From Published_Recipe__c 
                                                        Where Digital_Published_Asset__r.API_External_ID__c =:APIExternalID 
                                                        And Recipe__c IN :searchKeywordRecipeIds.values()
                                                        And Recipe__r.recordSaved__c = true
                                                        order by Recipe__r.API_External_ID__c]) {
				if(!setRcipeIds.contains(publishedRecipe.Recipe__c)) {
	        		recipeIds.add(publishedRecipe.Recipe__c);
	        		setRcipeIds.add(publishedRecipe.Recipe__c);	
	        	}
            }	
        }
        
        temp = null;
        setRcipeIds = null;
        searchKeywordRecipeIds = null;
     //4.3.2012-LSLEVIN-Case4405-START//   
       // Integer newResumePoint = 199;
       Integer newResumePoint = 9;
    //Case4405-END//   
        if((resumePoint+newResumePoint) < recipeIds.size()) {
			endOfResponse = false;
		}
        return generateXML(APIExternalID, recipeIds, resumePoint, newResumePoint, endOfResponse);
	}
	
	static String generateXML(String APIExternalID, List<Id> recipeIds, Integer resumePoint, Integer newResumePoint, Boolean endOfResponse) {
		List<Id> newRecipeIds;
		//Place all Recipe__c objects contained within the result set into the XML template generated in T-104967.
		APPIRIO_GenerateXMLKeywordSearch generateXMLKeywordSearch = new APPIRIO_GenerateXMLKeywordSearch();
		
    	newRecipeIds = new List<Id>();
    	Integer cnt = 1;
    	for(Id recipeId :recipeIds) {
    		if(resumePoint <= cnt && cnt <= (resumePoint+newResumePoint)) {
    			newRecipeIds.add(recipeId);
    		}
    		cnt = cnt+1;
    	}
    	
        generateXMLKeywordSearch.recipeIds = newRecipeIds;
        generateXMLKeywordSearch.endOfResponse = endOfResponse;
        generateXMLKeywordSearch.resumePoint = resumePoint+newResumePoint+1;
    	if(endOfResponse)
    		generateXMLKeywordSearch.resumePoint = null;
    	
        //Generate the XML output.
        generateXMLKeywordSearch.generateXMLRecipeIinfo();
        //Return the XML output.
        String xmlString;
        xmlString = generateXMLKeywordSearch.xmlString;
        generateXMLKeywordSearch.xmlString = '';
        
        /*
        if(xmlString.length() > 2500000) {
        	
        	if(newRecipeIds.size() == 1) {
        		return 'Single recipe record has contained more than 2.5MB data.';	
        	}
        	
        	Decimal dNum = xmlString.length()/2500000;
        	
        	Integer newPoint;
        	if(dNum >= 1 && dNum < 2 && newRecipeIds.size() >=2 ) {
        		newPoint = newRecipeIds.size()/2;	
        	} else if(newRecipeIds.size() > 1 && newRecipeIds.size() < dNum ) {
        		newPoint = newRecipeIds.size()/2;	
        	} else if(newRecipeIds.size() >= dNum ) {
        		newPoint = newRecipeIds.size()/dNum.intValue();
        	}
        	xmlString = generateXML(APIExternalID, recipeIds, resumePoint, newPoint, false);
        }*/
        return xmlString;
	}
}