TestRepo2/src/objects/Attribute__c.object
<CustomObject>
    <description>An Object that stores all the Attribute Types(Color,Flavor,Type) and its associated Attribute Values(Blue,Banana,Cocktails) along with its associated Atribute Value&apos;s Images(Fireworks Image for 4th of July)</description>
    <fields>
        <fullName>API_External_ID__c</fullName>
        <displayFormat>A-{0000}</displayFormat>
        <externalId>true</externalId>
        <label>API External ID</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Attribute_Type__c</fullName>
        <description>A Picklist Field that contains all the Attribute types that are being seen on a Recipe</description>
        <label>Attribute Type</label>
        <picklist>
            <picklistValues>
                <fullName>Barware Needed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Color</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Description/Overview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Drink Classification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Drink Type</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Effort Level</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flavor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Food Pairings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Glassware</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Good For Gatherings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Language</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Luxury Flag</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nutrition Fact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recipe Story</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Servings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Serving Size</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Serving Style</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standard Average Analysis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tasting Notes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wine Taste</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wine Type</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UnitofAlcohol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEO Meta Description</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEO Page Title</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEO Page URL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEO Hints</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Attribute_Value__c</fullName>
        <description>A Field That stores the Value of respective Attribute Type(Blue,Green,Banana,English)</description>
        <label>Attribute Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dynamic__c</fullName>
        <defaultValue>false</defaultValue>
        <description>A check box that helps in determining the Value of certain Attribute Types.</description>
        <label>Dynamic</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Locale__c</fullName>
        <label>Locale</label>
        <picklist>
            <picklistValues>
                <fullName>EN-US</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>EN-CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FR-CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PT-BR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ES-MX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ES-CO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ES-CL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ES-AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EN-GB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EN-IN</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Attribute</label>
    <nameField>
        <displayFormat>ATTR-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attributes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/Diageo_Brand__c.object
<CustomObject>
    <fields>
        <fullName>API_External_ID__c</fullName>
        <description>External ID field for usage in the RecipeDB API.</description>
        <displayFormat>B-{0000}</displayFormat>
        <externalId>true</externalId>
        <label>API External ID</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Vodka</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Whisky</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Whiskey</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rum</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Speciality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Liqueur</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tequila</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Locale__c</fullName>
        <label>Locale</label>
        <picklist>
            <picklistValues>
                <fullName>EN-US</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>EN-CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FR-CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PT-BR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ES-MX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ES-CO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ES-CL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ES-AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EN-GB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EN-IN</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Recipe Brand</label>
    <nameField>
        <label>Recipe Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recipe Brands</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

TestRepo2/src/objects/Diageo_Product__c.object
<CustomObject>
    <fields>
        <fullName>API_External_ID__c</fullName>
        <displayFormat>DP-{0000}</displayFormat>
        <externalId>true</externalId>
        <label>API External ID</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Blended Scotch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bourbon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Irish Whiskey</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Classic Malt</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Diageo_Brand_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Diageo Brand</label>
        <referenceTo>Diageo_Brand__c</referenceTo>
        <relationshipName>Diageo_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Locale__c</fullName>
        <label>Locale</label>
        <picklist>
            <picklistValues>
                <fullName>EN-US</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>EN-CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FR-CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PT-BR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ES-MX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ES-CO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ES-CL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ES-AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EN-GB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EN-IN</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Recipe Diageo Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recipe Diageo Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

TestRepo2/src/objects/Occasion__c.object
<CustomObject>
    <fields>
        <fullName>API_External_ID__c</fullName>
        <displayFormat>O-{0000}</displayFormat>
        <externalId>true</externalId>
        <label>API External ID</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Locale__c</fullName>
        <label>Locale</label>
        <picklist>
            <picklistValues>
                <fullName>EN-US</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EN-CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FR-CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PT-BR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ES-MX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ES-CO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ES-CL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ES-AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EN-GB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EN-IN</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Name_Of_The_Occasion__c</fullName>
        <label>Name of the Occasion</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Occasion_Tags__c</fullName>
        <label>Occasion Tags</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Occasion_Type__c</fullName>
        <label>Occasion Type</label>
        <picklist>
            <picklistValues>
                <fullName>Celebrations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Holidays</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Outdoor Gatherings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Theme Parties</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Occasion</label>
    <nameField>
        <displayFormat>Occ-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Occasions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/classes/APPIRIO_WebServiceCallRecipeClasifDtl.cls
/********************************************************************************************************************
Name        : APPIRIO_WebServiceCallRecipeClasifDtl
Updated By  : Appirio Offshore(Rishi Khirbat)   
Date        : 15th Jan, 2013
Purpose     : Create Web Service Call for Recipe Classifications & Values
Ref         : T-109754
			  	Create a web service call which returns the following XML format:

				<recipeClassifications>
				<recipeClassification>
				<key>Attribute__c.Attribute_type__c</key>
				<values>
				<value> Attribute__c.Attribute_Value__c </value>
				</values>
				</recipeClassification>
				</recipeClassifications>
				
				Data to put into the format:
				KEY: Select Attribute_type__c from Attribute__c where Dynamic__c == 0
				
				VALUES: Select Attribute__c.Attribute_value__c where Attribute__c.Attribute_type__c == KEY
				
				I-46016: REST Call should allow for an input parameter
				The user should be able to provide an input parameter: key=XXXX. 
				Key corresponds to the Recipe Classifications, and allows the user to get the related values for just one key. 
				If the parameter is not defined, return all results.
********************************************************************************************************************/
@RestResource(urlMapping='/CallRecipeClassificationDetails/*')
global with sharing class APPIRIO_WebServiceCallRecipeClasifDtl {
	//Web Service Call for Recipe Classifications & Values
	@HttpGet
	webservice static String WebServiceCallRecipeClassificationDetails() {
		
		RestRequest req = RestContext.request;
		map<String,String> paramMap = req.params;
		
		string xmlString;
		String key = paramMap.get('Key');
		map<string,List<Attribute__c>> setAttributeDetails = new map<string,List<Attribute__c>>();
		
		XmlStreamWriter w = new XmlStreamWriter();
		w.writeStartDocument(null,'1.0');
		
		if(key != null && key.trim() != '') {
			for(Attribute__c attribute :[Select Attribute_Type__c, Attribute_value__c, API_External_ID__c, Locale__c From Attribute__c 
													Where Dynamic__c = false 
													And Attribute_Type__c =: key 
													order by Attribute_Type__c, Attribute_value__c]) {
														
				if(attribute.Attribute_Type__c != null) {
					if(!setAttributeDetails.containsKey(attribute.Attribute_Type__c)){
						setAttributeDetails.put(attribute.Attribute_Type__c, new List<Attribute__c>());	
					}
					if(attribute.Attribute_value__c != null) 
						setAttributeDetails.get(attribute.Attribute_Type__c).add(attribute);
				}
			}	
		} else {
			for(Attribute__c attribute :[Select Attribute_Type__c, Attribute_value__c, API_External_ID__c, Locale__c From Attribute__c 
													Where Dynamic__c = false order by Attribute_Type__c, Attribute_value__c]) {
														
				if(attribute.Attribute_Type__c != null) {
					if(!setAttributeDetails.containsKey(attribute.Attribute_Type__c)){
						setAttributeDetails.put(attribute.Attribute_Type__c, new List<Attribute__c>());	
					}
					if(attribute.Attribute_value__c != null) 
						setAttributeDetails.get(attribute.Attribute_Type__c).add(attribute);
				}
			}
		}
		
		//recipeClassifications
		w.writeStartElement(null,'recipeClassifications',null);
			//---Attribute--//
			for(string ky :setAttributeDetails.keySet()) {
				//recipeClassification
				w.writeStartElement(null,'recipeClassification',null);
					//key
					w.writeStartElement(null,'key',null);
						w.writeCharacters(ky);
					w.writeEndElement();
					//end of key
					//values
					w.writeStartElement(null,'values',null);
						for(Attribute__c attribute :setAttributeDetails.get(ky)) {
							//value
							w.writeStartElement(null,'value',null);
								w.writeAttribute(null, null, 'id', ''+attribute.API_External_ID__c);
								w.writeAttribute(null, null, 'Locale', ''+attribute.Locale__c);
				                w.writeCharacters(String.valueOf(attribute.Attribute_value__c));
							w.writeEndElement();
							//end of value
						}
					w.writeEndElement();
					//end of values		
				w.writeEndElement();
				//end of recipeClassification		
			}
			
			Boolean display = true;
			if(key != null && key.trim() != '') {
				display = key.equals('Occasion') ? true : false;	
			} else {
				display = true;
			}
			
			if(display) {
				//---Occasion--//
				//recipeClassification
				w.writeStartElement(null,'recipeClassification',null);
					//key
					w.writeStartElement(null,'key',null);
						w.writeCharacters('Occasion');
					w.writeEndElement();
					//end of key
					//values
					w.writeStartElement(null,'values',null);
						for(Occasion__c occasion :[Select Name_Of_The_Occasion__c, API_External_ID__c, Locale__c, Occasion_Tags__c, Occasion_Type__c From Occasion__c order by Name_Of_The_Occasion__c]) {
							//value
							w.writeStartElement(null,'value',null);
								w.writeAttribute(null, null, 'id', occasion.API_External_ID__c);
				                w.writeAttribute(null, null, 'Locale', ''+occasion.Locale__c);
				                w.writeAttribute(null, null, 'Type', ''+occasion.Occasion_Type__c);
								w.writeCharacters(occasion.Name_Of_The_Occasion__c);
							w.writeEndElement();
							//end of value
							
							//tags
		                    w.writeStartElement(null,'tags',null);
		                        if(occasion.Occasion_Tags__c != null)
		                            w.writeCharacters(occasion.Occasion_Tags__c);
		                    w.writeEndElement();
		                    //end of tags
						}
					w.writeEndElement();
					//end of values
				w.writeEndElement();
				//end of recipeClassification
			}
			
			if(key != null && key.trim() != '') {
				display = key.equals('Brand') ? true : false;	
			} else {
				display = true;
			}
			
			if(display) {
				//---Brand--//
				//recipeClassification
				w.writeStartElement(null,'recipeClassification',null);
					//key
					w.writeStartElement(null,'key',null);
						w.writeCharacters('Brand');
					w.writeEndElement();
					//end of key
					//values
					w.writeStartElement(null,'values',null);
						for(Diageo_Brand__c brand :[Select Name, API_External_ID__c, Locale__c, Category__c From Diageo_Brand__c order by Name]) {
							//value
							w.writeStartElement(null,'value',null);
								w.writeAttribute(null, null, 'id', ''+brand.API_External_ID__c);
								if(brand.Locale__c == null) brand.Locale__c = '';
								w.writeAttribute(null, null, 'Locale', brand.Locale__c +'');
								if(brand.Category__c == null) brand.Category__c = '';
								w.writeAttribute(null, null, 'Category', brand.Category__c +'');
				                w.writeCharacters(brand.Name);
							w.writeEndElement();
							//end of value
						}
					w.writeEndElement();
					//end of values
				w.writeEndElement();
				//end of recipeClassification
			}
			
			if(key != null && key.trim() != '') {
				display = key.equals('Product') ? true : false;	
			} else {
				display = true;
			}
			
			if(display) {
				//---Product--//
				//recipeClassification
				w.writeStartElement(null,'recipeClassification',null);
					//key
					w.writeStartElement(null,'key',null);
						w.writeCharacters('Product');
					w.writeEndElement();
					//end of key
					//values
					w.writeStartElement(null,'values',null);
						for(Diageo_Product__c product :[Select Name, API_External_ID__c, Locale__c, Category__c, Diageo_Brand_Id__r.API_External_ID__c From Diageo_Product__c order by Name]) {
							//value
							w.writeStartElement(null,'value',null);
								w.writeAttribute(null, null, 'id', ''+product.API_External_ID__c);
								if(product.Locale__c == null) product.Locale__c = '';
								w.writeAttribute(null, null, 'Locale', product.Locale__c +'');
								if(product.Category__c == null) product.Category__c = '';
								w.writeAttribute(null, null, 'Category', product.Category__c +'');
								w.writeAttribute(null, null, 'BrandId', product.Diageo_Brand_Id__r.API_External_ID__c +'');
	                            w.writeCharacters(product.Name);
							w.writeEndElement();
							//end of value
						}
					w.writeEndElement();
					//end of values
				w.writeEndElement();
				//end of recipeClassification
			}
			
		w.writeEndElement();
		//end of recipeClassifications
		
		w.writeEndDocument();
		xmlString = w.getXmlString();
		system.debug('===================xmlString: '+ xmlString);
		w.close();
		
		return xmlString;
	}
}