TestRepo2/src/objects/Attribute__c.object
<CustomObject>
    <description>An Object that stores all the Attribute Types(Color,Flavor,Type) and its associated Attribute Values(Blue,Banana,Cocktails) along with its associated Atribute Value&apos;s Images(Fireworks Image for 4th of July)</description>
    <fields>
        <fullName>Attribute_Type__c</fullName>
        <description>A Picklist Field that contains all the Attribute types that are being seen on a Recipe</description>
        <label>Attribute Type</label>
        <picklist>
            <picklistValues>
                <fullName>Barware Needed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Color</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Description/Overview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Drink Classification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Drink Type</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Effort Level</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flavor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Food Pairings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Glassware</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Good For Gatherings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Language</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Luxury Flag</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nutrition Fact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recipe Story</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Servings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Serving Size</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Serving Style</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standard Average Analysis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tasting Notes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wine Taste</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wine Type</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UnitofAlcohol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEO Meta Description</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEO Page Title</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEO Page URL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEO Hints</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Dynamic__c</fullName>
        <defaultValue>false</defaultValue>
        <description>A check box that helps in determining the Value of certain Attribute Types.</description>
        <label>Dynamic</label>
        <type>Checkbox</type>
    </fields>
    <label>Attribute</label>
    <nameField>
        <displayFormat>ATTR-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attributes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/classes/APPIRIO_WebServiceCallRecipeClasifictins.cls
/********************************************************************************************************************
Name        : APPIRIO_WebServiceCallRecipeClasifictins
Updated By  : Appirio Offshore(Rishi Khirbat)   
Date        : 15th Jan, 2013
Purpose     : Write Web Service Call for Recipe Classifications
Ref         : T-109753
                Create a web service call which returns the following XML format:

                <recipeClassifications>
                <recipeClassification> Attribute__c.Attribute_type__c </recipeClassification>
                </recipeClassifications>
                
                Data to put into the format:
                Select Attribute_type__c from Attribute__c where Dynamic__c == 0
                
                I-46016: REST Call should allow for an input parameter
                The user should be able to provide an input parameter: key=XXXX. 
                Key corresponds to the Recipe Classifications, and allows the user to get the related values for just one key. 
                If the parameter is not defined, return all results.
********************************************************************************************************************/
@RestResource(urlMapping='/CallRecipeClassifications/*')
global with sharing class APPIRIO_WebServiceCallRecipeClasifictins {
    //Web Service Call for Recipe Classifications
    @HttpGet
    webservice static String WebServiceCallRecipeClassification() {
        RestRequest req = RestContext.request;
        map<String,String> paramMap = req.params;
        
        string xmlString;
        String key = paramMap.get('Key');
        set<string> setAttributeType = new set<string>();
        
        XmlStreamWriter w = new XmlStreamWriter();
        w.writeStartDocument(null,'1.0');
        
        //recipeClassifications
        w.writeStartElement(null,'recipeClassifications',null);
        if(key != null && key.trim() != '') {
            for(Attribute__c attribute :[Select Attribute_Type__c From Attribute__c 
                                                                  Where Dynamic__c = false 
                                                                  And Attribute_Type__c =: key 
                                                                  order by Attribute_Type__c]) {
                if(attribute.Attribute_Type__c != null && !setAttributeType.contains(attribute.Attribute_Type__c))  {
                    setAttributeType.add(attribute.Attribute_Type__c);
                    //recipeClassification
                    w.writeStartElement(null,'recipeClassification',null);
                        w.writeCharacters(String.valueOf(attribute.Attribute_Type__c));
                    w.writeEndElement();
                    //end of recipeClassification
                }
            }
            
            if(key.equals('Brand')) {
                //recipeClassification
                w.writeStartElement(null,'recipeClassification',null);
                    w.writeCharacters('Brand');
                w.writeEndElement();
                //end of recipeClassification
            }
            
            if(key.equals('Product')) {
                //recipeClassification
                w.writeStartElement(null,'recipeClassification',null);
                    w.writeCharacters('Product');
                w.writeEndElement();
                //end of recipeClassification
            }
            
            if(key.equals('Occasion')) {
                //recipeClassification
                w.writeStartElement(null,'recipeClassification',null);
                    w.writeCharacters('Occasion');
                w.writeEndElement();
                //end of recipeClassification
            }
                
        } else {
            for(Attribute__c attribute :[Select Attribute_Type__c From Attribute__c 
                                                                  Where Dynamic__c = false 
                                                                  order by Attribute_Type__c]) {
                if(attribute.Attribute_Type__c != null && !setAttributeType.contains(attribute.Attribute_Type__c))  {
                    setAttributeType.add(attribute.Attribute_Type__c);
                    //recipeClassification
                    w.writeStartElement(null,'recipeClassification',null);
                        w.writeCharacters(String.valueOf(attribute.Attribute_Type__c));
                    w.writeEndElement();
                    //end of recipeClassification
                }
            }
            //recipeClassification
            w.writeStartElement(null,'recipeClassification',null);
                w.writeCharacters('Brand');
            w.writeEndElement();
            //end of recipeClassification
            
            //recipeClassification
            w.writeStartElement(null,'recipeClassification',null);
                w.writeCharacters('Product');
            w.writeEndElement();
            //end of recipeClassification
            
            //recipeClassification
            w.writeStartElement(null,'recipeClassification',null);
                w.writeCharacters('Occasion');
            w.writeEndElement();
            //end of recipeClassification
        }
        
        w.writeEndElement();
        //end of recipeClassifications
        
        w.writeEndDocument();
        xmlString = w.getXmlString();
        w.close();
        
        return xmlString;
    }
}