TestRepo2/src/objects/Blitz__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Blitzes</relationshipLabel>
        <relationshipName>Blitzes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Blitz_Brand__c</fullName>
        <label>Blitz Brand</label>
        <picklist>
            <picklistValues>
                <fullName>Blackhaus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Goldschlager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rumple Minze</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Johnnie Walker Blue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Crown Royal Reserve</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Don Julio 1942</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bushmills Honey</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Crown Black</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Crown Maple</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Don Julio Blanco</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Don Julio Reposado</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Don Julio Anejo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Don Julio Real</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Blitz_Details__c</fullName>
        <defaultValue>&quot;1. Select Program&quot; &amp; BR() &amp; &quot;2. Select Brand&quot; &amp; BR() &amp; &quot;3. Enter the Amount as Follows:&quot; &amp; BR() &amp; BR() &amp; &quot;     a.) New Distribution - enter 1 in the amount field&quot; &amp; BR() &amp;
&quot;     b.) Menu - enter 1 in the amount field&quot; &amp; BR() &amp;
&quot;     c.) Feature - enter 1 in the amount field&quot; &amp; BR() &amp; BR() &amp;&quot;4. Click Save &amp; New to add another Brand&quot; &amp; BR() &amp; &quot;5. Click Save when done&quot;</defaultValue>
        <label>Blitz Details</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Blitz_Program__c</fullName>
        <label>Blitz Program</label>
        <picklist>
            <picklistValues>
                <fullName>All for One, One for Me - Additional Bottle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All for One, One for Me - Feature</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All for One, One for Me - New Distribution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Blitz Week December 3rd</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shot Heard Around the World</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cinco De Mayo-New Distribution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cinco De Mayo-Feature Cards</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cinco De Mayo-Menu</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Date_FInished__c</fullName>
        <defaultValue>Today ()</defaultValue>
        <label>Date FInished</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PDF_Link__c</fullName>
        <defaultValue>&quot;Not Available&quot;</defaultValue>
        <label>PDF Link</label>
        <type>Url</type>
    </fields>
    <label>Blitz</label>
    <nameField>
        <displayFormat>BL-{0000}</displayFormat>
        <label>Blitz Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Blitzes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/Blitz_History__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Blitz History</relationshipLabel>
        <relationshipName>Blitz_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Blitz_Brand__c</fullName>
        <label>Blitz Brand</label>
        <picklist>
            <picklistValues>
                <fullName>Blackhaus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Goldschlager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rumple Minze</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Blitz_Details__c</fullName>
        <defaultValue>&quot;1. Select Brand&quot; &amp; BR() &amp; &quot;2. Enter Amount in Bottles&quot; &amp; BR() &amp; &quot;3. Click Save &amp; New to add another Brand&quot; &amp; BR() &amp; &quot;4. Click Save when done&quot;</defaultValue>
        <label>Blitz Details</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Blitz_Program__c</fullName>
        <label>Blitz Program</label>
        <picklist>
            <picklistValues>
                <fullName>Shot Heard Around the World</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Date_Finished__c</fullName>
        <label>Date Finished</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PDF_Link__c</fullName>
        <label>PDF Link</label>
        <type>Url</type>
    </fields>
    <label>Blitz History</label>
    <nameField>
        <displayFormat>BLH-{0000}</displayFormat>
        <label>Blitz History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Blitz History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/classes/BlitzAdminController.cls
public without sharing class BlitzAdminController {
	
	public Integer activeCount {get;set;}
	public List<Blitz__c> blitzes {get;set;}
	public Map<Id, String> inactiveUserNamesById {get;set;}

	public BlitzAdminController(){
		init();
	}
	
	public void init(){
		blitzes =
			[SELECT Id,
					Account__c,
					Amount__c,
					Blitz_Brand__c,
					Blitz_Details__c, 
					Blitz_Program__c, 
					Comments__c, 
					Date_Finished__c, 
					OwnerId,
					Owner.isActive,
					Owner.Name,
					PDF_Link__c
			   FROM Blitz__c
			   ORDER BY Owner.Name
			];
		activeCount = blitzes.size();
		
		inactiveUserNamesById = new Map<Id, String>();
		for(Blitz__c blitz : blitzes){
			if(blitz.Owner.isActive == false && blitz.OwnerId != UserInfo.getUserId()){
				inactiveUserNamesById.put(blitz.OwnerId, blitz.Owner.Name);
			}
		}
		if(inactiveUserNamesById.size() > 0){
			String message = 'The following Blitz record owners are currently inactive: ';
			for(Integer i = 0; i < inactiveUserNamesById.size(); i++){
				message += inactiveUserNamesById.values()[i];
				if(i < inactiveUserNamesById.size() - 1){
					message += ', ';
				}
			}
			message += '. They must be activated before continuing.';
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING, message));
		}
	}
	
	public void doMassArchival(){
		/*
		List<User> users = [SELECT Id FROM User WHERE Id IN :inactiveUserNamesById.keyset()];
		if(users.size() > 0){
			//activate users
			for(User user : users){
				user.isActive = true;
			}
			update users;
		}*/
		
		List<Blitz_History__c> hists = new List<Blitz_History__c>();
		for(Blitz__c blitz : blitzes){
			Blitz_History__c hist = new Blitz_History__c();
			hist.Account__c = blitz.Account__c;
			hist.Amount__c = blitz.Amount__c;
			hist.Blitz_Brand__c = blitz.Blitz_Brand__c;
			hist.Blitz_Details__c = blitz.Blitz_Details__c;
			hist.Blitz_Program__c = blitz.Blitz_Program__c;
			hist.Comments__c = blitz.Comments__c;
			hist.Date_Finished__c = blitz.Date_Finished__c;
			hist.OwnerId = blitz.OwnerId;
			hist.PDF_Link__c = blitz.PDF_Link__c;
			hists.add(hist);
		}
		
		insert hists;
		delete blitzes;
		
		/*
		if(users.size() > 0){
			//deactivate users
			deactivateUsers(inactiveUserNamesById.keyset());
		}*/
		
		ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, activeCount + ' Blitz records have been converted to Blitz History records.'));
		init();
	}
	
	/*
	@future
	private static void deactivateUsers(Set<Id> userIds){
		List<User> users = [SELECT Id FROM User WHERE Id IN :userIds];
		for(User user : users){
			user.isActive = false;
		}
		update users;
	}*/

}