TestRepo2/src/objects/Bottle_Size__c.object
<CustomObject>
    <label>Bottle Size</label>
    <nameField>
        <label>Size</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bottle Sizes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/Brand__c.object
<CustomObject>
    <fields>
        <fullName>Brand_Type__c</fullName>
        <label>Brand Type</label>
        <picklist>
            <picklistValues>
                <fullName>Generic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Individual</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Innovation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Innovation</label>
        <type>Checkbox</type>
    </fields>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/BrandBottle_Size__c.object
<CustomObject>
    <fields>
        <fullName>Bottle_Size__c</fullName>
        <label>Bottle Size</label>
        <referenceTo>Bottle_Size__c</referenceTo>
        <relationshipLabel>BrandBottle Sizes</relationshipLabel>
        <relationshipName>BrandBottle_Sizes</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipLabel>BrandBottle Sizes</relationshipLabel>
        <relationshipName>BrandBottle_Sizes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>BrandBottle Size</label>
    <nameField>
        <label>BrandBottle Size Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BrandBottle Sizes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestRepo2/src/objects/Survey_Layout__c.object
<CustomObject>
    <description>Holds the configuration for dynamically rendered survey layouts.</description>
    <fields>
        <fullName>Activate_Survey__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this checkbox to activate survey layout and publish survey records to each account.</description>
        <inlineHelpText>Check this checkbox to activate survey layout and publish survey records to each account.</inlineHelpText>
        <label>Activate Survey</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Beating_Comp_Label_1__c</fullName>
        <description>This field is the label for a Beating The Competition line item.</description>
        <inlineHelpText>This field is the label for a Beating The Competition line item.  Leave this field blank if you do not want it rendered on this survey record.</inlineHelpText>
        <label>Beating Comp Label 1</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Beating_Comp_Success_Percent_1__c</fullName>
        <defaultValue>0</defaultValue>
        <description>This is the criteria that determines if the Diageo number and the Total number evaluate to a successful ratio / percentage.  If the label says &apos;&gt;= 35% of Displays,&apos; enter a &apos;35&apos; here.</description>
        <inlineHelpText>This is the criteria that determines if the Diageo number and the Total number evaluate to a successful ratio / percentage.  If the label says &apos;&gt;= 35% of Displays,&apos; enter a &apos;35&apos; here.</inlineHelpText>
        <label>Beating Comp Success Percent 1</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Clone_Survey_Layout__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Hidden field used for the survey layout trigger that will clone a survey layout and will also clone copies of the related brand item and brand bottle item layout records.</description>
        <label>Clone Survey Layout</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Extra_Credit_Label_1__c</fullName>
        <label>Extra Credit Label 1</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Percent_of_Grade_BeatComp__c</fullName>
        <label>Percent of Grade BeatComp</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Percent_of_Grade_Dist__c</fullName>
        <description>This field is used to calculate the percentage of Distrubution/Shelf/Display used for the final Account Grade.</description>
        <label>Percent of Grade Distribution</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Percent_of_Grade_Extra_Credit__c</fullName>
        <label>Percent of Grade Extra Credit</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Percent_of_Grade_Innovation__c</fullName>
        <label>Percent of Grade Innovation</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Survey Layout</label>
    <nameField>
        <label>Survey Layout Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Layouts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/Survey_Layout_Brand_Bottle_Item__c.object
<CustomObject>
    <fields>
        <fullName>BrandBottle_Size__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BrandBottle Size</label>
        <referenceTo>BrandBottle_Size__c</referenceTo>
        <relationshipLabel>Survey Innovation / Sustainovation</relationshipLabel>
        <relationshipName>Survey_Layout_Brand_Bottle_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Survey_Layout__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Survey Layout</label>
        <referenceTo>Survey_Layout__c</referenceTo>
        <relationshipName>Survey_Layout_Brand_Bottle_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Survey Innovation / Sustainovation</label>
    <nameField>
        <displayFormat>SLBBIN-{00000}</displayFormat>
        <label>Survey Layout Brand Bottle Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Innovation / Sustainovation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/SurveyLayout_Brand_Items__c.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipLabel>Survey Distribution / Shelf / Display</relationshipLabel>
        <relationshipName>SurveyLayout_Brand_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Display_Checkbox_Not_Applicable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Display Checkbox Not Applicable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Survey_Layout__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Survey Layout</label>
        <referenceTo>Survey_Layout__c</referenceTo>
        <relationshipName>SurveyLayout_Brand_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Survey Distribution / Shelf / Display</label>
    <nameField>
        <displayFormat>SLBIN-{00000}</displayFormat>
        <label>SurveyLayout Brand Items Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Distribution / Shelf / Display</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/classes/BatchGenerateSurveysTest.cls
@isTest
private class BatchGenerateSurveysTest {
	
	
	
	static testMethod void testSurveyBatch()
	{
		Survey_Layout__c layoutRecord = setupLayoutData();
		
		Account account = Test_Helper.testInsertAccount('testAcct');
		
		
		Test.StartTest();
			
			User testUser = Test_Helper.generateTestUser('A4L09', true, 'System Administrator');
			account.OwnerId = testUser.Id;
			update account;
			
			layoutRecord.OwnerId = testUser.Id;
			layoutRecord.Activate_Survey__c = true;
			update layoutRecord;
			
			
    		String query = 'select id, Due_Date__c, Activate_Survey__c, OwnerId from survey_layout__c where activate_survey__c = true ';
    		query += ' and id =  \'' + layoutRecord.Id + '\' ';
    		BatchGenerateSurveysAfterActivation batch = new BatchGenerateSurveysAfterActivation(query);
    		
    		ID batchprocessid = database.executebatch(batch,1);
    	//Updated by Akanksha(offshore) for case  00003540
	
    				
        Map<Id,User> activeUserMap = new Map<Id,User>( [select id, userRoleId from user where isActive = true] );
        Map<Id,UserRole> userRoleMap = new Map<Id,UserRole>( [select id, name, parentRoleId from userRole] );
        Map<Id,List<UserRole>> userRoleMapByParentId = new Map<Id,List<UserRole>>();

        for(UserRole usrRole1 : userRoleMap.values()) {
            if(usrRole1.parentRoleId != null) {
                List<UserRole> childList1 = userRoleMapByParentId.get(usrRole1.parentRoleId);
                if(childList1 == null) {
                    childList1 = new List<UserRole>();
                }
                childList1.add(usrRole1);
               
            }
        }
       List<User> subordinateUsersMap = batch.buildListOfSubordinateUsers(UserInfo.getUserId(), activeUserMap, userRoleMap);
	
    	Test.StopTest();
		
	}
	
	private static Survey_Layout__c setupLayoutData()
	{
		Survey_Layout__c layout = createSurveyLayout('test layout');
		
		Brand__c brand = new Brand__c();
        brand.Name = 'testBrand';
        brand.Innovation__c = true;
        brand.Brand_Type__c = 'Individual';
        insert brand;
        
        Bottle_Size__c bottleSize = new Bottle_Size__c();
        bottleSize.Name = '1000' ;
        insert bottleSize;
        
        BrandBottle_Size__c bbs = new BrandBottle_Size__c();
        bbs.Bottle_Size__c = bottleSize.Id;
        bbs.Brand__c = brand.Id;
        insert bbs;
        
        insert layout ;
       
        Survey_Layout_Brand_Bottle_Item__c bbi = new Survey_Layout_Brand_Bottle_Item__c();
        bbi.BrandBottle_Size__c = bbs.Id;
        bbi.Survey_Layout__c = layout.Id;
        
        SurveyLayout_Brand_Items__c bi = new SurveyLayout_Brand_Items__c();
        bi.Brand__c = brand.Id;
        bi.Survey_Layout__c = layout.Id;
        bi.Display_Checkbox_Not_Applicable__c = true;
		
		
		insert bbi;
		insert bi;
		
		return layout;
	}
	
	
	private static Survey_Layout__c createSurveyLayout(String layoutName)
	 {
	 	Survey_Layout__c layout = new Survey_Layout__c();
        layout.Name = layoutName;
        layout.Beating_Comp_Label_1__c = 'test 1';
        layout.Beating_Comp_Success_Percent_1__c = 10;
        layout.Extra_Credit_Label_1__c = 'test 1';
        layout.Percent_of_Grade_Innovation__c = 25;
        layout.Percent_of_Grade_Extra_Credit__c = 25;
        layout.Percent_of_Grade_Dist__c = 25;
        layout.Percent_of_Grade_BeatComp__c = 25;
        layout.Beating_Comp_Success_Percent_1__c = 0;
        layout.Clone_Survey_Layout__c = false;
        return layout;
	 }
	
	
}