TestRepo2/src/objects/Brand__c.object
<CustomObject>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/Item__c.object
<CustomObject>
    <description>POS Project: object that represents catalog items available for shopping</description>
    <fields>
        <fullName>Brand__c</fullName>
        <formula>IF(Brand_Count__c &lt; 1, &quot;&quot;, IF(Program__r.Brand__r.Portfolio_Brand__c, &quot;Portfolio&quot;, Program__r.Brand__r.Name))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Price__c</fullName>
        <label>Current Price</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Estimated_Price__c</fullName>
        <label>Estimated Price</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Estimated_Shipping_Tax__c</fullName>
        <label>Estimated Shipping/Tax %</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>On_Allocation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>On Allocation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Packout_Quantity__c</fullName>
        <label>Packout Quantity</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product_Image__c</fullName>
        <formula>IF(ISBLANK(Product_Image_URL__c), &quot;&quot;, HYPERLINK(Product_Image_URL__c, IMAGE(Product_Image_URL__c, Name , 60, 60), &quot;_blank&quot;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Image</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Development</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Approved w/Est Price</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted w/Final Price</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Removed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

TestRepo2/src/objects/Order_Window__c.object
<CustomObject>
    <description>POS Project: object that represents a period of time in which catalog items are offered and shoppers are allowed to buy them</description>
    <fields>
        <fullName>Order_Close_Date__c</fullName>
        <label>Order Close Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Order_Start_Date__c</fullName>
        <label>Order Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <controllingField>Type__c</controllingField>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Budgeting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Archived</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Order Window</label>
    <nameField>
        <label>Order Window Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Windows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/Program__c.object
<CustomObject>
    <description>POS Project: object that represents a set of events for which related catalog items are offered to shoppers (distributors and internal Diageo employees)</description>
    <fields>
        <fullName>Brand__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Window__c</fullName>
        <label>Order Window</label>
        <referenceTo>Order_Window__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestRepo2/src/classes/POS_ViewOrderWindowItemsController.cls
/**
 * @author      Model Metrics {Venkatesh Kamat}
 * @date        07/25/2012
 * @description Controller to list items of a given OrderWindow, support filtering by one or more Brands
 **/
public with sharing class POS_ViewOrderWindowItemsController {
    
    public List<Item__c> filterResult{get; set;}
    public Order_Window__c orderWindow{get; set;}
    String[] selectedBrands = new String[]{};
    List<Item__c> orderwindowItems;
    List<Brand__c> orderwindowBrands;
    
    public POS_ViewOrderWindowItemsController() {
        String owId = ApexPages.currentPage().getParameters().get('owId');

        orderWindow = [SELECT Name, Status__c, Order_Start_Date__c, Order_Close_Date__c  from Order_Window__c where id=:owId];
        orderwindowItems = [SELECT id, Name, Product_Image__c, Packout_Quantity__c, Status__c, On_Allocation__c, Estimated_Price__c, Estimated_Shipping_Tax__c, 
            Current_Price__c, Program__r.Order_Window__r.Name, Program__r.Brand__c, Program__r.Brand__r.name, Program__c, 
            Program__r.Name from Item__c where Program__r.Order_Window__r.Id= :owId order by //Program__r.Brand__r.name, 
            Program__r.Name, Name];
        
        System.debug('orderwindowItems -' + orderwindowItems);
        List<Id> brandIds = new List<Id>();
        for(Item__c i : orderwindowItems) {
            brandIds.add(i.Program__r.Brand__c);
        }   
                    
        orderwindowBrands = [SELECT Id, Name from Brand__c where id in :brandIds];
        //orderwindowBrands.addAll(orderwindowBrands);
        //orderwindowBrands.addAll(orderwindowBrands);
    }
    

    public PageReference filterByBrand() {
        System.debug('selectedBrands -' + selectedBrands);
        filterResult = new List<Item__c>();
        
        if(selectedBrands != null && selectedBrands.size() > 0) {

            for(Item__c a : orderwindowItems) {
                for(String s : selectedBrands) {
                    if(a.Program__r.Brand__c == s) {
                        filterResult.add(a);
                        break;
                    }
                }
            }
        }
        
        return null;
    }

    public List<SelectOption> getApplicableBrands() {
        List<SelectOption> options = new List<SelectOption>();
        for(Brand__c b:orderwindowBrands) {
            options.add(new SelectOption(b.Id, b.Name));
        }

        return options;
    }

    public String[] getSelectedBrands() {
        return selectedBrands;
    }

    public void setSelectedBrands(String[] brands) {
        this.selectedBrands = brands;
    }    
    
    
    @isTest(SeeAllData=true)
    public static void testViewOrderWindowItems () {
        
        Profile p = [select id from profile where name='POS - API User Agency'];
         
        User u = new User(alias = 'posmmtst', email='posmmunittest@diageo.com',
        emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US',
        localesidkey='en_US', profileid = p.Id,
        timezonesidkey='America/Chicago', username='posmmunittest@diageo.com');
        
        System.runAs(u) {
            //Create Agency
            Account agency = POS_TestDataUtil.createProductionAgency();
        
           
            Program__c program1 = POS_TestDataUtil.createProgram();
            Item__c item11 = POS_TestDataUtil.populateItem(program1, agency);
            insert item11;
            
            
            Test.startTest(); 
            
            Program__c program2 = POS_TestDataUtil.createProgram(program1.Order_Window__c);
            Item__c item21 = POS_TestDataUtil.populateItem(program2, agency);
            insert item21; 
                    
           
            String owId = program1.Order_Window__c;
            Test.setCurrentPageReference(new PageReference('Page.POS_ViewOrderWindowItems'));
            System.currentPagereference().getParameters().put('owId',owId);         
            
            POS_ViewOrderWindowItemsController ctrl = new POS_ViewOrderWindowItemsController(); 
            
            System.debug('ctrl.getApplicableBrands() - ' + ctrl.getApplicableBrands());
            System.assertEquals(2, ctrl.getApplicableBrands().size());
            
            ctrl.setSelectedBrands(new String[]{program1.Brand__c});
            ctrl.filterByBrand();
            System.debug('ctrl.getSelectedBrands() - ' + ctrl.getSelectedBrands());
            System.assertEquals(1, ctrl.filterResult.size());
            
            Test.stopTest();
        }
    }     

    
}