TestRepo2/src/objects/Brand__c.object
<CustomObject>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/BrandBottle_Size__c.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipLabel>BrandBottle Sizes</relationshipLabel>
        <relationshipName>BrandBottle_Sizes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>BrandBottle Size</label>
    <nameField>
        <label>BrandBottle Size Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BrandBottle Sizes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestRepo2/src/objects/Gold_Standard_Met__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Gold Standards Met</relationshipLabel>
        <relationshipName>Gold_Standards_Met</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>BrandBottle_Size__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Optional relationship - use only for sub brands ie. Smirnoff flavors</inlineHelpText>
        <label>BrandBottle Size</label>
        <referenceTo>BrandBottle_Size__c</referenceTo>
        <relationshipLabel>Gold Standards Met</relationshipLabel>
        <relationshipName>Gold_Standards_Met</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipLabel>Gold Standards Met</relationshipLabel>
        <relationshipName>Gold_Standards_Met</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Gold_Standard_Display_Not_Applicable__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If Brand does not have a Display, this field is checked and is propagated from the layout objects.</description>
        <inlineHelpText>If Brand does not have a Display, this field is checked and is propagated from the layout objects.</inlineHelpText>
        <label>Gold Standard Display Not Applicable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>Gold Standards Met</relationshipLabel>
        <relationshipName>Gold_Standards_Met</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Gold Standard Met</label>
    <nameField>
        <displayFormat>GS-{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>Gold Standard</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gold Standards Met</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestRepo2/src/objects/Survey__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Surveys</relationshipLabel>
        <relationshipName>Surveys</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Survey_Layout__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The layout record is used to determine how to display the survey data in its related dynamic layout.</description>
        <label>Survey Layout</label>
        <referenceTo>Survey_Layout__c</referenceTo>
        <relationshipLabel>Surveys</relationshipLabel>
        <relationshipName>Surveys</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Survey</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestRepo2/src/objects/Survey_Layout__c.object
<CustomObject>
    <description>Holds the configuration for dynamically rendered survey layouts.</description>
    <fields>
        <fullName>Activate_Survey__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this checkbox to activate survey layout and publish survey records to each account.</description>
        <inlineHelpText>Check this checkbox to activate survey layout and publish survey records to each account.</inlineHelpText>
        <label>Activate Survey</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <label>Survey Layout</label>
    <nameField>
        <label>Survey Layout Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Layouts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/Survey_Layout_Brand_Bottle_Item__c.object
<CustomObject>
    <fields>
        <fullName>BrandBottle_Size__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BrandBottle Size</label>
        <referenceTo>BrandBottle_Size__c</referenceTo>
        <relationshipLabel>Survey Innovation / Sustainovation</relationshipLabel>
        <relationshipName>Survey_Layout_Brand_Bottle_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Survey_Layout__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Survey Layout</label>
        <referenceTo>Survey_Layout__c</referenceTo>
        <relationshipName>Survey_Layout_Brand_Bottle_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Survey Innovation / Sustainovation</label>
    <nameField>
        <displayFormat>SLBBIN-{00000}</displayFormat>
        <label>Survey Layout Brand Bottle Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Innovation / Sustainovation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/SurveyLayout_Brand_Items__c.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipLabel>Survey Distribution / Shelf / Display</relationshipLabel>
        <relationshipName>SurveyLayout_Brand_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Display_Checkbox_Not_Applicable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Display Checkbox Not Applicable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Survey_Layout__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Survey Layout</label>
        <referenceTo>Survey_Layout__c</referenceTo>
        <relationshipName>SurveyLayout_Brand_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Survey Distribution / Shelf / Display</label>
    <nameField>
        <displayFormat>SLBIN-{00000}</displayFormat>
        <label>SurveyLayout Brand Items Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Distribution / Shelf / Display</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/classes/BatchGenerateSurveysAfterActivation.cls
/**
*   @Someone added a query inside of a loop here.   
*
*/
global class BatchGenerateSurveysAfterActivation implements Database.Batchable<sObject>
{
    string query = 'select id, Due_Date__c, Activate_Survey__c, OwnerId from survey_layout__c where activate_survey__c = true';
    
    global BatchGenerateSurveysAfterActivation() 
    {
    }
    
    global BatchGenerateSurveysAfterActivation(String constructorQuery) 
    {
        query = constructorQuery;
    }
    
    global database.queryLocator start(Database.BatchableContext BC) 
    {
        if(test.isRunningTest()) {
            query += ' LIMIT 1' ;
        }
        return database.getQueryLocator(query);
    }
    
    
    
    global void execute(Database.BatchableContext BC, List<Survey_Layout__c> surveyLayoutList) 
    {
        Map<Id,Survey_Layout__c> newMap = new Map<Id,Survey_Layout__c>(surveyLayoutList);
        
        generateAndSaveChildRecordsForApplicableSurveyRecords(surveyLayoutList, newMap);
    }
    
    global Map<Id,List<SurveyLayout_Brand_Items__c>> buildBrandItemMapBySurveyLayoutId(Map<Id, Survey_Layout__c> surveyLayout) 
    {
        
        Map<Id,List<SurveyLayout_Brand_Items__c>> mapToReturn = new Map<Id,List<SurveyLayout_Brand_Items__c>>();
        
        for(SurveyLayout_Brand_Items__c brandItem : [select Id, Name, Brand__c, Survey_Layout__c, Display_Checkbox_Not_Applicable__c from SurveyLayout_Brand_Items__c where Survey_Layout__c in :surveyLayout.keySet() order by createddate] ) {
            
            List<SurveyLayout_Brand_Items__c> childList = mapToReturn.get(brandItem.Survey_Layout__c) ;
            
            if(childList == null || childList.isEmpty()) {
                childList = new List<SurveyLayout_Brand_Items__c>() ;
            }
            
            childList.add(brandItem);
            
            mapToReturn.put(brandItem.Survey_Layout__c, childList) ;
            
        }
        
        return mapToReturn ;
    }
    
    global Map<Id,List<Survey_Layout_Brand_Bottle_Item__c>> buildBrandBottleItemMapBySurveyLayoutId(Map<Id, Survey_Layout__c> surveyLayoutMap) {
        
        Map<Id,List<Survey_Layout_Brand_Bottle_Item__c>> mapToReturn = new Map<Id,List<Survey_Layout_Brand_Bottle_Item__c>>();
        
        for(Survey_Layout_Brand_Bottle_Item__c brandBottleItem : [select Id, Name, BrandBottle_Size__c, BrandBottle_Size__r.Brand__c, Survey_Layout__c from Survey_Layout_Brand_Bottle_Item__c where Survey_Layout__c in :surveyLayoutMap.keySet() order by createddate]) {
            
            List<Survey_Layout_Brand_Bottle_Item__c> childList = mapToReturn.get(brandBottleItem.Survey_Layout__c) ;
            
            if(childList == null || childList.isEmpty()) {
                childList = new List<Survey_Layout_Brand_Bottle_Item__c>() ;
            }
            
            childList.add(brandBottleItem);
            
            mapToReturn.put(brandBottleItem.Survey_Layout__c, childList) ;
            
        }
        
        return mapToReturn ;
    }
    
    global List<User> buildListOfSubordinateUsers( Id currentUserId, Map<Id,User> activeUserMap, Map<Id,UserRole> userRoleMap )
    {
        List<User> userListToReturn = new List<User>();
        User manager = activeUserMap.get( currentUserId );
        userListToReturn.add(manager);
        
        List<Id> roleIds = recursivelyGetListOfSubordinateRoleIds( manager.UserRoleId, userRoleMap );
        
        if(!roleIds.isEmpty()) {
            Map<Id,Id> roleIdMap = new Map<Id,Id>(); 
            for(Id roleid : roleIds) {
                roleIdMap.put(roleid, roleid); //to eliminate a sub-loop
            }
            
            for(User usr : activeUserMap.values()) {
                if(usr.userRoleId != null && roleIdMap.get(usr.userRoleId) != null) {
                    userListToReturn.add(usr);
                }
            }
        }
        
        return userListToReturn;
    }
    
    global List<Id> recursivelyGetListOfSubordinateRoleIds(Id currentLevelRoleId, Map<Id,UserRole> userRoleMap)
    {
        UserRole currentLevelRole = userRoleMap.get(currentLevelRoleId);
        List<Id> listToReturn = new List<Id>();
        
        if(currentLevelRole == null)
            return listToReturn ;
        
        for(UserRole usrRole : userRoleMap.values()) {
            if(usrRole.ParentRoleId == currentLevelRole.Id) {
                listToReturn.add(usrRole.Id);
                List<Id> childList = recursivelyGetListOfSubordinateRoleIds(usrRole.Id, userRoleMap) ;
                if(!childList.isEmpty()) {
                    listToReturn.addAll(childList);
                }
            }
        }
        
        return listToReturn ;
    }
    
    
    global void generateAndSaveChildRecordsForApplicableSurveyRecords(List<Survey_Layout__c> surveyLayoutList, Map<Id,Survey_Layout__c> newMap)
    {
        Map<Id,User> activeUserMap = new Map<Id,User>( [select id, userRoleId from user where isActive = true] );
        Map<Id,List<SurveyLayout_Brand_Items__c>> brandItemsMapBySurveyLayoutId = buildBrandItemMapBySurveyLayoutId(newMap);
        Map<Id,List<Survey_Layout_Brand_Bottle_Item__c>> brandBottleItemsMapBySurveyLayoutId = buildBrandBottleItemMapBySurveyLayoutId(newMap);
        
        List<Gold_Standard_Met__c> goldMetRecordsToInsert = new List<Gold_Standard_Met__c>();
        
        Map<Id,UserRole> userRoleMap = new Map<Id,UserRole>( [select id, name, parentRoleId from userRole] );
        
        //!!!!!!!!!!!!
        //if the batch was created such that the context is one record per batch, all should be o.k. with regard to optimization:
        //!!!!!!!!!!!!
        for(Survey_Layout__c surveyLayout : surveyLayoutList) 
        {
            if(surveyLayout.Activate_Survey__c == true)
            {
                //temporarily adding some duplication-avoidance logic now that the business rule has changed, and partial survey-sets may have been created.
                Set<String> existingSurveyAccountIds = new Set<String>();
                
                for(Survey__c tempSurveyRecord : [select id, Account__c from survey__c where survey_layout__c = :surveyLayout.Id]) {
                    if(tempSurveyRecord.Account__c != null)
                        existingSurveyAccountIds.add(tempSurveyRecord.Account__c);
                }
                
                
                Survey__c[] surveysInserted = new Survey__c[]{};
                List<SurveyLayout_Brand_Items__c> relatedBrandItems = brandItemsMapBySurveyLayoutId.get(surveyLayout.Id) ;
                List<Survey_Layout_Brand_Bottle_Item__c> relatedBrandBottleItems = brandBottleItemsMapBySurveyLayoutId.get(surveyLayout.Id);
                for(Account acct1 :  [select id, ownerId from account where billingstate = 'CT' and Id not in :existingSurveyAccountIds])
                {
                    Survey__c survey = new Survey__c();
                    survey.Account__c = acct1.Id ;
                    survey.Survey_Layout__c = surveyLayout.Id ;
                    survey.Due_Date__c = surveyLayout.Due_Date__c;
                    
                    surveysInserted.add(survey);
                }
                system.debug('==============surveysInserted=============='+surveysInserted);
                insert surveysInserted ;
                    
                for(Survey__c survey : surveysInserted) 
                {
                    generateSurveyChildRecords(surveyLayout, survey, relatedBrandItems, relatedBrandBottleItems, goldMetRecordsToInsert) ;
                }
                system.debug('==============goldMetRecordsToInsert=============='+goldMetRecordsToInsert);
                insert goldMetRecordsToInsert ;
                    
                    
                
            }
        
        }   
        
        
        
            
    }
    
    
    global void generateSurveyChildRecords(Survey_Layout__c surveyLayout, Survey__c survey, List<SurveyLayout_Brand_Items__c> relatedBrandItems, List<Survey_Layout_Brand_Bottle_Item__c> relatedBrandBottleItems, List<Gold_Standard_Met__c> goldMetRecordsToInsert)
    {
        if(relatedBrandItems != null && !relatedBrandItems.isEmpty())
        {
            for(SurveyLayout_Brand_Items__c brandItem : relatedBrandItems) {
                Gold_Standard_Met__c insertRecord = new Gold_Standard_Met__c();
                insertRecord.Brand__c = brandItem.Brand__c ;
                insertRecord.Survey__c = survey.Id ;
                insertRecord.Account__c = survey.Account__c ;
                insertRecord.Gold_Standard_Display_Not_Applicable__c = brandItem.Display_Checkbox_Not_Applicable__c ;
                
                goldMetRecordsToInsert.add(insertRecord);
            }
        }
        
        if(relatedBrandBottleItems != null && !relatedBrandBottleItems.isEmpty())
        {
            for(Survey_Layout_Brand_Bottle_Item__c brandBottleItem : relatedBrandBottleItems) {
                Gold_Standard_Met__c insertRecord2 = new Gold_Standard_Met__c();
                insertRecord2.Brand__c = brandBottleItem.BrandBottle_Size__r.Brand__c ;
                insertRecord2.BrandBottle_Size__c = brandBottleItem.BrandBottle_Size__c ;
                insertRecord2.Survey__c = survey.Id ;
                insertRecord2.Account__c = survey.Account__c ;
                
                goldMetRecordsToInsert.add(insertRecord2);
            }
        }
        
        
        
        
        
    }
    
        
    global void finish(Database.BatchableContext BC) 
    {
    
    }
}