TestRepo2/src/objects/Brand__c.object
<CustomObject>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/Order_Window__c.object
<CustomObject>
    <description>POS Project: object that represents a period of time in which catalog items are offered and shoppers are allowed to buy them</description>
    <fields>
        <fullName>Fiscal_Year__c</fullName>
        <label>Fiscal Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Close_Date__c</fullName>
        <label>Order Close Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Order_Delivery_Date__c</fullName>
        <label>Order Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Order_Start_Date__c</fullName>
        <label>Order Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <controllingField>Type__c</controllingField>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Budgeting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Archived</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Quarterly</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Demand</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Order Window</label>
    <nameField>
        <label>Order Window Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Windows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/Order_Window_Customer__c.object
<CustomObject>
    <description>POS Project: junction object that represents the many-to-many relationship between Order Windows and Users (customers)</description>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Order_Window_Customers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Window__c</fullName>
        <label>Order Window</label>
        <referenceTo>Order_Window__c</referenceTo>
        <relationshipLabel>Order Window Customers</relationshipLabel>
        <relationshipName>Order_Window_Customers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Order Window Customer</label>
    <nameField>
        <displayFormat>OWC-{000000}</displayFormat>
        <label>Order Window Customer ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Window Customers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestRepo2/src/objects/Organizational_Unit__c.object
<CustomObject>
    <description>POS Project: object that represents a hierarchy level within the distributors hierarchy</description>
    <fields>
        <fullName>Label__c</fullName>
        <label>Label</label>
        <picklist>
            <picklistValues>
                <fullName>Division</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Market</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>State District</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Region</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Spirits</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wine</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Organizational Unit</label>
    <nameField>
        <label>Organizational Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organizational Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/classes/POS_Test_Reports.cls
@isTest
private class POS_Test_Reports {
	public static testmethod void testReportsFilters(){
		Test.startTest();
		
		//UserRole role = [select id from UserRole where name='Diageo NA' limit 1];
		User currUser = [select id from User where id = :Userinfo.getUserId()];
		System.runas(currUser){
			
			Organizational_Unit__c orgUnit = new Organizational_Unit__c(Name = 'test ou', Label__c = 'Division', Type__c = 'Spirits');
			insert orgUnit;
			
			Account account = Test_Helper.testInsertAccount('acc name', orgUnit.id);
			
			Contact contact = Test_Helper.testInsertContact('first', 'last', account.id);
			User user = Test_Helper.testInsertDiageoPortalUser(contact.id);
			
			Order_Window__c orderWindow = new Order_Window__c(Name = 'test order window', Type__c = 'Monthly', Fiscal_Year__c = '2013', Order_Start_Date__c = Date.today(), Order_Close_Date__c = Date.today().addMonths(1), Order_Delivery_Date__c = Date.today().addMonths(2), Status__c = 'Open');
			insert orderWindow;
			Order_Window_Customer__c orderWindowCustomer = new Order_Window_Customer__c(Customer__c = user.id, Order_Window__c = orderWindow.id);
			insert orderWindowCustomer;
			
			Brand__c brand = Test_Helper.testInsertBrand('test brand');
			Test_Helper.testInsertAccountBrand(account.ID, brand.ID);
			
			PageReference currPage = new PageReference('/apex/POS_Reports');
			Test.setCurrentPage(currPage);
			
			System.runAs(user){
				POS_ReportsController cont = new POS_ReportsController();
				
				cont.classification = 'Spirits';
				cont.fillOrganizationalUnitOptions();
				cont.orgUnitsString = orgUnit.id;
				cont.fillDistributorOptions();
				
				system.assertEquals(1, cont.orderWindowOptions.size());
				system.assertEquals(2, cont.classificationOptions.size());
				//system.assertEquals(1, cont.brandOptions.size());
				system.assertEquals(new Set<Id>{account.id}, POS_ReportsController.aids);
				system.assertEquals(1, cont.organizationalUnitOptions.size());
				system.assertEquals(1, cont.distributorOptions.size());
				
				cont.resetClassification();
				cont.reset();
				cont.resetOrganizationalUnitOptions();
				
			}
		}
		
		Test.stopTest();
	}
	
	public static testmethod void testRenderers(){
		Test.startTest();
		
		User currUser = [select id from User where id = :Userinfo.getUserId()];
		System.runas(currUser){
			
			Organizational_Unit__c orgUnit = new Organizational_Unit__c(Name = 'test ou', Label__c = 'Division', Type__c = 'Spirits');
			insert orgUnit;
			
			Account account = Test_Helper.testInsertAccount('acc name', orgUnit.id);
			
			Order_Window__c orderWindow = new Order_Window__c(Name = 'test order window', Type__c = 'Monthly', Fiscal_Year__c = '2013', Order_Start_Date__c = Date.today(), Order_Close_Date__c = Date.today().addMonths(1), Order_Delivery_Date__c = Date.today().addMonths(2), Status__c = 'Open');
			insert orderWindow;
			
			Brand__c brand = Test_Helper.testInsertBrand('test brand');
			
			PageReference currPage = new PageReference('/apex/POS_ReportRendererCSV?ow='+orderWindow.id+'&cl=Spirits&br='+brand.id+'&ou='+orgUnit.id+'&ds='+account.id);
			Test.setCurrentPage(currPage);
			
			POS_ReportRendererController cont = new POS_ReportRendererController();
		}
		
		Test.stopTest();
	}
}