TestRepo2/src/objects/Brand__c.object
<CustomObject>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/Budget__c.object
<CustomObject>
    <description>POS Project: object that represents an estimate of expenditure for a given brand, order window and shopper</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Budgets</relationshipLabel>
        <relationshipName>Budgets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipLabel>Budgets</relationshipLabel>
        <relationshipName>Budgets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Budget_Creator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Budget Creator</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Budgets_Created</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Budgeter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Budgeter</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Created_Budgets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Channel__c</fullName>
        <label>Channel</label>
        <picklist>
            <picklistValues>
                <fullName>Off-premise</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On-premise</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Item_Allocation_Quantity__c</fullName>
        <label>Item Allocation Quantity</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Item</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>Budgets</relationshipLabel>
        <relationshipName>Budgets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Window__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Window</label>
        <referenceTo>Order_Window__c</referenceTo>
        <relationshipLabel>Budgets</relationshipLabel>
        <relationshipName>Budgets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Organizational_Unit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organizational Unit</label>
        <referenceTo>Organizational_Unit__c</referenceTo>
        <relationshipLabel>Budgets</relationshipLabel>
        <relationshipName>Budgets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Budgets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent</label>
        <referenceTo>Budget__c</referenceTo>
        <relationshipLabel>Budgets</relationshipLabel>
        <relationshipName>Budgets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Budgets</relationshipLabel>
        <relationshipName>Budgets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shopper__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shopper</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Assigned_Budgets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sub_Allocated_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Sub-Allocated Amount</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Sub_Allocated_Item_Quantity__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Sub-Allocated Item Quantity</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Budget</label>
    <nameField>
        <displayFormat>BDG-{0000000}</displayFormat>
        <label>Budget ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budgets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/Item__c.object
<CustomObject>
    <description>POS Project: object that represents catalog items available for shopping</description>
    <fields>
        <fullName>Brand__c</fullName>
        <formula>IF(Brand_Count__c &lt; 1, &quot;&quot;, IF(Program__r.Brand__r.Portfolio_Brand__c, &quot;Portfolio&quot;, Program__r.Brand__r.Name))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Channel__c</fullName>
        <label>Channel</label>
        <picklist>
            <picklistValues>
                <fullName>Off-premise</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On-premise</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>Item Variations</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

TestRepo2/src/objects/Order_Window__c.object
<CustomObject>
    <description>POS Project: object that represents a period of time in which catalog items are offered and shoppers are allowed to buy them</description>
    <label>Order Window</label>
    <nameField>
        <label>Order Window Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Windows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/Organizational_Unit__c.object
<CustomObject>
    <description>POS Project: object that represents a hierarchy level within the distributors hierarchy</description>
    <fields>
        <fullName>Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent</label>
        <referenceTo>Organizational_Unit__c</referenceTo>
        <relationshipLabel>Organizational Units</relationshipLabel>
        <relationshipName>Organizational_Units</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Organizational Unit</label>
    <nameField>
        <label>Organizational Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organizational Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/Program__c.object
<CustomObject>
    <description>POS Project: object that represents a set of events for which related catalog items are offered to shoppers (distributors and internal Diageo employees)</description>
    <fields>
        <fullName>Brand__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Window__c</fullName>
        <label>Order Window</label>
        <referenceTo>Order_Window__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestRepo2/src/classes/POS_TestBudgetingGrid.cls
public with sharing class POS_TestBudgetingGrid {
@isTest
	public static void testOrderHistory () {
		//Profile p = [select id from profile where name='System Administrator'];
        /*
		User u = [select Id from User where Id='005Z0000000X1Xn'];
		
		
		
		
		System.runAs(u) {
			PageReference pageRef = Page.HomePage;
        	Test.setCurrentPage(pageRef);
        	String owId = 'a12Z000000060xCIAQ';
        	List<Budget__c> orderwindowBudgets	= [SELECT Id, Account__c, Account__r.Name, Amount__c, Brand__c, Brand__r.Name, Budgeter__c, Budgeter__r.Name, Channel__c, 
        	Item__c, Item_Allocation_Quantity__c, Sub_Allocated_Amount__c, Sub_Allocated_Item_Quantity__c,
        	LastModifiedById, LastModifiedDate, Organizational_Unit__c, Parent__c, Program__c, Program__r.Name,
        	Shopper__c, Shopper__r.Name, (SELECT Id, Account__c, Account__r.Name, Amount__c, Brand__c, Brand__r.Name, Budgeter__c, Budgeter__r.Name, 
        	Channel__c, Item__c, Item_Allocation_Quantity__c, Sub_Allocated_Amount__c, Sub_Allocated_Item_Quantity__c, LastModifiedById, LastModifiedDate, Organizational_Unit__c, Parent__c, Program__c, Program__r.Name,
        	Shopper__c, Shopper__r.Name FROM Budgets__r order by Shopper__r.Name) FROM Budget__c where Order_Window__c=:owId and 
        								Parent__r.Shopper__c != :UserInfo.getUserId() and
        									(Shopper__c=:UserInfo.getUserId() or 
        									 Budgeter__c=:UserInfo.getUserId() or Budget_Creator__c=:UserInfo.getUserId()) and
        									(Parent__r.Shopper__c != :UserInfo.getUserId() and Parent__r.Budgeter__c != :UserInfo.getUserId() and
        									 Parent__r.Budget_Creator__c != :UserInfo.getUserId())
        									order by Shopper__r.Name];
        	System.debug('BUDGETS: '+orderwindowBudgets);
        	
		}
		*/
	}
}