TestRepo2/src/objects/Brand__c.object
<CustomObject>
    <fields>
        <fullName>Content_Description__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Content Description (logo)</description>
        <label>Content Description</label>
        <referenceTo>Content_Description__c</referenceTo>
        <relationshipLabel>Brands</relationshipLabel>
        <relationshipName>Brands</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/Calendar__c.object
<CustomObject>
    <label>Calendar</label>
    <nameField>
        <label>Calendar Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Calendar</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

TestRepo2/src/objects/Content_Description__c.object
<CustomObject>
    <label>Content Description</label>
    <nameField>
        <label>Content Description Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Content Descriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/Content_Property__c.object
<CustomObject>
    <fields>
        <fullName>Calendar__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Calendar</label>
        <referenceTo>Calendar__c</referenceTo>
        <relationshipLabel>Content Properties</relationshipLabel>
        <relationshipName>Content_Properties</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Content_Description__c</fullName>
        <label>Content Description</label>
        <referenceTo>Content_Description__c</referenceTo>
        <relationshipLabel>Content Properties</relationshipLabel>
        <relationshipName>Content_Properties</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Content Property</label>
    <nameField>
        <label>Content Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Content Properties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestRepo2/src/objects/ContentBrand__c.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipLabel>ContentBrand</relationshipLabel>
        <relationshipName>ContentBrand</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Content_Description__c</fullName>
        <label>Content Description</label>
        <referenceTo>Content_Description__c</referenceTo>
        <relationshipLabel>ContentBrand</relationshipLabel>
        <relationshipName>ContentBrand_del</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>ContentBrand</label>
    <nameField>
        <label>ContentBrand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ContentBrand</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestRepo2/src/objects/File__c.object
<CustomObject>
    <description>File store information about files inside folders</description>
    <fields>
        <fullName>Calendar__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Calendar</label>
        <referenceTo>Calendar__c</referenceTo>
        <relationshipLabel>Files</relationshipLabel>
        <relationshipName>Files</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>File</label>
    <nameField>
        <displayFormat>file-{0000000}</displayFormat>
        <label>File Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Files</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/classes/Test_Controller_ContentDelete.cls
@isTest
private class Test_Controller_ContentDelete {
    
    static testMethod void testControllerfile() {   
        Test.StartTest();
            Controller_ContentDelete controller =  new Controller_ContentDelete();
            Content_Description__c contentDesc  = Test_Helper.testInsertContentDescription();               
                        
            Calendar__c cal = Test_Helper.testInsertPCalendar('test', 'test', date.valueOf('2011-11-1'), date.valueOf('2011-11-10'));           
            Content_Property__c cp = Test_Helper.testInsertContentProperty('test', cal.Id, contentDesc.Id, 'test', 'test', 'test', 'test');
            
            Brand__c b = Test_Helper.testInsertBrand('testbrand');
            
            ContentBrand__c cb = Test_Helper.testInsertContentBrand(contentDesc.Id, b.Id);
            
            controller.currentSection = 'file';
            controller.switchSection();
        
            Integer beforeFilesInsert = controller.setCtrl.getResultSize();
            File__c fileFirst    = Test_Helper.testInsertFile();   
            File__c fileSecond   = Test_Helper.testInsertFile();            
            
            controller.reloadLists();
            //@todo: needs to change it
            //System.assertEquals(beforeFilesInsert, controller.setCtrl.getResultSize()-2);
            
            Integer beforeDelete = controller.setCtrl.getResultSize();
            controller.contentItemList[0].selected = TRUE;
            controller.deleteContent();
            //@todo: needs to change it         
            //System.assertEquals(beforeDelete, controller.setCtrl.getResultSize()+1);
        Test.StopTest();    
    } 

    static testMethod void testControllerdescr() {   
        Test.StartTest();
            Controller_ContentDelete controller =  new Controller_ContentDelete();
            Content_Description__c contentDesc  = Test_Helper.testInsertContentDescription();               
                        
            Calendar__c cal = Test_Helper.testInsertPCalendar('test', 'test', date.valueOf('2011-11-1'), date.valueOf('2011-11-10'));           
            Content_Property__c cp = Test_Helper.testInsertContentProperty('test', cal.Id, contentDesc.Id, 'test', 'test', 'test', 'test');
            
            Brand__c b = Test_Helper.testInsertBrand('testbrand');
            
            ContentBrand__c cb = Test_Helper.testInsertContentBrand(contentDesc.Id, b.Id);
            
            controller.currentSection = 'desc';
            controller.switchSection();
            
            controller.getOrganizationunits();
            controller.getClassificationRow1();
            controller.getClassificationRow2();
            controller.resetFilters(); 
            controller.getBrands();
        
            Integer beforeDeleteDes = controller.setCtrl.getResultSize();
            controller.contentItemList[0].selected = TRUE;
            controller.deleteContent();
            //@todo: needs to change it
            //System.assertEquals(beforeDeleteDes, controller.setCtrl.getResultSize()+1);         
            controller.cancelDelete();
            List<SelectOption> gPS = controller.getPageSections();
            System.assertEquals(3, gPS.size());
            
        Test.StopTest();    
    } 

    
    static testMethod void testController2() {  
        Test.StartTest();
            Controller_ContentDelete controller =  new Controller_ContentDelete(); 
            controller.next();
            controller.previous();
            controller.last();
            controller.first();
            Integer tp =  controller.totalPages;
            Integer pN = controller.pageNumber;
            Boolean hP = controller.hasPrevious;
            Boolean hN = controller.hasNext;
            
            controller.getDivisions();
            controller.getFolders();
            controller.getCalendars();
            controller.getCategories();
            controller.getSubcategories();
            controller.getSubsubcategories();
            controller.getSubsubsubcategories();
            controller.reloadListsAfterSearch();
            controller.cancelDelete();
        Test.StopTest();
     }
     
   
     
      
    
}