TestRepo2/src/objects/Brand__c.object
<CustomObject>
    <fields>
        <fullName>Brand_Type__c</fullName>
        <label>Brand Type</label>
        <picklist>
            <picklistValues>
                <fullName>Generic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Individual</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Innovation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Innovation</label>
        <type>Checkbox</type>
    </fields>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/BrandBottle_Size__c.object
<CustomObject>
    <fields>
        <fullName>Bottle_Size__c</fullName>
        <label>Bottle Size</label>
        <referenceTo>Bottle_Size__c</referenceTo>
        <relationshipLabel>BrandBottle Sizes</relationshipLabel>
        <relationshipName>BrandBottle_Sizes</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipLabel>BrandBottle Sizes</relationshipLabel>
        <relationshipName>BrandBottle_Sizes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>BrandBottle Size</label>
    <nameField>
        <label>BrandBottle Size Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BrandBottle Sizes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestRepo2/src/objects/Gold_Standard_Met__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Gold Standards Met</relationshipLabel>
        <relationshipName>Gold_Standards_Met</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>BrandBottle_Size__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Optional relationship - use only for sub brands ie. Smirnoff flavors</inlineHelpText>
        <label>BrandBottle Size</label>
        <referenceTo>BrandBottle_Size__c</referenceTo>
        <relationshipLabel>Gold Standards Met</relationshipLabel>
        <relationshipName>Gold_Standards_Met</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipLabel>Gold Standards Met</relationshipLabel>
        <relationshipName>Gold_Standards_Met</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>Gold Standards Met</relationshipLabel>
        <relationshipName>Gold_Standards_Met</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Gold Standard Met</label>
    <nameField>
        <displayFormat>GS-{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>Gold Standard</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gold Standards Met</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestRepo2/src/objects/Survey__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Surveys</relationshipLabel>
        <relationshipName>Surveys</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Beating_Comp_Diageo_Val_10__c</fullName>
        <label>Beating Comp Diageo Val 10</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Beating_Comp_Diageo_Val_1__c</fullName>
        <label>Beating Comp Diageo Val 1</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Beating_Comp_Diageo_Val_2__c</fullName>
        <label>Beating Comp Diageo Val 2</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Beating_Comp_Diageo_Val_3__c</fullName>
        <label>Beating Comp Diageo Val 3</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Beating_Comp_Diageo_Val_4__c</fullName>
        <label>Beating Comp Diageo Val 4</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Beating_Comp_Diageo_Val_5__c</fullName>
        <label>Beating Comp Diageo Val 5</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Beating_Comp_Diageo_Val_6__c</fullName>
        <label>Beating Comp Diageo Val 6</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Beating_Comp_Diageo_Val_7__c</fullName>
        <label>Beating Comp Diageo Val 7</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Beating_Comp_Diageo_Val_8__c</fullName>
        <label>Beating Comp Diageo Val 8</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Beating_Comp_Diageo_Val_9__c</fullName>
        <label>Beating Comp Diageo Val 9</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Extra_Credit_Value_1__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Extra Credit Value 1</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Survey_Layout__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The layout record is used to determine how to display the survey data in its related dynamic layout.</description>
        <label>Survey Layout</label>
        <referenceTo>Survey_Layout__c</referenceTo>
        <relationshipLabel>Surveys</relationshipLabel>
        <relationshipName>Surveys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Survey_Status__c</fullName>
        <label>Survey Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open - Not Started</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Open - In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Survey</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestRepo2/src/objects/Survey_Layout__c.object
<CustomObject>
    <description>Holds the configuration for dynamically rendered survey layouts.</description>
    <fields>
        <fullName>Activate_Survey__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this checkbox to activate survey layout and publish survey records to each account.</description>
        <inlineHelpText>Check this checkbox to activate survey layout and publish survey records to each account.</inlineHelpText>
        <label>Activate Survey</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Beating_Comp_Label_1__c</fullName>
        <description>This field is the label for a Beating The Competition line item.</description>
        <inlineHelpText>This field is the label for a Beating The Competition line item.  Leave this field blank if you do not want it rendered on this survey record.</inlineHelpText>
        <label>Beating Comp Label 1</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Beating_Comp_Success_Percent_1__c</fullName>
        <defaultValue>0</defaultValue>
        <description>This is the criteria that determines if the Diageo number and the Total number evaluate to a successful ratio / percentage.  If the label says &apos;&gt;= 35% of Displays,&apos; enter a &apos;35&apos; here.</description>
        <inlineHelpText>This is the criteria that determines if the Diageo number and the Total number evaluate to a successful ratio / percentage.  If the label says &apos;&gt;= 35% of Displays,&apos; enter a &apos;35&apos; here.</inlineHelpText>
        <label>Beating Comp Success Percent 1</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Beating_Comp_Success_Percent_2__c</fullName>
        <label>Beating Comp Success Percent 2</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Beating_Comp_Success_Percent_3__c</fullName>
        <label>Beating Comp Success Percent 3</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Beating_Comp_Success_Percent_4__c</fullName>
        <label>Beating Comp Success Percent 4</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Clone_Survey_Layout__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Hidden field used for the survey layout trigger that will clone a survey layout and will also clone copies of the related brand item and brand bottle item layout records.</description>
        <label>Clone Survey Layout</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Extra_Credit_Label_1__c</fullName>
        <label>Extra Credit Label 1</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Percent_of_Grade_BeatComp__c</fullName>
        <label>Percent of Grade BeatComp</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Percent_of_Grade_Dist__c</fullName>
        <description>This field is used to calculate the percentage of Distrubution/Shelf/Display used for the final Account Grade.</description>
        <label>Percent of Grade Distribution</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Percent_of_Grade_Extra_Credit__c</fullName>
        <label>Percent of Grade Extra Credit</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Percent_of_Grade_Innovation__c</fullName>
        <label>Percent of Grade Innovation</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Survey Layout</label>
    <nameField>
        <label>Survey Layout Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Layouts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/Survey_Layout_Brand_Bottle_Item__c.object
<CustomObject>
    <fields>
        <fullName>BrandBottle_Size__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BrandBottle Size</label>
        <referenceTo>BrandBottle_Size__c</referenceTo>
        <relationshipLabel>Survey Innovation / Sustainovation</relationshipLabel>
        <relationshipName>Survey_Layout_Brand_Bottle_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Survey_Layout__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Survey Layout</label>
        <referenceTo>Survey_Layout__c</referenceTo>
        <relationshipName>Survey_Layout_Brand_Bottle_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Survey Innovation / Sustainovation</label>
    <nameField>
        <displayFormat>SLBBIN-{00000}</displayFormat>
        <label>Survey Layout Brand Bottle Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Innovation / Sustainovation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/SurveyLayout_Brand_Items__c.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipLabel>Survey Distribution / Shelf / Display</relationshipLabel>
        <relationshipName>SurveyLayout_Brand_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Display_Checkbox_Not_Applicable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Display Checkbox Not Applicable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Survey_Layout__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Survey Layout</label>
        <referenceTo>Survey_Layout__c</referenceTo>
        <relationshipName>SurveyLayout_Brand_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Survey Distribution / Shelf / Display</label>
    <nameField>
        <displayFormat>SLBIN-{00000}</displayFormat>
        <label>SurveyLayout Brand Items Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Distribution / Shelf / Display</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/classes/Test_Controller_AccountSurvey.cls
@isTest
private class Test_Controller_AccountSurvey {
	 
	 
	 
	 static testMethod void testControllerUpdates()
	 {
	 	Account account = Test_Helper.testInsertAccount('testAcct');
        Survey_Layout__c layout = createSurveyLayout('test layout');
        
        
        Brand__c brand = new Brand__c();
        brand.Name = 'testBrand';
        brand.Innovation__c = true;
        brand.Brand_Type__c = 'Individual';
        insert brand;
        
        Bottle_Size__c bottleSize = new Bottle_Size__c();
        bottleSize.Name = '1000' ;
        insert bottleSize;
        
        BrandBottle_Size__c bbs = new BrandBottle_Size__c();
        bbs.Bottle_Size__c = bottleSize.Id;
        bbs.Brand__c = brand.Id;
        insert bbs;
        
        
        
		insert layout ;
       
        Survey_Layout_Brand_Bottle_Item__c bbi = new Survey_Layout_Brand_Bottle_Item__c();
        bbi.BrandBottle_Size__c = bbs.Id;
        bbi.Survey_Layout__c = layout.Id;
        
        SurveyLayout_Brand_Items__c bi = new SurveyLayout_Brand_Items__c();
        bi.Brand__c = brand.Id;
        bi.Survey_Layout__c = layout.Id;
        bi.Display_Checkbox_Not_Applicable__c = true;
		
		
		insert bbi;
		insert bi;
        
        system.test.startTest();
			
			
			layout.Activate_Survey__c = true;
			update layout;
			
			
			
			
			
			Survey__c survey = new Survey__c();
			//[select id, Extra_Credit_Value_1__c, Beating_Comp_Diageo_Val_1__c, Beating_Comp_Diageo_Val_5__c,
				//				Beating_Comp_Diageo_Val_6__c, Beating_Comp_Diageo_Val_4__c, Beating_Comp_Diageo_Val_3__c, Beating_Comp_Diageo_Val_2__c, 
					//			Beating_Comp_Diageo_Val_7__c, Beating_Comp_Diageo_Val_8__c, Beating_Comp_Diageo_Val_9__c, Beating_Comp_Diageo_Val_10__c
						//		from Survey__c where Survey_Layout__c = :layout.Id limit 1] ;
						
			survey.Extra_Credit_Value_1__c = true;
			survey.Beating_Comp_Diageo_Val_1__c = 11;
			survey.Beating_Comp_Diageo_Val_2__c = 1;
			survey.Beating_Comp_Diageo_Val_3__c = 1;
			survey.Beating_Comp_Diageo_Val_4__c = 1;
			survey.Beating_Comp_Diageo_Val_5__c = 1;
			survey.Beating_Comp_Diageo_Val_6__c = 1;
			survey.Beating_Comp_Diageo_Val_7__c = 1;
			survey.Beating_Comp_Diageo_Val_8__c = 1;
			survey.Beating_Comp_Diageo_Val_9__c = 1;
			survey.Beating_Comp_Diageo_Val_10__c = 1;
			survey.Survey_Layout__c = layout.Id;
			survey.Account__c = account.Id;
			//update survey;
			insert survey;
			
			
			Gold_Standard_Met__c newGsmRecord = new Gold_Standard_Met__c();
			newGsmRecord.Brand__c = brand.Id ;
			newGsmRecord.Survey__c = survey.Id ;
			newGsmRecord.Account__c = account.Id ;
			insert newGsmRecord;
			
			Gold_Standard_Met__c newGsmRecord2 = new Gold_Standard_Met__c();
			newGsmRecord2.Brand__c = brand.Id ;
			newGsmRecord2.BrandBottle_Size__c = bbi.BrandBottle_Size__c;
			newGsmRecord2.Survey__c = survey.Id ;
			newGsmRecord2.Account__c = account.Id ;
			insert newGsmRecord2;
			
			
			Controller_AccountSurvey controllerExt = new Controller_AccountSurvey( survey.Id );
			controllerExt.submitSurvey();
			//Updated by Akanksha(offshore) for case  00003540
			ApexPages.StandardController sc = new ApexPages.StandardController(survey);
			Controller_AccountSurvey controller = new Controller_AccountSurvey(sc);
			
		
		system.test.stopTest();
	 }
	 
	 
	 
	 
	 static testMethod void testDeletes()
	 {
	 	Account account = Test_Helper.testInsertAccount('testAcct');
        Survey_Layout__c layout = createSurveyLayout('test layout');
        
        
        Brand__c brand = new Brand__c();
        brand.Name = 'testBrand';
        brand.Innovation__c = true;
        brand.Brand_Type__c = 'Individual';
        insert brand;
        
        Bottle_Size__c bottleSize = new Bottle_Size__c();
        bottleSize.Name = '1000' ;
        insert bottleSize;
        
        BrandBottle_Size__c bbs = new BrandBottle_Size__c();
        bbs.Bottle_Size__c = bottleSize.Id;
        bbs.Brand__c = brand.Id;
        insert bbs;
        
        
        
		insert layout ;
       
        Survey_Layout_Brand_Bottle_Item__c bbi = new Survey_Layout_Brand_Bottle_Item__c();
        bbi.BrandBottle_Size__c = bbs.Id;
        bbi.Survey_Layout__c = layout.Id;
        
        SurveyLayout_Brand_Items__c bi = new SurveyLayout_Brand_Items__c();
        bi.Brand__c = brand.Id;
        bi.Survey_Layout__c = layout.Id;
        bi.Display_Checkbox_Not_Applicable__c = true;
		
		
		insert bbi;
		insert bi;
        
		layout.Activate_Survey__c = true;
		update layout;
		
		Survey__c survey = new Survey__c();
			//[select id, Extra_Credit_Value_1__c, Beating_Comp_Diageo_Val_1__c, Beating_Comp_Diageo_Val_5__c,
				//				Beating_Comp_Diageo_Val_6__c, Beating_Comp_Diageo_Val_4__c, Beating_Comp_Diageo_Val_3__c, Beating_Comp_Diageo_Val_2__c, 
					//			Beating_Comp_Diageo_Val_7__c, Beating_Comp_Diageo_Val_8__c, Beating_Comp_Diageo_Val_9__c, Beating_Comp_Diageo_Val_10__c
						//		from Survey__c where Survey_Layout__c = :layout.Id limit 1] ;
						
		survey.Extra_Credit_Value_1__c = true;
		survey.Beating_Comp_Diageo_Val_1__c = 11;
		survey.Beating_Comp_Diageo_Val_2__c = 1;
		survey.Beating_Comp_Diageo_Val_3__c = 1;
		survey.Beating_Comp_Diageo_Val_4__c = 1;
		survey.Beating_Comp_Diageo_Val_5__c = 1;
		survey.Beating_Comp_Diageo_Val_6__c = 1;
		survey.Beating_Comp_Diageo_Val_7__c = 1;
		survey.Beating_Comp_Diageo_Val_8__c = 1;
		survey.Beating_Comp_Diageo_Val_9__c = 1;
		survey.Beating_Comp_Diageo_Val_10__c = 1;
		survey.Survey_Layout__c = layout.Id;
		survey.Account__c = account.Id;
		//update survey;
		insert survey;
		
		Controller_AccountSurvey controllerExt = new Controller_AccountSurvey( survey.Id );
		controllerExt.submitSurvey();
		
		
        system.test.startTest();
			
			try {
				survey.Survey_Status__c = 'Closed - Complete';
				update survey;
				survey.Beating_Comp_Diageo_Val_1__c = 1;
				update survey;
			} catch (Exception e) {}
			
			layout.Clone_Survey_Layout__c = true;
			try {
				update layout ;
			}
			catch (Exception e) {
			}
			
			delete layout ;
		
		system.test.stopTest();
	 }
	 
	 
	 private static Survey_Layout__c createSurveyLayout(String layoutName)
	 {
	 	Survey_Layout__c layout = new Survey_Layout__c();
        layout.Name = layoutName;
        layout.Beating_Comp_Label_1__c = 'test 1';
        layout.Beating_Comp_Success_Percent_1__c = 10;
        layout.Extra_Credit_Label_1__c = 'test 1';
        layout.Percent_of_Grade_Innovation__c = 25;
        layout.Percent_of_Grade_Extra_Credit__c = 25;
        layout.Percent_of_Grade_Dist__c = 25;
        layout.Percent_of_Grade_BeatComp__c = 25;
        layout.Beating_Comp_Success_Percent_1__c = 0;
        layout.Beating_Comp_Success_Percent_2__c = 0;
        layout.Beating_Comp_Success_Percent_3__c = 0;
        layout.Beating_Comp_Success_Percent_4__c = 0;
        layout.Beating_Comp_Success_Percent_5__c = 0;
        layout.Beating_Comp_Success_Percent_6__c = 0;
        layout.Beating_Comp_Success_Percent_7__c = 0;
        layout.Beating_Comp_Success_Percent_8__c = 0;
        layout.Beating_Comp_Success_Percent_9__c = 0;
        layout.Beating_Comp_Success_Percent_10__c = 0;
        layout.Clone_Survey_Layout__c = false;
        return layout;
	 }
	 
	 
	 static testMethod void testController() 
	 {	 	

        Account account = Test_Helper.testInsertAccount('testAcct');
        Survey_Layout__c layout = createSurveyLayout('test layout');
        
        
        Brand__c brand = new Brand__c();
        brand.Name = 'testBrand';
        brand.Innovation__c = true;
        brand.Brand_Type__c = 'Individual';
        insert brand;
        
        Bottle_Size__c bottleSize = new Bottle_Size__c();
        bottleSize.Name = '1000' ;
        insert bottleSize;
        
        BrandBottle_Size__c bbs = new BrandBottle_Size__c();
        bbs.Bottle_Size__c = bottleSize.Id;
        bbs.Brand__c = brand.Id;
        insert bbs;
        
        
        
        
        system.test.startTest();
			
			//going to put this here as another project missed this simple line:
			AggregateResultHolder testHolder = new AggregateResultHolder(); 
			
			insert layout ;
        
	        Survey_Layout_Brand_Bottle_Item__c bbi = new Survey_Layout_Brand_Bottle_Item__c();
	        bbi.BrandBottle_Size__c = bbs.Id;
	        bbi.Survey_Layout__c = layout.Id;
	        
	        SurveyLayout_Brand_Items__c bi = new SurveyLayout_Brand_Items__c();
	        bi.Brand__c = brand.Id;
	        bi.Survey_Layout__c = layout.Id;
	        bi.Display_Checkbox_Not_Applicable__c = true;
			
			
			insert bbi;
			insert bi;
			
		
		system.test.stopTest();
	
	 }

}