TestRepo2/src/objects/Brand__c.object
<CustomObject>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/NABCA_Brand__c.object
<CustomObject>
    <description>We will store the National Alcohol Beverage Control Association brands data in this object</description>
    <fields>
        <fullName>Brand_Composite_Key__c</fullName>
        <description>External Id for Sales Record (Material Code + NABCA state code)</description>
        <externalId>true</externalId>
        <label>Brand Composite Key</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Common_Description__c</fullName>
        <label>Common Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>NABCA_Category__c</fullName>
        <label>NABCA Category</label>
        <referenceTo>NABCA_Category__c</referenceTo>
        <relationshipLabel>NABCA Brands</relationshipLabel>
        <relationshipName>NABCA_Brands</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>NABCA_Size_Description__c</fullName>
        <label>NABCA Size Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>NABCA_Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NABCA Vendor</label>
        <referenceTo>NABCA_Vendor__c</referenceTo>
        <relationshipLabel>NABCA Brands</relationshipLabel>
        <relationshipName>NABCA_Brands</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>NABCA Brand</label>
    <nameField>
        <displayFormat>NB-{YYYY}{MM}{DD}-{0000000}</displayFormat>
        <label>NABCA Brand ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NABCA Brands</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestRepo2/src/objects/NABCA_Category__c.object
<CustomObject>
    <description>This object stores the National Alcohol Beverage Control Association Category data</description>
    <fields>
        <fullName>NABCA_Major_Category_Code__c</fullName>
        <externalId>true</externalId>
        <label>NABCA Major Category Code</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>NABCA_Major_Category_Description__c</fullName>
        <label>NABCA Major Category Description</label>
        <type>TextArea</type>
    </fields>
    <label>NABCA Category</label>
    <nameField>
        <displayFormat>NC-{YYYY}{MM}{DD}-{0000000}</displayFormat>
        <label>Competitor Category</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NABCA Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/NABCA_Sales_Data__c.object
<CustomObject>
    <description>National Alcohol Beverage Control Association sales data</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>NABCA Sales Data</relationshipLabel>
        <relationshipName>NABCA_Sales2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Brand</label>
        <referenceTo>NABCA_Brand__c</referenceTo>
        <relationshipLabel>NABCA Sales Data</relationshipLabel>
        <relationshipName>NABCA_Sales2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Month24_9L_Volume__c</fullName>
        <label>Current Month - 12</label>
        <precision>16</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Month24_ShelfDollar_Volume__c</fullName>
        <label>SV Current Month - 12</label>
        <precision>16</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Month36_9L_Volume__c</fullName>
        <label>Current Month Volume</label>
        <precision>16</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Month36_ShelfDollar_Volume__c</fullName>
        <label>SV Current Month Volume</label>
        <precision>16</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Month_End_Date__c</fullName>
        <label>Month End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sale_Composite_Key__c</fullName>
        <description>External Id for Sales Record (Material Code + Licensee code + NABCA state code)</description>
        <externalId>true</externalId>
        <label>Sale Composite Key</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>NABCA Sales Data</label>
    <nameField>
        <displayFormat>NS-{MM}{DD}{YYYY}-{000000000}</displayFormat>
        <label>NABCA Sales Volume ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NABCA Sales Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/NABCA_Vendor__c.object
<CustomObject>
    <fields>
        <fullName>NABCA_Vendor_Code__c</fullName>
        <externalId>true</externalId>
        <label>Vendor Code</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>NABCA_Vendor_Description__c</fullName>
        <label>Vendor Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <label>NABCA Vendor</label>
    <nameField>
        <displayFormat>NVN-{MM}{DD}{YYYY}-{000000000}</displayFormat>
        <label>NABCA Vendor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NABCA Vendors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/classes/Test_Controller_ShareReporting.cls
@isTest
private class Test_Controller_ShareReporting {

    static testMethod void testController_ShareReporting() {
    	Account acc = new Account();
    	acc.Name = 'test account';
    	insert acc;
    	
    	NABCA_Category__c nc = new NABCA_Category__c();
    	nc.NABCA_Major_Category_Description__c = 'nc';
    	nc.NABCA_Major_Category_Code__c = 'code';
    	insert nc;
    	
    	NABCA_Vendor__c nv = new NABCA_Vendor__c();
    	nv.NABCA_Vendor_Description__c = 'nv';
    	nv.NABCA_Vendor_Code__c = 'code';
    	insert nv;
    	
    	NABCA_Brand__c brand = new NABCA_Brand__c();
    	brand.NABCA_Category__c = nc.Id;
    	brand.NABCA_Vendor__c = nv.Id;
    	brand.Common_Description__c = 'desc';
    	brand.NABCA_Size_Description__c = 'big';
    	brand.Brand_Composite_Key__c = 'key';
    	insert brand;
    	
    	NABCA_Sales_Data__c sd = new NABCA_Sales_Data__c();
    	sd.Account__c = acc.Id;
    	sd.Brand__c = brand.Id;
    	sd.Month_End_Date__c = Date.today();
    	sd.Sale_Composite_Key__c = '12345';
    	sd.Month36_9L_Volume__c = 100;
    	sd.Month36_ShelfDollar_Volume__c = 100;
    	sd.Month24_9L_Volume__c = 100;
    	sd.Month24_ShelfDollar_Volume__c = 100;
    	insert sd;
    	
    	Test.startTest();
    	
        Controller_ShareReporting cont = new Controller_ShareReporting(new ApexPages.StandardController(acc));
    
    	cont.getGroupByOptions();
    	cont.getSelectedRecordsOptions();
    	cont.getStartDateOptions();
    	cont.getBeverageTypeOptions();
    	cont.getDateRangeOptions();
    	cont.getMeasurementOptions();
    	cont.getTableRowList();
    	cont.measurementType = cont.VOLUME;
    	cont.getData();
    	cont.measurementType = cont.SHELF_DOLLAR;
    	cont.getData();
    	cont.dateRange = cont.LAST12;
    	cont.beverageType = cont.SPIRIT;
    	cont.selectedGroup = cont.CATEGORY;
    	cont.measurementType = cont.VOLUME;
    	cont.getData();
    	cont.fetchInternalSalesData(cont.selectedGroup, cont.selectedMonth, cont.dateRange, cont.TOPTEN, cont.ALL, cont.VOLUME);
    	cont.measurementType = cont.SHELF_DOLLAR;
    	cont.getData();
    	cont.dateRange = cont.CURRENTFISCAL;
    	cont.beverageType = cont.WINE;
    	cont.measurementType = cont.VOLUME;
    	cont.getData();
    	cont.measurementType = cont.SHELF_DOLLAR;
    	cont.getData();
    	
    	cont.getCurrencyFromString('3.00');
    	cont.getCurrencyFromString('3.0');
    	cont.getCurrencyFromString('3');
    	cont.sortDown(cont.topTenTableRowList);
    	cont.sortUp(cont.topTenTableRowList);
    	cont.setBevTypeToSpirits();
    }
}