TestRepo2/src/objects/Brand__c.object
<CustomObject>
    <fields>
        <fullName>Magento_Id__c</fullName>
        <externalId>true</externalId>
        <label>Magento Id</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/Calendar__c.object
<CustomObject>
    <label>Calendar</label>
    <nameField>
        <label>Calendar Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Calendar</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

TestRepo2/src/objects/Order_Window__c.object
<CustomObject>
    <description>POS Project: object that represents a period of time in which catalog items are offered and shoppers are allowed to buy them</description>
    <fields>
        <fullName>Magento_Id__c</fullName>
        <externalId>true</externalId>
        <label>Magento Category Id</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <controllingField>Type__c</controllingField>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Budgeting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Archived</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Order Window</label>
    <nameField>
        <label>Order Window Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Windows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/Program__c.object
<CustomObject>
    <description>POS Project: object that represents a set of events for which related catalog items are offered to shoppers (distributors and internal Diageo employees)</description>
    <fields>
        <fullName>Brand__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Calendar__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Calendar</label>
        <referenceTo>Calendar__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Magento_Id__c</fullName>
        <externalId>true</externalId>
        <label>Magento Category Id</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Window_Close_Date__c</fullName>
        <formula>Order_Window__r.Order_Close_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Order Window Close Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Order_Window_Start_Date__c</fullName>
        <formula>Order_Window__r.Order_Start_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Order Window Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Order_Window_Status__c</fullName>
        <formula>TEXT(Order_Window__r.Status__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Order Window Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Window__c</fullName>
        <label>Order Window</label>
        <referenceTo>Order_Window__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sales_Channel_Group__c</fullName>
        <label>Sales Channel Group</label>
        <picklist>
            <picklistValues>
                <fullName>Execution Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flow Visibility</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Multicultural</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VAP</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestRepo2/src/classes/POS_APIGetPrograms.cls
@RestResource(urlMapping='/GetPrograms/*')
global with sharing class POS_APIGetPrograms {
	
	private static String fieldList = 'Brand__c, Calendar__c, Id, Magento_Id__c, '+
	  'Order_Window__c, Order_Window_Close_Date__c, Order_Window_Start_Date__c, '+
	  'Order_Window_Status__c, Name, Sales_Channel_Group__c from Program__c '+
	  'where Order_Window_Status__c != \'New\'';
 	  
 	@HttpGet
    global static APIProgramResponse doGet () {
    	RestRequest req=RestContext.request;
    	RestResponse res=RestContext.response;
    	
        String UpdateTime = req.params.get('UpdateTime');   
    	
    	String soql = 'select '+fieldList;
    	if (UpdateTime!=null) {
    		UpdateTime = String.escapeSingleQuotes(UpdateTime);
    		soql = soql +' and SystemModstamp > '+UpdateTime;
    	}
    	String WindowId = req.params.get('WindowId');
    	if (WindowId != null) {
    		WindowId = String.escapeSingleQuotes(WindowId);
    		soql = soql +' and Order_Window__c = \''+WindowId+'\'';
    	}
    	
    	System.debug('Query: '+soql); 
    	
    	List<Program__c> programs = (List<Program__c>)Database.query(soql);
    	
    	APIProgramResponse response = new APIProgramResponse();
    	response.Programs=programs;
    	return response;
    
    }
    
    global class APIProgramResponse {
    	public List<Program__c> Programs;
    }
    
    @isTest
    public static void testGetPrograms () {
    	
    	POS_TestDataUtil.initializeTestData();
    	
    	RestRequest req = new RestRequest();
    	RestResponse res = new RestResponse();
    	
	    RestContext.request = req;
	    RestContext.response = res;
    	
    	//Try query with no populated data first
    	APIProgramResponse response = POS_APIGetPrograms.doGet();
    	List<Program__c> programs = response.Programs;
    	System.assert(programs.size()==0);
    	
    	//Now add data and test again
    	Order_Window__c window = POS_TestDataUtil.createOrderWindow();
    	window.Status__c='New';
    	update window;
    	
    	
    	
    	Program__c program = POS_TestDataUtil.createProgram();
    	program.Order_Window__c=window.Id;
    	update program;
    	
    	//Check to make sure no results come back with a new window
    	response = POS_APIGetPrograms.doGet();
    	programs = response.Programs;
    	System.assert(programs.size()==0);
    	
    	window.Status__c='In Review';
    	update window;
    	
    	//Now we should get results
    	response = POS_APIGetPrograms.doGet();
    	programs = response.Programs;
    	System.assert(programs.size()==1);
    	
    	//Now try with Window ID
    	req.addParameter('WindowId',window.Id);
    	response = POS_APIGetPrograms.doGet();
    	programs = response.Programs;
    	System.assert(programs.size()==1);
    	
    	//And with a bad Window ID we should get no results
    	req.addParameter('WindowId','000000000000000');
    	response = POS_APIGetPrograms.doGet();
    	programs = response.Programs;
    	System.assert(programs.size()==0);
    	
    	//Now try using a more recent update time and see if we get no results again
    	req=new RestRequest();
    	Datetime now = System.now();
    	now=now.addDays(2);
    	
    	String dateString = now.format('yyyy-MM-dd\'T\'HH:mm:ss\'Z\'');
    	req.addParameter('UpdateTime',dateString);
    	RestContext.request=req;
    	
    	response = POS_APIGetPrograms.doGet();
    	programs = response.Programs;
    	System.assert(programs.size()==0);
    	
    	
    }
   
}