TestRepo2/src/objects/Calendar__c.object
<CustomObject>
    <fields>
        <fullName>Classification__c</fullName>
        <label>Classification</label>
        <picklist>
            <picklistValues>
                <fullName>Spirits</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wine</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mixed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description Text</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Calendar</label>
    <nameField>
        <label>Calendar Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Calendar</pluralLabel>
    <recordTypes>
        <fullName>Planning</fullName>
        <active>true</active>
        <label>Planning</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

TestRepo2/src/objects/ContentVersion.object
<CustomObject>
    <fields>
        <fullName>Classification__c</fullName>
        <label>Classification</label>
        <picklist>
            <picklistValues>
                <fullName>Spirits</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wine</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>File__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>File</label>
        <referenceTo>File__c</referenceTo>
        <relationshipLabel>Content</relationshipLabel>
        <relationshipName>Content</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Image_Resolution__c</fullName>
        <label>Image Resolution</label>
        <picklist>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Portfolio__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Portfolio</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RTS__c</fullName>
        <defaultValue>false</defaultValue>
        <label>RTS</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Planning</fullName>
        <active>true</active>
        <label>Planning</label>
    </recordTypes>
</CustomObject>

TestRepo2/src/objects/File__c.object
<CustomObject>
    <description>File store information about files inside folders</description>
    <fields>
        <fullName>Available_Until__c</fullName>
        <label>Available Until</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Brand_Names__c</fullName>
        <label>Brands</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Brands__c</fullName>
        <label>Brand IDs</label>
        <picklist>
            <picklistValues>
                <fullName>a</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>b</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>c</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Calendar__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Calendar</label>
        <referenceTo>Calendar__c</referenceTo>
        <relationshipLabel>Files</relationshipLabel>
        <relationshipName>Files</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Classification__c</fullName>
        <label>Classification</label>
        <picklist>
            <picklistValues>
                <fullName>Spirits</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Wine</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Content_ID__c</fullName>
        <label>Content ID</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Content_Version_Id__c</fullName>
        <label>Content Version Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Distributor_Names__c</fullName>
        <description>Names of selected distributors.</description>
        <label>Distributors</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Distributors__c</fullName>
        <label>Distributor IDs</label>
        <picklist>
            <picklistValues>
                <fullName>a</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>b</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>c</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Division_Access__c</fullName>
        <label>Division Access</label>
        <picklist>
            <picklistValues>
                <fullName>Charmer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Control</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Franchise</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Glazers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Independent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SWS</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Folder_Names__c</fullName>
        <description>Names of selected folders.</description>
        <label>Folders</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Folders__c</fullName>
        <label>Folder IDs</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>17</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>18</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>19</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>21</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>22</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>23</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>24</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>25</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>26</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>27</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>28</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>29</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Image_Resolution__c</fullName>
        <label>Image Resolution</label>
        <picklist>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Is_Video__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Video</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Only_For_Internal_User__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Only For Internal User</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OrgUnits__c</fullName>
        <label>OrgUnit Id</label>
        <picklist>
            <picklistValues>
                <fullName>OrgUnit</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Page_Section__c</fullName>
        <label>Page Section</label>
        <picklist>
            <picklistValues>
                <fullName>Planning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Performance Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Collaboration</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Portfolio__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Portfolio</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Preview_Available__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Preview Available</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Preview_Id__c</fullName>
        <label>Preview Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RTS__c</fullName>
        <defaultValue>false</defaultValue>
        <label>RTS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Tags__c</fullName>
        <label>Tags</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Video_Id__c</fullName>
        <label>Video Id</label>
        <length>13</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>filesize__c</fullName>
        <label>filesize</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>filetype__c</fullName>
        <label>filetype</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>share_link__c</fullName>
        <label>share_link</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>File</label>
    <nameField>
        <displayFormat>file-{0000000}</displayFormat>
        <label>File Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Files</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/Folder__c.object
<CustomObject>
    <fields>
        <fullName>Classification__c</fullName>
        <label>Classification</label>
        <picklist>
            <picklistValues>
                <fullName>Spirits</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wine</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Distributor_Names__c</fullName>
        <label>Distributors</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Distributors__c</fullName>
        <label>Distributor IDs</label>
        <picklist>
            <picklistValues>
                <fullName>Distributor</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Only_For_Internal_User__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Only For Internal User</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OrgUnits__c</fullName>
        <label>OrgUnit Id</label>
        <picklist>
            <picklistValues>
                <fullName>OrgUnits</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Page_Section__c</fullName>
        <label>Page Section</label>
        <picklist>
            <picklistValues>
                <fullName>Planning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Performance Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Collaboration</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Folder</label>
    <nameField>
        <label>Folder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Folders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/classes/TriggerFile.cls
public with sharing class TriggerFile {
    public static boolean disabled = false;
    public static void onBeforeUpdate(map<id, File__c> newFileMap, map<id, File__c> oldFileMap) {
        if (TriggerFile.disabled) {
            return;
        }
              
       	
        List<String> contentList = new List<String>();
        Map<id, File__c> copyMap = new Map<id, File__c>();
        list<ContentVersion> cvs = new list<ContentVersion>();

        
	    for(String key : newFileMap.keySet()) {
	        File__c cd = newFileMap.get(key);
	        contentList.add(cd.Content_Id__c);	    
	        copyMap.put(cd.Content_Id__c, cd);
            boolean changed = false;
            ContentVersion cv = new ContentVersion(Id=cd.Content_Version_Id__c);
            if( cd.Title__c != oldFileMap.get(key).Title__c) {
                cv.Title = cd.Title__c;
                changed = true;
            }
            if( cd.Description__c != oldFileMap.get(key).Description__c) {
                cv.Description = cd.Description__c;
                changed = true;
            }
            if( cd.Classification__c != oldFileMap.get(key).Classification__c) {
                cv.Classification__c = cd.Classification__c;
                changed = true;
            }
            if (changed) {
                cvs.add(cv);
            }
	        
	    }
	    
       
        Set<Id> keySet = new Set<Id>(); 
        keySet = newFileMap.keySet();
        List<File__c> files = [Select f.share_link__c, f.filetype__c, f.filesize__c, f.Video_Id__c, f.Title__c, f.Tags__c, f.SystemModstamp, f.Start_Date__c, f.RTS__c, f.Preview_Id__c, f.Preview_Available__c, f.Portfolio__c, f.Page_Section__c, f.OwnerId, f.Only_For_Internal_User__c, f.Name, f.LastModifiedDate, f.LastModifiedById, f.Is_Video__c, f.IsDeleted, f.Image_Resolution__c, f.Id, f.Folders__c, f.Folder_Names__c, f.End_Date__c, f.OrgUnits__c, f.Division_Access__c, f.Distributors__c, f.Distributor_Names__c, f.Description__c, f.CreatedDate, f.CreatedById, f.Content_Version_Id__c, f.Content_ID__c, f.Calendar__c, f.Brands__c, f.Brand_Names__c, f.Available_Until__c From File__c f
        					   Where(
        					   			f.Content_ID__c IN :contentList
        					   			AND f.Id NOT IN :keySet
        					   		)
        					  ];       
       	           	
       	for(File__c file : files) {	       
	       File__c f = copyMap.get(file.Content_Id__c);	       
	       
	       file.share_link__c = f.share_link__c; 	 
	       file.filetype__c = f.filetype__c;
	       file.filesize__c = f.filesize__c;
	       file.Video_Id__c = f.Video_Id__c;
	       file.Title__c = f.Title__c;
	       file.Tags__c = f.Tags__c;	    
	       file.Start_Date__c = f.Start_Date__c;
	       file.RTS__c = f.RTS__c;
	       file.Preview_Id__c = f.Preview_Id__c;
	       file.Preview_Available__c = f.Preview_Available__c;
	       file.Portfolio__c = f.Portfolio__c;
	       file.Page_Section__c = f.Page_Section__c;
	       file.OwnerId = f.OwnerId;
	       file.Only_For_Internal_User__c = f.Only_For_Internal_User__c;
	       file.Is_Video__c = f.Is_Video__c;
	       file.Image_Resolution__c = f.Image_Resolution__c;
	       file.Folders__c = f.Folders__c;
	       file.Folder_Names__c = f.Folder_Names__c;
	       file.End_Date__c = f.End_Date__c;
	       file.OrgUnits__c = f.OrgUnits__c;
	       file.Division_Access__c = f.Division_Access__c;
	       file.Distributors__c = f.Distributors__c;
	       file.Distributor_Names__c = f.Distributor_Names__c;
	       file.Description__c = f.Description__c;
	       file.Content_Version_Id__c = f.Content_Version_Id__c;
	       file.Content_ID__c = f.Content_ID__c;
	       file.Brands__c = f.Brands__c;
	       file.Brand_Names__c = f.Brand_Names__c;
	       file.Available_Until__c = f.Available_Until__c;
	    }
	    
	    TriggerFile.disabled = true;
	    update(files);
	    if (cvs.size()>0) {
            TriggerContentVersion.disabled = true;
            update cvs;
            TriggerContentVersion.disabled = false;
	    }
	    TriggerFile.disabled = false;
    }
    
    public static void setClassification(list<File__c> files) {
        if (TriggerFile.disabled) {
            return;
        }
	    
	    set<string> folderIds = new set<string>();
	    
	    for(File__c f : files){
	        if(f.Folders__c != null && f.Folders__c != '' && f.Page_Section__c == 'Planning'){
	            List<String> fileFolders = f.Folders__c.split(';');
	            for(string folderId : fileFolders){
	                if(folderId != null && folderId != '' && !folderIds.contains(folderId)) {
	                    folderIds.add(folderId);
	                }
	            }
	        }
	    }
	
	    Map<Id,folder__c>  folderInformation = new Map <Id,folder__c>([select id, classification__c from folder__c where id = :folderIds and classification__c != null]);
	
	    for(File__c f : files){
	        if(f.Folders__c != null && f.Folders__c != '' && f.Page_Section__c == 'Planning'){
	            List<String> fileFolders = f.Folders__c.split(';');
	            for(string folderId : fileFolders){
	                if(folderId != null && folderId != '' && folderInformation.containsKey(folderId)) {
	                    List<String> folderClasifications = folderInformation.get(folderId).classification__c.split(';');
	                    for(String clsf : folderClasifications){
	                        if(clsf == '' || clsf == null){
	                            continue;
	                        }
	                        if(f.classification__c != null && f.classification__c.contains(clsf.trim())){
	                            continue;
	                        }
	                        if( f.classification__c == null){
	                            f.classification__c = clsf;
	                        } else {
	                            f.classification__c = f.classification__c+' ;'+clsf;
	                        }
	                    }
	                }
	            }
	        }
	    }    	
    }
}