TestRepo2/src/objects/Cart__c.object
<CustomObject>
    <description>POS Project: object that represents a shopping cart</description>
    <fields>
        <fullName>Order_Window__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Window</label>
        <referenceTo>Order_Window__c</referenceTo>
        <relationshipLabel>Carts</relationshipLabel>
        <relationshipName>Carts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shopper__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shopper</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Carts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Processing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Removed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Cart</label>
    <nameField>
        <displayFormat>CRT-{00000000}</displayFormat>
        <label>Cart ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Carts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/Cart_Item__c.object
<CustomObject>
    <description>POS Project: junction object that represents the many-to-many relationship between Carts and Items</description>
    <fields>
        <fullName>Carrier__c</fullName>
        <label>Carrier</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cart__c</fullName>
        <label>Cart</label>
        <referenceTo>Cart__c</referenceTo>
        <relationshipLabel>Cart Items</relationshipLabel>
        <relationshipName>Carts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Company_Code__c</fullName>
        <label>Company Code</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Custom_Attribute_Value__c</fullName>
        <label>Custom Attribute Value</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Item_Customization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Item Customization</label>
        <referenceTo>Item_Customization__c</referenceTo>
        <relationshipLabel>Cart Items</relationshipLabel>
        <relationshipName>Cart_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item__c</fullName>
        <label>Item</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>Cart Items</relationshipLabel>
        <relationshipName>Cart_Items</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Ship_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To</label>
        <referenceTo>Ship_To__c</referenceTo>
        <relationshipLabel>Cart Items</relationshipLabel>
        <relationshipName>Cart_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Selected</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Processing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shipped</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Tracking_Code__c</fullName>
        <label>Tracking Code</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WBS__c</fullName>
        <label>WBS</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Cart Item</label>
    <nameField>
        <displayFormat>CIT-{0000000000}</displayFormat>
        <label>Cart Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cart Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestRepo2/src/objects/Item__c.object
<CustomObject>
    <description>POS Project: object that represents catalog items available for shopping</description>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Development</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Approved w/Est Price</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted w/Final Price</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Removed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

TestRepo2/src/objects/Item_Customization__c.object
<CustomObject>
    <description>POS Project: object that represents different customizations that a catalog item may have</description>
    <fields>
        <fullName>Item__c</fullName>
        <label>Item</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>Item Customizations</relationshipLabel>
        <relationshipName>Item_Customizations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Item Customization</label>
    <nameField>
        <label>Custom Attribute Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Item Customizations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestRepo2/src/objects/Order_Window__c.object
<CustomObject>
    <description>POS Project: object that represents a period of time in which catalog items are offered and shoppers are allowed to buy them</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <controllingField>Type__c</controllingField>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Budgeting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Archived</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Order Window</label>
    <nameField>
        <label>Order Window Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Windows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/POSAPIConfiguration__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Row_Limit__c</fullName>
        <description>The number of rows to return in any API request</description>
        <label>Row Limit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>POS API Configuration</label>
</CustomObject>

TestRepo2/src/objects/Program__c.object
<CustomObject>
    <description>POS Project: object that represents a set of events for which related catalog items are offered to shoppers (distributors and internal Diageo employees)</description>
    <fields>
        <fullName>Order_Window__c</fullName>
        <label>Order Window</label>
        <referenceTo>Order_Window__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestRepo2/src/objects/Ship_To__c.object
<CustomObject>
    <description>POS Project: object that represents a delivery address associated to a particular account</description>
    <label>Ship To</label>
    <nameField>
        <label>Ship To Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ship To&apos;s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestRepo2/src/classes/POS_APIGetCartItems2.cls
/**
 * @author      Model Metrics {Venkatesh Kamat}
 * @date        06/19/2012
 * @description Class exposing Active Carts as REST Outbound service.
 */
 
@RestResource(urlMapping='/GetCartItems2/*')
global with sharing class POS_APIGetCartItems2 {
	
	
    @HttpPost
     global static APICartResponse doPost (String UpdateTime, Integer Offset, String WindowId, String CartId) {
    	RestRequest req = RestContext.request; 
        RestResponse res = RestContext.response;	
        
        POSAPIConfiguration__c settings;
        if (Test.isRunningTest()) {
        	settings=new POSAPIConfiguration__c(Row_Limit__c=100);	
        }
        else {
        	settings = POSAPIConfiguration__c.getOrgDefaults();
        }
        Integer ROW_LIMIT = (Integer)settings.Row_Limit__c;
    	
    	if (UpdateTime==null) {
    		res.StatusCode = 400;
    		res.addHeader('Error','UpdateTime is a required field');
    		
			return null;
    	}
    	
		
    	String soql = 'Select i.Status__c, i.Ship_To__c, i.Quantity__c, i.Name, i.Item__c, i.Id, i.WBS__c, i.Company_Code__c, ' +
			'Custom_Attribute_Value__c, Item_Customization__r.Name, Cart__r.Name, Cart__r.Status__c, Cart__r.Shopper__c, Cart__r.Order_Window__c, '+
			'Cart__r.Order_Window__r.Status__c, Cart__r.Order_Window__r.Name, '+
			'i.Carrier__c, i.Tracking_Code__c From Cart_Item__c i where Quantity__c>0 and (SystemModstamp > '+UpdateTime+' OR Cart__r.SystemModstamp > '+ UpdateTime +')';
			
			
    	if (WindowId!=null) {
    		soql = soql + ' AND Cart__r.Order_Window__c = \''+WindowId+'\' ';
    	}
    	if (CartId!=null) {
    		soql = soql + ' AND Cart__c= \''+CartId+'\'';
    	}
    	
    	//To avoid erroring out we limit the total results to 50K
    	soql = soql + ' limit 50000';
    	
    	
    	/*if (Offset!=null) {
    		soql = soql + ' offset '+Offset;
    	}else {
    		Offset = 0; //Set this to zero going forward
    	}*/
    	
    	System.debug('Query: '+soql);
    	
    	integer index=0;
    	
    	List<Cart_Item__c> cartsReturned = new List<Cart_Item__c>();
    	
    	APICartResponse apiResponse = new APICartResponse();
    	
    	for (Cart_Item__c cartItem:Database.query(soql)) {
    		
    		if (index<offset) {
    			index++;
    			continue;
    		}
    		index++;
    		
    		cartsReturned.add(cartItem);
    		
    		if (index==offset+ROW_LIMIT) {
    			apiResponse.moreResults=true;
    			break;
    		}
    	}
    	
    	
        apiResponse.lastRowIndex = Offset+cartsReturned.size();
    	apiResponse.carts=cartsReturned;
    	if (Offset+cartsReturned.size()==50000) {
    		//limit reached, so flag it
    		apiResponse.maxResults=true;
    	}
    	else {
    		apiResponse.maxResults=false;
    	}


    	return apiResponse;
     }
    
    
    global class APICartResponse {

        global List <Cart_Item__c> carts { get; set; }
        global Integer lastRowIndex {get; set;}
        global Boolean moreResults {get;set;}
        global Boolean maxResults {get;set;}

    } 
    
    
    /**
    	Just test the basic request to get the list based on update time
    */ 
    //@IsTest
    public static void testGetCartItems () {
    	
    	//Get the current time
    	Datetime now = System.now();
    	
    	Profile p = [select id from profile where name='System Administrator'];
         
		User u = new User(alias = 'posmmtst', email='posmmunittest@diageo.com',
        emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US',
		localesidkey='en_US', profileid = p.Id,
		timezonesidkey='America/Chicago', username='posmmunittest@diageo.com');
		
		System.runAs(u) {
			
			POS_TestDataUtil.initializeTestData();
    	
    		//Create Agency
    		Account agency = POS_TestDataUtil.createProductionAgency();
	    	
	    	Program__c program = POS_TestDataUtil.createProgram();
	    	Item__c item = POS_TestDataUtil.populateItem(program, agency);
	    	insert item;
	    	
	    	Order_Window__c ow = POS_TestDataUtil.createOrderWindow();
	    	Cart__c crt = POS_TestDataUtil.createCart(u, ow);
	    	
	    	Cart_Item__c ci = POS_TestDataUtil.populateCartItem(item, crt);
	    	insert ci;
	    	
	    	//APICartResponse response1 = POS_APIGetCartItems.doPost(null, null);
	    	//System.assertEquals(null, response1);
	    	
	    	APICartResponse response = POS_APIGetCartItems2.doPost(now.format('yyyy-MM-dd\'T\'HH:mm:ss\'Z\''), null, null, null);
	    	
	    	//Should only see the one record
	    	System.assert(response.carts.size()==1);
	    	System.assert(response.lastRowIndex==1);
	    	System.assert(response.moreResults==false);
	    	
	    	// add another cart Item
			Cart_Item__c ci2 = POS_TestDataUtil.populateCartItem(item, crt);
	    	insert ci2;	 
	    	
	        response = POS_APIGetCartItems2.doPost(now.format('yyyy-MM-dd\'T\'HH:mm:ss\'Z\''), null, null, null);
	    	
	    	//Should see 2 CartItem records 
	    	System.assert(response.carts.size()==2);
	    	System.assertEquals(1, response.lastRowIndex);
	    	System.assert(response.moreResults==false);	    	   	
	    	
	    	//Update the time and try again so that record doesn't appear
	    	now=now.addDays(1);
	    	response = POS_APIGetCartItems2.doPost(now.format('yyyy-MM-dd\'T\'HH:mm:ss\'Z\''),0, null, null);
	    	System.assert(response.carts.size()==0);
	    	System.assert(response.lastRowIndex==0);
	    	System.assert(response.moreResults==false);
	    	
	    	//Now test queries for offset filter, set the offset so we get one again
	    	response = POS_APIGetCartItems2.doPost(now.format('yyyy-MM-dd\'T\'HH:mm:ss\'Z\''),1, null, null);
	    	System.assert(response.carts.size()==0);
	    	System.assert(response.lastRowIndex==1);
	    	System.assert(response.moreResults==false);
	    	
	    	//Now create enough items to hit row limit and make sure that the pagination works
	    	Cart__c crt2 = POS_TestDataUtil.createCart(u, ow);
	    	
	    	List<Cart_Item__c> testCItems = new List<Cart_Item__c>();
	    	integer citemCount=0;
	    	integer ROW_LIMIT=25;
	    	while (true) {
	    		if (citemCount==ROW_LIMIT) {
	    			break;
	    		}
	    		citemCount++;

		    	Cart_Item__c citem = POS_TestDataUtil.populateCartItem(item, crt2);
		    	
	    		testCItems.add(citem);
	    	}
	 
	    	
	    	insert testCItems;
	    	
	    	now = System.now();
	    	response = POS_APIGetCartItems2.doPost(now.format('yyyy-MM-dd\'T\'HH:mm:ss\'Z\''), 0, null, null);
	    	System.assertEquals(ROW_LIMIT, response.carts.size());
	    	System.assert(response.lastRowIndex==2);
	    	System.assert(response.moreResults==false);
	    	
	    	//Now test for the order window
	    	response = POS_APIGetCartItems2.doPost(now.format('yyyy-MM-dd\'T\'HH:mm:ss\'Z\''), 0, ow.Id, null);
	    	System.assertEquals(ROW_LIMIT, response.carts.size());
	    	System.assert(response.lastRowIndex==2);
	    	System.assert(response.moreResults==false);
	    	
	    	//Make sure a bad window id gets no results
	    	Order_Window__c ow2 = POS_TestDataUtil.createOrderWindow();
	    	response = POS_APIGetCartItems2.doPost(now.format('yyyy-MM-dd\'T\'HH:mm:ss\'Z\''), 0, ow2.Id, null);
	    	System.assert(response.carts.size()==0);
		}
		
		
    	
    }	
    
 
}