TestRepo2/src/objects/Cart__c.object
<CustomObject>
    <description>POS Project: object that represents a shopping cart</description>
    <fields>
        <fullName>Order_Window__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Window</label>
        <referenceTo>Order_Window__c</referenceTo>
        <relationshipLabel>Carts</relationshipLabel>
        <relationshipName>Carts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Processing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Removed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Cart</label>
    <nameField>
        <displayFormat>CRT-{00000000}</displayFormat>
        <label>Cart ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Carts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/Cart_Item__c.object
<CustomObject>
    <description>POS Project: junction object that represents the many-to-many relationship between Carts and Items</description>
    <fields>
        <fullName>Carrier__c</fullName>
        <label>Carrier</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cart__c</fullName>
        <label>Cart</label>
        <referenceTo>Cart__c</referenceTo>
        <relationshipLabel>Cart Items</relationshipLabel>
        <relationshipName>Carts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Item__c</fullName>
        <label>Item</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>Cart Items</relationshipLabel>
        <relationshipName>Cart_Items</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Selected</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Processing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shipped</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Tracking_Code__c</fullName>
        <label>Tracking Code</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Cart Item</label>
    <nameField>
        <displayFormat>CIT-{0000000000}</displayFormat>
        <label>Cart Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cart Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestRepo2/src/objects/Item__c.object
<CustomObject>
    <description>POS Project: object that represents catalog items available for shopping</description>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Development</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Approved w/Est Price</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted w/Final Price</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Removed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

TestRepo2/src/objects/Order_Window__c.object
<CustomObject>
    <description>POS Project: object that represents a period of time in which catalog items are offered and shoppers are allowed to buy them</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <controllingField>Type__c</controllingField>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Budgeting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Archived</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Order Window</label>
    <nameField>
        <label>Order Window Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Windows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/POSAPIConfiguration__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <label>POS API Configuration</label>
</CustomObject>

TestRepo2/src/objects/Program__c.object
<CustomObject>
    <description>POS Project: object that represents a set of events for which related catalog items are offered to shoppers (distributors and internal Diageo employees)</description>
    <fields>
        <fullName>Order_Window__c</fullName>
        <label>Order Window</label>
        <referenceTo>Order_Window__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestRepo2/src/classes/POS_APIUpdateCartItems.cls
/**
 * @author      Model Metrics {Venkatesh Kamat}
 * @date        06/25/2012
 * @description Class exposing Update to Carts as REST Inbound service for Agency interface.
 */
 
@RestResource(urlMapping='/UpdateCartItems/*')
global with sharing class POS_APIUpdateCartItems {
	
	@HttpPost
    global static List<Cart_Item__c> doPost (List<Cart_Item__c> CartItems) {
    	RestRequest req = RestContext.request; 
        RestResponse res = RestContext.response;	
    	
    	if (cartItems==null || cartItems.size() == 0) {
    		res.StatusCode = 400;
    		res.addHeader('Error','CartItems list is a required field');
    		
			return null;
    	}
    	
		Map<Id, Cart_Item__c> cItmIdMap = new Map<Id, Cart_Item__c>();
    	for(Cart_Item__c cItm : cartItems) {
    		cItmIdMap.put(cItm.Id, cItm);
    	}
    	
    	List<Cart_Item__c> cartItemsForUpdate = [Select Id, Status__c, Tracking_Code__c, Carrier__c from Cart_Item__c where id in :cItmIdMap.keySet()];
    	
    	for(Cart_Item__c cItm : cartItemsForUpdate) {
    		if(cItmIdMap.get(cItm.id).Status__c != null) {
    			cItm.Status__c = cItmIdMap.get(cItm.id).Status__c;
    		}
    		if(cItmIdMap.get(cItm.id).Carrier__c != null) {
    			cItm.Carrier__c = cItmIdMap.get(cItm.id).Carrier__c;
    		}    		
    		if(cItmIdMap.get(cItm.id).Tracking_Code__c != null) {
    			cItm.Tracking_Code__c = cItmIdMap.get(cItm.id).Tracking_Code__c;
    		}
    		
    		System.debug('cItm.Tracking_Code__c - ' + cItmIdMap.get(cItm.id).Tracking_Code__c);
    	} 
    	
    	update(cartItemsForUpdate); 
    	System.debug('cartItemsForUpdate.size() - ' + cartItemsForUpdate.size());  	   	
 
		return cartItemsForUpdate;
    }   
    	
    	
   	@IsTest(SeeAllData=true)
    public static void testUpdateCartItem () {
    	
    	//Get the current time
    	Datetime now = System.now();
    	
    	Profile p = [select id from profile where name='POS - API User Agency'];
         
		User u = new User(alias = 'posmmtst', email='posmmunittest@diageo.com',
        emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US',
		localesidkey='en_US', profileid = p.Id,
		timezonesidkey='America/Chicago', username='posmmunittest@diageo.com');
		RecordType posAgencyRecordType = [select Id from RecordType where Name='POS Production Agency' and sObjectType='Account'];
		
		
		System.runAs(u) {
			POSAPIConfiguration__c settings = POSAPIConfiguration__c.getOrgDefaults();
    	
	    	Order_Window__c window = POS_TestDataUtil.createOrderWindow();
	    	window.Status__c='Open';
	   		update window;
	   		
	    	Program__c program = POS_TestDataUtil.createProgram();
	    	Account account = POS_TestDataUtil.createAccount();
	    	account.RecordTypeId = posAgencyRecordType.Id;
	    	update account;
	    
	    	Item__c item = POS_TestDataUtil.createItem(program);
	    	Cart__c cart = POS_TestDataUtil.createCart(u, window);
	    	Cart_Item__c cartItem = POS_TestDataUtil.populateCartItem(item, cart);
	    	insert cartItem;
	    	
	    	//Flag item as shipped so there's a change
	    	cartItem.Status__c = 'Shipped';
	    	cartItem.Carrier__c = 'Fedex';
	    	cartItem.Tracking_Code__c = 'TESTING123';
			
			List<Cart_Item__c> cartItems = new List<Cart_Item__c>();
			cartItems.add(cartItem);
			
	    	
	        POS_APIUpdateCartItems.doPost(cartItems);
	        
	        Id cartItemId=cartItem.Id;
	        
	        //Now load the item and see if it changed
	        Cart_Item__c loaded = [select Id, Status__C from Cart_Item__c where Id=:cartItemId];
	        System.assert(loaded.Status__c == 'Shipped');
    	
		}
    }

}