TestRepo2/src/objects/Cart__c.object
<CustomObject>
    <description>POS Project: object that represents a shopping cart</description>
    <fields>
        <fullName>Order_Window__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Window</label>
        <referenceTo>Order_Window__c</referenceTo>
        <relationshipLabel>Carts</relationshipLabel>
        <relationshipName>Carts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Cart</label>
    <nameField>
        <displayFormat>CRT-{00000000}</displayFormat>
        <label>Cart ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Carts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/Cart_Item__c.object
<CustomObject>
    <description>POS Project: junction object that represents the many-to-many relationship between Carts and Items</description>
    <fields>
        <fullName>Cart__c</fullName>
        <label>Cart</label>
        <referenceTo>Cart__c</referenceTo>
        <relationshipLabel>Cart Items</relationshipLabel>
        <relationshipName>Carts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Item__c</fullName>
        <label>Item</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>Cart Items</relationshipLabel>
        <relationshipName>Cart_Items</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Packout_Quantity__c</fullName>
        <formula>Item__r.Packout_Quantity__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Packout Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Ship_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To</label>
        <referenceTo>Ship_To__c</referenceTo>
        <relationshipLabel>Cart Items</relationshipLabel>
        <relationshipName>Cart_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Cart Item</label>
    <nameField>
        <displayFormat>CIT-{0000000000}</displayFormat>
        <label>Cart Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cart Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestRepo2/src/objects/Item__c.object
<CustomObject>
    <description>POS Project: object that represents catalog items available for shopping</description>
    <fields>
        <fullName>Packout_Quantity__c</fullName>
        <label>Packout Quantity</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

TestRepo2/src/objects/Order_Window__c.object
<CustomObject>
    <description>POS Project: object that represents a period of time in which catalog items are offered and shoppers are allowed to buy them</description>
    <label>Order Window</label>
    <nameField>
        <label>Order Window Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Windows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/Program__c.object
<CustomObject>
    <description>POS Project: object that represents a set of events for which related catalog items are offered to shoppers (distributors and internal Diageo employees)</description>
    <fields>
        <fullName>Order_Window__c</fullName>
        <label>Order Window</label>
        <referenceTo>Order_Window__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestRepo2/src/objects/Ship_To__c.object
<CustomObject>
    <description>POS Project: object that represents a delivery address associated to a particular account</description>
    <label>Ship To</label>
    <nameField>
        <label>Ship To Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ship To&apos;s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestRepo2/src/classes/POS_BatchUpdateShiptos.cls
/*
This class updates the various shipto records when a specific shipto is edited or removed
*/
global class POS_BatchUpdateShiptos implements Database.Batchable<sObject> {
    private integer operation;
    private Ship_To__c originalShipTo;
    private Ship_To__c replacementShipTo;
    
    
    public static String query = 'select Id, Ship_To__c, Item__c from Cart_Item__c ';
    
    public POS_BatchUpdateShiptos (Ship_To__c originalShipTo, Ship_To__c replacementShipTo) {
        this.originalShipTo=originalShipTo;
        this.replacementShipTo = replacementShipTo;
    }
    
    global database.queryLocator start(Database.BatchableContext BC) 
    {
        String filteredQuery = query+' where Ship_To__c=\''+originalShipTo.Id+'\'';
        
        System.debug('QUERY: '+query);
        return database.getQueryLocator(filteredQuery);
    }
    
    global void execute(Database.BatchableContext BC, List<Cart_Item__c> cartItems){
        System.debug('Updating: '+cartItems);
        for (Cart_Item__c cartItem:cartItems) {
            cartItem.Ship_To__c = replacementShipTo.Id;
        }
        
        update cartItems;
    }

    global void finish(Database.BatchableContext BC) {
        
    }
    
    @isTest 
    public static void testReplaceShipToId () {
        Order_Window__c ow = POS_TestDataUtil.createOrderWindow();
        Program__c program = POS_TestDataUtil.createProgram(ow.Id);
        Item__c item = POS_TestDataUtil.createItem(program);
        User shopper = [Select Id,Name FROM User WHERE Id =:UserInfo.getUserId()];//POS_TestDataUtil.createStdUser();
        Cart__c cart = POS_TestDataUtil.createCart(shopper, ow);
        
        Ship_To__c shipTo = POS_TestDataUtil.createShipTo();
        
        Cart_Item__c cartItem = new Cart_Item__c();
        cartItem.Item__c=item.Id;
        cartItem.Cart__c=cart.Id;
        cartItem.Quantity__c=item.Packout_Quantity__c;
        cartItem.Ship_To__c=shipTo.Id;
        insert cartItem;
        
        Ship_To__c shipTo2 = POS_TestDataUtil.createShipTo();
        
        Test.startTest();
        POS_BatchUpdateShiptos batch = new POS_BatchUpdateShiptos(shipTo,shipTo2);
        Database.executeBatch(batch);
        Test.stopTest();
        
        Cart_Item__c cartItemLoaded = [select Ship_To__c from Cart_Item__c where Id=:cartItem.Id];
        System.debug('LOADED: '+cartItemLoaded);
        System.assert(cartItemLoaded.Ship_To__c==shipTo2.Id);
        
        
    }
}