TestRepo2/src/objects/Cart__c.object
<CustomObject>
    <description>POS Project: object that represents a shopping cart</description>
    <fields>
        <fullName>Last_Submitted__c</fullName>
        <label>Last Submitted</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Magento_ID__c</fullName>
        <externalId>true</externalId>
        <label>Magento ID</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Window__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Window</label>
        <referenceTo>Order_Window__c</referenceTo>
        <relationshipLabel>Carts</relationshipLabel>
        <relationshipName>Carts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shopper__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shopper</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Carts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Processing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Removed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Cart</label>
    <nameField>
        <displayFormat>CRT-{00000000}</displayFormat>
        <label>Cart ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Carts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/Order_Window__c.object
<CustomObject>
    <description>POS Project: object that represents a period of time in which catalog items are offered and shoppers are allowed to buy them</description>
    <fields>
        <fullName>Fiscal_Year__c</fullName>
        <label>Fiscal Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Icon_Label__c</fullName>
        <label>Icon Label</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Magento_Id__c</fullName>
        <externalId>true</externalId>
        <label>Magento Category Id</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>On_Demand_Site_URL__c</fullName>
        <label>On Demand Site URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Order_Close_Date__c</fullName>
        <label>Order Close Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Order_Delivery_Date__c</fullName>
        <label>Order Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Order_Start_Date__c</fullName>
        <label>Order Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <controllingField>Type__c</controllingField>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Budgeting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Archived</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Quarterly</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Demand</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Order Window</label>
    <nameField>
        <label>Order Window Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Windows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/Order_Window_Customer__c.object
<CustomObject>
    <description>POS Project: junction object that represents the many-to-many relationship between Order Windows and Users (customers)</description>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Order_Window_Customers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Magento_Id__c</fullName>
        <externalId>true</externalId>
        <label>Magento Id</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Open_For_Shopping__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Open for Shopping</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Order_Window__c</fullName>
        <label>Order Window</label>
        <referenceTo>Order_Window__c</referenceTo>
        <relationshipLabel>Order Window Customers</relationshipLabel>
        <relationshipName>Order_Window_Customers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Order Window Customer</label>
    <nameField>
        <displayFormat>OWC-{000000}</displayFormat>
        <label>Order Window Customer ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Window Customers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestRepo2/src/objects/POS_Magento_Configuration__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>stores all values like API key, User Name, Endpoint etc. required for Magento Integration service</description>
    <fields>
        <fullName>IDP_Url__c</fullName>
        <description>The URL to the Salesforce IDP initiated SSO</description>
        <label>IDP Url</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Magento_Catalog_Path__c</fullName>
        <label>Magento_Catalog_Path</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>POS Magento Configuration</label>
</CustomObject>

TestRepo2/src/objects/Program__c.object
<CustomObject>
    <description>POS Project: object that represents a set of events for which related catalog items are offered to shoppers (distributors and internal Diageo employees)</description>
    <fields>
        <fullName>Magento_Id__c</fullName>
        <externalId>true</externalId>
        <label>Magento Category Id</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Window__c</fullName>
        <label>Order Window</label>
        <referenceTo>Order_Window__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestRepo2/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Magento_Id__c</fullName>
        <externalId>true</externalId>
        <label>Magento_Id</label>
        <length>80</length>
        <type>Text</type>
    </fields>
</CustomObject>

TestRepo2/src/classes/POS_OrderTimelineController.cls
public class POS_OrderTimelineController extends Controller_Base {

	
	private Id currentUser {get;set;}
	public String baseUrl {get;set;}
	public String idpUrl {get;set;}
	
	public integer selectedYear {get;set;}
	private DateTime selectedDateTime {get;set;}
	
	public List <Order_Window_Customer__c> orderWindowCustomers {get;set;}
	public List<POS_BreadCrumb> breadCrumbs {get;set;}
	public Map<Id,List<Program__c>> programs {get;set;}
	
	public List<CalendarDisplay> calendarDisplays {get;set;}
	public List<POS_OrderWindowRow> orderWindowRows {get;set;}
	
	public Map <Id,Cart__c> carts {get;set;}
	
	public POS_OrderTimelineController () {
		
		
		
		currentUser = UserInfo.getUserId();
		
		if (selectedYear==null) {
			selectedDateTime = System.now();
			selectedYear = selectedDateTime.year();
		}
		
		loadOrderWindows();
		
		POS_Magento_Configuration__c settings = POS_Magento_Configuration__c.getOrgDefaults();
       	baseUrl = settings.Magento_Catalog_Path__c;
       	idpUrl = settings.IDP_Url__c;
       	
       	loadOrderWindows();
       	
       	loadCalendarDisplays();
       	
       	breadCrumbs = new List<POS_BreadCrumb>();
       	breadCrumbs.add(new POS_BreadCrumb('POS','POS_OrderWindowView'));
       	breadCrumbs.add(new POS_BreadCrumb('Budgeting and Ordering Timeline','#'));
		
	}
	
	private void loadCalendarDisplays () {
		calendarDisplays = new List<CalendarDisplay>();
		Date month = Date.newInstance(selectedYear,1,1);
		for (integer x=0;x<12;x++) { 
			CalendarDisplay display = new CalendarDisplay();
			display.month=month;
			calendarDisplays.add(display);
			month = month.addMonths(1);
		}
		
		//Add order windows to the months
		orderWindowRows = new List<POS_OrderWindowRow>();
		for (Order_Window_Customer__c owc:orderWindowCustomers) {
			POS_OrderWindowRow row = new POS_OrderWindowRow(owc.Order_Window__r);
			orderWindowRows.add(row);
		}
		orderWindowRows.sort();
	}


	private void loadOrderWindows () {
		Date beginningOfYear = Date.newInstance(selectedYear,1,1);
		Date endOfYear = Date.newInstance(selectedYear,12,31);
		
		orderWindowCustomers = [Select Open_For_Shopping__c, o.Order_Window__r.Name, o.Order_Window__r.Type__c, 
		 o.Order_Window__r.Status__c, o.Order_Window__r.Order_Start_Date__c, 
		 o.Order_Window__r.Order_Delivery_Date__c, o.Order_Window__r.Order_Close_Date__c, 
		 o.Order_Window__r.On_Demand_Site_URL__c, o.Order_Window__r.Magento_Id__c, o.Order_Window__r.Fiscal_Year__c,
		 o.Order_Window__r.Icon_Label__c from Order_Window_Customer__c o
		 where Customer__c = :currentUser and o.Order_Window__r.Status__c in ('Open','Budgeting','Closed', 'In Review') 
		 and o.Order_Window__r.Order_Start_Date__c >= :beginningOfYear
		 and o.Order_Window__r.Order_Start_Date__c <= :endOfYear
		 order by o.Order_Window__r.Order_Start_Date__c DESC
		]; 
		
		carts = new Map<Id,Cart__c>();
		
		
		List<Cart__c> cartList = [Select c.Status__c, c.Last_Submitted__c, c.Order_Window__c, c.Id From Cart__c c where c.Shopper__c = :currentUser ];
		for (Cart__c cart:cartList) {
			if (cart.Order_Window__c != null) {
				carts.put(cart.Order_Window__c,cart);
			}
		}
	
		
		
		List<Id> windowIds = new List<Id>();
		programs = new Map<Id,List<Program__c>>();
		
		//Build a map of related programs to display their details in a hover
		for (Order_Window_Customer__c owc:orderWindowCustomers) {
			if (owc.Order_Window__r.Type__c == 'Monthly') {
				windowIds.add(owc.Order_Window__c);
			}
			programs.put(owc.Order_Window__c,new List<Program__c>());
			
			//Make sure that any windows that didn't have carts don't break the UI with nulls
			if (carts.get(owc.Order_Window__c)==null) {
				carts.put(owc.Order_Window__c,new Cart__c());
			}
		}
		
		
		List<Program__c> programList = [Select Order_Window__c, Name from Program__c where Order_Window__c in :windowIds];
		for (Program__c program:programList) {
			List<Program__c> programListFromMap = programs.get(program.Order_Window__c);
			programListFromMap.add(program);
		}
		
		System.debug('Programs: '+programs);
		
		System.debug('Order window customers: '+orderWindowCustomers);
	}
	
	public PageReference previousYear () {
		selectedDateTime = selectedDateTime.addYears(-1);
		selectedYear = selectedDateTime.year();
		loadOrderWindows();	
		loadCalendarDisplays();
		
		return null;
	}
	
	public PageReference nextYear () {
		selectedDateTime = selectedDateTime.addYears(1);
		selectedYear = selectedDateTime.year();
		loadOrderWindows();
		loadCalendarDisplays();
		
		return null;
	}
	
	public class CalendarDisplay {
		//public List<OrderWindowRow> orderWindows {get;set;}
		public Date month {get;set;}
		
	}
	
	
	
	@isTest
	public static void testOrderTimeline () {
		Profile p = [select id from profile where name='System Administrator'];
         
		User u = new User(alias = 'posmmtst', email='posmmunittest@diageo.com',
        emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US',
		localesidkey='en_US', profileid = p.Id,
		timezonesidkey='America/Chicago', username='posmmunittest@diageo.com');
		
		System.runAs(u) {
			PageReference pageRef = Page.HomePage;
        	Test.setCurrentPage(pageRef);
        	
			Order_Window__c ow = POS_TestDataUtil.createOrderWindow();
			
			Order_Window_Customer__c owc = new Order_Window_Customer__c();
			owc.Customer__c = u.Id;
			owc.Order_Window__c = ow.Id;
			insert owc;
			
			Cart__c cart = POS_TestDataUtil.createCart(u, ow);
			cart.Status__c = 'Submitted';
			update cart;
			
			POS_OrderTimelineController controller = new POS_OrderTimelineController();
			System.assert(controller.orderWindowCustomers.size()==1);
			
		}
	}
	
	// for HTML conditional comments    
    public String getLt(){
		return '<';
	}
		
	public String getGt(){
		return '>';
	}	
	
}