TestRepo2/src/objects/Content_Description__c.object
<CustomObject>
    <fields>
        <fullName>Classification__c</fullName>
        <label>Classification</label>
        <picklist>
            <picklistValues>
                <fullName>Spirits</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Wine</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Content_ID__c</fullName>
        <label>Content ID</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Content_Version_Id__c</fullName>
        <label>Content Version Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>filesize__c</fullName>
        <description>Size of file</description>
        <inlineHelpText>Size of file</inlineHelpText>
        <label>filesize</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>filetype__c</fullName>
        <label>filetype</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Content Description</label>
    <nameField>
        <label>Content Description Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Content Descriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/ContentVersion.object
<CustomObject>
    <fields>
        <fullName>Classification__c</fullName>
        <label>Classification</label>
        <picklist>
            <picklistValues>
                <fullName>Spirits</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wine</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Content_Description__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Content Description</label>
        <referenceTo>Content_Description__c</referenceTo>
        <relationshipLabel>Content</relationshipLabel>
        <relationshipName>Content</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>File__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>File</label>
        <referenceTo>File__c</referenceTo>
        <relationshipLabel>Content</relationshipLabel>
        <relationshipName>Content</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Collaboration</fullName>
        <active>true</active>
        <label>Collaboration</label>
    </recordTypes>
</CustomObject>

TestRepo2/src/objects/File__c.object
<CustomObject>
    <description>File store information about files inside folders</description>
    <fields>
        <fullName>Available_Until__c</fullName>
        <label>Available Until</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Classification__c</fullName>
        <label>Classification</label>
        <picklist>
            <picklistValues>
                <fullName>Spirits</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Wine</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Content_ID__c</fullName>
        <label>Content ID</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Content_Version_Id__c</fullName>
        <label>Content Version Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Distributor_Names__c</fullName>
        <description>Names of selected distributors.</description>
        <label>Distributors</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Distributors__c</fullName>
        <label>Distributor IDs</label>
        <picklist>
            <picklistValues>
                <fullName>a</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>b</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>c</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Folders__c</fullName>
        <label>Folder IDs</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>17</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>18</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>19</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>21</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>22</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>23</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>24</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>25</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>26</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>27</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>28</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>29</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>OrgUnitsNames__c</fullName>
        <label>Organizational Units</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>OrgUnits__c</fullName>
        <label>OrgUnit Id</label>
        <picklist>
            <picklistValues>
                <fullName>OrgUnit</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Page_Section__c</fullName>
        <label>Page Section</label>
        <picklist>
            <picklistValues>
                <fullName>Planning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Performance Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Collaboration</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>filesize__c</fullName>
        <label>filesize</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>filetype__c</fullName>
        <label>filetype</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>File</label>
    <nameField>
        <displayFormat>file-{0000000}</displayFormat>
        <label>File Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Files</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/Folder__c.object
<CustomObject>
    <fields>
        <fullName>Classification__c</fullName>
        <label>Classification</label>
        <picklist>
            <picklistValues>
                <fullName>Spirits</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wine</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Distributor_Names__c</fullName>
        <label>Distributors</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Distributors__c</fullName>
        <label>Distributor IDs</label>
        <picklist>
            <picklistValues>
                <fullName>Distributor</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>OrgUnitsNames__c</fullName>
        <label>Organizational Units</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>OrgUnits__c</fullName>
        <label>OrgUnit Id</label>
        <picklist>
            <picklistValues>
                <fullName>OrgUnits</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Page_Section__c</fullName>
        <label>Page Section</label>
        <picklist>
            <picklistValues>
                <fullName>Planning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Performance Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Collaboration</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Folder</label>
    <nameField>
        <label>Folder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Folders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/Folder_Comment__c.object
<CustomObject>
    <fields>
        <fullName>Classification__c</fullName>
        <label>Classification</label>
        <picklist>
            <picklistValues>
                <fullName>Spirits</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wine</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Comment_Body__c</fullName>
        <label>Comment Body</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Distributor_Access__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Distributor Access</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Folder Comments (Distributor Access)</relationshipLabel>
        <relationshipName>Folder_Comments1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Distributor_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Distributor Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Folder Comments</relationshipLabel>
        <relationshipName>Folder_Comments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>File__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>File</label>
        <referenceTo>File__c</referenceTo>
        <relationshipLabel>Folder Comments</relationshipLabel>
        <relationshipName>Folder_Comments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Folder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Folder</label>
        <referenceTo>Folder__c</referenceTo>
        <relationshipLabel>Folder Comments</relationshipLabel>
        <relationshipName>Folder_Comments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Folder Comment</label>
    <nameField>
        <label>Comment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Folder Comments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/classes/Service_EditFile.cls
/*****************************************************************************************************************
Name        : Service_EditFile.cls

Updated By  : Jonathan Freese (Appirio)   
Date        : 6/19/13
Story/Task  : US604/TA1000

Updated By  : Basant Verma (AppirioOffShore)   
Date        : 6/20/13
Story/Task  : (after the pop up window closes, 
							User should remain on the same page they were already on 
							when they started to edit)

*******************************************************************************************************************/

public without sharing class Service_EditFile {
	
	public ContentVersion file {get;set;}
	public String availableUntil {get;set;}
	public Id folderId {get;set;}
    public Id distributorId {get;set;}
    public String distributorName {get;set;}
    public Id organizationalHierarchyId {get;set;}
	public String organizationalHierarchyName {get; set;}
	public String afterUploadRedirectTo {get;set;}
	public String commentBody {get;set;}
	
	public String description {get;set{
			description = value;
			file.Description = value;
		}
	}
	public String pathOnClient {get;set;}
	public String folderName {get;set;} 
	private Boolean commentExists;
	private Folder_Comment__c fcomment;
	
	private Boolean fileIdSetted = false;
	public Boolean allowComments = true;
	
	
    public Service_EditFile() {
        distributorName = '';
    }

	public Id fileId{
		get;
		set{
			if(fileIdSetted)
				return;
			fileIdSetted = true;
			this.file = new ContentVersion(id = value);
			this.fileId = value;
			try{
				file = [select Title, Description, File__r.Available_Until__c, File__c, Id, Content_Description__c, ContentDocumentId from ContentVersion where id = :value limit 1];
				availableUntil = String.valueof(file.File__r.Available_Until__c);
				description = file.Description;
			} catch(Exception ex) {}
			if(value == null){
				fileIdSetted = false;
			}
		}
	}
	
	public PageReference saveFile(){
		try{
			file.description = description;
			update file;
			if(allowComments && commentBody != ''){
				fcomment = new Folder_Comment__c();
				fcomment.Comment_Body__c = commentBody;
				fcomment.Distributor_Name__c = Service_API.getAID();
				fcomment.Distributor_Access__c = DistributorId;
				fcomment.folder__c = folderId;
				fcomment.file__c = file.File__c;
				fcomment.Classification__c = Service_API.getSectionTheme();
				insert fcomment;
			} else if(!allowComments && commentBody != ''){
				ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR, 'Cannot add comments on search page.'));
			}
		} catch(Exception ex){
			ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR, 'Unable to save changes.'));
			clear();
			return null;
		}
		return clear();
	}
	
	
	public PageReference replaceFile(){
		try{
			if(file.PathOnClient == null) {
	        	ApexPages.addMessage( new ApexPages.Message( ApexPages.Severity.ERROR, 'Too large file'));
	            return null;
	    	} else {
	    		ContentWorkspace CW = [SELECT DefaultRecordTypeId, Id FROM ContentWorkspace WHERE Name='Collaboration'];
	    		// Start : Changes for TA1000 - Jonathan Freese
	    		ContentVersion cv = new ContentVersion(File__c = file.File__c, RecordTypeId = CW.DefaultRecordTypeId, Title = file.PathOnClient, ReasonForChange = 'replace (' + description + ')', description = description, ContentDocumentID = file.ContentDocumentID, PathOnClient = file.PathOnClient, VersionData = file.VersionData);
	    		// End : Changes for TA1000 - Jonathan Freese
	    		insert cv;
	    		if(organizationalHierarchyId==null || DistributorId==null || folderId==null){
	    			File__c f = new File__c(id 					  			= file.File__c,
	                    					Content_Version_Id__c 			= cv.id,
	                    					Content_ID__c  		  			= cv.ContentDocumentId,
	                    					title__c 			 			= cv.Title,
	                    					filetype__c           			= cv.filetype,
	                    					filesize__c          			= TriggerContentVersion.convertFileSize(file.contentSize),
	                						Page_Section__c     		 	= 'Collaboration');
	    			update f;
	    		} else {
		    		File__c f = new File__c(folders__c            			= folderId,
							                OrgUnits__c           			= organizationalHierarchyId,
							                OrgUnitsNames__c      			= organizationalHierarchyName,
						                    Distributors__c       			= DistributorId,
	                						Distributor_Names__c 			= distributorName,
	                    					id 					  			= file.File__c,
	                    					Content_Version_Id__c 			= cv.id,
	                    					Content_ID__c  		  			= cv.ContentDocumentId,
	                    					title__c 			 			= cv.Title,
	                    					filetype__c           			= cv.filetype,
	                    					filesize__c          			= TriggerContentVersion.convertFileSize(file.contentSize),
	                						Page_Section__c      			= 'Collaboration');
		    		update f;
	    		}
	    		cv.description = description;
	    		update cv;
	    		if(allowComments && commentBody != ''){
					fcomment = new Folder_Comment__c();
					fcomment.Comment_Body__c = commentBody;
					fcomment.Distributor_Name__c = Service_API.getAID();
					fcomment.Distributor_Access__c = DistributorId;
					fcomment.folder__c = folderId;
					fcomment.file__c = cv.File__c;
					insert fcomment;
				} else if(!allowComments && commentBody != ''){
					ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR, 'Cannot add comments on search page.'));
				}
			}
		} catch(Exception ex){
			ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR, 'Unable to save changes.'));
			clear();
			return null;
		}
		return clear();
	}
	
	public PageReference clear(){
		fileIdSetted = false;
		// Start : Changes - Basant Verma (after the pop up window closes, User should remain on the same page they were already on when they started to edit)
		PageReference pr = ApexPages.currentPage();
		if(afterUploadRedirectTo != null && !afterUploadRedirectTo.trim().equals(''))
			pr = new Pagereference(afterUploadRedirectTo);
		// End : Changes - Basant Verma
		pr.setRedirect(true);
		return pr;
	}
	
	public PageReference deleteFile(){
		try{
			List<Folder_Comment__c> fc = [select Id from Folder_Comment__c where file__c = :file.File__c];
			delete fc;
			ContentDocument cd = [select Id from ContentDocument where Id = :file.ContentDocumentId];
			List<File__c> f = [select Id from File__c where Content_Version_Id__c = :file.id];
			delete cd;
			delete f;
		} catch(Exception ex){
			ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR, 'Unable to delete file.'));
			clear();
			return null;
		}
		return clear();
	}
}