TestRepo2/src/objects/Content_Description__c.object
<CustomObject>
    <fields>
        <fullName>Classification__c</fullName>
        <label>Classification</label>
        <picklist>
            <picklistValues>
                <fullName>Spirits</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Wine</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Content_ID_Low__c</fullName>
        <label>Content ID Low</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Content_ID__c</fullName>
        <label>Content ID</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Content_Version_Id_Low__c</fullName>
        <label>Content Version Id Low</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Content_Version_Id__c</fullName>
        <label>Content Version Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Image_Resolution__c</fullName>
        <label>Image Resolution</label>
        <picklist>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Matrix_type__c</fullName>
        <label>Matrix type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Portfolio__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Portfolio</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RTS__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Ready to Serve</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TBA__c</fullName>
        <defaultValue>false</defaultValue>
        <label>TBA</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Tags__c</fullName>
        <label>Tags</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Uploaded_date__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Uploaded date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>filesize__c</fullName>
        <description>Size of file</description>
        <inlineHelpText>Size of file</inlineHelpText>
        <label>filesize</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>filesize_low__c</fullName>
        <description>Size of low quality file</description>
        <inlineHelpText>Size of low quality file</inlineHelpText>
        <label>filesize_low</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>filetype__c</fullName>
        <label>filetype</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Content Description</label>
    <nameField>
        <label>Content Description Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Content Descriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/ContentVersion.object
<CustomObject>
    <fields>
        <fullName>Classification__c</fullName>
        <label>Classification</label>
        <picklist>
            <picklistValues>
                <fullName>Spirits</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wine</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Content_Description__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Content Description</label>
        <referenceTo>Content_Description__c</referenceTo>
        <relationshipLabel>Content</relationshipLabel>
        <relationshipName>Content</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>File__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>File</label>
        <referenceTo>File__c</referenceTo>
        <relationshipLabel>Content</relationshipLabel>
        <relationshipName>Content</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>High_Resolution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>High Resolution</label>
        <referenceTo>Content_Description__c</referenceTo>
        <relationshipLabel>Content (High Resolution)</relationshipLabel>
        <relationshipName>Content1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Image_Resolution__c</fullName>
        <label>Image Resolution</label>
        <picklist>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Matrix_type__c</fullName>
        <label>Matrix Type</label>
        <picklist>
            <picklistValues>
                <fullName>Program Execution Brief</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Portfolio__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Portfolio</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RTS__c</fullName>
        <defaultValue>false</defaultValue>
        <label>RTS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TBA__c</fullName>
        <defaultValue>false</defaultValue>
        <label>TBA</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Collaboration</fullName>
        <active>true</active>
        <label>Collaboration</label>
    </recordTypes>
    <recordTypes>
        <fullName>Low_Resolution</fullName>
        <active>true</active>
        <label>Low Resolution</label>
    </recordTypes>
    <recordTypes>
        <fullName>Performance_Management</fullName>
        <active>true</active>
        <label>Performance Management</label>
    </recordTypes>
    <recordTypes>
        <fullName>Planning</fullName>
        <active>true</active>
        <label>Planning</label>
    </recordTypes>
</CustomObject>

TestRepo2/src/objects/File__c.object
<CustomObject>
    <description>File store information about files inside folders</description>
    <fields>
        <fullName>Classification__c</fullName>
        <label>Classification</label>
        <picklist>
            <picklistValues>
                <fullName>Spirits</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Wine</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Content_ID__c</fullName>
        <label>Content ID</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Content_Version_Id__c</fullName>
        <label>Content Version Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Image_Resolution__c</fullName>
        <label>Image Resolution</label>
        <picklist>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Page_Section__c</fullName>
        <label>Page Section</label>
        <picklist>
            <picklistValues>
                <fullName>Planning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Performance Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Collaboration</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Portfolio__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Portfolio</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RTS__c</fullName>
        <defaultValue>false</defaultValue>
        <label>RTS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Tags__c</fullName>
        <label>Tags</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Uploaded_date__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Uploaded date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>filesize__c</fullName>
        <label>filesize</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>filetype__c</fullName>
        <label>filetype</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>File</label>
    <nameField>
        <displayFormat>file-{0000000}</displayFormat>
        <label>File Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Files</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/classes/TriggerContentVersion.cls
public global class TriggerContentVersion {
    public static boolean disabled = false;
	public static void updateContentDescriptionAndFileOnBeforeUpdate(map<id, ContentVersion> ContentVersionMap) {
		if (disabled) {
			return;
		}
        List<Content_Description__c> contentDescriptionAddList    = new List<Content_Description__c>();
        List<Content_Description__c> contentDescriptionUpdateList = new List<Content_Description__c>();        
     
        Set<Id> contentDescriptionAddSet = new Set<Id>();
        List<file__c> fileAddList    = new List<file__c>();
        List<file__c> fileUpdateList = new List<file__c>();
        map<String, ContentVersion> helper = new map<String, ContentVersion>(); 
        recordtype[] rts = [SELECT id, DeveloperName FROM recordtype where DeveloperName in :new list<string>{'Low_Resolution', 'Performance_Management', 'Collaboration', 'Planning', 'Multicultural'} AND SobjectType = 'ContentVersion'];
        Id lowResolutionRecordTypeId,performanceManagementRecordTypeId,collaborationRecordTypeId,planningRecordTypeId,multiculturalRecordTypeId;
        for(recordtype rt : rts) {
        	if (rt.DeveloperName == 'Low_Resolution') {
                lowResolutionRecordTypeId = rt.Id;
            } else if (rt.DeveloperName =='Performance_Management') {
                performanceManagementRecordTypeId = rt.Id;
            } else if (rt.DeveloperName =='Collaboration') {
                collaborationRecordTypeId = rt.Id;
            } else if (rt.DeveloperName =='Planning') {
                planningRecordTypeId = rt.Id;
            } else if (rt.DeveloperName =='Multicultural') {
                multiculturalRecordTypeId = rt.Id;
            }
        }
        for(ContentVersion c : contentVersionMap.values()){
            helper.put(c.ContentDocumentId, c);
            if (c.RecordTypeId == lowResolutionRecordTypeId) {
                Content_Description__c cd = new Content_Description__c(
                    Id                        = c.High_Resolution__c,
                    Content_Version_Id_Low__c = c.Id,
                    Content_ID_Low__c         = c.ContentDocumentId
                );
                
                if((!contentDescriptionAddSet.contains(cd.Id)) && cd.Id != null){
                	contentDescriptionUpdateList.add(cd);
                	contentDescriptionAddSet.add(cd.Id);
                }
            	
            } else if (c.RecordTypeId == performanceManagementRecordTypeId || c.RecordTypeId == collaborationRecordTypeId || c.RecordTypeId == planningRecordTypeId) {
                if (c.file__c == null) {
                    string pageSection = '';
                    String fileClassification = '';
                    if (c.RecordTypeId == performanceManagementRecordTypeId) {
                        pageSection = 'Performance Management';
                        
                        // only one classification is allowed, get first selected
						if(c.classification__c != null && c.classification__c != ''){
    						list<string> thms = c.classification__c.split(';');
							for(String t : thms){
								if(t!='' && t!=null){
									fileClassification = t;
									break;
								}
							}
						}	 
                    } else if (c.RecordTypeId == collaborationRecordTypeId) {
                        pageSection = 'Collaboration';
                        // only one classification is allowed, get first selected
						if(c.classification__c != null && c.classification__c != ''){
    						list<string> thms = c.classification__c.split(';');
							for(String t : thms){
								if(t!='' && t!=null){
									fileClassification = t;
									break;
								}
							}
						}	    		
                    } else if (c.RecordTypeId == planningRecordTypeId) {
                        pageSection = 'Planning';
                        fileClassification = c.Classification__c;
                    }
                    file__c f = new file__c(
                        Title__c              = c.Title,
                        Description__c        = c.Description,
                        Content_Version_Id__c = c.Id,
                        Content_ID__c         = c.ContentDocumentId,
                        filetype__c           = c.filetype,
                        Page_Section__c       = pageSection,
                        Image_Resolution__c   = c.Image_Resolution__c,
                        Tags__c				  = c.TagCsv,
						Portfolio__c          = c.Portfolio__c,
                        RTS__c				  = c.RTS__c,
                        Uploaded_date__c	  = c.LastModifiedDate,
						Classification__c	  = fileClassification
                    );
                    fileAddList.add(f);
                } else {
                    file__c f = new file__c(
                        Id                    = c.file__c,
                        Title__c              = c.Title,
                        Description__c        = c.Description,
                        Content_Version_Id__c = c.Id,
                        Content_ID__c         = c.ContentDocumentId,
                        filetype__c           = c.filetype,
                        Image_Resolution__c   = c.Image_Resolution__c,
                        Tags__c				  = c.TagCsv,
						Portfolio__c          = c.Portfolio__c,
                        RTS__c				  = c.RTS__c,
                        Uploaded_date__c	  = c.LastModifiedDate,
						Classification__c	  = c.Classification__c
                    );
                    fileUpdateList.add(f);
                }
            } else {
                string name = c.title;
                if(name.length()>80) {
                    name = name.substring(0, 79);
                }

                if (c.Content_Description__c == null) {
                    Content_Description__c cd = new Content_Description__c(
                        Name                  = name,
                        Title__c              = c.Title,
                        Description__c        = c.Description,
                        Content_Version_Id__c = c.Id,
                        Content_ID__c         = c.ContentDocumentId,
                        filetype__c           = c.filetype,
                        Image_Resolution__c   = c.Image_Resolution__c,
                        Portfolio__c          = c.Portfolio__c,
                        TBA__c                = c.TBA__c,
                        Tags__c				  = c.TagCsv,
                        RTS__c				  = c.RTS__c,
                        Matrix_type__c		  = c.Matrix_type__c,
                        Uploaded_date__c	  = c.LastModifiedDate,
						Classification__c	  = c.Classification__c
                    );
                     
                  	contentDescriptionAddList.add(cd); 
                  	
                } else {
                    Content_Description__c cd = new Content_Description__c(
                        Id                    = c.Content_Description__c,
                        Name                  = name,
                        Title__c              = c.Title,
                        Description__c        = c.Description,
                        Content_Version_Id__c = c.Id,
                        Content_ID__c         = c.ContentDocumentId,
                        filetype__c           = c.filetype,
                        Image_Resolution__c   = c.Image_Resolution__c,
                        Portfolio__c          = c.Portfolio__c,
                        TBA__c                = c.TBA__c,
                        Tags__c				  = c.TagCsv,
                        RTS__c				  = c.RTS__c,
                        Matrix_type__c		  = c.Matrix_type__c,
                        Uploaded_date__c	  = c.LastModifiedDate,
						Classification__c	  = c.Classification__c
                    );
                    if((!contentDescriptionAddSet.contains(cd.Id)) && cd.Id != null){                    	
                   		contentDescriptionUpdateList.add(cd);                   		
                   		contentDescriptionAddSet.add(cd.Id);
                    }
                } 
            }
        }
        if (contentDescriptionAddList.size()>0) {
            try {
            	insert contentDescriptionAddList;
            } catch (System.Dmlexception dmlex) {
        		for(ContentVersion c : contentVersionMap.values()){
                    String[] messages = dmlex.getMessage().split('FIELD_CUSTOM_VALIDATION_EXCEPTION,');                     
                    c.addError(messages.size()>1?messages[1]:messages[0]);
                }
            }
            contentDescriptionAddList = [SELECT Id, Content_ID__c FROM Content_Description__c WHERE Id in: contentDescriptionAddList];

            for(Content_Description__c cd : contentDescriptionAddList) {
                helper.get(cd.Content_ID__c).Content_Description__c = cd.Id;
            }
        }
        if (contentDescriptionUpdateList.size()>0) {        
        	update contentDescriptionUpdateList;
        }
        if (fileAddList.size()>0) { 
            insert fileAddList;
            fileAddList = [SELECT Id, Content_ID__c FROM file__c WHERE Id in: fileAddList];

            for(file__c f : fileAddList) {
                helper.get(f.Content_ID__c).file__c = f.Id;
            }
        }
        if (fileUpdateList.size()>0) {
            update fileUpdateList;
        }
    }
    
    public static void updateContentDescriptionAndFileOnAfterUpdate(map<id, ContentVersion> ContentVersionMap) {
        if (disabled) {
            return;
        }
        List<Content_Description__c> contentDescriptionUpdateList = new List<Content_Description__c>();
        Set<Id> contentDescriptionAddSet = new Set<Id>();
        List<file__c> fileUpdateList = new List<file__c>();
        recordtype[] rts = [SELECT id, DeveloperName FROM recordtype where DeveloperName in :new list<string>{'Low_Resolution', 'Performance_Management', 'Collaboration', 'Planning', 'Multicultural'} AND SobjectType = 'ContentVersion'];
        Id lowResolutionRecordTypeId,performanceManagementRecordTypeId,collaborationRecordTypeId,planningRecordTypeId,multiculturalRecordTypeId;
        for(recordtype rt : rts) {
            if (rt.DeveloperName == 'Low_Resolution') {
                lowResolutionRecordTypeId = rt.Id;
            } else if (rt.DeveloperName =='Performance_Management') {
                performanceManagementRecordTypeId = rt.Id;
            } else if (rt.DeveloperName =='Collaboration') {
                collaborationRecordTypeId = rt.Id;
            } else if (rt.DeveloperName =='Planning') {
                planningRecordTypeId = rt.Id;
            } else if (rt.DeveloperName =='Multicultural') {
                multiculturalRecordTypeId = rt.Id;
            }
        }
        
        ContentVersion[] cvs = new list<ContentVersion>(); 
        for (Id key : ContentVersionMap.keySet()) {
        	if(ContentVersionMap.get(key).ContentSize != null) {
        		cvs.add(ContentVersionMap.get(key));
        	}
        }
        if (cvs.size()==0) {
            cvs = [SELECT Id, RecordTypeId, ContentSize, High_Resolution__c, Content_Description__c, file__c FROM ContentVersion WHERE Id in: ContentVersionMap.keySet()];
        }
        
        for(ContentVersion c : cvs){
            if (c.RecordTypeId == lowResolutionRecordTypeId) {
                Content_Description__c cd = new Content_Description__c(
                    Id              = c.High_Resolution__c,
                    filesize_Low__c = TriggerContentVersion.convertFileSize(c.contentSize)
                );
                if((!contentDescriptionAddSet.contains(cd.Id)) && cd.Id != null){ 
               		contentDescriptionUpdateList.add(cd);
               		contentDescriptionAddSet.add(cd.Id);
                }
                
            } else if (c.RecordTypeId == performanceManagementRecordTypeId || c.RecordTypeId == collaborationRecordTypeId || c.RecordTypeId == planningRecordTypeId) {
                file__c f = new file__c(
                    Id          = c.file__c,
                    filesize__c = TriggerContentVersion.convertFileSize(c.contentSize)
                );
                fileUpdateList.add(f);
                
            } else {
                Content_Description__c cd = new Content_Description__c(
                    Id          = c.Content_Description__c,
                    filesize__c = TriggerContentVersion.convertFileSize(c.contentSize)
                );
                if((!contentDescriptionAddSet.contains(cd.Id)) && cd.Id != null){ 
              		contentDescriptionUpdateList.add(cd);
               		contentDescriptionAddSet.add(cd.Id);
                }
                
            }
        }
        
        if (contentDescriptionUpdateList.size()>0) {
            update contentDescriptionUpdateList;
        }
        if (fileUpdateList.size()>0) {
            update fileUpdateList;
        }
    }
    
    public static string convertFileSize(integer bytes) {
        if (bytes==null) {
        	bytes = 0;
        } else {
            bytes /= 1024;
        }
        String result = bytes + 'kB';
        if (bytes > 1024) {
            bytes /= 1024;
            result = bytes + 'MB';
        }
        return result;
    }
}