TestRepo2/src/objects/Content_Description__c.object
<CustomObject>
    <fields>
        <fullName>Is_Video__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Video</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Video_Id__c</fullName>
        <description>Brightcove video Id</description>
        <label>Video Id</label>
        <length>13</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>filetype__c</fullName>
        <label>filetype</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Content Description</label>
    <nameField>
        <label>Content Description Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Content Descriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/ContentVersion.object
<CustomObject>
    <fields>
        <fullName>Content_Description__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Content Description</label>
        <referenceTo>Content_Description__c</referenceTo>
        <relationshipLabel>Content</relationshipLabel>
        <relationshipName>Content</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>File__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>File</label>
        <referenceTo>File__c</referenceTo>
        <relationshipLabel>Content</relationshipLabel>
        <relationshipName>Content</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

TestRepo2/src/objects/File__c.object
<CustomObject>
    <description>File store information about files inside folders</description>
    <fields>
        <fullName>Is_Video__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Video</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Video_Id__c</fullName>
        <label>Video Id</label>
        <length>13</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>filetype__c</fullName>
        <label>filetype</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>File</label>
    <nameField>
        <displayFormat>file-{0000000}</displayFormat>
        <label>File Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Files</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/classes/ControllerBrightcoveUpload.cls
public with sharing class ControllerBrightcoveUpload {
	public ContentVersion contentVer {get;set;}
	public String videoId {get;set;}
	public String videoDesc{get;set;}
	public List<selectOption> libsOptions {get;set;}
	public Id selectedLibrary {get;set;}
	
	public ControllerBrightcoveUpload(){
		
		contentVer = new ContentVersion();
		contentVer.ContentUrl = 'a';
				
		
		libsOptions = getLibraries(); 
	}	
	
	public List<selectOption> getLibraries()
    {
    	List<SelectOption> options = new List<SelectOption>();          
		List<ContentWorkspace> libraries = [Select c.Name, c.Id From ContentWorkspace c];
        for(ContentWorkspace lib: libraries){
            options.add(new SelectOption(lib.Id, lib.Name));
        }
        return options;
    }
	
	
	public PageReference submit(){
		
		contentVer.Description = videoDesc;
		Id RecordTyId = [Select c.DefaultRecordTypeId From ContentWorkspace c Where c.Id = :selectedLibrary].DefaultRecordTypeId;		
		contentVer.RecordTypeId = RecordTyId;
		
		insert contentVer;		
		
		ContentWorkspaceDoc contentWorkDoc = new ContentWorkspaceDoc();
			contentWorkDoc.ContentWorkspaceId = selectedLibrary;
			contentWorkDoc.ContentDocumentId  = [Select c.ContentDocumentId, c.Title From ContentVersion c Where c.Id = :contentVer.id].ContentDocumentId;
		
		insert contentWorkDoc;
		
		contentVer = [Select c.File__c, c.Title, c.Content_Description__c From ContentVersion c Where c.Id = :contentVer.id];
		
		if(contentVer.File__c != NULL){
			File__c fileN = new File__c(id=contentVer.File__c);
			fileN.Is_Video__c  = true;
			fileN.Video_Id__c = videoId;
			fileN.FileType__c = 'Video';			 
			update(fileN);			
			
			PageReference pr = new PageReference('/'+ fileN.id);
    		pr.setRedirect(true);
    		return pr;
		}else if(contentVer.Content_Description__c != NULL){
			Content_Description__c conDe = new Content_Description__c(id=contentVer.Content_Description__c);
			conDe.Is_Video__c = true;
			conDe.Video_Id__c = videoId;
			conDe.FileType__c = 'Video';			
			update(conDe);
			
			PageReference pr = new PageReference('/'+ conDe.id);
    		pr.setRedirect(true);
    		return pr;			
		}
	
		
		ApexPages.addMessage( new ApexPages.Message( ApexPages.Severity.ERROR, 'Unable to add video'));
        return null; 
	}
}