TestRepo2/src/objects/Content_Description__c.object
<CustomObject>
    <fields>
        <fullName>Classification__c</fullName>
        <label>Classification</label>
        <picklist>
            <picklistValues>
                <fullName>Spirits</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Wine</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Content_Version_Id__c</fullName>
        <label>Content Version Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Image_Resolution__c</fullName>
        <label>Image Resolution</label>
        <picklist>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Matrix_type__c</fullName>
        <label>Matrix type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Portfolio__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Portfolio</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RTS__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Ready to Serve</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TBA__c</fullName>
        <defaultValue>false</defaultValue>
        <label>TBA</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Content Description</label>
    <nameField>
        <label>Content Description Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Content Descriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/ContentVersion.object
<CustomObject>
    <fields>
        <fullName>Classification__c</fullName>
        <label>Classification</label>
        <picklist>
            <picklistValues>
                <fullName>Spirits</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wine</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Content_Description__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Content Description</label>
        <referenceTo>Content_Description__c</referenceTo>
        <relationshipLabel>Content</relationshipLabel>
        <relationshipName>Content</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Image_Resolution__c</fullName>
        <label>Image Resolution</label>
        <picklist>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Matrix_type__c</fullName>
        <label>Matrix Type</label>
        <picklist>
            <picklistValues>
                <fullName>Program Execution Brief</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Portfolio__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Portfolio</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RTS__c</fullName>
        <defaultValue>false</defaultValue>
        <label>RTS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TBA__c</fullName>
        <defaultValue>false</defaultValue>
        <label>TBA</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

TestRepo2/src/classes/TriggerContentDescription.cls
public with sharing class TriggerContentDescription {
    public static boolean disabled = false;
    public static void onBeforeUpdate(boolean isUpdate, map<id, Content_Description__c> newContentDescriptionMap, map<id, Content_Description__c> oldContentDescriptionMap) {
        if (TriggerContentDescription.disabled) {
            return;
        }
        list<ContentVersion> cvs = new list<ContentVersion>();
        for(String key : newContentDescriptionMap.keySet()) {
            Content_Description__c cd = newContentDescriptionMap.get(key);
            string name = cd.title__c;
            if(name.length()>80) {
                name = name.substring(0, 79);
            }
            cd.name = name;
	        if (isUpdate) {
	        	boolean changed = false;
	        	ContentVersion cv = new ContentVersion(Id=cd.Content_Version_Id__c);
                if( cd.Title__c != oldContentDescriptionMap.get(key).Title__c) {
                    cv.Title = cd.Title__c;
                    changed = true;
                }
                if( cd.Classification__c != oldContentDescriptionMap.get(key).Classification__c) {
                    cv.Classification__c = cd.Classification__c;
                    changed = true;
                }
                if( cd.Portfolio__c != oldContentDescriptionMap.get(key).Portfolio__c) {
                    cv.Portfolio__c = cd.Portfolio__c;
                    changed = true;
                }
                if( cd.RTS__c != oldContentDescriptionMap.get(key).RTS__c) {
                    cv.RTS__c = cd.RTS__c;
                    changed = true;
                }
                if( cd.Description__c != oldContentDescriptionMap.get(key).Description__c) {
                    cv.Description = cd.Description__c;
                    changed = true;
                }
                if( cd.TBA__c != oldContentDescriptionMap.get(key).TBA__c) {
                    cv.TBA__c = cd.TBA__c;
                    changed = true;
                }
                if( cd.Image_Resolution__c != oldContentDescriptionMap.get(key).Image_Resolution__c) {
                    cv.Image_Resolution__c = cd.Image_Resolution__c;
                    changed = true;
                }
                if( cd.Matrix_type__c != oldContentDescriptionMap.get(key).Matrix_type__c) {
                    cv.Matrix_type__c = cd.Matrix_type__c;
                    changed = true;
                }
                if (changed) {
                    cvs.add(cv);
                }
	        }
	    }
	    if (cvs.size()>0) {
	        TriggerContentVersion.disabled = true;
	        update cvs;
	        TriggerContentVersion.disabled = false;
	    }
    }

}