TestRepo2/src/objects/Content_Description__c.object
<CustomObject>
    <fields>
        <fullName>Content_ID__c</fullName>
        <label>Content ID</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Content Description</label>
    <nameField>
        <label>Content Description Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Content Descriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/Content_Property__c.object
<CustomObject>
    <fields>
        <fullName>Content_Description__c</fullName>
        <label>Content Description</label>
        <referenceTo>Content_Description__c</referenceTo>
        <relationshipLabel>Content Properties</relationshipLabel>
        <relationshipName>Content_Properties</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Content Property</label>
    <nameField>
        <label>Content Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Content Properties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestRepo2/src/objects/ContentBrand__c.object
<CustomObject>
    <fields>
        <fullName>Content_Description__c</fullName>
        <label>Content Description</label>
        <referenceTo>Content_Description__c</referenceTo>
        <relationshipLabel>ContentBrand</relationshipLabel>
        <relationshipName>ContentBrand_del</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>ContentBrand</label>
    <nameField>
        <label>ContentBrand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ContentBrand</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestRepo2/src/classes/Controller_ContentDescDelete.cls
public with sharing class Controller_ContentDescDelete {
	
	private ApexPages.StandardController con;
	public Content_Description__c descRecord{get;set;}	
	
	public Controller_ContentDescDelete(ApexPages.StandardController controller) {    	
        con = controller;                
        descRecord = (Content_Description__c)controller.getRecord();                		     
    }
    
    public PageReference deleteAndRedirect()
    {
    	Content_Description__c descR = [Select Id, Content_ID__c From Content_Description__c  Where Id=:descRecord.Id];
    	List<Content_Property__c> cp = [Select Content_Description__c From Content_Property__c Where Content_Description__c = :descR.Id];
		delete(cp);
		 
		List<ContentBrand__c> cb = [Select Content_Description__c From ContentBrand__c Where Content_Description__c = :descR.Id];
		delete(cb);
		
		List<ContentDocument> cd = [Select Id From ContentDocument Where Id = :descR.Content_ID__c];
		delete(cd);
		        		
		delete(descR);

		String url = Content_Description__c.SObjectType.getDescribe().getKeyPrefix();
		return new PageReference('/'+url);
    }

}