TestRepo2/src/objects/Content_Change_Notification__c.object
<CustomObject>
    <fields>
        <fullName>Content_Subscription__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Content Subscription</label>
        <referenceTo>Content_Subscription__c</referenceTo>
        <relationshipLabel>Change Notifications</relationshipLabel>
        <relationshipName>Content_Change_Notifications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Content__c</fullName>
        <label>Content</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Content_Change_Notifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Content Change Notification</label>
    <nameField>
        <displayFormat>CN-{000000}</displayFormat>
        <label>Content Change Notification Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Content Change Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/Content_Subscription__c.object
<CustomObject>
    <description>Content subscription object that subscribes a user to a piece of content</description>
    <fields>
        <fullName>Content__c</fullName>
        <label>Content</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Content_Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Content Subscription</label>
    <nameField>
        <displayFormat>CS-{000000}</displayFormat>
        <label>Content Subscription Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Content Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Content_Notification_Frequency__c</fullName>
        <label>Content Notification Frequency</label>
        <picklist>
            <picklistValues>
                <fullName>Real Time</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Daily</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Weekly</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

TestRepo2/src/classes/Test_ContentVersionTrigger.cls
/*******************************************************************************
Name        : Test_ContentVersionTrigger.cls

Updated By  : Basant Verma (Appirio Offshore)   
Date        : 6/5/13
Story/Task  : US79/TA1001
Description	: Test Class which provide code coverage for 
									ContentVersionTrigger.trigger and
									ContentVersionTriggerHandler.cls 
*******************************************************************************/
@isTest
private class Test_ContentVersionTrigger {
	private static ContentWorkspace selectedWorkspace;
	private static ContentVersion cVersion;
	private static ContentDocument cDoc;
	private static User testUser;
	private static Content_Subscription__c sub;
	static testMethod void testContentNotification() {
	    Test.startTest();
	    createTestDate();
	    
	    // After Test Data
	    system.assertNotEquals(testUser.Id, null);
	    system.assertNotEquals(cVersion.Id, null);
	    system.assertNotEquals(cDoc.Id, null);
	    system.assertNotEquals(sub.Id, null);
	    
	    // Before Any Version
	    List<Content_Change_Notification__c> notifications = [Select Id, User__c, Content__c 
	    			From Content_Change_Notification__c 
	    				Where User__c = :testUser.Id
	    					AND Content__c = :cDoc.Id];
	   	system.assertEquals(notifications.size(), 0);
	    
	    // Create a new Version
	    ContentVersion cVersion2 = new ContentVersion();
	    cVersion2.ContentDocumentId = cDoc.Id;
	    cVersion2.ReasonForChange = 'TestClass';
	    cVersion2.pathOnClient = 'test1.xml';
		  cVersion2.VersionData = Blob.valueOf('Hello');
		  cVersion2.RecordTypeId = selectedWorkspace.defaultRecordTypeId;
		  cVersion2.Description = 'UpdatedTest';
	    insert cVersion2;
	    system.assertNotEquals(cVersion2.Id, null);
	    
	    // After a Version
	    notifications = [Select Id, User__c, Content__c 
	    			From Content_Change_Notification__c 
	    				Where User__c = :testUser.Id
	    					AND Content__c = :cDoc.Id];
	   	system.assertEquals(notifications.size(), 1);
	    
	    Test.stopTest();
	}
	
	private static void createTestDate(){
		testUser = Test_Helper.generateTestUser('TUser', false, 'System Administrator');
		testUser.content_Notification_Frequency__c = 'Real Time';
        insert testUser;
		
		selectedWorkspace = [SELECT Name, Id, DefaultRecordTypeId  
                                FROM ContentWorkspace WHERE 
                                DefaultRecordTypeId != NULL LIMIT 1 ];
    
    	//Insert ContentVersion to get contentDocument Id for first time;
    	cVersion = new ContentVersion();
    	cVersion.pathOnClient = 'test1.xml';
	  	cVersion.VersionData = Blob.valueOf('Hello');
	  	cVersion.ReasonForChange = 'Created';
	  	cVersion.FirstPublishLocationId = selectedWorkspace.Id;
	  	cVersion.RecordTypeId = selectedWorkspace.defaultRecordTypeId;
	  	cVersion.Description = 'TestDesc';
    	insert cVersion;
    
    	// Fetch ContentDocument
    	cDoc = [Select id from ContentDocument where id = :[select ContentDocumentId 
    					from ContentVersion where id = :cVersion.id].ContentDocumentId];
    
    	sub = new Content_Subscription__c();
    	sub.User__c = testUser.Id;
    	sub.Content__c = cDoc.Id;
    	insert sub;
	}
}