TestRepo2/src/objects/Content_Subscription__c.object
<CustomObject>
    <description>Content subscription object that subscribes a user to a piece of content</description>
    <fields>
        <fullName>Content__c</fullName>
        <label>Content</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Content_Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Content Subscription</label>
    <nameField>
        <displayFormat>CS-{000000}</displayFormat>
        <label>Content Subscription Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Content Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/classes/ContentNotificationController.cls
public class ContentNotificationController {
    
    private final List<Content_Subscription__c> contentSubs;
    private Set<Id> contentDocIds;
    private Map<Id, ContentDocument> contentDocMap;
    
    public ContentNotificationController() {
        contentSubs = [SELECT Id, User__c, Content__c 
                       FROM Content_Subscription__c];
                
        if(contentSubs != null && contentSubs.size() > 0) {
            contentDocIds = new Set<Id>();
            for(Content_Subscription__c conSub : contentSubs) {
                contentDocIds.add(conSub.Content__c);
            }
        }
        
        contentDocMap = new Map<Id, ContentDocument>([SELECT Id
                                                      FROM ContentDocument
                                                      WHERE Id IN : contentDocIds
                                                            AND LastModifiedDate <=: system.now()]);

        //@TODO - Loop through the Map of Content that has been recently changed for which there are Subscriptions
    }

    public List<Content_Subscription__c> getContentSubs() {
        return contentSubs;
    }
    
    public class ContentNotification {
        public Content_Subscription__c contentSub;
        public String contentName;
        public String contentURL;
    
        public ContentNotification(){}
    }
}