TestRepo2/src/objects/ContentVersion.object
<CustomObject>
    <fields>
        <fullName>Classification__c</fullName>
        <label>Classification</label>
        <picklist>
            <picklistValues>
                <fullName>Spirits</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wine</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>File__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>File</label>
        <referenceTo>File__c</referenceTo>
        <relationshipLabel>Content</relationshipLabel>
        <relationshipName>Content</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Image_Resolution__c</fullName>
        <label>Image Resolution</label>
        <picklist>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Collaboration</fullName>
        <active>true</active>
        <label>Collaboration</label>
    </recordTypes>
</CustomObject>

TestRepo2/src/objects/File__c.object
<CustomObject>
    <description>File store information about files inside folders</description>
    <fields>
        <fullName>Classification__c</fullName>
        <label>Classification</label>
        <picklist>
            <picklistValues>
                <fullName>Spirits</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Wine</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Content_ID__c</fullName>
        <label>Content ID</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Content_Version_Id__c</fullName>
        <label>Content Version Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Distributors__c</fullName>
        <label>Distributor IDs</label>
        <picklist>
            <picklistValues>
                <fullName>a</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>b</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>c</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Division_Access__c</fullName>
        <label>Division Access</label>
        <picklist>
            <picklistValues>
                <fullName>Charmer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Control</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Franchise</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Glazers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Independent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SWS</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Folders__c</fullName>
        <label>Folder IDs</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>17</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>18</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>19</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>21</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>22</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>23</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>24</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>25</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>26</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>27</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>28</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>29</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Image_Resolution__c</fullName>
        <label>Image Resolution</label>
        <picklist>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Is_Video__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Video</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OrgUnits__c</fullName>
        <label>OrgUnit Id</label>
        <picklist>
            <picklistValues>
                <fullName>OrgUnit</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Page_Section__c</fullName>
        <label>Page Section</label>
        <picklist>
            <picklistValues>
                <fullName>Planning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Performance Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Collaboration</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Preview_Available__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Preview Available</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Preview_Id__c</fullName>
        <label>Preview Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Uploaded_date__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Uploaded date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Video_Id__c</fullName>
        <label>Video Id</label>
        <length>13</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>filesize__c</fullName>
        <label>filesize</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>filetype__c</fullName>
        <label>filetype</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>File</label>
    <nameField>
        <displayFormat>file-{0000000}</displayFormat>
        <label>File Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Files</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/Folder__c.object
<CustomObject>
    <fields>
        <fullName>Classification__c</fullName>
        <label>Classification</label>
        <picklist>
            <picklistValues>
                <fullName>Spirits</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wine</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Distributors__c</fullName>
        <label>Distributor IDs</label>
        <picklist>
            <picklistValues>
                <fullName>Distributor</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>OrgUnits__c</fullName>
        <label>OrgUnit Id</label>
        <picklist>
            <picklistValues>
                <fullName>OrgUnits</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Page_Section__c</fullName>
        <label>Page Section</label>
        <picklist>
            <picklistValues>
                <fullName>Planning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Performance Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Collaboration</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Folder</label>
    <nameField>
        <label>Folder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Folders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/Organizational_Unit__c.object
<CustomObject>
    <description>POS Project: object that represents a hierarchy level within the distributors hierarchy</description>
    <fields>
        <fullName>Label__c</fullName>
        <label>Label</label>
        <picklist>
            <picklistValues>
                <fullName>Division</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Market</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>State District</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Region</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent</label>
        <referenceTo>Organizational_Unit__c</referenceTo>
        <relationshipLabel>Organizational Units</relationshipLabel>
        <relationshipName>Organizational_Units</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Spirits</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wine</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Organizational Unit</label>
    <nameField>
        <label>Organizational Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organizational Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/classes/Test_Service_ContentItem.cls
@isTest(seeAllData=true)
private class Test_Service_ContentItem {
	
    private static AggregateResultHolder resultHolder;    
    private static Organizational_Unit__c division;
    private static Organizational_Unit__c region;
    private static Organizational_Unit__c district;
    private static Organizational_Unit__c market;
   	private static File__c fileContent;
   	private static ContentWorkspace CW;
    static testmethod void testServiceUpload(){
        
        Service_ContentItem sci = new Service_ContentItem();
        AggregateResultHolder ag = new AggregateResultHolder();
        sci.aggregated = ag;
        Boolean isIpad = sci.isIpadComponent;
        Boolean editable = sci.editable;     
        Datetime createdDate1 = sci.createdDate1;     
        Datetime lastLoginDateItem1 = sci.lastLoginDateItem1;     
        String cvid1 = sci.cvid1;     
        String cvidlow1 = sci.cvidlow1;     
        String imageRes1 = sci.imageRes1;     
        String fileType1 = sci.fileType1;     
        String fileSize1 = sci.fileSize1;     
        Boolean displayUploadDate1 = sci.displayUploadDate1;     
        Boolean showDownloadShare1 = sci.showDownloadShare1;     
        Boolean showListButtons1 = sci.showListButtons1;     
        Boolean isVideo1 = sci.isVideo1;     
        String videoId1 = sci.videoId1;     
        Boolean previewAvailable1 = sci.previewAvailable1;     
        String previewId1 = sci.previewId1;
        String width1 = sci.width1;
        String height1 = sci.height1;
        String margin1 = sci.margin1;
        Boolean renderAsList1 = sci.renderAsList1;
        String description2 = sci.description2;
        set<id> basketIds = sci.basketIds;     
        set<id> followIds = sci.followIds;     
        Boolean inBasket = sci.inBasket;
        Boolean inFollow = sci.inFollow;
        Date getcreatedDate2 = sci.getcreatedDate2();
        Boolean getisNew = sci.getisNew();
        String id = sci.cid;
        sci.setlastLoginDateItem(getcreatedDate2);
    }
    
    // Test method tests controller functionality with content
    static testmethod void testServiceContentWithAggregatedContent(){
        
        Service_ContentItem sci = new Service_ContentItem();
        AggregateResultHolder ag = new AggregateResultHolder();
        
        // Creates test data
        createTestData();
        //sci.editableIdsString = ''+
        sci.setaggregated(resultHolder);       
        system.assert(sci.canEdit() == true);
        system.assert(sci.cvid1 != null);
        system.assert(sci.title1 != null);
        system.assert(sci.cutoffDescription2  != null);
        system.assert(sci.previewId1  == null);
        system.assert(sci.videoId1  == null);
        system.assert(sci.fileTypePath != null);
        Boolean inBasket = sci.inBasket;
        Boolean inFollow = sci.inFollow;
        Date getcreatedDate2 = sci.getcreatedDate2();
        Boolean getisNew = sci.getisNew();
        String id = sci.cid;
        sci.setlastLoginDateItem(getcreatedDate2);
    }
    // Test method tests controller functionality with content
    static testmethod void testServiceContentForFileType(){
    	Service_ContentItem sci = new Service_ContentItem();
        // Creates test data
        createTestData();
        updateFilepath('c:\\video.AI');
        sci.setaggregated(fetchFileContent(fileContent.Id));       
        system.assertEquals(sci.fileTypePath , '/i/filetype/ai_120.png');
        updateFilepath('c:\\video.M4V');
        sci.setaggregated(fetchFileContent(fileContent.Id));       
        system.assertEquals(sci.fileTypePath , '/i/filetype/m4v_120.png');
        updateFilepath('c:\\video.MP3');
        sci.setaggregated(fetchFileContent(fileContent.Id));       
        system.assertEquals(sci.fileTypePath , '/i/filetype/mp3_120.png');
        updateFilepath('c:\\video.PNG');
        sci.setaggregated(fetchFileContent(fileContent.Id));       
        system.assertEquals(sci.fileTypePath , '/i/filetype/png_120.png');
        
        updateFilepath('c:\\video.TXT');
        sci.setaggregated(fetchFileContent(fileContent.Id));       
        system.assertEquals(sci.fileTypePath , '/i/filetype/txt_120.png');
        updateFilepath('c:\\video.PSD');
        sci.setaggregated(fetchFileContent(fileContent.Id));       
        system.assertEquals(sci.fileTypePath , '/i/filetype/psd_120.png');
        updateFilepath('c:\\video.WMV');
        sci.setaggregated(fetchFileContent(fileContent.Id));       
        system.assertEquals(sci.fileTypePath , '/i/filetype/wmv_120.png');
        updateFilepath('c:\\video.TEXT');
        sci.setaggregated(fetchFileContent(fileContent.Id));       
        system.assertEquals(sci.fileTypePath , '/i/filetype/general_120_2.png');
        updateFilepath('c:\\video.ZIP');
        sci.setaggregated(fetchFileContent(fileContent.Id));       
        system.assertEquals(sci.fileTypePath , '/i/filetype/zip_120.png');
        
    }
    
      
    // Method Creates test data
    private static void createTestData(){
        Test_Helper.generateTestMDUser('12345', false, [SELECT Name FROM Profile Limit 1].Name);
        setup();         
        Account a = Test_Helper.testGetDiageoAccount();
		
        Folder__c folderParent = Test_Helper.testInsertFolder(false, true, market.Id, false, false, CONSTANT.COLLABORATION, null, a.Id);
        Folder__c folderChild = Test_Helper.testInsertFolder(true, false, market.Id, false, false, CONSTANT.COLLABORATION, folderParent.ID, a.Id);
        fileContent = Test_Helper.testInsertFile(folderChild.ID, Constant.COLLABORATION, division.Name, market.Id, a.ID);
         
        resultHolder = fetchFileContent(fileContent.Id);
        
    }
    
    private static AggregateResultHolder fetchFileContent(Id fileId){
    	String query = 'select OwnerID, Description__c folderName, id, Content_Version_Id__c cvid, Description__c description, '
        			  + 'filesize__c filesize, filetype__c filetype, Title__c  title, is_video__c is_video, video_id__c video_id, '
        			  + 'Preview_Available__c previewAvailable, Preview_Id__c previewId, max(Uploaded_date__c) createdDate, '
        			  + 'Image_Resolution__c imageRes '
                      + 'from File__c where id = \'' + fileId + '\' '             
        			  + 'GROUP BY id, Content_Version_Id__c, Description__c, filesize__c, filetype__c, '
        			  + 'Title__c, is_video__c, video_id__c, Preview_Available__c, Preview_Id__c, Image_Resolution__c, '
        			  + 'OwnerID ORDER BY Description__c';
        List<AggregateResult> content = database.query(query);
        AggregateResultHolder aggResultHolder = new AggregateResultHolder();
        system.assert(content.size() > 0);
        aggResultHolder.result = content[0];
        return aggResultHolder;
    }
    private static void updateFilepath(String fieldPath){
    	if(CW==null){
    		CW = [select Id, DefaultRecordTypeId from ContentWorkspace where name = :Constant.COLLABORATION];
    	}
        
        ContentVersion c = new ContentVersion();
        c.Title = 'test upload';        // some title
        c.PathOnClient = fieldPath; //dummy filepath, file doesn't exist on my computer. filetype is set based on a value of this field
        c.VersionData = blob.valueof('1115660548001'); //We store video Id from the BrightCove webstire
        c.Description = 'Test Description';
        c.RecordTypeId = CW.DefaultRecordTypeId;

        insert c;
        c = [SELECT Id, ContentDocumentId,File__c FROM ContentVersion WHERE Id =: c.Id];
        ContentWorkspaceDoc cwd = new ContentWorkspaceDoc(
            ContentDocumentId = c.ContentDocumentId,
            ContentWorkspaceId = CW.Id
        );
            
        insert cwd;
        Id testFileId = [SELECT Id, ContentDocumentId, File__c FROM ContentVersion WHERE Id =: c.Id Limit 1].File__c;
        File__c testFile = [SELECT Content_ID__c, Content_Version_Id__c, Folders__c, Page_Section__c, Distributors__c, Division_Access__c, OrgUnits__c From File__c Where Id =:testFileId Limit 1 ];
        testFile.Content_ID__c = c.ContentDocumentId;
        testFile.Content_Version_Id__c = c.Id;
        testFile.Folders__c = fileContent.Folders__c;
        testFile.Page_Section__c = fileContent.Page_Section__c;
        testFile.Distributors__c = fileContent.Distributors__c;
        testFile.Division_Access__c = fileContent.Division_Access__c;
        testFile.OrgUnits__c = fileContent.OrgUnits__c;
		testFile.Classification__c = fileContent.Classification__c;
		update testFile;
		fileContent = testFile;
        
    }
    
    
    // Method set up organization units
	private static void setup(){
        division = new Organizational_Unit__c(Label__c = 'Division', Name = 'divisionName', Type__c='Spirits');
        insert division;
        region = new Organizational_Unit__c(Label__c = 'Region', Name = 'regionName', Parent__c=division.Id, Type__c='Spirits');
        insert region;
        district = new Organizational_Unit__c(Label__c = 'State District', Name = 'regionName', Parent__c=region.Id, Type__c='Spirits');
        insert district;
        market = new Organizational_Unit__c(Label__c = 'Market', Name = 'regionName', Parent__c=district.Id, Type__c='Spirits');
        insert market;
    }
}