TestRepo2/src/objects/ContentVersion.object
<CustomObject>
    <fields>
        <fullName>File__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>File</label>
        <referenceTo>File__c</referenceTo>
        <relationshipLabel>Content</relationshipLabel>
        <relationshipName>Content</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

TestRepo2/src/objects/File__c.object
<CustomObject>
    <description>File store information about files inside folders</description>
    <label>File</label>
    <nameField>
        <displayFormat>file-{0000000}</displayFormat>
        <label>File Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Files</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/Folder__c.object
<CustomObject>
    <label>Folder</label>
    <nameField>
        <label>Folder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Folders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/classes/Test_Service_EditFile.cls
@isTest(SeeAllData=true)
public class Test_Service_EditFile {

    public static testmethod void testEdit(){
        ContentVersion cv = [select Id, File__c from ContentVersion limit 1];
        Account account = new Account(Name = 'A B');
        insert account;
        Folder__c folder = new Folder__c();
        insert folder;
        Test.startTest();
        
        Service_EditFile sv = new Service_EditFile();
        sv.file = cv;
        sv.DistributorId = account.id;
        sv.folderId = folder.id;
        sv.commentBody = 'ABC';
        sv.saveFile();
        sv.fileId = cv.id;
        sv.file = cv;
        sv.description = 'abc';
        sv.saveFile();
        
        Test.stopTest();
    }
    
    public static testmethod void testReplace(){
        ContentVersion cv1 = [select Id, File__c, PathOnClient, ContentDocumentId, VersionData from ContentVersion where PathOnClient != null limit 1];
        Account account = new Account(Name = 'A B');
        insert account;
        Folder__c folder = new Folder__c();
        insert folder;
        User user = new User(Id = UserInfo.getUserId());
        Test.startTest();
        
        system.runas(user){
	        Service_EditFile sv = new Service_EditFile();
	        sv.file = cv1;
	        sv.organizationalHierarchyName = 'Control';
	        sv.DistributorId = account.id;
	        sv.folderId = folder.id;
	        sv.commentBody = 'ABC';
	        sv.replaceFile();
	        sv.description = 'abc';
	        sv.PathOnClient = 'dummy file';
	        sv.replaceFile();
        }
        Test.stopTest();
    }
    
    public static testmethod void testDelete(){
        ContentVersion cv = [select Id, File__c from ContentVersion limit 1];
        Account account = new Account(Name = 'A B');
        insert account;
        Folder__c folder = new Folder__c();
        insert folder;
        Test.startTest();
        
        Service_EditFile sv = new Service_EditFile();
        sv.file = cv;
        sv.DistributorId = account.id;
        sv.folderId = folder.id;
        sv.commentBody = 'ABC';
        sv.deleteFile();
        sv.description = 'abc';
        sv.deleteFile();
        
        Test.stopTest();
    }

}