TestRepo2/src/objects/Content_Description__c.object
<CustomObject>
    <fields>
        <fullName>Content_Version_Id_Low__c</fullName>
        <label>Content Version Id Low</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Content_Version_Id__c</fullName>
        <label>Content Version Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Is_Video__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Video</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Preview_Available__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Preview Available</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Preview_Id__c</fullName>
        <description>Preview ID (attachment)</description>
        <label>Preview_Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Video_Id__c</fullName>
        <description>Brightcove video Id</description>
        <label>Video Id</label>
        <length>13</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>filesize__c</fullName>
        <description>Size of file</description>
        <inlineHelpText>Size of file</inlineHelpText>
        <label>filesize</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>filesize_low__c</fullName>
        <description>Size of low quality file</description>
        <inlineHelpText>Size of low quality file</inlineHelpText>
        <label>filesize_low</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>filetype__c</fullName>
        <label>filetype</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Content Description</label>
    <nameField>
        <label>Content Description Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Content Descriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/Content_Property__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Brand Marketing Information</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly Execution Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Images &amp; Logos</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Selling Materials</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Innovation, Sustainovation &amp; VAP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Multicultural</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Category Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Innovation, Sustainovation &amp; Vintage Transition</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Content_Description__c</fullName>
        <label>Content Description</label>
        <referenceTo>Content_Description__c</referenceTo>
        <relationshipLabel>Content Properties</relationshipLabel>
        <relationshipName>Content_Properties</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sub_Category__c</fullName>
        <label>Sub Category</label>
        <picklist>
            <controllingField>Category__c</controllingField>
            <picklistValues>
                <fullName>Selling Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Category Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarterly Selling Materials</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fact Sheets</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wine Notes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Programming</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Selling Materials</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Media</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Drink Shots</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Shots</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Logos</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Images</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shipping Details</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Success Stories</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Performance Updates</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Planning Calendars</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Creative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Overview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Visibility Tracking</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Selling Standards</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarterly Programming Materials</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Innovation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brand Fact Sheets</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Current Programming</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tools</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumer Info</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Best Practices</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sub_Sub_Category__c</fullName>
        <label>Sub Sub Category</label>
        <picklist>
            <controllingField>Sub_Category__c</controllingField>
            <picklistValues>
                <fullName>Display &amp; Merchandising</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Innovations Sell Sheets</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Launch Decks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Media Sell Sheets</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Off Premise</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Premise</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plannograms</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Program Brief</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Program Execution Standards</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Program Overview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shelf</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rums and Cordials</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Whiskies</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vodkas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gin and Cocktails</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tequilas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TV Commercials</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flow Charts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Digital</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sizzle Reels</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Creative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Radio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Preliminary Long Lead Deck</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Final Launch Deck</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brand Fact Sheet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing Deck</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retail Mailers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Media</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Logo Shots</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sub_Sub_Sub_Category__c</fullName>
        <label>Sub Sub Sub Category</label>
        <picklist>
            <controllingField>Sub_Sub_Category__c</controllingField>
            <picklistValues>
                <fullName>Assortment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brand Fact Sheet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Card / Hot Sheet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Category Selling Stories</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cocktails on Tap</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Diageo Monthly PR Reports</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Display &amp; Merchandising</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Knowledge and Best Practices</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Launch Sell Sheet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Media Selling Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Media Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Miscellaneous</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Multicultural Selling Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Preliminary Long Lead Deck</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Process and Governance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Program Execution Brief</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Program Execution Standards</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Program Overview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Promotional Strategies</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retailer Mailer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retail Standards</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Selling Deck</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shelf Principles</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shelf Standards &amp; Planograms</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Specs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tasting Notes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trade Ad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vision and Strategy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>World Class 2012</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Program Selling Deck</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Content Property</label>
    <nameField>
        <label>Content Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Content Properties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestRepo2/src/classes/Controller_Compliance.cls
public with sharing class Controller_Compliance extends Controller_Base {

	public List<AggregateResult> content {get; set;}
    public List<AggregateResultHolder> contentHolder {
    	get {
    		List<AggregateResultHolder> contentHolder1 = new List<AggregateResultHolder>();
    		if(content!=null){
	    		for(AggregateResult ar : content){
	    			AggregateResultHolder tmp = new AggregateResultHolder();
	    			tmp.result = ar;
	    			contentHolder1.add(tmp);
	    		}
    		}
    		return contentHolder1;
    	}
    	set;
    }	
	
	public Controller_Compliance() {
        addBreadcrumbItem(Apexpages.currentPage().getUrl(), Constant.COMPLIANCE);
		pageUrl = Page.Compliance.getUrl();
        refreshPageContent();
	}
	
	public override void refreshPageContent() {
        content = [SELECT Sub_Category__c, Sub_Sub_Category__c, Sub_Sub_Sub_Category__c, content_description__r.is_video__c is_video, content_description__r.video_id__c video_id, content_description__r.Title__c title, content_description__r.Description__c description, content_description__r.Content_Version_Id__c cvid, content_description__r.filetype__c filetype, content_description__r.Preview_Available__c previewAvailable, content_description__r.Preview_Id__c previewId, content_description__r.filesize__c filesize, content_description__r.filesize_low__c filesize_low, content_description__r.Content_Version_Id_Low__c cvidlow,  max(LastModifiedDate) createdDate 
			        FROM content_property__c 
			        WHERE Category__c =: Constant.COMPLIANCE
			         GROUP BY Sub_Category__c, Sub_Sub_Category__c, Sub_Sub_Sub_Category__c, content_description__r.is_video__c, content_description__r.video_id__c, content_description__r.Title__c, content_description__r.Description__c, content_description__r.Content_Version_Id__c, content_description__r.filetype__c, content_description__r.Preview_Available__c, content_description__r.Preview_Id__c, content_description__r.filesize__c, content_description__r.filesize_low__c, content_description__r.Content_Version_Id_Low__c 
			         ORDER BY Sub_Sub_Sub_Category__c, content_description__r.Description__c ASC
			      ];
			      
		numberOfItems = Integer.valueOf(content.size());
		content = getRequestedPage(content);	
		currentBasketIds = Service_Basket.getBasketIds();		
	}
}