TestRepo2/src/objects/Diageo_Brand__c.object
<CustomObject>
    <fields>
        <fullName>Locale__c</fullName>
        <label>Locale</label>
        <picklist>
            <picklistValues>
                <fullName>EN-US</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>EN-CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FR-CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PT-BR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ES-MX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ES-CO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ES-CL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ES-AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EN-GB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EN-IN</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Recipe Brand</label>
    <nameField>
        <label>Recipe Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recipe Brands</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

TestRepo2/src/objects/Diageo_Ingredient__c.object
<CustomObject>
    <fields>
        <fullName>Recipe__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Recipe</label>
        <referenceTo>Recipe__c</referenceTo>
        <relationshipLabel>Recipe Ingredients</relationshipLabel>
        <relationshipName>Diageo_Ingredients</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Recipe Ingredient</label>
    <nameField>
        <displayFormat>DI-{00000}</displayFormat>
        <label>Diageo Ingredient Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recipe Ingredients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/Diageo_Product__c.object
<CustomObject>
    <fields>
        <fullName>Locale__c</fullName>
        <label>Locale</label>
        <picklist>
            <picklistValues>
                <fullName>EN-US</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>EN-CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FR-CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PT-BR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ES-MX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ES-CO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ES-CL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ES-AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EN-GB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EN-IN</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Recipe Diageo Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recipe Diageo Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

TestRepo2/src/objects/Digital_Published_Asset__c.object
<CustomObject>
    <description>An object to track Assets which leverage Recipe DB. (Websites, mobile apps, etc.)</description>
    <fields>
        <fullName>Publisher__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Publisher</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Digital_Published_Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Digital Published Asset</label>
    <nameField>
        <label>Digital Published Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Digital Published Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/Master_Recipe__c.object
<CustomObject>
    <description>Master Recipe object to accomodate language and version of Recipes.</description>
    <label>Master Recipe</label>
    <nameField>
        <label>Master Recipe Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Recipes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/Recipe__c.object
<CustomObject>
    <fields>
        <fullName>Edit_Notification_To_Publisher_Time__c</fullName>
        <label>Edit Notification To Publisher Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Locale__c</fullName>
        <label>Locale</label>
        <picklist>
            <picklistValues>
                <fullName>EN-US</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>EN-CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FR-CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PT-BR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ES-MX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ES-CO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ES-CL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ES-AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EN-GB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EN-IN</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Master_Recipe__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Master Recipe</label>
        <referenceTo>Master_Recipe__c</referenceTo>
        <relationshipLabel>Recipes</relationshipLabel>
        <relationshipName>Recipes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Archive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Recipe</label>
    <nameField>
        <displayFormat>RCP-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recipes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/classes/APPIRIO_RecipeIngredientTriggerHand_Test.cls
/**************************************************************************************
Name        : APPIRIO_RecipeIngredientTriggerHand_Test 
Created By  : Appirio Offshore(Rishi Khirbat)   
Date        : 26th Feb, 2013
Purpose     : Test class for 
                - APPIRIO_RecipeIngredientTrigger.trigger
                - APPIRIO_RecipeIngredientTriggerHandler.cls 
***************************************************************************************/
@isTest(SeeAllData = true)
public with sharing class APPIRIO_RecipeIngredientTriggerHand_Test {
    //variable declaration
    static Id currentUser = UserInfo.getUserId();
    static Account account;
    static UserRole adminRole = [select Id from UserRole where Name =: MM_RecipeBase.RECIPE_ADMIN];
    static UserRole editorRole = [select Id from UserRole where Name =: MM_RecipeBase.RECIPE_EDITOR ];
    
    static User editor;
    static User admin;
    
    static Master_Recipe__c mastRec;
    static Recipe__c recipe; 
    
    static Diageo_Brand__c diagBrnd;
    static Diageo_Product__c diagPrdct;
    static Diageo_Ingredient__c diagIng;
    
    static Digital_Published_Asset__c digitalPublishedAsset;
    
    static {
        editor = new User(alias = 'unittest', email='unittest@diageorecipes.com', 
                emailencodingkey='UTF-8', lastname='Testing', 
                languagelocalekey='en_US', 
                localesidkey='en_US', profileid = UserInfo.getProfileId(), userroleid = editorRole.Id,
                timezonesidkey='America/Los_Angeles', 
                username='unittest@diageorecipes.com');
        
        admin = new User(alias = 'unitadm', email='unitadm@diageorecipes.com', 
                emailencodingkey='UTF-8', lastname='Testing', 
                languagelocalekey='en_US', 
                localesidkey='en_US', profileid = UserInfo.getProfileId(), userroleid = adminRole.Id,
                timezonesidkey='America/Los_Angeles', 
                username='unitadm@diageorecipes.com');
        
        editor.isActive=true;
        admin.isActive=true;
            
        insert editor;
        insert admin;
        
        system.runas(editor) {
            //creating a account
            account = new Account(Name='Test Account');
            insert account;
        
            //creating a Master Recipe
            mastRec = TestUtil.createMasterRecipe('MasterRecipe');
            
            //Creates a Recipe
            recipe = TestUtil.createRecipe('TestRecipe1',mastRec.Id,'Draft',true);
            recipe.Locale__c = 'EN-US';
            recipe.Status__c = 'Approved';
            update recipe;
            
            //Creating a Diageo Brand(Parent Product)       
            diagBrnd  = TestUtil.createDiageoBrand('ModelBrand',null);
            //Creating a Recipe Diageo Product(Categeory/Sub Brand of Daigeo Brand)
            diagPrdct = TestUtil.createDiageoProduct('ModelBrandCaramel',diagBrnd.Id,null);
            
            //Creating Digital Published Asset 
            digitalPublishedAsset =  TestUtil.createDigitalPublishedAsset('TestDigitalPublishedAsset1', 'Website', 'EN-US');
            digitalPublishedAsset.Publisher__c = currentUser;
            update digitalPublishedAsset;
        }
    } 
    
    //Test RecipeIngredientTriggerHandler
    public static TestMethod void TestRecipeIngredientTriggerHandler() {
        
        system.runas(admin) {
        	Test.startTest();
                //Creating Recipe Ingredients
                diagIng = TestUtil.createRecipeIngredient(true,'1.25','Oz.',recipe.Id,diagBrnd.Id,diagPrdct.id,null,1);
                recipe = [Select Edit_Notification_To_Publisher_Time__c, LastModifiedDate From Recipe__c Where Id =:recipe.Id];
                System.assert(recipe.Edit_Notification_To_Publisher_Time__c != null);
                System.assert(recipe.Edit_Notification_To_Publisher_Time__c > recipe.LastModifiedDate);
           	Test.stopTest();
        }
    }
}