TestRepo2/src/objects/Diageo_Ingredient__c.object
<CustomObject>
    <fields>
        <fullName>Recipe__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Recipe</label>
        <referenceTo>Recipe__c</referenceTo>
        <relationshipLabel>Recipe Ingredients</relationshipLabel>
        <relationshipName>Diageo_Ingredients</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Recipe Ingredient</label>
    <nameField>
        <displayFormat>DI-{00000}</displayFormat>
        <label>Diageo Ingredient Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recipe Ingredients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/Recipe__c.object
<CustomObject>
    <fields>
        <fullName>Edit_Notification_To_Publisher__c</fullName>
        <defaultValue>false</defaultValue>
        <description>T-120059 - Email When Admin Changes are made on Recipe</description>
        <label>Edit Notification To Publisher?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Archive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Recipe</label>
    <nameField>
        <displayFormat>RCP-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recipes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/classes/APPIRIO_RecipeIngredientTriggerHandler.cls
/********************************************************************************************************************
Name        : APPIRIO_RecipeIngredientTriggerHandler
Updated By  : Appirio Offshore(Rishi Khirbat)   
Date        : 26th Feb, 2013
Purpose     : This class handles the business logic of Recipe Ingredient's trigger
              Triggers:
                - APPIRIO_RecipeIngredientTrigger
              
              -In this trigger Recipe's field "Edit Notification To Publisher?" will be updated 
               when "Recipe-Admin" update "Recipe Ingredient" of Approved Recipe.
********************************************************************************************************************/
public with sharing class APPIRIO_RecipeIngredientTriggerHandler {

	//The following variable has the Id of "Recipe - Admin" role.
	static Id roleRecipeAdminId = [Select Id From UserRole Where Name = 'Recipe - Admin' limit 1].Id;
	
	/*
    @Method Name : onAfterInsertUpdateRecipeIngredient
	@description : Static method called on After Insert/Update event of trigger APPIRIO_RecipeIngredientTrigger  
	@parameters  : List<Diageo_Ingredient__c>
	@returns	 : Nothing
    */
    //In this trigger Recipe's field "Edit Notification To Publisher?" will be updated 
    //when "Recipe-Admin" update "Recipe Ingredient" of Approved Recipe.
	public static void onAfterInsertUpdateRecipeIngredient(List<Diageo_Ingredient__c> newRecipeIngredients) {
		//Verify that the current user’s role is “Recipe - Admin”.
		system.debug('==============================UserInfo.getUserRoleId(): '+UserInfo.getUserRoleId());
		system.debug('==============================roleRecipeAdminId: '+roleRecipeAdminId);
		if(UserInfo.getUserRoleId() == roleRecipeAdminId) {
			set<Id> recipeIds = new set<Id>();
			for(Diageo_Ingredient__c recipeIngredient :newRecipeIngredients) {
				recipeIds.add(recipeIngredient.Recipe__c);
			}
			
			//Create a list of Recipe to update
			List<Recipe__c> lstRecipe = new List<Recipe__c>();
			//For loop to iterate through all the approved recipe records
			for(Recipe__c recipe : [Select Edit_Notification_To_Publisher__c From Recipe__c 
																			 Where Status__c = 'Approved' 
																			 And Edit_Notification_To_Publisher__c = false
																			 And Id IN :recipeIds]) {
				recipe.Edit_Notification_To_Publisher__c = true;
				lstRecipe.add(recipe);
			}
			
			if(lstRecipe.size() > 0) {
				update lstRecipe;
			}
		}
	}
}