TestRepo2/src/objects/Digital_Published_Asset__c.object
<CustomObject>
    <description>An object to track Assets which leverage Recipe DB. (Websites, mobile apps, etc.)</description>
    <label>Digital Published Asset</label>
    <nameField>
        <label>Digital Published Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Digital Published Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/Occasion__c.object
<CustomObject>
    <fields>
        <fullName>Locale__c</fullName>
        <label>Locale</label>
        <picklist>
            <picklistValues>
                <fullName>EN-US</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EN-CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FR-CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PT-BR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ES-MX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ES-CO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ES-CL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ES-AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EN-GB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EN-IN</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Name_Of_The_Occasion__c</fullName>
        <label>Name of the Occasion</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Occasion_Type__c</fullName>
        <label>Occasion Type</label>
        <picklist>
            <picklistValues>
                <fullName>Celebrations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Holidays</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Outdoor Gatherings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Theme Parties</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Occasion</label>
    <nameField>
        <displayFormat>Occ-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Occasions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/Published_Occasion__c.object
<CustomObject>
    <fields>
        <fullName>Digital_Published_Asset__c</fullName>
        <label>Digital Published Asset</label>
        <referenceTo>Digital_Published_Asset__c</referenceTo>
        <relationshipLabel>Published Occasions</relationshipLabel>
        <relationshipName>Published_Occasions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Occasion__c</fullName>
        <label>Occasion</label>
        <referenceTo>Occasion__c</referenceTo>
        <relationshipLabel>Asset - Occasion Use</relationshipLabel>
        <relationshipName>Published_Occasions</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Published</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Suppressed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Published Occasion</label>
    <nameField>
        <displayFormat>PO-{000000}</displayFormat>
        <label>Published Occasion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Published Occasions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestRepo2/src/objects/Published_Recipe__c.object
<CustomObject>
    <description>Junction object between Digital Published Asset &amp; Recipe</description>
    <fields>
        <fullName>Digital_Published_Asset__c</fullName>
        <label>Digital Published Asset</label>
        <referenceTo>Digital_Published_Asset__c</referenceTo>
        <relationshipLabel>Published Recipes</relationshipLabel>
        <relationshipName>Published_Recipes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Recipe__c</fullName>
        <label>Recipe</label>
        <referenceTo>Recipe__c</referenceTo>
        <relationshipLabel>Asset - Recipe Use</relationshipLabel>
        <relationshipName>Published_Recipes</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suppressed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Published Recipe</label>
    <nameField>
        <displayFormat>PR-{00000}</displayFormat>
        <label>Published Recipe Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Published Recipes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestRepo2/src/objects/Recipe__c.object
<CustomObject>
    <fields>
        <fullName>Locale__c</fullName>
        <label>Locale</label>
        <picklist>
            <picklistValues>
                <fullName>EN-US</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>EN-CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FR-CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PT-BR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ES-MX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ES-CO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ES-CL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ES-AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EN-GB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EN-IN</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Occasion_Type__c</fullName>
        <label>Occasion Type</label>
        <picklist>
            <picklistValues>
                <fullName>Celebrations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Theme Parties</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Outdoor Gatherings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Holidays</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Occasion__c</fullName>
        <label>Occasion</label>
        <picklist>
            <controllingField>Occasion_Type__c</controllingField>
            <picklistValues>
                <fullName>4th of July</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anniversary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>April Fool&apos;s Day</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Award Show Night</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Baby Shower</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bachelorette Party</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bachelor Party</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BBQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beach Party</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Before the Bar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Block Party</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Board Game Night</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bonfire Party</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Book Club</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bridal Shower</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brunch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Camping</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carnival Night</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Casino Night</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cinco de Mayo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Clambake</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Class Reunion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cocktail Party</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cuban Night</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Day at the Races</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>December Holidays</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dessert Party</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Draft Party</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Election Day</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engagement Party</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Recipe_Title__c</fullName>
        <label>Recipe Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Archive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Recipe</label>
    <nameField>
        <displayFormat>RCP-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recipes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/classes/APPIRIO_ManageAssetController.cls
/********************************************************************************************************************
Name        : APPIRIO_ManageAssetController
Updated By  : Appirio Offshore(Rishi Khirbat)   
Date        : 21st Nov, 2012
Purpose     : Controller of APPIRIO_ManageAsset.page
Ref         : T-96368
              Create a Visualforce page per the specs in the attached file.
              This page allows the user to search for Recipe__c objects, and then link them to an asset via 
              the Published_Recipe__c junction object. 
              It contains all the search functionality and we should be able to add onto it to perform the junction object save operations.
********************************************************************************************************************/
public with sharing class APPIRIO_ManageAssetController {
	
	//variable declaration
	public Digital_Published_Asset__c publishedAsset{get; set;}
	
	public Boolean hasPublishedRecipe{get; set;}
	public Boolean hasPublishedOccasion{get; set;}
	public integer currentRecipeLimit{get;set;}
	public integer currentOccasionLimit{get;set;}
	public integer recipeCount{get;set;}
	public integer occasionCount{get;set;}
	
	public integer recipeCounter{get;set;}
	public integer occasionCounter{get;set;}
	
	public integer limitValue{get;set;}
	
	//public integer currentLimitValue{get;set;}
	//public integer currentLimitValue{get;set;}
	
	//public integer recipePAGE_SIZE = 5;
	//public integer occasionPAGE_SIZE = 5;
	
	public ApexPages.StandardSetController conRecipe {get;set;}
	public ApexPages.StandardSetController conOccasion {get;set;}
	
	String queryString;
	//returns the current logged in Browser name to associate respective CSS.
    public String getUserAgent() { 
	 	return ApexPages.currentPage().getHeaders().get('User-Agent');
	}
	
	//Constructor of calss APPIRIO_ManageAssetController
	public APPIRIO_ManageAssetController(Apexpages.Standardcontroller controller) {
		hasPublishedRecipe = false;
		hasPublishedOccasion = false;
		
		limitValue = 5;
		currentRecipeLimit = 5;
		currentOccasionLimit = 5;
		recipeCounter = 1;
		occasionCounter = 1;
		
		if(controller.getId() != null) {
			publishedAsset = [Select Id, Name From Digital_Published_Asset__c Where Id =: controller.getId()];
		} else {
			publishedAsset = new Digital_Published_Asset__c();
		}
		
		//Grabbing/getting all the details of the Published_Recipe__c that is Published.
		queryString = ' Select Id From Published_Recipe__c Where Digital_Published_Asset__c =\''+ publishedAsset.Id +'\'And Status__c = \'Published\'';
		conRecipe = new ApexPages.StandardSetController(Database.getQueryLocator(queryString));
		recipeCount = conRecipe.getResultSize();
		
		//Grabbing/getting all the details of the Published_Occasion__c that is Published.
		queryString = ' Select Id From Published_Occasion__c Where Digital_Published_Asset__c =\''+ publishedAsset.Id +'\'And Status__c = \'Published\'';
		conOccasion = new ApexPages.StandardSetController(Database.getQueryLocator(queryString));
		occasionCount = conOccasion.getResultSize();
	}
	
	//Generating Published Recipes info.
	public List<Published_Recipe__c> getPublishedRecipes() {
		
		queryString = ' Select Status__c, Recipe__r.Recipe_Title__c, CreatedDate, Recipe__r.Locale__c, LastModifiedDate ';
		queryString += ' From Published_Recipe__c  Where Digital_Published_Asset__c =\''+ publishedAsset.Id +'\'And Status__c = \'Published\'  Order by LastModifiedDate DESC limit '+currentRecipeLimit;
		conRecipe = new ApexPages.StandardSetController(Database.getQueryLocator(queryString));
		
		List<Published_Recipe__c> publishedRecipe = (List<Published_Recipe__c>)conRecipe.getRecords();
		if(publishedRecipe.size() > 0)
			hasPublishedRecipe = true;
		
		return publishedRecipe;
	}
	
	public pageReference showMoreRecipe(){
    	recipeCounter = recipeCounter+1;
        currentRecipeLimit = limitValue * recipeCounter;
        return null;
	}
   
   	public pageReference showLessRecipe(){
      	recipeCounter = recipeCounter-1;
      	currentRecipeLimit = limitValue * recipeCounter;
      	return null;
   	}
	
	//Generating Published Occasions info.
	public List<Published_Occasion__c> getPublishedOccasions() {
		
		queryString = ' Select Status__c, Occasion__r.Occasion_Type__c, Occasion__r.Name_Of_The_Occasion__c, Occasion__r.Locale__c, LastModifiedDate ';
		queryString += ' From Published_Occasion__c Where Digital_Published_Asset__c =\''+ publishedAsset.Id +'\'And Status__c = \'Published\'  Order by LastModifiedDate DESC limit '+currentOccasionLimit;
		conOccasion = new ApexPages.StandardSetController(Database.getQueryLocator(queryString));
		
		List<Published_Occasion__c> publishedOccasion = (List<Published_Occasion__c>)conOccasion.getRecords();
		if(publishedOccasion.size() > 0)
			hasPublishedOccasion = true;
		
		return publishedOccasion;
	}
	
	public pageReference showMoreOccasion(){
    	occasionCounter = occasionCounter+1;
        currentOccasionLimit = limitValue * occasionCounter;
        return null;
	}
   
   	public pageReference showLessOccasion(){
      	occasionCounter = occasionCounter-1;
      	currentOccasionLimit = limitValue * occasionCounter;
      	return null;
   	}
	
	/*
	// indicates whether there are more records of Recipes after the current page set.
	public Boolean hasNextRecipes {
		get {
			return conRecipe.getHasNext();
		}
		set;
	}
	
	public Integer totalRecordRecipes {
		get {
			return conRecipe.getResultSize()+1;
		}
		set;
	}
	
	public Integer currentStartRecordRecipes {
		get {
			return (pageNumberRecipe*recipePAGE_SIZE)-4;
		}
		set;
	}
	
	public Integer currentEndRecordRecipes {
		get {
			if (hasNextRecipes)
				return currentStartRecordRecipes+(recipePAGE_SIZE-1);
			else{
				Integer tmp = Math.mod(totalRecordRecipes,recipePAGE_SIZE);
				if (tmp == 0)
					return (recipePAGE_SIZE-1)+currentStartRecordRecipes;
				else
					return (tmp-1)+currentStartRecordRecipes;
					
			}
		}
		set;
	}	
   
   	//Returns the Page Numbers to display on to the screen.
   	public list<pageNumberWrapperRecipe> pageNumbersRecipes {
		get {
	   		Integer lastRow = Integer.valueOf(Math.ceil(totalRecordRecipes/recipePAGE_SIZE));
	   		if( Math.mod(totalRecordRecipes,recipePAGE_SIZE)!= 0)
	   			lastRow+=1;
	   		
	   		List<pageNumberWrapperRecipe> pNo = new List<pageNumberWrapperRecipe>();
	   		Integer j=1;
	   		for(Integer i=pageNumberRecipe;i<=lastRow && j<6;i++) {
	   			pNo.add(new pageNumberWrapperRecipe(i,j,conRecipe,pageNumberRecipe));
	   			j++;
	   		}
	   		return pNo;
	   	}
   		set;
   }
   
	public class pageNumberWrapperRecipe {
   		public Integer num{get;set;}
   		public Integer cnt{get;set;}
   		public String col{get; set;}
   		ApexPages.StandardSetController conRecipe;
   		public pageNumberWrapperRecipe(Integer n,Integer c,ApexPages.StandardSetController conRecipe, Integer pno)
   		{
	   		this.num=n;
	   		this.cnt=c;
	   		this.conRecipe=conRecipe;
	   		if(this.num == pno)
	   		this.col='red';
	   		else
	   		this.col='black';
   		}
   	
   		public void pageItems() {
      		Integer n = Integer.valueOf(Apexpages.currentPage().getParameters().get('cnt')); 
      		for(Integer i=1;i<n;i++)
         	this.conRecipe.next();
      	}
 
	}
	// indicates whether there are more records before the current page set.
	public Boolean hasPreviousRecipes {
		get {
			return conRecipe.getHasPrevious();
		}
		set;
	}
 
	// returns the page number of the current page set
	public Integer pageNumberRecipe {
		get {
			return conRecipe.getPageNumber();
		}
		set;
	}
 
	// returns the first page of records
 	public void firstRecipes() {
 		conRecipe.first();
 	}
 
 	// returns the last page of records
 	public void lastRecipes() {
 		conRecipe.last();
 	}
 
 	// returns the previous page of records
 	public void previousRecipes() {
 		conRecipe.previous();
 	}
 
 	// returns the next page of records
 	public void nextRecipes() {
 		conRecipe.next();
 		
 	}
 	
 	// indicates whether there are more records of Occasions after the current page set.
	public Boolean hasNextOccasions {
		get {
			return conOccasion.getHasNext();
		}
		set;
	}
	
	public Integer totalRecordOccasions {
		get {
			return conOccasion.getResultSize()+1;
		}
		set;
	}
	
	public Integer currentStartRecordOccasions {
		get {
			return (pageNumberOccasion*OccasionPAGE_SIZE)-4;
		}
		set;
	}
	
	public Integer currentEndRecordOccasions {
		get {
			if (hasNextOccasions)
				return currentStartRecordOccasions+(OccasionPAGE_SIZE-1);
			else{
				Integer tmp = Math.mod(totalRecordOccasions,OccasionPAGE_SIZE);
				if (tmp == 0)
					return (OccasionPAGE_SIZE-1)+currentStartRecordOccasions;
				else
					return (tmp-1)+currentStartRecordOccasions;
					
			}
		}
		set;
	}	
   
   	//Returns the Page Numbers to display on to the screen.
   	public list<pageNumberWrapperOccasion> pageNumbersOccasions {
		get {
	   		Integer lastRow = Integer.valueOf(Math.ceil(totalRecordOccasions/OccasionPAGE_SIZE));
	   		if( Math.mod(totalRecordOccasions,OccasionPAGE_SIZE)!= 0)
	   			lastRow+=1;
	   		
	   		List<pageNumberWrapperOccasion> pNo = new List<pageNumberWrapperOccasion>();
	   		Integer j=1;
	   		for(Integer i=pageNumberOccasion;i<=lastRow && j<6;i++) {
	   			pNo.add(new pageNumberWrapperOccasion(i,j,conOccasion,pageNumberOccasion));
	   			j++;
	   		}
	   		return pNo;
	   	}
   		set;
   }
   
	public class pageNumberWrapperOccasion {
   		public Integer num{get;set;}
   		public Integer cnt{get;set;}
   		public String col{get; set;}
   		ApexPages.StandardSetController conOccasion;
   		public pageNumberWrapperOccasion(Integer n,Integer c,ApexPages.StandardSetController conOccasion, Integer pno)
   		{
	   		this.num=n;
	   		this.cnt=c;
	   		this.conOccasion=conOccasion;
	   		if(this.num == pno)
	   		this.col='red';
	   		else
	   		this.col='black';
   		}
   	
   		public void pageItems() {
      		Integer n = Integer.valueOf(Apexpages.currentPage().getParameters().get('cnt')); 
      		for(Integer i=1;i<n;i++)
         	this.conOccasion.next();
      	}
 
	}
	// indicates whether there are more records before the current page set.
	public Boolean hasPreviousOccasions {
		get {
			return conOccasion.getHasPrevious();
		}
		set;
	}
 
	// returns the page number of the current page set
	public Integer pageNumberOccasion {
		get {
			return conOccasion.getPageNumber();
		}
		set;
	}
 
	// returns the first page of records
 	public void firstOccasions() {
 		conOccasion.first();
 	}
 
 	// returns the last page of records
 	public void lastOccasions() {
 		conOccasion.last();
 	}
 
 	// returns the previous page of records
 	public void previousOccasions() {
 		conOccasion.previous();
 	}
 
 	// returns the next page of records
 	public void nextOccasions() {
 		conOccasion.next();
 		
 	}	
 	*/
}