TestRepo2/src/objects/Digital_Published_Asset__c.object
<CustomObject>
    <description>An object to track Assets which leverage Recipe DB. (Websites, mobile apps, etc.)</description>
    <label>Digital Published Asset</label>
    <nameField>
        <label>Digital Published Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Digital Published Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/Occasion__c.object
<CustomObject>
    <fields>
        <fullName>Day_Of_The_Week__c</fullName>
        <label>Day of the Week</label>
        <picklist>
            <picklistValues>
                <fullName>Monday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tuesday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wednesday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Thursday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Friday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saturday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sunday</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Locale__c</fullName>
        <label>Locale</label>
        <picklist>
            <picklistValues>
                <fullName>EN-US</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EN-CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FR-CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PT-BR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ES-MX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ES-CO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ES-CL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ES-AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EN-GB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EN-IN</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Name_Of_The_Occasion__c</fullName>
        <label>Name of the Occasion</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Occasion_Type__c</fullName>
        <label>Occasion Type</label>
        <picklist>
            <picklistValues>
                <fullName>Celebrations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Holidays</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Outdoor Gatherings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Theme Parties</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Start_Month__c</fullName>
        <label>Start Month</label>
        <picklist>
            <picklistValues>
                <fullName>01</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>03</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>05</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>07</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>09</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Occasion</label>
    <nameField>
        <displayFormat>Occ-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Occasions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/Published_Occasion__c.object
<CustomObject>
    <fields>
        <fullName>Digital_Published_Asset__c</fullName>
        <label>Digital Published Asset</label>
        <referenceTo>Digital_Published_Asset__c</referenceTo>
        <relationshipLabel>Published Occasions</relationshipLabel>
        <relationshipName>Published_Occasions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Occasion__c</fullName>
        <label>Occasion</label>
        <referenceTo>Occasion__c</referenceTo>
        <relationshipLabel>Asset - Occasion Use</relationshipLabel>
        <relationshipName>Published_Occasions</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Published</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Suppressed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Published Occasion</label>
    <nameField>
        <displayFormat>PO-{000000}</displayFormat>
        <label>Published Occasion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Published Occasions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestRepo2/src/classes/APPIRIO_OccasionsAssetLinkingContrl_Test.cls
/*
	Class : APPIRIO_OccasionsAssetLinkingContrl_Test 
	Description :  Test Class for a APPIRIO_OccasionsAssetLinkingController
	Developed by : Manmeet Manethiya
	CreatedDate : Dec 07, 2012
*/

@isTest(SeeAllData=false)
private class APPIRIO_OccasionsAssetLinkingContrl_Test {
		// initialising static variables
		public static Digital_Published_Asset__c digiTalPublishedAsset;
		public static Published_Occasion__c pubOccasion;
		
		//test method to test assests for system admin functionality
		static testMethod void OccasionsAssetLinkingController_DFT_Test() {
			//creating test data
			createTestData();
			Pagereference curntPage = Page.APPIRIO_OccasionsAssetLinking;
			curntPage.getParameters().put('aId', digiTalPublishedAsset.id);
			curntPage.getParameters().put('aName', digiTalPublishedAsset.id);
			curntPage.getParameters().put('isNavigatingFromDetail', 'false');
			Test.setCurrentPage(curntPage);
			ApexPages.currentPage().getParameters().put('cnt', '1');
			Test.startTest();
			//calling controller
			APPIRIO_OccasionsAssetLinkingController controller = new APPIRIO_OccasionsAssetLinkingController();
			//initialising controller varaibles
			controller.searchTerm = 'Test';
			controller.currentType = 'Test';
			controller.currentMonth = '2';
			controller.currentDay = '2';
			controller.currentLocale = 'EN-US';
			controller.commaSet(new Set<String>{'test1, test 2, test3'});
			controller.genericCounter(new Set<String>{'test1, test 2, test3'});
			controller.typeFilter = new Set<String>{'Test'};
			controller.monthFilter = new Set<String>{'2'};
			controller.dayFilter = new Set<String>{'2'};
			controller.localeFilter = new Set<String>{'EN-US'};
			//fetching occasions and other variables
			//controller.getOccasions();
			controller.getTypes();
			controller.getMonths();
			controller.getDays();
			controller.getLocales();
			controller.getSortOrderTypes();
			controller.getWrapperOccasions();
			controller.filterResults();
			controller.publishAll();
			controller.suppressedAll();
			controller.publishOccasion();
			boolean hasNext = controller.hasNext;
			Integer totalR = controller.totalRecords;
			Integer startRecord = controller.currentStartRecord;
			Integer endRecord = controller.currentEndRecord;
			boolean hasPrevious = controller.hasPrevious;
			Integer pgNumber = controller.pageNumber; 
			//calling page navigator functions for covering data
			controller.first();
			controller.last();
			controller.previous();
			controller.next();
			controller.cancel();
			controller.getUserAgent();
			controller.clearFilters();
			controller.refreshPanel();
			controller.splitString('[test1,test2]', new Set<String>{'test1', 'test2'}, new Set<String>(), 'true');
			//preparing list of page numbers
			list<APPIRIO_OccasionsAssetLinkingController.pageNumberWrapper> pageNumbers = controller.pageNumbers;
			if(pageNumbers != null && pageNumbers.size() > 0)
				pageNumbers[0].pageItems();
			Test.stopTest();
		}
		
		static testMethod void OccasionsAssetLinkingController_DESC_Test() {
			//creating test data
			createTestData();
			Pagereference curntPage = Page.APPIRIO_OccasionsAssetLinking;
			curntPage.getParameters().put('aId', digiTalPublishedAsset.id);
			curntPage.getParameters().put('aName', digiTalPublishedAsset.id);
			curntPage.getParameters().put('isNavigatingFromDetail', 'false');
			curntPage.getParameters().put('sortType', 'DESC');
			Test.setCurrentPage(curntPage);
			ApexPages.currentPage().getParameters().put('cnt', '1');
			Test.startTest();
				//calling controller
				APPIRIO_OccasionsAssetLinkingController controller = new APPIRIO_OccasionsAssetLinkingController();
				controller.getWrapperOccasions();
			Test.stopTest();
		}
		
		static testMethod void OccasionsAssetLinkingController_AVL_Test() {
			//creating test data
			createTestData();
			Pagereference curntPage = Page.APPIRIO_OccasionsAssetLinking;
			curntPage.getParameters().put('aId', digiTalPublishedAsset.id);
			curntPage.getParameters().put('aName', digiTalPublishedAsset.id);
			curntPage.getParameters().put('isNavigatingFromDetail', 'false');
			curntPage.getParameters().put('sortType', 'AVL');
			Test.setCurrentPage(curntPage);
			ApexPages.currentPage().getParameters().put('cnt', '1');
			Test.startTest();
				//calling controller
				APPIRIO_OccasionsAssetLinkingController controller = new APPIRIO_OccasionsAssetLinkingController();
				controller.getWrapperOccasions();
			Test.stopTest();
		}
		
		//method to create test data
		private static void createTestData(){
			//creating digital published asset
			digiTalPublishedAsset = new Digital_Published_Asset__c();
			digiTalPublishedAsset.Name = 'TestAsset';
			insert digiTalPublishedAsset;
			
			//creating occasion
			Occasion__c occasion = new Occasion__c();
			occasion.Name_Of_The_Occasion__c  = 'Test';
			occasion.Occasion_Type__c = 'Test';
			occasion.Start_Month__c = '2';
			occasion.Day_Of_The_Week__c = '2';
			occasion.locale__c = 'EN-US';
			insert occasion;
			
			//creating published occasion
			pubOccasion = new Published_Occasion__c();
			pubOccasion.Digital_Published_Asset__c = digiTalPublishedAsset.id;
			pubOccasion.Status__c = 'Published';
			pubOccasion.Occasion__c = occasion.id;
			insert pubOccasion;
		}
}