TestRepo2/src/objects/Digital_Published_Asset__c.object
<CustomObject>
    <description>An object to track Assets which leverage Recipe DB. (Websites, mobile apps, etc.)</description>
    <label>Digital Published Asset</label>
    <nameField>
        <label>Digital Published Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Digital Published Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/Master_Recipe__c.object
<CustomObject>
    <description>Master Recipe object to accomodate language and version of Recipes.</description>
    <label>Master Recipe</label>
    <nameField>
        <label>Master Recipe Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Recipes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/Occasion__c.object
<CustomObject>
    <fields>
        <fullName>Locale__c</fullName>
        <label>Locale</label>
        <picklist>
            <picklistValues>
                <fullName>EN-US</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EN-CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FR-CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PT-BR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ES-MX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ES-CO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ES-CL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ES-AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EN-GB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EN-IN</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Occasion</label>
    <nameField>
        <displayFormat>Occ-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Occasions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/Published_Occasion__c.object
<CustomObject>
    <fields>
        <fullName>Digital_Published_Asset__c</fullName>
        <label>Digital Published Asset</label>
        <referenceTo>Digital_Published_Asset__c</referenceTo>
        <relationshipLabel>Published Occasions</relationshipLabel>
        <relationshipName>Published_Occasions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Occasion__c</fullName>
        <label>Occasion</label>
        <referenceTo>Occasion__c</referenceTo>
        <relationshipLabel>Asset - Occasion Use</relationshipLabel>
        <relationshipName>Published_Occasions</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Published</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Suppressed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Published Occasion</label>
    <nameField>
        <displayFormat>PO-{000000}</displayFormat>
        <label>Published Occasion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Published Occasions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestRepo2/src/objects/Published_Recipe__c.object
<CustomObject>
    <description>Junction object between Digital Published Asset &amp; Recipe</description>
    <fields>
        <fullName>Digital_Published_Asset__c</fullName>
        <label>Digital Published Asset</label>
        <referenceTo>Digital_Published_Asset__c</referenceTo>
        <relationshipLabel>Published Recipes</relationshipLabel>
        <relationshipName>Published_Recipes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Recipe__c</fullName>
        <label>Recipe</label>
        <referenceTo>Recipe__c</referenceTo>
        <relationshipLabel>Asset - Recipe Use</relationshipLabel>
        <relationshipName>Published_Recipes</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suppressed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Published Recipe</label>
    <nameField>
        <displayFormat>PR-{00000}</displayFormat>
        <label>Published Recipe Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Published Recipes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestRepo2/src/objects/Recipe__c.object
<CustomObject>
    <fields>
        <fullName>Locale__c</fullName>
        <label>Locale</label>
        <picklist>
            <picklistValues>
                <fullName>EN-US</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>EN-CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FR-CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PT-BR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ES-MX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ES-CO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ES-CL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ES-AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EN-GB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EN-IN</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Master_Recipe__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Master Recipe</label>
        <referenceTo>Master_Recipe__c</referenceTo>
        <relationshipLabel>Recipes</relationshipLabel>
        <relationshipName>Recipes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Occasion__c</fullName>
        <label>Occasion</label>
        <picklist>
            <controllingField>Occasion_Type__c</controllingField>
            <picklistValues>
                <fullName>4th of July</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anniversary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>April Fool&apos;s Day</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Award Show Night</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Baby Shower</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bachelorette Party</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bachelor Party</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BBQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beach Party</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Before the Bar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Block Party</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Board Game Night</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bonfire Party</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Book Club</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bridal Shower</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brunch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Camping</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carnival Night</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Casino Night</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cinco de Mayo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Clambake</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Class Reunion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cocktail Party</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cuban Night</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Day at the Races</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>December Holidays</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dessert Party</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Draft Party</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Election Day</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engagement Party</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Archive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Recipe</label>
    <nameField>
        <displayFormat>RCP-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recipes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/classes/APPIRIO_ManageAssetController_Test.cls
/*
	Class : APPIRIO_ManageAssetController_Test 
	Description :  Test Class for a APPIRIO_ManageAssetController
	Developed by : Manmeet Manethiya
	CreatedDate : Dec 07, 2012
*/

@isTest(SeeAllData=false)
private class APPIRIO_ManageAssetController_Test {
	public static Digital_Published_Asset__c digiTalPublishedAsset;
	public static Published_Recipe__c pubRecipe;
	public static Published_Occasion__c pubOccasion;
	
	static testMethod void testManageAssets() {
		createTestData();
		Apexpages.Standardcontroller stController = new Apexpages.Standardcontroller(digiTalPublishedAsset);
		Test.startTest();
		//calling controller
		APPIRIO_ManageAssetController controller = new APPIRIO_ManageAssetController(stController);
		//fetching published asset receipes
		controller.getPublishedRecipes();
		controller.showMoreRecipe();
		controller.showLessRecipe();
		controller.getPublishedOccasions();
		controller.showMoreOccasion();
		controller.showLessOccasion();
		//fetching user agesnts
		controller.getUserAgent();
		Test.stopTest();
		
		//assert to check size of occasion
		System.assertEquals(1, controller.occasionCount);
		//assert to check size of recipe
		System.assertEquals(1, controller.recipeCount);
	}
	
	//method to create test data
	private static void createTestData(){
		//creating digigtal published asset
		digiTalPublishedAsset = new Digital_Published_Asset__c();
		insert digiTalPublishedAsset;
		
		//creating a Master Recipe
		Master_Recipe__c mastRec = TestUtil.createMasterRecipe('MasterRecipe');
		
		//Creates a Recipe
		Recipe__c recipe = TestUtil.createRecipe('TestRecipe1',mastRec.Id,'Draft',true);
		recipe.Locale__c = 'EN-US';
		update recipe;
		
		//creating published recipe
		pubRecipe = new Published_Recipe__c();
		pubRecipe.Digital_Published_Asset__c = digiTalPublishedAsset.id;
		pubRecipe.Status__c = 'Published';
		pubRecipe.Recipe__c = recipe.id;
		insert pubRecipe;
		
		//creating occasion
		Occasion__c occasion = new Occasion__c();
		insert occasion;
		
		
		//creating published occasion
		pubOccasion = new Published_Occasion__c();
		pubOccasion.Digital_Published_Asset__c = digiTalPublishedAsset.id;
		pubOccasion.Status__c = 'Published';
		pubOccasion.Occasion__c = occasion.id;
		insert pubOccasion;
		
	}
}