TestRepo2/src/objects/File__c.object
<CustomObject>
    <description>File store information about files inside folders</description>
    <fields>
        <fullName>Classification__c</fullName>
        <label>Classification</label>
        <picklist>
            <picklistValues>
                <fullName>Spirits</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Wine</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Distributor_Names__c</fullName>
        <description>Names of selected distributors.</description>
        <label>Distributors</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Distributors__c</fullName>
        <label>Distributor IDs</label>
        <picklist>
            <picklistValues>
                <fullName>a</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>b</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>c</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Folder_Names__c</fullName>
        <description>Names of selected folders.</description>
        <label>Folders</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Folders__c</fullName>
        <label>Folder IDs</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>17</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>18</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>19</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>21</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>22</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>23</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>24</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>25</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>26</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>27</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>28</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>29</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>OrgUnits__c</fullName>
        <label>OrgUnit Id</label>
        <picklist>
            <picklistValues>
                <fullName>OrgUnit</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Page_Section__c</fullName>
        <label>Page Section</label>
        <picklist>
            <picklistValues>
                <fullName>Planning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Performance Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Collaboration</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>File</label>
    <nameField>
        <displayFormat>file-{0000000}</displayFormat>
        <label>File Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Files</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/Folder__c.object
<CustomObject>
    <fields>
        <fullName>Classification__c</fullName>
        <label>Classification</label>
        <picklist>
            <picklistValues>
                <fullName>Spirits</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wine</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Distributor_Names__c</fullName>
        <label>Distributors</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Distributors__c</fullName>
        <label>Distributor IDs</label>
        <picklist>
            <picklistValues>
                <fullName>Distributor</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>OrgUnits__c</fullName>
        <label>OrgUnit Id</label>
        <picklist>
            <picklistValues>
                <fullName>OrgUnits</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Page_Section__c</fullName>
        <label>Page Section</label>
        <picklist>
            <picklistValues>
                <fullName>Planning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Performance Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Collaboration</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Folder</label>
    <nameField>
        <label>Folder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Folders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/Organizational_Unit__c.object
<CustomObject>
    <description>POS Project: object that represents a hierarchy level within the distributors hierarchy</description>
    <fields>
        <fullName>Label__c</fullName>
        <label>Label</label>
        <picklist>
            <picklistValues>
                <fullName>Division</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Market</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>State District</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Region</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Spirits</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wine</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Organizational Unit</label>
    <nameField>
        <label>Organizational Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organizational Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/classes/Test_ControllerFile.cls
@isTest
private class Test_ControllerFile {

    class TestSettings {
        File__c file;
        File__c file2;
        Folder__c parentFolder;
        Folder__c parentFolder2;
        Folder__c child1;
        Folder__c child2;
        Folder__c child12;
        Folder__c child22;
        Organizational_Unit__c division;
        
        Account[] accounts;
        
        public TestSettings(){
            division = new Organizational_Unit__c(Label__c = 'Division', Name = 'Control', Type__c = 'Spirits');
            insert division;
            
            Test_Helper.generateTestMDUser('12345', false, [SELECT Name FROM Profile Limit 1].Name);
            Folder__c[] f = [select Id from Folder__c];
            delete f;
            file = Test_Helper.testInsertFile(null, 'Planning', division.Id, null, null);
            file2 = Test_Helper.testInsertFile(null, 'Collaboration', division.Id, null, null);
            
            parentFolder = Test_Helper.testInsertFolder('parent', false, false,  division.Id, false, false, 'Planning', null, null);
            child1 = Test_Helper.testInsertFolder('child1', false, false,  division.Id, false, false, 'Planning', parentFolder.Id, null);
            child2 = Test_Helper.testInsertFolder('child2', false, false,  division.Id, false, false, 'Planning', parentFolder.Id, null);
            
            parentFolder2 = Test_Helper.testInsertFolder('parent', false, false,  division.Id, false, false, 'Collaboration', null, null);
            child12 = Test_Helper.testInsertFolder('child1', false, false,  division.Id, false, false, 'Collaboration', parentFolder2.Id, null);
            child22 = Test_Helper.testInsertFolder('child2', false, false,  division.Id, false, false, 'Collaboration', parentFolder2.Id, null);
        
            accounts = new Account[]{
                Test_Helper.testInsertAccount('account1',  division.Id),
                Test_Helper.testInsertAccount('account2',  division.Id),
                Test_Helper.testInsertAccount('account3',  division.Id)
            };
        }
        
    }
    
    static testmethod void testControllerFile(){
        TestSettings ts = new  TestSettings();
        
        ApexPages.StandardController sc = new ApexPages.standardController(ts.file);
        ControllerFile c = new ControllerFile(sc);
        
        system.assertEquals(3, c.folders.size());
        system.assertEquals(0, c.folderDeepth.get(c.folders[0].getValue()));
        system.assertEquals(1, c.folderDeepth.get(c.folders[1].getValue()));
        
        system.assertEquals(0, c.foldersSelected.size());
        
        system.assertEquals(0, c.Distributors.size());
        system.assertEquals(0, c.DistributorsSelected.size());
        
        system.assertEquals(3, ts.accounts.size());     
                
        ts.file.Distributors__c = ts.accounts[0].Id+';'+ts.accounts[2].Id;      
        ts.file.Folders__c = ts.parentFolder.id+';'+ts.child2.id;       
        c.save();

        File__c testFile = [select id, name, Folder_Names__c, Distributor_Names__c, OrgUnits__c, Folders__c, Page_Section__c, Distributors__c, Classification__c from file__c where id =: ts.file.id limit 1];
                
        system.assertEquals('parent; child2', testFile.Folder_Names__c);
        
        ApexPages.StandardController sc2 = new ApexPages.standardController(testFile);
        ControllerFile d = new ControllerFile(sc2);
        system.assertEquals(0, d.Distributors.size());
        system.assertEquals(0, d.DistributorsSelected.size());
        d.SelectedOrganizationUnitsIds = d.SelectedOrganizationUnits = ts.division.id;
        d.setOrganizationUnits();
        d.updateOrganizationUnits();
        d.fileRecord.Page_Section__c = Constant.MULTICULTURAL;
        d.refreshFolderList();
        d.fileRecord.Page_Section__c = Constant.PERFORMANCE_MANAGMENT;
        d.refreshFolderList();
        d.setOnlyForInternalUser();
        
    }
    
    static testmethod void testControllerFile2(){
        TestSettings ts = new  TestSettings();
        
        ApexPages.StandardController sc = new ApexPages.standardController(ts.file2);
        ControllerFile c = new ControllerFile(sc);
        
        ts.file2.Distributors__c = ts.accounts[0].Id+';'+ts.accounts[2].Id;     
        ts.file2.Folders__c = ts.parentFolder2.id+';'+ts.child22.id;        
        c.save();

    }
    
}