TestRepo2/src/objects/File__c.object
<CustomObject>
    <description>File store information about files inside folders</description>
    <fields>
        <fullName>Content_ID__c</fullName>
        <label>Content ID</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Content_Version_Id__c</fullName>
        <label>Content Version Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>File</label>
    <nameField>
        <displayFormat>file-{0000000}</displayFormat>
        <label>File Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Files</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/classes/CleanContentVersion2.cls
global class CleanContentVersion2 implements Database.Batchable<sObject>{
    
    global final String FileQuery;
    
    global CleanContentVersion2(){
        FileQuery = 'SELECT id, Content_ID__c, Content_Version_Id__c FROM FILE__c';
    } 
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(FileQuery);
    }
    
    global void execute(Database.BatchableContext BC, List<sObject> scope){
        List<File__c> fileDeleteList = new List<File__c>();

        set<string> fileIDs = new Set<String>();
        for(sObject file : scope){
            fileIDs.add(String.valueOf(file.get('Content_Version_Id__c')));
        }

        List<ContentDocument> contentDocuments = [SELECT LatestPublishedVersionId FROM ContentDocument WHERE LatestPublishedVersionId = :fileIDs];                       
        set<string> documentIDs = new Set<String>();
        for(ContentDocument doc : contentDocuments){
            documentIDs.add(String.valueOf(doc.LatestPublishedVersionId));
        }
          
        for(sObject file : scope){
            
            file__c cfile = (file__c)file;
            
            if(cfile.Content_Version_Id__c == null){
                fileDeleteList.add(cfile);
            } else {
                if (!documentIDs.contains(cfile.Content_Version_Id__c)) {
                    fileDeleteList.add(cfile);
                }
            } 
        }
        
        if (fileDeleteList.size()>0) {          	         
            delete fileDeleteList;
        }       
    }
       
    global void finish(Database.BatchableContext BC){
		try{
   		   
   		   ScheduledContentVersion2 n = new ScheduledContentVersion2();
   			
		   DateTime curr = System.now();
		   curr = curr.addMinutes(15);
		   String name = 'File Delete';
		   String nextTime = '';
		   nextTime+=curr.second()+' ';
		   nextTime+=curr.minute()+' ';
		   nextTime+=curr.hour()+' ';
		   nextTime+=curr.day()+' ';
		   nextTime+=curr.month()+' ? ';
		   nextTime+=curr.year();
   		   
   		   system.schedule(name,nextTime,n);
   		   
  		} catch(Exception ex){

  		}
	}
}