TestRepo2/src/objects/Goal__c.object
<CustomObject>
    <label>Goal</label>
    <nameField>
        <label>Goal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Goals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

TestRepo2/src/objects/Goal_Product_Link__c.object
<CustomObject>
    <fields>
        <fullName>Generic_Brand__c</fullName>
        <label>Generic Brand</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Goal__c</fullName>
        <label>Goal</label>
        <referenceTo>Goal__c</referenceTo>
        <relationshipName>Goal_Product_Links</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Report_Brand__c</fullName>
        <label>Report Brand</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Brand__c</fullName>
        <label>Sub Brand</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Goal Brand</label>
    <nameField>
        <displayFormat>GPL-{0000000000}</displayFormat>
        <label>Brand ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Goal Brands</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestRepo2/src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Brand_Composite_Key__c</fullName>
        <externalId>true</externalId>
        <label>Brand Composite Key</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Generic_Brand__c</fullName>
        <label>Generic Brand</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Report_Brand__c</fullName>
        <label>Report Brand</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Brand__c</fullName>
        <label>Sub Brand</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/classes/GoalProductLinkActionsTest.cls
@isTest
private class GoalProductLinkActionsTest {
	
	static testMethod void testPopulateReportBrand() {
		Product__c prod = new Product__c();
		prod.Generic_Brand__c = 'generic brand unique';
		prod.Sub_Brand__c = 'sub brand unique';
		prod.Report_Brand__c = 'report brand unique';
		prod.Brand_Composite_Key__c = 'something';
		insert prod;
		
		Goal__c parent = new Goal__c();
        insert parent;
        
        Goal_Product_Link__c link1 = new Goal_Product_Link__c();
        link1.Goal__c = parent.Id;
        link1.Generic_Brand__c = 'generic brand unique';
        link1.Sub_Brand__c = 'sub brand unique';
        
        Goal_Product_Link__c link2 = new Goal_Product_Link__c();
        link2.Goal__c = parent.Id;
        link2.Generic_Brand__c = 'generic brand unique';
        link2.Sub_Brand__c = 'sub brand different';
        
        Test.startTest();
        
        insert link1;
        insert link2;
        
        Test.stopTest();
        
        link1 = [SELECT Id, Report_Brand__c FROM Goal_Product_Link__c WHERE Id = :link1.Id];
        System.assertEquals('report brand unique', link1.Report_Brand__c);
        
        link2 = [SELECT Id, Report_Brand__c FROM Goal_Product_Link__c WHERE Id = :link2.Id];
        System.assertEquals('generic brand unique', link2.Report_Brand__c);
        
        link2.Sub_Brand__c = 'sub brand unique';
        update link2;
        link2 = [SELECT Id, Report_Brand__c FROM Goal_Product_Link__c WHERE Id = :link2.Id];
        System.assertEquals('report brand unique', link2.Report_Brand__c);
	}

    static testMethod void testDeduplicateLinks() {
        Goal__c parent = new Goal__c();
        insert parent;
        
        List<Goal_Product_Link__c> links = new List<Goal_Product_Link__c>();
        
        Goal_Product_Link__c link1 = new Goal_Product_Link__c();
        link1.Goal__c = parent.Id;
        link1.Generic_Brand__c = 'gen brand unique';
        links.add(link1);
        
        Goal_Product_Link__c link2 = new Goal_Product_Link__c();
        link2.Goal__c = parent.Id;
        link2.Generic_Brand__c = 'gen brand dupe';
        links.add(link2);
        
        Goal_Product_Link__c link3 = new Goal_Product_Link__c();
        link3.Goal__c = parent.Id;
        link3.Generic_Brand__c = 'gen brand dupe';
        links.add(link3);
        
        Test.startTest();
        
        insert links;
        
        Test.stopTest();
        
        links = [SELECT Id FROM Goal_Product_Link__c WHERE Id IN :links];
        System.assertEquals(2, links.size());
    }
    
    
    static testMethod void testDeduplicateLinks2() {
        Goal__c parent = new Goal__c();
        insert parent;
        
        Goal_Product_Link__c link1 = new Goal_Product_Link__c();
        link1.Goal__c = parent.Id;
        link1.Generic_Brand__c = 'gen brand unique';
        insert link1;
        
        Goal_Product_Link__c link2 = new Goal_Product_Link__c();
        link2.Goal__c = parent.Id;
        link2.Generic_Brand__c = 'gen brand dupe';
        insert link2;
        
        Goal_Product_Link__c link3 = new Goal_Product_Link__c();
        link3.Goal__c = parent.Id;
        link3.Generic_Brand__c = 'gen brand dupe';
        
        Test.startTest();
        
        insert link3;
        
        Test.stopTest();
        
       	List<Goal_Product_Link__c> links = [SELECT Id FROM Goal_Product_Link__c WHERE Id = :link3.Id];
        System.assertEquals(0, links.size());
    }
}