TestRepo2/src/objects/Goal__c.object
<CustomObject>
    <fields>
        <fullName>Account_Grade__c</fullName>
        <label>Account Grade</label>
        <picklist>
            <picklistValues>
                <fullName>A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>D</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Content_Link__c</fullName>
        <label>Marketing Materials</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Feature_Type__c</fullName>
        <label>Feature Type</label>
        <picklist>
            <picklistValues>
                <fullName>Cocktail List</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shot List</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dessert List</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Drink List</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wine list</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Goal_Type__c</fullName>
        <label>Goal Type</label>
        <picklist>
            <picklistValues>
                <fullName>On-Premise - Control</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Off-Premise - Control</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Length_of_Training__c</fullName>
        <inlineHelpText>Length of time in minutes that the training took place</inlineHelpText>
        <label>Length of Training</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Location_Grade__c</fullName>
        <inlineHelpText>A = Front end cap, main lobby, checkout
B = Back of store, isle display, mid end cap
C = Others</inlineHelpText>
        <label>Location Grade</label>
        <picklist>
            <picklistValues>
                <fullName>A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Long_Name__c</fullName>
        <label>Long Name</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Number_of_Attendees__c</fullName>
        <label>Number of Attendees</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Parent_Goal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Goal</label>
        <referenceTo>Goal__c</referenceTo>
        <relationshipLabel>Child Goals</relationshipLabel>
        <relationshipName>Child_Goals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <picklist>
            <picklistValues>
                <fullName>National</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Local</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product_Sample_s__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Product Sample(s)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Calendar__c</referenceTo>
        <relationshipLabel>Goals</relationshipLabel>
        <relationshipName>Goals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SFA_POS_Items__c</fullName>
        <label>SFA POS Items</label>
        <picklist>
            <picklistValues>
                <fullName>Banner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Case Card</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Case Stacker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Case Tucker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ceiling Dangler</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coasters</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Condiment Tray</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contravision</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corebuff</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Counter Card</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Counter Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coupon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Decal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Display</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Glassware</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gutter Mat</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hats</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Key Rings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lapel Pins</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Napkins</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Napkin Holder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Necker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>One Case Bin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pennant String</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pens</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Permanent Display Piece</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pole Topper</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Poster</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Premiums</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Shelf_Set_Criteria__c</fullName>
        <label>Shelf Set Criteria</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Size_of_Ad__c</fullName>
        <label>Size of Ad</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WY</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Suggested_Price__c</fullName>
        <inlineHelpText>The prices discussed herein are suggestions and for discussion purposes only. All pricing decisions are and will be the sole decision of the final selling party.</inlineHelpText>
        <label>Suggested Retail Price</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Tasted_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Tasted Product</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Trainer__c</fullName>
        <label>Trainer</label>
        <picklist>
            <picklistValues>
                <fullName>Diageo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Rep (me)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brand Ambassador</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Training_Audience__c</fullName>
        <label>Training Audience</label>
        <picklist>
            <picklistValues>
                <fullName>Bartender</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wait Staff</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Managers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Floor Employees</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Type_of_Ad__c</fullName>
        <label>Type of Ad</label>
        <picklist>
            <picklistValues>
                <fullName>Coupon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FSI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Magazine</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Newspaper</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>Goal</label>
    <nameField>
        <label>Goal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Goals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

TestRepo2/src/objects/Goal_Product_Link__c.object
<CustomObject>
    <fields>
        <fullName>Generic_Brand__c</fullName>
        <label>Generic Brand</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Goal__c</fullName>
        <label>Goal</label>
        <referenceTo>Goal__c</referenceTo>
        <relationshipName>Goal_Product_Links</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Individual_Brand__c</fullName>
        <label>Individual Brand</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Classification__c</fullName>
        <label>Product Classification</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Group__c</fullName>
        <label>Product Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Report_Brand__c</fullName>
        <label>Report Brand</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Size__c</fullName>
        <label>Size</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Brand__c</fullName>
        <label>Sub Brand</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Goal Brand</label>
    <nameField>
        <displayFormat>GPL-{0000000000}</displayFormat>
        <label>Brand ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Goal Brands</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestRepo2/src/classes/ActionAssignmentGoalSaver.cls
public without sharing class ActionAssignmentGoalSaver {

	public ActionAssignmentGoalSaver(ActionAssignmentController cont){}

	@RemoteAction
	public static Boolean saveGoals(List<Goal__c> childGoals){
		Goal__c parentGoal = 
			[SELECT Id,
					Name,
					Long_Name__c,
					Priority__c,
					Goal_Type__c,
					RecordTypeId,
					Program__c,
					State__c,
					Comments__c,
					SFA_POS_Items__c,
					Account_Grade__c,
					Location_Grade__c,
					Start_Date__c,
					Due_Date__c,
					Content_Link__c,
					Feature_Type__c,
					Length_of_Training__c,
					Number_of_Attendees__c,
					Product_Sample_s__c,
					Shelf_Set_Criteria__c,
					Size_of_Ad__c,
					Suggested_Price__c,
					Tasted_Product__c,
					Trainer__c,
					Training_Audience__c,
					Type_of_Ad__c,
					(SELECT Id,
							Product_Classification__c,
							Product_Group__c,
							Report_Brand__c,
							Generic_Brand__c,
							Sub_Brand__c,
							Individual_Brand__c,
							Size__c
					   FROM Goal_Product_Links__r
					)
			   FROM Goal__c
			  WHERE Id = :childGoals[0].Parent_Goal__c
			];
		
		for(Goal__c childGoal : childGoals){
			childGoal.Name = parentGoal.Name;
			childGoal.Long_Name__c = parentGoal.Long_Name__c;
			childGoal.Priority__c = parentGoal.Priority__c;
			childGoal.Goal_Type__c = parentGoal.Goal_Type__c;
			childGoal.RecordTypeId = parentGoal.RecordTypeId;
			childGoal.Program__c = parentGoal.Program__c;
			childGoal.State__c = parentGoal.State__c;
			childGoal.Comments__c = parentGoal.Comments__c;
			childGoal.SFA_POS_Items__c = parentGoal.SFA_POS_Items__c;
			childGoal.Account_Grade__c = parentGoal.Account_Grade__c;
			childGoal.Location_Grade__c = parentGoal.Location_Grade__c;
			childGoal.Start_Date__c = parentGoal.Start_Date__c;
			childGoal.Due_Date__c = parentGoal.Due_Date__c;
			childGoal.Content_Link__c = parentGoal.Content_Link__c;
			childGoal.Feature_Type__c = parentGoal.Feature_Type__c;
			childGoal.Length_of_Training__c = parentGoal.Length_of_Training__c;
			childGoal.Number_of_Attendees__c = parentGoal.Number_of_Attendees__c;
			childGoal.Product_Sample_s__c = parentGoal.Product_Sample_s__c;
			childGoal.Shelf_Set_Criteria__c = parentGoal.Shelf_Set_Criteria__c;
			childGoal.Size_of_Ad__c = parentGoal.Size_of_Ad__c;
			childGoal.Suggested_Price__c = parentGoal.Suggested_Price__c;
			childGoal.Tasted_Product__c = parentGoal.Tasted_Product__c;
			childGoal.Trainer__c = parentGoal.Trainer__c;
			childGoal.Training_Audience__c = parentGoal.Training_Audience__c;
			childGoal.Type_of_Ad__c = parentGoal.Type_of_Ad__c;
			
			childGoal.Goal_Level__c = 'Rep';
		}
		
		insert childGoals;
		
		if(parentGoal.Goal_Product_Links__r.size() > 0){
			List<Goal_Product_Link__c> gpls = new List<Goal_Product_Link__c>();
			for(Goal__c childGoal : childGoals){
				for(Goal_Product_Link__c oldGPL : parentGoal.Goal_Product_Links__r){
					Goal_Product_Link__c newGPL = new Goal_Product_Link__c();
					
					newGPL.Goal__c = childGoal.Id;
					newGPL.Product_Classification__c = oldGPL.Product_Classification__c;
					newGPL.Product_Group__c = oldGPL.Product_Group__c;
					newGPL.Report_Brand__c = oldGPL.Report_Brand__c;
					newGPL.Generic_Brand__c = oldGPL.Generic_Brand__c;
					newGPL.Sub_Brand__c = oldGPL.Sub_Brand__c;
					newGPL.Individual_Brand__c = oldGPL.Individual_Brand__c;
					newGPL.Size__c = oldGPL.Size__c;
					
					gpls.add(newGPL);
				}
			}
			insert gpls;
		}
		
		parentGoal.Completed__c = true;
		update parentGoal;
		
		return true;
	}

}