TestRepo2/src/objects/Goal__c.object
<CustomObject>
    <label>Goal</label>
    <nameField>
        <label>Goal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Goals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

TestRepo2/src/objects/Goal_Brand_Report_Item__c.object
<CustomObject>
    <fields>
        <fullName>Completed_Actions__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Completed Actions - Total</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Generic_Brand__c</fullName>
        <label>Generic Brand</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Goal__c</fullName>
        <label>Goal</label>
        <referenceTo>Goal__c</referenceTo>
        <relationshipLabel>Goal Brand Report Items</relationshipLabel>
        <relationshipName>Goal_Brand_Report_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Individual_Brand__c</fullName>
        <label>Individual Brand</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Label__c</fullName>
        <formula>IF(Product_Classification__c != null, Product_Classification__c,
IF(Product_Group__c != null, Product_Group__c,
IF(Generic_Brand__c != null, Generic_Brand__c,
IF(Sub_Brand__c != null, Sub_Brand__c,
IF(Individual_Brand__c != null, Individual_Brand__c,
IF(Size__c != null, Size__c,
IF(Report_Brand__c != null, Report_Brand__c,
IF(Ind_Brand_Size__c != null, Ind_Brand_Size__c,
&apos;&apos;))))))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Label</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Level__c</fullName>
        <formula>IF(Product_Classification__c != null, &apos;Product Classification&apos;,
IF(Product_Group__c != null, &apos;Product Group&apos;,
IF(Generic_Brand__c != null, &apos;Generic Brand&apos;,
IF(Sub_Brand__c != null, &apos;Sub Brand&apos;,
IF(Individual_Brand__c != null, &apos;Individual Brand&apos;,
IF(Size__c != null, &apos;Size&apos;,
IF(Report_Brand__c != null, &apos;Report Brand&apos;,
IF(Ind_Brand_Size__c != null, &apos;Ind. Brand / Size&apos;,
&apos;&apos;))))))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Level</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Classification__c</fullName>
        <label>Product Classification</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Group__c</fullName>
        <label>Product Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Report_Brand__c</fullName>
        <label>Report Brand</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Size__c</fullName>
        <label>Size</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Brand__c</fullName>
        <label>Sub Brand</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Goal Brand Report Item</label>
    <nameField>
        <displayFormat>GBRI-{00000000}</displayFormat>
        <label>Goal Brand Report Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Goal Brand Report Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestRepo2/src/objects/Goal_Product_Link__c.object
<CustomObject>
    <fields>
        <fullName>Generic_Brand__c</fullName>
        <label>Generic Brand</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Goal__c</fullName>
        <label>Goal</label>
        <referenceTo>Goal__c</referenceTo>
        <relationshipName>Goal_Product_Links</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Individual_Brand__c</fullName>
        <label>Individual Brand</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Classification__c</fullName>
        <label>Product Classification</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Group__c</fullName>
        <label>Product Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Report_Brand__c</fullName>
        <label>Report Brand</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Size__c</fullName>
        <label>Size</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Brand__c</fullName>
        <label>Sub Brand</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Goal Brand</label>
    <nameField>
        <displayFormat>GPL-{0000000000}</displayFormat>
        <label>Brand ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Goal Brands</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestRepo2/src/classes/GoalTriggerActionsTest.cls
@isTest
private class GoalTriggerActionsTest {

   static testMethod void testCreateBlankGBRI() {
        Goal__c goal = new Goal__c();
        
        Test.startTest();
        
        insert goal;
        
        Test.stopTest();
        
        List<Goal_Brand_Report_Item__c> gbris = [SELECT Id, Completed_Actions__c, Level__c, Label__c FROM Goal_Brand_Report_Item__c WHERE Goal__c = :goal.Id];
        System.assertEquals(8, gbris.size());
        System.assertEquals(0, gbris[0].Completed_Actions__c);
        System.assertEquals(0, gbris[1].Completed_Actions__c);
        System.assertEquals(0, gbris[2].Completed_Actions__c);
        System.assertEquals(0, gbris[3].Completed_Actions__c);
        System.assertEquals(0, gbris[4].Completed_Actions__c);
        System.assertEquals(0, gbris[5].Completed_Actions__c);
        System.assertEquals(0, gbris[6].Completed_Actions__c);
        System.assertEquals(0, gbris[7].Completed_Actions__c);
        System.assertEquals('(Undefined)', gbris[0].Label__c);
        System.assertEquals('(Undefined)', gbris[1].Label__c);
        System.assertEquals('(Undefined)', gbris[2].Label__c);
        System.assertEquals('(Undefined)', gbris[3].Label__c);
        System.assertEquals('(Undefined)', gbris[4].Label__c);
        System.assertEquals('(Undefined)', gbris[5].Label__c);
        System.assertEquals('(Undefined)', gbris[6].Label__c);
        System.assertEquals('(Undefined)', gbris[7].Label__c);
        System.assertEquals('Product Classification', 	gbris[0].Level__c);
        System.assertEquals('Product Group', 			gbris[1].Level__c);
        System.assertEquals('Generic Brand', 			gbris[2].Level__c);
        System.assertEquals('Sub Brand', 				gbris[3].Level__c);
        System.assertEquals('Individual Brand', 		gbris[4].Level__c);
        System.assertEquals('Size', 					gbris[5].Level__c);
        System.assertEquals('Report Brand', 			gbris[6].Level__c);
        System.assertEquals('Ind. Brand / Size', 		gbris[7].Level__c);
    }
    
    static testMethod void testCheckToDeleteBlankGBRI(){
    	Goal__c goal = new Goal__c();
    	insert goal;
    	
    	Goal_Product_Link__c gpl = new Goal_Product_Link__c();
    	gpl.Goal__c = goal.Id;
    	gpl.Product_Classification__c = 'Test Product Classification';
    	gpl.Product_Group__c = 'Test Product Group';
    	gpl.Generic_Brand__c = 'Test Generic Brand';
    	gpl.Sub_Brand__c = 'Test Sub Brand';
    	gpl.Individual_Brand__c = 'Test Individual Brand';
    	gpl.Size__c = 'Test Size';
    	gpl.Report_Brand__c = 'Test Report Brand';
    	
    	Test.startTest();
    	
    	insert gpl;
    	
    	Test.stopTest();
    	
        List<Goal_Brand_Report_Item__c> gbris = [SELECT Id, Completed_Actions__c, Level__c, Label__c FROM Goal_Brand_Report_Item__c WHERE Goal__c = :goal.Id];
        System.assertEquals(8, gbris.size());
        System.assertEquals(0, gbris[0].Completed_Actions__c);
        System.assertEquals(0, gbris[1].Completed_Actions__c);
        System.assertEquals(0, gbris[2].Completed_Actions__c);
        System.assertEquals(0, gbris[3].Completed_Actions__c);
        System.assertEquals(0, gbris[4].Completed_Actions__c);
        System.assertEquals(0, gbris[5].Completed_Actions__c);
        System.assertEquals(0, gbris[6].Completed_Actions__c);
        System.assertEquals(0, gbris[7].Completed_Actions__c);
        Integer foundCount = 0;
        for(Goal_Brand_Report_Item__c gbri : gbris){
        	if(gbri.Level__c == 'Product Classification' && gbri.Label__c == 'Test Product Classification'){
        		foundCount++;
        	}
        	if(gbri.Level__c == 'Product Group' && gbri.Label__c == 'Test Product Group'){
        		foundCount++;
        	}
        	if(gbri.Level__c == 'Generic Brand' && gbri.Label__c == 'Test Generic Brand'){
        		foundCount++;
        	}
        	if(gbri.Level__c == 'Sub Brand' && gbri.Label__c == 'Test Sub Brand'){
        		foundCount++;
        	}
        	if(gbri.Level__c == 'Individual Brand' && gbri.Label__c == 'Test Individual Brand'){
        		foundCount++;
        	}
        	if(gbri.Level__c == 'Size' && gbri.Label__c == 'Test Size'){
        		foundCount++;
        	}
        	if(gbri.Level__c == 'Report Brand' && gbri.Label__c == 'Test Report Brand'){
        		foundCount++;
        	}
        	if(gbri.Level__c == 'Ind. Brand / Size' && gbri.Label__c == 'Test Individual Brand, Test Size'){
        		foundCount++;
        	}
        }
        System.assertEquals(8, foundCount);
        
        delete gpl;
        delete gbris;
        
        gbris = [SELECT Id, Completed_Actions__c, Level__c, Label__c FROM Goal_Brand_Report_Item__c WHERE Goal__c = :goal.Id];
        System.assertEquals(8, gbris.size());
        System.assertEquals(0, gbris[0].Completed_Actions__c);
        System.assertEquals(0, gbris[1].Completed_Actions__c);
        System.assertEquals(0, gbris[2].Completed_Actions__c);
        System.assertEquals(0, gbris[3].Completed_Actions__c);
        System.assertEquals(0, gbris[4].Completed_Actions__c);
        System.assertEquals(0, gbris[5].Completed_Actions__c);
        System.assertEquals(0, gbris[6].Completed_Actions__c);
        System.assertEquals(0, gbris[7].Completed_Actions__c);
        System.assertEquals('(Undefined)', gbris[0].Label__c);
        System.assertEquals('(Undefined)', gbris[1].Label__c);
        System.assertEquals('(Undefined)', gbris[2].Label__c);
        System.assertEquals('(Undefined)', gbris[3].Label__c);
        System.assertEquals('(Undefined)', gbris[4].Label__c);
        System.assertEquals('(Undefined)', gbris[5].Label__c);
        System.assertEquals('(Undefined)', gbris[6].Label__c);
        System.assertEquals('(Undefined)', gbris[7].Label__c);
        System.assertEquals('Product Classification', 	gbris[0].Level__c);
        System.assertEquals('Product Group', 			gbris[1].Level__c);
        System.assertEquals('Generic Brand', 			gbris[2].Level__c);
        System.assertEquals('Sub Brand', 				gbris[3].Level__c);
        System.assertEquals('Individual Brand', 		gbris[4].Level__c);
        System.assertEquals('Size', 					gbris[5].Level__c);
        System.assertEquals('Report Brand', 			gbris[6].Level__c);
        System.assertEquals('Ind. Brand / Size', 		gbris[7].Level__c);
    }
}