TestRepo2/src/objects/HomeVideo__c.object
<CustomObject>
    <fields>
        <fullName>Classification__c</fullName>
        <label>Classification</label>
        <picklist>
            <picklistValues>
                <fullName>Spirits</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Wine</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>current__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If set to true, video will be displayed on the home page</description>
        <label>current</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>description__c</fullName>
        <description>short video description</description>
        <label>description</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>videoId__c</fullName>
        <description>BrightCove Video Id</description>
        <label>video id</label>
        <length>13</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Home Video</label>
    <nameField>
        <label>Home video Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Home Videos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/NewsAndArticles__c.object
<CustomObject>
    <description>News and Articles object</description>
    <fields>
        <fullName>Classification__c</fullName>
        <label>Classification</label>
        <picklist>
            <picklistValues>
                <fullName>Spirits</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Wine</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>News&amp;Articles</label>
    <nameField>
        <displayFormat>A{00000000}</displayFormat>
        <label>Article Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>News&amp;Articles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/classes/Controller_Home.cls
public with sharing class Controller_Home extends Controller_Base {

	// RKW 8/20/2013 - Testing Git (still)
	// video
    public String videoId{get; private set;}
    public String videoDesc{get; private set;}
    public String showPlayer{get; private set;}

    public Id contentBrand{get; set;}

	// articles
	public list<NewsAndArticles__c> articles {get; set;}
    public String articleUrl {get; set; }
    
    public Boolean innovationSectionName {
 		get{
 			return (siteTheme == 'Spirits');
		}
		private set;
	}
    	    
    public Controller_Home() {
    	// Start: Changes for Responsive Site - Randy Wandell (Appirio) 7/10/13
//		pageUrl = Page.HomePage.getUrl();
		setResponsiveState();
		// End:
        
        //articles
        articles = Service_API.getNewsAndArticles();
				articleUrl = Page.NewsAndArticles.getUrl();
		
        HomeVideo__c[] videos = [Select videoId__c, description__c FROM HomeVideo__c WHERE current__c=true and Classification__c = :Service_API.getSectionTheme()];
        if (videos.size() == 1) {
            videoId      = videos[0].videoId__c;
            videoDesc    = videos[0].description__c;
            showPlayer   = 'block';
        } else {
            showPlayer = 'none';            
        }
    }

	// Start: Changes for Responsive Site - Randy Wandell (Appirio) 7/10/13    
    public void setResponsiveState() {
		pageUrl = ApexPages.currentPage().getUrl();
		if(pageUrl.toLowerCase().indexOf('r_homepage') > -1) {
			isResponsive = true;
			preapareSiteNavigationMenu();
		} else {
			isResponsive = false;
			preapareSiteNavigationMenu();
		}    	
    }
    // End:
}