TestRepo2/src/objects/HomeVideo__c.object
<CustomObject>
    <label>Home Video</label>
    <nameField>
        <label>Home video Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Home Videos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/NewsAndArticles__c.object
<CustomObject>
    <description>News and Articles object</description>
    <label>News&amp;Articles</label>
    <nameField>
        <displayFormat>A{00000000}</displayFormat>
        <label>Article Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>News&amp;Articles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/Organizational_Unit__c.object
<CustomObject>
    <description>POS Project: object that represents a hierarchy level within the distributors hierarchy</description>
    <fields>
        <fullName>Label__c</fullName>
        <label>Label</label>
        <picklist>
            <picklistValues>
                <fullName>Division</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Market</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>State District</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Region</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Spirits</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wine</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Organizational Unit</label>
    <nameField>
        <label>Organizational Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organizational Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/classes/Test_Controller_Home.cls
@isTest
private class Test_Controller_Home {
    
    class TestSettings {
        List <NewsAndArticles__c> newsAndArticles;
        HomeVideo__c currentVideo;
        public TestSettings(){
            List <NewsAndArticles__c> news = [select id from NewsAndArticles__c];
            delete news;
            List <HomeVideo__c> videos = [select id from HomeVideo__c];
            delete videos;
            newsAndArticles = new NewsAndArticles__c[]{ 
                Test_Helper.testInsertNewsAndArticles('title1', 'body1'),
                Test_Helper.testInsertNewsAndArticles('title2', 'body2'),
                Test_Helper.testInsertNewsAndArticles('title3', 'body3'),
                Test_Helper.testInsertNewsAndArticles('title4', 'body4'),
                Test_Helper.testInsertNewsAndArticles('title5', 'body5'),
                Test_Helper.testInsertNewsAndArticles('title6', 'body6')
            };
        }
        
        public void addVideos(){
            Test_Helper.testInsertHomeVideo('1115632928001', 'name1', 'description1', false);
            currentVideo = Test_Helper.testInsertHomeVideo('1115632928002', 'name2', 'description2', true);
        }
    }
    
    static testmethod void testHome(){
        PageReference pageRef = Page.HomePage;
        Test.setCurrentPage(pageRef);
        
        Organizational_Unit__c division = new Organizational_Unit__c(Label__c = 'Division', Name = 'divisionName', Type__c = 'Spirits');
        insert division;
        Account account = Test_Helper.testInsertAccount('test_account', division.Id);
        Contact contact = Test_Helper.testInsertContact('firstName', 'lastName', account.id);
        User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];   
        User usr;
        System.runAs (thisUser) {
            usr = Test_Helper.testInsertDistributorPortalUser(contact.id);
        } 

        TestSettings ts = new  TestSettings();
        
        System.runAs(usr){  
            Controller_Home c = new Controller_Home();
            System.assertEquals(6, c.articles.size());
            System.assertEquals('none', c.showPlayer);
        }
    }
    
    static testmethod void testHomeWithVideo(){
        PageReference pageRef = Page.HomePage;
        Test.setCurrentPage(pageRef);
        
        TestSettings ts = new  TestSettings();
        
        Organizational_Unit__c division = new Organizational_Unit__c(Label__c = 'Division', Name = 'divisionName', Type__c = 'Spirits');
        insert division;
        Account account = Test_Helper.testInsertAccount('test_account', division.Id);
        Contact contact = Test_Helper.testInsertContact('firstName', 'lastName', account.id);
        User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];   
        User usr;
        System.runAs (thisUser) {
            usr = Test_Helper.testInsertDistributorPortalUser(contact.id);
        }

        ts.addVideos();

        System.runAs(usr){  
            Controller_Home c = new Controller_Home();
            System.assertEquals(6, c.articles.size());
            System.assertEquals('block', c.showPlayer);
            System.assertEquals('1115632928002', c.videoId);
            System.assertEquals('description2', c.videoDesc);
        }
    }
}