TestRepo2/src/objects/Master_Recipe__c.object
<CustomObject>
    <description>Master Recipe object to accomodate language and version of Recipes.</description>
    <label>Master Recipe</label>
    <nameField>
        <label>Master Recipe Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Recipes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/Recipe__c.object
<CustomObject>
    <fields>
        <fullName>Locale__c</fullName>
        <label>Locale</label>
        <picklist>
            <picklistValues>
                <fullName>EN-US</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>EN-CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FR-CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PT-BR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ES-MX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ES-CO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ES-CL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ES-AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EN-GB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EN-IN</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Master_Recipe__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Master Recipe</label>
        <referenceTo>Master_Recipe__c</referenceTo>
        <relationshipLabel>Recipes</relationshipLabel>
        <relationshipName>Recipes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Preparation_Steps__c</fullName>
        <label>Preparation Steps</label>
        <length>32000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Recipe_Title__c</fullName>
        <label>Recipe Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Recipe</label>
    <nameField>
        <displayFormat>RCP-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recipes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/Recipe_Media__c.object
<CustomObject>
    <fields>
        <fullName>Content_id__c</fullName>
        <label>Content Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Media</label>
    <nameField>
        <label>Recipe Media Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

TestRepo2/src/classes/MM_TestMediaController.cls
@isTest(SeeAllData=true)
private class MM_TestMediaController {

    static testMethod void myUnitTest() {
	   	Master_Recipe__c master = new Master_Recipe__c();
	    insert master;
	    
		Recipe__c recipe = new Recipe__c();
		recipe.Master_Recipe__c=master.Id;
		recipe.Recipe_Title__c = 'TEST Recipe PREP STEPS';
		recipe.Locale__c = 'EN-US';
		recipe.Preparation_Steps__c='TEST PREP STEPS';
		insert recipe;
		  
		  
      	MM_MediaController controller = new MM_MediaController (recipe.Id);     
        controller.editMode = 'false';
	 	ContentVersion myImage = new ContentVersion();
	 	myImage.title='TITLE';
	 	//myImage.contentUrl='http://www.salesforce.com'; 		
 		myImage.VersionData = Blob.valueOf('sdfasfsafsf');
 		myImage.PathOnClient = 'test.png';
	    insert myImage;
	    controller.myImage=myImage;
	    controller.upload();
        
  		Recipe_Media__c media = new Recipe_Media__c();
 	    media.Content_id__c=myImage.Id;
      	insert media;
        
		controller.loadAllImages();
      
	    List<String> mediaName = new List<String>();
	    mediaName.add('mainRecipe');
	    mediaName.add('mobileDrink');
	    mediaName.add('mainIngredient');
	    mediaName.add('additional1');
	    mediaName.add('additional2');
	    mediaName.add('background');
	    mediaName.add('brandRecipe');
	    mediaName.add('searchRecipe');
	    mediaName.add('searchRecipe');
	    mediaName.add('mobileSelected');
	    mediaName.add('mobileUnselected');
              
	   	for (String name:mediaName) {
	   		controller.mediaName=name;
	   		controller.mediaId=media.Id;
	    	controller.associateMedia();
	    	controller.setMediaType2();
	   	}
	   	
	   	
	   	controller.saveImages();
        
	    controller.close();
	    controller.loadRecentImages();
	    
	    controller.showUpload();
	    controller.showSelectImages();
	    controller.imageNameFilter='test';
	    controller.filterImages();
	    controller.getUserAgent();
	    controller.getAlphabets();
	    MM_MediaController.setMediaType('image');
       
	   
	    
	    controller.setMediaType2();
	    mediaName.add('mainRecipe');
	    mediaName.add('mobileDrink');
	    mediaName.add('mainIngredient');
	    mediaName.add('additional1');
	    mediaName.add('additional2');
	    mediaName.add('background');
	    mediaName.add('brandRecipe');
	    mediaName.add('searchRecipe');
	    mediaName.add('searchRecipe');
	    mediaName.add('mobileSelected');
	    mediaName.add('mobileUnselected');
	    
	    for (String name:mediaName) {
        controller.mediaName=name;
        controller.mediaId=media.Id;
        controller.disassociateMedia();
      }
      
      
      PageReference pg = page.MM_Media;
      Test.setCurrentPageReference(pg);
      ApexPages.currentPage().getParameters().put('recipeId',recipe.Id);
      controller = new MM_MediaController();    
    
    }
}