TestRepo2/src/objects/NABCA_Opportunity__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>NABCA Opportunities</relationshipLabel>
        <relationshipName>NABCA_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity_Composite_Key__c</fullName>
        <description>External Id (NABCA_STATE_CODE + NABCA_MATERIAL_CODE + NABCA_LICENSEE_CODE)</description>
        <externalId>true</externalId>
        <label>Opportunity Composite Key</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>NABCA Opportunity</label>
    <nameField>
        <displayFormat>NO-{MM}{DD}{YYYY}-{0000000}</displayFormat>
        <label>NABCA Objective ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NABCA Opportunities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/classes/Test_Controller_OppurtunityWhitespace.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 * Created by Akanksha(offshore) for case  00003540
 **/
@isTest
private class Test_Controller_OppurtunityWhitespace {
	/*
    static testMethod void myUnitTest() {
       Account accountData = Test_Helper.testInsertAccount('accountNeme');
       NABCA_Opportunity__c opp = new NABCA_Opportunity__c(account__c = accountData.id, Opportunity_Composite_Key__c = accountData.id);
       insert opp;
       ApexPages.StandardController sc = new ApexPages.StandardController(accountData);
	   Controller_OppurtunityWhitespace controller = new Controller_OppurtunityWhitespace(sc);
    }*/
}