TestRepo2/src/objects/Order_Window__c.object
<CustomObject>
    <description>POS Project: object that represents a period of time in which catalog items are offered and shoppers are allowed to buy them</description>
    <fields>
        <fullName>Order_Close_Date__c</fullName>
        <label>Order Close Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Order_Start_Date__c</fullName>
        <label>Order Start Date</label>
        <type>Date</type>
    </fields>
    <label>Order Window</label>
    <nameField>
        <label>Order Window Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Windows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/classes/POS_OrderWindowRow.cls
global class POS_OrderWindowRow implements Comparable {
	public Order_Window__c orderWindow {get;set;}
	public Integer monthSpan {get;set;}
	public Integer startMonth {get;set;}
	
	public POS_OrderWindowRow (Order_Window__c orderWindow) {
		this.orderWindow=orderWindow;
		startMonth = orderWindow.Order_Start_Date__c.month();
		monthSpan = orderWindow.Order_Start_Date__c.monthsBetween(orderWindow.Order_Close_Date__c);
		
	}
	
	global Integer compareTo(Object compareTo) {
	    POS_OrderWindowRow comparison = (POS_OrderWindowRow)compareTo;
	    return this.startMonth-comparison.startMonth;
	}
}