TestRepo2/src/objects/Page_Content__c.object
<CustomObject>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Page_Content_Value__c</fullName>
        <label>Page Content Value</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Page_Name__c</fullName>
        <label>Page Name</label>
        <picklist>
            <picklistValues>
                <fullName>Terms &amp; Conditions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Privacy Policy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Codes &amp; Policies</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Page Content</label>
    <nameField>
        <label>Page Content Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Page Contents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/classes/Controller_TermsAndConditions.cls
public with sharing class Controller_TermsAndConditions extends Controller_Base  {

	public Page_Content__c[] contentItems {get; set;}
	public list<Attachment> attachments {get; set;}
	
	
	public Controller_TermsAndConditions() {
		pageUrl = Page.TermsAndConditions.getUrl();
        addBreadcrumbItem(Apexpages.currentPage().getUrl(), Constant.TERMS_AND_CONDITIONS);
        contentItems = [select Id, Page_Content_Value__c from Page_Content__c where Page_Name__c = : Constant.TERMS_AND_CONDITIONS ORDER BY Order__c];
		
		Set<id> contentItemsIds = new set<id>();
		
		for(Page_Content__c c : contentItems){
			contentItemsIds.add(c.id);
		}
		
    	this.attachments = [select Id, Name from Attachment where ParentId IN :contentItemsIds and isDeleted = false];
    	//system.debug(this.attachments); 
    }
}