TestRepo2/src/objects/PDF_State_Rules__c.object
<CustomObject>
    <fields>
        <fullName>State_Rules_ID__c</fullName>
        <label>State Rules ID</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>PDF State Rules</label>
    <nameField>
        <label>PDF State Rules Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PDF State Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/Rule__c.object
<CustomObject>
    <label>Issue</label>
    <nameField>
        <label>Issue Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Issues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/State__c.object
<CustomObject>
    <label>State</label>
    <nameField>
        <label>State</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/State_Rules__c.object
<CustomObject>
    <fields>
        <fullName>Applicability_Comment__c</fullName>
        <label>Conditions/Restrictions</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Rule_Applies__c</fullName>
        <label>Permissible?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes (with Restrictions)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Rule__c</fullName>
        <label>Rule</label>
        <referenceTo>Rule__c</referenceTo>
        <relationshipName>State_Rules</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <referenceTo>State__c</referenceTo>
        <relationshipName>State_Rules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Statute_Ref__c</fullName>
        <inlineHelpText>The legal statute reference</inlineHelpText>
        <label>Statute Ref</label>
        <length>400</length>
        <type>LongTextArea</type>
    </fields>
    <label>State Issue</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>State Issues ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>State Issues</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TestRepo2/src/classes/Controller_LegalPDFGenerator.cls
public with sharing class Controller_LegalPDFGenerator{
    
    private List<String> theIds;
    private PDF_State_Rules__c pdf;
    public List<State_Rules__c> Issues {get; set;}
     
    public Controller_LegalPDFGenerator(){
        
        
        pdf = new PDF_State_Rules__c();
        pdf = [SELECT State_Rules_ID__c FROM PDF_State_Rules__c WHERE Id =: ApexPages.CurrentPage().getParameters().get('id')];
        
          
        theIds = pdf.State_Rules_ID__c.split(',');
        
        Issues = [SELECT id, name, State__c, Rule_Applies__c, Rule__r.Name, State__r.Name, Rule__c , Applicability_Comment__c, Statute_Ref__c 
                        FROM State_Rules__c 
                       WHERE id in :theIds
                    ORDER BY State__r.Name, Rule__r.Name];     
        
    }
    
    
}