TestRepo2/src/objects/REST_Queue_Message__c.object
<CustomObject>
    <description>POS Project: stores outbound message request to be processed by a Batch Queue Processor</description>
    <fields>
        <fullName>FieldName__c</fullName>
        <description>API name of the field that stores the External ID corresponding to the object being synched.</description>
        <label>Field Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ObjectId__c</fullName>
        <description>Saleforce ID of the Object Record</description>
        <label>Object Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ObjectName__c</fullName>
        <description>API Name of the SFDC Object that is being synched</description>
        <label>Object Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Request_apiArguments__c</fullName>
        <label>Request apiArguments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Request_apiPath__c</fullName>
        <label>Request apiPath</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Ready-to-Process</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Processed-Successfully</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Processed-Failed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Failed-3-Attempts</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>REST Queue Message</label>
    <nameField>
        <label>REST Queue Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>REST Queue Message</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/classes/Test_RESTQueueMessageTrigger.cls
/* Created by Jai gupta [Appirio Jaipur]
   created date June 26, 2013
   Test class for : RESTQueueMessageTrigger

 **/
@isTest
public class Test_RESTQueueMessageTrigger  {

    public static testmethod void testTrigger(){
        REST_Queue_Message__c msg = new REST_Queue_Message__c(Name='postMagentoCallDocumentsObjId', ObjectId__c='sObjId', ObjectName__c='sObjTypeName', FieldName__c='sObjFieldName',
                Request_apiPath__c='apiPath', Request_apiArguments__c='optionalArguments');
        insert msg ;
                
        msg.Status__c = 'Failed-3-Attempts';
        update msg;
    }
}