TestRepo2/src/objects/Survey_Layout__c.object
<CustomObject>
    <description>Holds the configuration for dynamically rendered survey layouts.</description>
    <fields>
        <fullName>Activate_Survey__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this checkbox to activate survey layout and publish survey records to each account.</description>
        <inlineHelpText>Check this checkbox to activate survey layout and publish survey records to each account.</inlineHelpText>
        <label>Activate Survey</label>
        <type>Checkbox</type>
    </fields>
    <label>Survey Layout</label>
    <nameField>
        <label>Survey Layout Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Layouts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/Survey_Layout_Brand_Bottle_Item__c.object
<CustomObject>
    <fields>
        <fullName>Survey_Layout__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Survey Layout</label>
        <referenceTo>Survey_Layout__c</referenceTo>
        <relationshipName>Survey_Layout_Brand_Bottle_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Survey Innovation / Sustainovation</label>
    <nameField>
        <displayFormat>SLBBIN-{00000}</displayFormat>
        <label>Survey Layout Brand Bottle Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Innovation / Sustainovation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/objects/SurveyLayout_Brand_Items__c.object
<CustomObject>
    <fields>
        <fullName>Survey_Layout__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Survey Layout</label>
        <referenceTo>Survey_Layout__c</referenceTo>
        <relationshipName>SurveyLayout_Brand_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Survey Distribution / Shelf / Display</label>
    <nameField>
        <displayFormat>SLBIN-{00000}</displayFormat>
        <label>SurveyLayout Brand Items Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Distribution / Shelf / Display</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TestRepo2/src/classes/SurveyLayoutChildRecordActions.cls
public with sharing class SurveyLayoutChildRecordActions 
{
	
	
	public static void validateParentSurveyIsNotClosedOnInsert(List<SurveyLayout_Brand_Items__c> newLayoutItems) 
	{
		Set<String> layoutIds = new Set<String>();
		for(SurveyLayout_Brand_Items__c item : newLayoutItems) {
			if(item.Survey_Layout__c != null)
				layoutIds.add(item.Survey_Layout__c);
		}
		
		if(!layoutIds.isEmpty()) {
			
			Map<Id,Survey_Layout__c> layoutMap = new Map<Id,Survey_Layout__c>( [select id, Activate_Survey__c 
																					from survey_layout__c
																					where id in :layoutIds] );
			
			for(SurveyLayout_Brand_Items__c newLayoutItem : newLayoutItems)
			{
				if(newLayoutItem.Survey_Layout__c != null) {
					Survey_Layout__c layout = layoutMap.get(newLayoutItem.Survey_Layout__c);
					if(layout != null && layout.Activate_Survey__c == true) {
						newLayoutItem.addError('You cannot add layout items to activated surveys.');
					}
				}
				
			}
			
		}
		
	}
	
	
	
	
	public static void validateParentSurveyIsNotClosedOnInsert(List<Survey_Layout_Brand_Bottle_Item__c> newLayoutItems) 
	{
		Set<String> layoutIds = new Set<String>();
		for(Survey_Layout_Brand_Bottle_Item__c item : newLayoutItems) {
			if(item.Survey_Layout__c != null)
				layoutIds.add(item.Survey_Layout__c);
		}
		
		if(!layoutIds.isEmpty()) {
			
			Map<Id,Survey_Layout__c> layoutMap = new Map<Id,Survey_Layout__c>( [select id, Activate_Survey__c 
																					from survey_layout__c
																					where id in :layoutIds] );
			
			for(Survey_Layout_Brand_Bottle_Item__c newLayoutItem : newLayoutItems)
			{
				if(newLayoutItem.Survey_Layout__c != null) {
					Survey_Layout__c layout = layoutMap.get(newLayoutItem.Survey_Layout__c);
					if(layout != null && layout.Activate_Survey__c == true) {
						newLayoutItem.addError('You cannot add layout items to activated surveys.');
					}
				}
				
			}
			
		}
	}
	
}